### ISSUE TITLE
Please explain me

### ISSUE THREAD

**Issue by RayMarmAung** [bkerler/mtkclient#10]
I got all command but confused on footer, dumprom, stage and plstage command. Can you explain these commands for what ?
i mean these commands use in which places ?

If i use dumprom command and can i use this to load brom ?
I am interested stage and plstage command. Can you guide me how to use these

**Comment by bkerler** [comment]
footer : Dump metadata partition
dumprom : Dump bootrom
stage : Run kamakiri payload in brom mode
plstage : Run kamakiri payload in preloader mode

For more details, see example in the readme
