### ISSUE TITLE
Trying to Unbrick Realme Narzo 10A (RMX2020) device using MTK client tool 

### ISSUE THREAD

**Issue by triloksh07** [bkerler/mtkclient#1006]
Edited 

Update - this problem has been solved.

the error i was getting probably is due to drivers / boot.img file after changing that it worked and i am able to flash boot + recovery, through MTK client tool. If anyone face the same issue or something else can msg me. Thank you !

What is the problem ?
my device get into boot loop after flashing a PBRP ( pitch black recovery ) and booted to it directly, and now my device is not getting into fastboot mode nor recovery, so i am trying MTK tool to re flash boot img.

After successfully setup all the drivers and tool when connected my device to pc it started flashing but after few minutes 
getting error

Cmd terminal O/P - 

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

.......Port - Device detected :)
Preloader -     CPU:                    MT6768(Helio P65/G85 k68v1)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x707
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      A00E0C1036282214D8D53E961AAC4B11
Preloader - SOC_ID:                     F4F0D7468D75EB31688B445ADDA41DE1BA8C07A9A8ACA88310C6B35A0046E139
PLTools - Loading payload from mt6768_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: F:\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6768_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 90014a6843396150
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         hC9aP3
DAXFlash - EMMC CID:        90014a6843396150330143a9e48f27cd
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x1000000
DAXFlash - EMMC USER Size:  0xe8f800000
DAXFlash - DA-CODE      : 0x70E0
DAXFlash - DA Extensions successfully added
Progress: |██████--------------------------------------------| 12.5% Write (Sector 0x2000 of 0x10000, 08s left) 3.05 MB/Progress: |█████████-----------------------------------------| 18.8% Write (Sector 0x3000 of 0x10000, 07s left) 3.90 MB/Progress: |████████████--------------------------------------| 25.0% Write (Sector 0x4000 of 0x10000, 06s left) 3.75 MB/Progress: |████████████████----------------------------------| 31.2% Write (Sector 0x5000 of 0x10000, 06s left) 3.71 MB/susb_class - USBError(5, 'Input/Output Error')
DAXFlash
DAXFlash - [LIB]: unpack requires a buffer of 12 bytes
Failed to write boot.img to sector 3592192 with sector count 65536.

F:\mtkclient-main\mtkclient-main>

**Comment by NasiGorengBurung** [comment]
My man, what is the solution?
