### ISSUE TITLE
Links to LiveDVD V4, they do not work.

### ISSUE THREAD

**Issue by ilia3367** [bkerler/mtkclient#1011]
Dear developer of this program!
Please update the links to LiveDVD V4, they do not work.
![dvdv4](https://github.com/bkerler/mtkclient/assets/9367060/d680889b-af52-42d5-bcac-7693ac5db583)

**Comment by wujinjun-MC** [comment]
A link from [Hovatek](https://www.hovatek.com/forum/thread-38456-post-234837.html#pid234837) is probably available.

If it is against site/issue rule, please ask me to remove.

[Direct link](https://drive.proton.me/urls/YWB8FZ0ZJM#PHfLBD1ids46)

**Comment by ThunderStud613** [comment]
Sometimes you have to back out and go back to the web page. I run into that issue a lot with the Android file host site
