### ISSUE TITLE
Please support for new cpu (mtk6080)

### ISSUE THREAD

**Issue by Fe1raVed** [bkerler/mtkclient#1025]
I have tried using this MTK client but it doesn't work on my device "Tecno pova 5 pro 5g" which uses an MTK6080 CPU

**Comment by bkerler** [comment]
can you give more details, like hwcode etc. and firmware package ?

**Comment by Fe1raVed** [comment]
This is the firmware I use (login first ): https://www.needrom.com/server/download.php?server=needrom-hgfee43h765hf&info=42578hghgf67s1&value=hgfdhjhkjkloi7654hgf654&form=1h5gf61bgfb4hg1f61hg1hhg6&post=thkgfohigjf5gf543&inclu =plokgfdjgfd4gfd56

**Comment by Fe1raVed** [comment]
These are the specifications of Tecno pova 5 pro 5g, maybe it can help: 
https://deviceinfohw.ru/devices/item.php?item=94630

**Comment by bkerler** [comment]
ok, will have a look

**Comment by naden01** [comment]
i use pova 5 pro too

**Comment by bkerler** [comment]
It's a dimensity 6080, not mtk6080, such cpu doesn't exist. Currently no support for newer chipsets until we have a new bootrom flaw, sorry. Correct chipset is MT6833GP, which is patched. Closing as no support currently planned.

**Comment by naden01** [comment]
its okay
