### ISSUE TITLE
Request to add support for Linux-arm64

### ISSUE THREAD

**Issue by harojpgyy** [bkerler/mtkclient#1032]
I use Ubuntu-arm64
The package to run the tool on cannot be found, request to add a package that can support running on arm64

**Comment by bkerler** [comment]
Can you please give more details, error logs ?

**Comment by ColdWindScholar** [comment]
i think its already supported.

**Comment by Reyhank45** [comment]
It's is already supported i mean i can already run it on my Debian android chroot (aarch64)

**Comment by harojpgyy** [comment]
> 它已经得到支持，我的意思是我已经可以在我的 Debian android chroot (aarch64) 上运行它了

Can you provide a screenshot of the gui running?

**Comment by Reyhank45** [comment]
> > 它已经得到支持，我的意思是我已经可以在我的 Debian android chroot (aarch64) 上运行它了
> 
> Can you provide a screenshot of the gui running?

Yes here's the CLI :
![Screenshot_2024-06-14-20-28-04-528_com.termux.jpg](https://github.com/bkerler/mtkclient/assets/156046852/2cffd4f4-de0b-48fc-9324-4e10505a3a9f)


And here's the GUI version running in XFCE Xorg (xvfb)
![Screenshot_2024-06-14-20-31-15-967_com.iiordanov.freebVNC.jpg](https://github.com/bkerler/mtkclient/assets/156046852/425315e2-2256-4dde-8229-4b4e71a8277c)


I haven't managed to successfully do anything as the mtkclient won't detect that the phone has been connected, even though it is there when i entered lsusb.

Maybe i think it's just some kind of permission issue but idk.

BTW I think you should use Debian i mean the packages is just perfect.

**Comment by ColdWindScholar** [comment]
ok, please close the issue and i will add Linux-arm64 to support list

**Comment by harojpgyy** [comment]
> > > 它已经得到了支持，我已经可以在我的 Debian android chroot (aarch64) 上线程了
> > 
> > 
> > 您能提供 GUI 运行的截图吗？
> 
> 是的，这是 CLI： ![Screenshot_2024-06-14-20-28-04-528_com.termux.jpg](https://private-user-images.githubusercontent.com/156046852/339785651-2cffd4f4-de0b-48fc-9324-4e10505a3a9f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzk2NzQsIm5iZiI6MTcxODM3OTM3NCwicGF0aCI6Ii8xNTYwNDY4NTIvMzM5Nzg1NjUxLTJjZmZkNGY0LWRlMGItNDhmYy05MzI0LTRlMTA1MDVhM2E5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNTM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDg1Nzk2ZGZmOThmMjZjNWUxNGNmMzc3ODhhZTRkNzVlNjlmNTAzYzdhZDZjZWZhNjE4MjE3YjhiZTY0ODNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R8ELYytDchMo8TD4T8MdJGsZWoXTxcWu62hTpzq2Hms)
> 
> 这是在 XFCE Xorg (xvfb) 中运行的 GUI 版本 ![Screenshot_2024-06-14-20-33-25-820_com.iiordanov.freebVNC.jpg](https://private-user-images.githubusercontent.com/156046852/339787925-a7cfc15a-cfe8-43f3-aa1a-f370c0a062f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzk2NzQsIm5iZiI6MTcxODM3OTM3NCwicGF0aCI6Ii8xNTYwNDY4NTIvMzM5Nzg3OTI1LWE3Y2ZjMTVhLWNmZTgtNDNmMy1hYTFhLWYzNzBjMGEwNjJmMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNTM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ4NjE5MmQzZjQwNGU1MjgyYTZmMzhlODlhYzI2NThiMzlhODVmNmEwZDk5YTFlYjdhMDg5YjkwOGIwMzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lw-KvWcUdMu3l-fWmfNSnHEAtAato7dxEk0lXyVZyzU)
> 
> 我没有成功地做任何事情，因为mtkclient无法检测到手机已经连接，即使我输入lsusb时它就在那儿。
> 
> 也许我认为这只是素食主义者的问题，但我不确定。
> 
> 顺便说一句，我认为您应该使用 Debian，因为它非常完美。



> > > 它已经得到支持，我的意思是我已经可以在我的 Debian android chroot (aarch64) 上运行它了
> > 
> > 
> > Can you provide a screenshot of the gui running?
> 
> Yes here's the CLI : ![Screenshot_2024-06-14-20-28-04-528_com.termux.jpg](https://private-user-images.githubusercontent.com/156046852/339785651-2cffd4f4-de0b-48fc-9324-4e10505a3a9f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzk2NzQsIm5iZiI6MTcxODM3OTM3NCwicGF0aCI6Ii8xNTYwNDY4NTIvMzM5Nzg1NjUxLTJjZmZkNGY0LWRlMGItNDhmYy05MzI0LTRlMTA1MDVhM2E5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNTM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDg1Nzk2ZGZmOThmMjZjNWUxNGNmMzc3ODhhZTRkNzVlNjlmNTAzYzdhZDZjZWZhNjE4MjE3YjhiZTY0ODNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R8ELYytDchMo8TD4T8MdJGsZWoXTxcWu62hTpzq2Hms)
> 
> And here's the GUI version running in XFCE Xorg (xvfb) ![Screenshot_2024-06-14-20-33-25-820_com.iiordanov.freebVNC.jpg](https://private-user-images.githubusercontent.com/156046852/339787925-a7cfc15a-cfe8-43f3-aa1a-f370c0a062f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzk2NzQsIm5iZiI6MTcxODM3OTM3NCwicGF0aCI6Ii8xNTYwNDY4NTIvMzM5Nzg3OTI1LWE3Y2ZjMTVhLWNmZTgtNDNmMy1hYTFhLWYzNzBjMGEwNjJmMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNTM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ4NjE5MmQzZjQwNGU1MjgyYTZmMzhlODlhYzI2NThiMzlhODVmNmEwZDk5YTFlYjdhMDg5YjkwOGIwMzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lw-KvWcUdMu3l-fWmfNSnHEAtAato7dxEk0lXyVZyzU)
> 
> I haven't managed to successfully do anything as the mtkclient won't detect that the phone has been connected, even though it is there when i entered lsusb.
> 
> Maybe i think it's just some kind of permission issue but idk.
> 
> BTW I think you should use Debian i mean the packages is just perfect.

Can you provide a restore backup? I tried many times and got different errors.
