### ISSUE TITLE
libfuse python library never installs

### ISSUE THREAD

**Issue by MeenoTEK** [bkerler/mtkclient#1038]
I've been using MTKclient for a while now until this issue started.

I've tried installing manually and finding alternative packages but it never works

![image_2024-06-05_18-20-07](https://github.com/bkerler/mtkclient/assets/89714718/1fb9bde0-24c4-4b2c-bd10-ce0fe5dd3cc3)

**Comment by ColdWindScholar** [comment]
Its fixed!

**Comment by ColdWindScholar** [comment]
https://github.com/bkerler/mtkclient/pull/993

**Comment by bkerler** [comment]
Should be fixed in the latest release
