### ISSUE TITLE
crash on windows 11

### ISSUE THREAD

**Issue by J3rr1ck** [bkerler/mtkclient#1039]
hey all getting the following crash when trying to dump all partitions
`Port - Device detected :)
Preloader -     CPU:                    MT6789(MTK Helio G99)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x1208
Preloader - Target config:              0xe0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      9CCE41F58F2090A8489557B5FF11F3BA
Preloader - SOC_ID:                     6B993CDADE1B7D4DA15EA661C2DE871A6512C7A112B3978CED70D308D421B2F6
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
DA_handler
DA_handler - [LIB]: Failed to dump preloader from ram, provide a valid one via --preloader option
DAXML - Uploading xflash stage 1 from MTK_DA_V6.bin
DAXML - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXML - Stage 1 successfully loaded.
DAXML - Uploading stage 2...
Progress: |██████████████████████████████████████████████████| 100.0% Written (Sector 0x2A3 of 0x2A3, ) 1.66 MB/s
DAXML - Successfully uploaded stage 2.
DAXML - Successfully uploaded stage 2
DAXML - SLA is enabled
Traceback (most recent call last):
  File "C:\Users\Jerrick\mtkclient\mtk", line 943, in <module>
    mtk = Main(args).run(parser)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jerrick\mtkclient\mtkclient\Library\mtk_main.py", line 653, in run
    mtk = da_handler.configure_da(mtk, preloader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jerrick\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 149, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jerrick\mtkclient\mtkclient\Library\DA\mtk_daloader.py", line 295, in upload_da
    return self.da.upload_da()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jerrick\mtkclient\mtkclient\Library\DA\xml\xml_lib.py", line 569, in upload_da
    self.reinit(True)
  File "C:\Users\Jerrick\mtkclient\mtkclient\Library\DA\xml\xml_lib.py", line 935, in reinit
    if self.storage.storagetype == "EMMC":
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'storagetype'`

**Comment by ColdWindScholar** [comment]
pls pretty it 😥
