### ISSUE TITLE
MTK 8300 ultra 

### ISSUE THREAD

**Issue by AbdElrahmanShaker446** [bkerler/mtkclient#1055]
hello, can this tool be used to unlock bootlader of new xiaomi device ( K70E) which is china mainland version of poco x6pro 5G ? it's chipset is MTK 8300 ultra , any hope to support ?

**Comment by bkerler** [comment]
there is no such cpu. You mean Dimensity 8300 ultra, which is patched. No support for fused devices with newer chipsets is currently planned.
