### ISSUE TITLE
Handshake failed on MediaTek Helio G85 (Poco C65)

### ISSUE THREAD

**Issue by immortalpao** [bkerler/mtkclient#1058]
![image](https://github.com/bkerler/mtkclient/assets/96258071/ef621741-a6cd-4022-8812-c6b0953792c1)

how to fix?

**Comment by r4db** [comment]
hello, have you found a fix? and if you have can you tell me?

**Comment by immortalpao** [comment]
> hello, have you found a fix? and if you have can you tell me?

now i can't fix
