### ISSUE TITLE
MT6873 da error

### ISSUE THREAD

**Issue by qianmo-xw** [bkerler/mtkclient#107]
Device is Redmi10x （5G） and huawei enjoy 20 pro
CPU is MT6873

When I try other DA also failed

this is log:

Port - Please Connect Brom Mode: Turn-Off U Phone Then Hold Vol- Vol+ or Testpoint And USB Connect.

Port - Device detected :)
Preloader -     CPU:                    MT6873(Dimensity 800/820 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x886
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      5EA2C864887450869DE28DF8F8F743E1
Preloader - SOC_ID:                     DDE15840C558B2D78AF289CC6A7319F78795EEE638FEFE1152B5C7D08774FAA3
PLTools - Loading payload from mt6873_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: E:\AUTO_MTK_UNBL_TOOL.V.07.10.21_Pass_knotthailand\mtkclient\payloads\mt6873_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
usb_class - USBError(5, 'Input/Output Error')
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2124.bin
Preloader
Preloader - [LIB]: [31mError on DA_Send cmd[0m
DAXFlash
DAXFlash - [LIB]: [31mError on sending DA.[0m
Main
Main - [LIB]: [31mError uploading da[0m

**Comment by bkerler** [comment]
no dacode seems to be fine. Can you run wireshark and sniff usb when using sp flash ? That might help sorting out the issue.

**Comment by qianmo-xw** [comment]
> 没有 dacode 似乎没问题。使用 sp flash 时可以运行wireshark 和嗅探usb 吗？这可能有助于解决问题。

I will try

**Comment by qianmo-xw** [comment]
> no dacode seems to be fine. Can you run wireshark and sniff usb when using sp flash ? That might help sorting out the issue.

how can I use wireshark and sniff usb?just install and open?

**Comment by qianmo-xw** [comment]
> Please try [2d8df2b](https://github.com/bkerler/mtkclient/commit/2d8df2b69d89fbdf1ef564cb82277254133ffeca) and report back :)

OK，work！！！！！thank you.
