### ISSUE TITLE
Help me Realme 10 4G - RMX3630 - Error

### ISSUE THREAD

**Issue by Realme-10-4G** [bkerler/mtkclient#1070]
Tell me what I'm doing wrong why I can't do it.

Device: Realme 10 4G   RMX3630

mtkclient 2.01

Preloader - 	CPU:			MT6789(MTK Helio G99)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x1208
Preloader - Target config:		0x5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			7D6B2D67385ACE139234A8DDE5BCD711
Preloader - SOC_ID:			634E2DAA63BD9ED5DB8B07077C36FC916193331366CF6FA0E90FAA91641978EF
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
None

**Comment by r4db** [comment]
try mtk bypass
