### ISSUE TITLE
"[Errno 2] Entity not found" error, then PC freezes

### ISSUE THREAD

**Issue by CrazyBoy2014** [bkerler/mtkclient#1073]
Device: Lenovo A7000-a
Chipset: MT6752M
Hello!

So I'm trying to extract the partitions from flash, but the command fails and the PC freezes for some reason. (On Ubuntu 24.04)
[log.txt](https://github.com/user-attachments/files/15950684/log.txt)

EDIT: The same happens on Windows, but there is no error and the PC doesn't freeze.
[windows-log.txt](https://github.com/user-attachments/files/16045547/windows-log.txt)

**Comment by schmidt-daniel** [comment]
I received the same error message (without the PC freezing, though) when trying to connect a Mi Smart Clock (X04G).

My solution was to downgrade mtkclient to 1.63

**Comment by andreondra** [comment]
I had the same error (Fedora 40, Python 3.12.4), downgrading to 1.63 worked also for me.

**Comment by CrazyBoy2014** [comment]
OK, I'm gonna try. If it works, I'm closing this issue.

**Comment by schmidt-daniel** [comment]
Don't close it, it still need fixing in the newer versions

**Comment by CrazyBoy2014** [comment]
Doesn't work on 1.63 for me
[log.txt](https://github.com/user-attachments/files/16709709/log.txt)

**Comment by CrazyBoy2014** [comment]
If necessary, my Python version is 3.12.3

**Comment by 19atlas** [comment]
same issue on MT8163 based device

**Comment by CrazyBoy2014** [comment]
Any updates on this issue?
