### ISSUE TITLE
`pip3 install .` fails, "mtkclient/Tools" directory not found; easy fix

### ISSUE THREAD

**Issue by LaiKash** [bkerler/mtkclient#1085]
Small but, the installation with `pip3 install .` fails as it is looking for the `Tools` directory inside the mktclient one. I solved it simply creating a symlink to the Tools folder in the parent directory (from the mtkclient one):

`ln -s ../Tools Tools`

I don't exactly know how you would like to solve it @bkerler so I won't mess with a pull request, just posting an idea :)

**Comment by bkerler** [comment]
Sorry, seems I missed to update the project file. Should be fixed now.
