### ISSUE TITLE
Keystone not installing when trying to get requirements.txt 

### ISSUE THREAD

**Issue by ilooklikemymama** [bkerler/mtkclient#1086]
When installing requirements I get this error when it's time to install keystone-engine.

Running setup.py install for keystone-engine ... error
  error: subprocess-exited-with-error

  × Running setup.py install for keystone-engine did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /home/ugly/.venv/lib/python3.11/site-packages/setuptools/dist.py:775: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      /home/ugly/.venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      Building C++ extensions
      ../make-share.sh: 21: cmake: not found
      make: *** No targets specified and no makefile found.  Stop.
      error: [Errno 2] No such file or directory: '/tmp/pip-install-zzaocf6h/keystone-engine_ed48cb971762418aa8dc9f2011653026/src/build/llvm/lib64/libkeystone.so'
      [end of output]
                                                             note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> keystone-engine

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
![Screenshot_20240701_080531_Termux](https://github.com/bkerler/mtkclient/assets/174336897/1ef62ec2-3710-4c01-bb73-37eda6c3e064)

**Comment by bkerler** [comment]
please make sure to install cmake and build-essentials, otherwise it cannot be compiled. Also this is non-related with mtkclient, please post such questions at the keystone repository.
