### ISSUE TITLE
ROOT with mtkclient how to create vbmeta.img.empty?

### ISSUE THREAD

**Issue by YerongLi** [bkerler/mtkclient#1088]
I tried to root my LG phone with mtkclient following official README and I do not know how to create on **vbmeta.img.empty file**
```
python mtk.py w boot,vbmeta boot.patched,vbmeta.img.empty

DAXFlash - Boot to succeeded.
DAXFlash - Successfully uploaded stage 2
DAXFlash - DA SLA is disabled
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         QE63MB
DAXFlash - EMMC CID:        150100514536334d420357b8f2849677
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x3a3e00000
DAXFlash - HW-CODE         : 0x766
DAXFlash - HWSUB-CODE      : 0x8A00
DAXFlash - HW-VERSION      : 0xCA00
DAXFlash - SW-VERSION      : 0x0
DAXFlash - CHIP-EVOLUTION  : 0x0
DAXFlash - DA-VERSION      : 1.0
DAXFlash - Extensions were accepted. Jumping to extensions...
DAXFlash - Boot to succeeded.
DAXFlash - DA Extensions successfully added
Progress: |██████████████████████████████████████████████████| 100.0% Write (Sector 0x14000 of 0x14000, ) 3.24 MB/s58 MB/s
Wrote boot.patched to sector 1543168 with sector count 81920.
DAXFlash
DAXFlash - [LIB]: Filename doesn't exists: vbmeta.img.empty, aborting flash write.
Failed to write vbmeta.img.empty to sector 1661952 with sector count 16384.
(base) 

```
The only files I have are from mtkclient and magisk
```
boot.img
boot.patched
vbmeta.img
```

**Comment by bkerler** [comment]
Please see the examples folder for an empty vbmeta. I wouldn't recommend to use it in general, only if the device requires an empty vbmeta.

**Comment by MelancholyDay** [comment]
I have similar issue, trying to root realme 8i.
Got all files required i woud say, vbmeta was easy to find, boot.img was bit tricky i had to decrypt .ofm to .img 
Now when i tried to flash using 

python mtk.py w boot,vbmeta boot.patched,vbmeta.img.empty

Im getting this 
![image](https://github.com/user-attachments/assets/ea0a3fdd-b118-46b4-a5f6-2f07a32beb03)


This is how my MTK folder looks like 
![image](https://github.com/user-attachments/assets/4b806fa2-3c5f-4b3a-a85f-009fcb666925)

Did i miss anything or any idea wtd

**Comment by bkerler** [comment]
it's not recommended to flash the vbmeta.empty, instead use the new da vbmeta function as stated in the readme.
