### ISSUE TITLE
Unable to install MTKClient

### ISSUE THREAD

**Issue by sysfox** [bkerler/mtkclient#1100]
macOS: 14.2
MTKClient: latest
python: 3.12.4
 macFuse and openssl installed

When I try to run `pip3 install -r requirements.txt`   , the terminal returned error code below:
```
scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:10: fatal error: 'openssl/aes.h' file not found
      #include <openssl/aes.h>
               ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scrypt
Failed to build scrypt
ERROR: Could not build wheels for scrypt, which is required to install pyproject.toml-based projects
```

How can I solve the problem?

**Comment by sysfox** [comment]
<img width="829" alt="image" src="https://github.com/bkerler/mtkclient/assets/99103591/7c376fcf-2e02-4917-b24a-0e2663bb2c52">
<img width="920" alt="image" src="https://github.com/bkerler/mtkclient/assets/99103591/d742392b-6b9b-45d3-94dd-22a276bc471a">

**Comment by sysfox** [comment]
<img width="774" alt="image" src="https://github.com/bkerler/mtkclient/assets/99103591/510d7bad-e00a-42d0-8d8c-52b8745b4675">
<img width="710" alt="image" src="https://github.com/bkerler/mtkclient/assets/99103591/80b4ae3d-af9c-4e3f-95c8-e83d43b17e7e">

**Comment by sysfox** [comment]
Problem solved.Thank you @hopez13

**Comment by LaiKash** [comment]
These issues are usually related to environment specific things. The readme was already updated onces, but I think that installing libusb with brew is better as it will automatically link everything. For example:

```
python3.9 -m venv mtk_venv
source mtk_venv/bin/activate
brew install macFUSE 
brew install libusb
ln -s /opt/homebrew/lib ~/lib
pip3 install --pre --no-binary capstone capstone
pip3 install --no-cache-dir --force-reinstall scrypt
pip3 install PySide6
pip3 install -r requirements.txt
```

I'll make another PR soon.
