### ISSUE TITLE
What's wrong with python is this wrong python ?

### ISSUE THREAD

**Issue by AxelAlfareza199** [bkerler/mtkclient#1103]
![Screenshot (13)](https://github.com/user-attachments/assets/c077329a-350a-4450-a2af-b016266f99d0)

**Comment by ThunderStud613** [comment]
It might just be due to having spaces in your PATH. You should place it in the root of your C:\ drive and see if that ends up working

**Comment by AYIKxD** [comment]
same error with me

**Comment by nasc7** [comment]
> ![Screenshot (13)](https://private-user-images.githubusercontent.com/134942605/348299922-c077329a-350a-4450-a2af-b016266f99d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTY0MzYsIm5iZiI6MTcyMDk1NjEzNiwicGF0aCI6Ii8xMzQ5NDI2MDUvMzQ4Mjk5OTIyLWMwNzczMjlhLTM1MGEtNDQ1MC1hMmFmLWIwMTYyNjZmOTlkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMTIyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjEwMDRjY2VjZWVlYTcyZGY4YTE1YmYwYjU4ZmYwOTQ2NjBkNmQ4YmVlM2E2NzgwNTQwZDUwYjhjZTY4OGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-bNAewxjW8Em0BlvsocpyMkATNjQ1v-ooyjer-xCnr4)

Start from v2.0.1 python mtk is not working anymore. The correct command is python mtk.py

**Comment by bkerler** [comment]
Exactly, documented in the readme
