### ISSUE TITLE
Not detecting on Windows

### ISSUE THREAD

**Issue by MarekSurek** [bkerler/mtkclient#1105]
Mtkclient only on Windows didn't detect my realme c55. On this os by default it comes as 'oplus preloader' but after installing dedicated driver it appear as always but it still didn't detected. Linux works out of the box.
![realme](https://github.com/user-attachments/assets/6f76c2e0-1d5d-4c5a-a040-ea4ad00de236)

**Comment by bkerler** [comment]
Yep, that happens on patched Oppo/Realme devices.

**Comment by evanferrao** [comment]
> Mtkclient only on Windows didn't detect my realme c55. On this os by default it comes as 'oplus preloader' but after installing dedicated driver it appear as always but it still didn't detected. Linux works out of the box. ![realme](https://private-user-images.githubusercontent.com/47944966/348511750-6f76c2e0-1d5d-4c5a-a040-ea4ad00de236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzQ2NzYsIm5iZiI6MTcyNTQzNDM3NiwicGF0aCI6Ii80Nzk0NDk2Ni8zNDg1MTE3NTAtNmY3NmMyZTAtMWQ1ZC00YzVhLWEwNDAtZWE0YWQwMGRlMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODBkMWM2Y2UwMzkyMDU5Njg2MjQ4M2Y3ODg2OWY3NjU5MTQzZDFkNmQ0ZjBkMGQ0NmNkN2ExY2U3N2Q2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NeYS-GjAlHRa0-6FIN5c9QDXsyHkmsKXyJ4SrtpCUxo)

Does the bootloader unlocking work for you on your c55?

**Comment by MarekSurek** [comment]
> > Mtkclient only on Windows didn't detect my realme c55. On this os by default it comes as 'oplus preloader' but after installing dedicated driver it appear as always but it still didn't detected. Linux works out of the box. ![realme](https://private-user-images.githubusercontent.com/47944966/348511750-6f76c2e0-1d5d-4c5a-a040-ea4ad00de236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzQ2NzYsIm5iZiI6MTcyNTQzNDM3NiwicGF0aCI6Ii80Nzk0NDk2Ni8zNDg1MTE3NTAtNmY3NmMyZTAtMWQ1ZC00YzVhLWEwNDAtZWE0YWQwMGRlMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODBkMWM2Y2UwMzkyMDU5Njg2MjQ4M2Y3ODg2OWY3NjU5MTQzZDFkNmQ0ZjBkMGQ0NmNkN2ExY2U3N2Q2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NeYS-GjAlHRa0-6FIN5c9QDXsyHkmsKXyJ4SrtpCUxo)
> 
> Does the bootloader unlocking work for you on your c55?
Yes only in Linux
