### ISSUE TITLE
cant boot in BROM (realme 12 +)

### ISSUE THREAD

**Issue by Tonklaistonton** [bkerler/mtkclient#1106]
Preloader - 	CPU:			MT6877/MT6877V(Dimensity 900/1080)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x959
Preloader - Target config:		0x5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			867D09C85DF1D13F06C3EBD701CFFD0D
Preloader - SOC_ID:			04197D7D3B387B4FB72F1D6CA669F7B011CA2DEE83A1CEB013B127F6411FDC26
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode

it dont reboot to  brom mode but boot in on normal

**Comment by bkerler** [comment]
brom is patched.
