### ISSUE TITLE
"None" log in mtkclient

### ISSUE THREAD

**Issue by jyuuren** [bkerler/mtkclient#1107]
I can't get into mtk_gui. Here is the log:
![mtkclientLOG](https://github.com/user-attachments/assets/80a04559-9e55-4cc1-939e-956a2dedf322)

C:\Users\BEN\mtkclient>python mtk_gui.py
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode

...........

...........

Preloader -     CPU:                    MT6893(Dimensity 1200)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x950
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      60297778E793E79A383C7C9FBD481C6E
Preloader - SOC_ID:                     E00C2B1240F0E0DCB8E9B47F546196221DC33B1DC09FCE13F0143BE5557563F0
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode
Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m

...........
Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m
Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m
Preloader -     CPU:                    MT6893(Dimensity 1200)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x950
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      60297778E793E79A383C7C9FBD481C6E
Preloader - SOC_ID:                     E00C2B1240F0E0DCB8E9B47F546196221DC33B1DC09FCE13F0143BE5557563F0
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
None

**Comment by bkerler** [comment]
Please use the console instead to see what error is written.

**Comment by jyuuren** [comment]
Depending on what i do, i did get either "Couldn't get device configuration" error (Gave me this error when i was trying to flash preloader) or the error at mtkgui debug log "DA hash mismatch error"(Gave me this error when i was trying to flash boot image). I did unbrick my phone somehow using spflashtool which was present in miflashpro app (it required me to log in mi account or spflashtool didn't work). So i can't reproduce error log again since i unbricked it. Thanks.
