### ISSUE TITLE
The program crashes when executing 'reconnecting to stage 2 with tiger speed'

### ISSUE THREAD

**Issue by wilson305f** [bkerler/mtkclient#1111]
The program crashes when executing 'reconnecting to stage 2 with tiger speed'。MY devices is "金立F100S"。MY system is windows 11.

.........Preloader -    CPU:                    MT6735/T,MT8735A()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10212000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10217c00
Preloader -     Var1:                   0x28
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x321
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      A787E20505501151128E01102E024714
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode

ANd another problem,how should I enter Preloader VCOM? I tried to Short circuit motherboard，bet nothing happend.
![Snipaste_2024-07-18_11-48-59](https://github.com/user-attachments/assets/415e0cd7-c320-4b7b-b0ca-627ef32746b1)

**Comment by wilson305f** [comment]
I use another computer to do the same steps,but the same problem happend. It seems that the MTKCLient Has a problem that will cause the program crashes at the step"Reconnecting to stage2 with higer speed..."..    How should i do? Or how should I skip this step???

**Comment by wilson305f** [comment]
It is at the second time when i connect wire to mobile phone. At the first time the program will only layout" Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode"

**Comment by wilson305f** [comment]
Microsoft Windows [版本 10.0.19045.4651]
(c) Microsoft Corporation。保留所有权利。

C:\Users\SoEZzz\mtkclient>
C:\Users\SoEZzz\mtkclient>
C:\Users\SoEZzz\mtkclient>
C:\Users\SoEZzz\mtkclient>C:\Users\SoEZzz\mtkclient\mtk_gui.py
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode


...........


...........


...........


...........


..........Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........


Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........
[[[[[[[[[[[[[[[[[[[[[[[  Here waas the first time I connect the phone    ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

.......Preloader -      CPU:                    MT6735/T,MT8735A()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10212000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10217c00
Preloader -     Var1:                   0x28
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x321
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      A787E20505501151128E01102E024714
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m

[[[[[[[[[[[[[[[[[[[[[[[  Here waas the first time I disconnect the phone    ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
...........
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........


...........


........Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........


...........


..........Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m


...........


...........


...........
[[[[[[[[[[[[[[[[[[[[[[[  Here waas the second time I connect the phone    ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

....Preloader -         CPU:                    MT6735/T,MT8735A()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10212000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10217c00
Preloader -     Var1:                   0x28
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x321
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      A787E20505501151128E01102E024714
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.

[[[[[[[[[[[[[[[[[[[[[[[  Here the program crashed and the GUI windows disappear..    ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

C:\Users\SoEZzz\mtkclient>

**Comment by Lapizman** [comment]
I have the same problem and can't figure out the problem.... so I'm now stucked a thies point and waiting for a solution.

I used this tool a couple of months ago and worked perfect

**Comment by wilson305f** [comment]
in addition,my phone is x86.

**Comment by Lapizman** [comment]
mine is ARM32

**Comment by bkerler** [comment]
that's a driver issue, especially under windows. use --noreconnect option

**Comment by Lapizman** [comment]
the --noreconnect option works on cli mode but not in GUI.

is there any option/solution for GUI?

thanks for taking the time to respond and keep doing this excelent work

**Comment by wilson305f** [comment]
I will try your solutions in recent days.Thanks! do not close this issue.

**Comment by wilson305f** [comment]
I am going to school and may have no time to try your ideas and solutions. You can ask @Lapizman for more imformations. Sorry!

**Comment by bkerler** [comment]
@Lapizman I didn't do the gui, but if you start the gui with --noreconnect it should work. But I need to check that. Closing the issue now.
