### ISSUE TITLE
mt6878 support

### ISSUE THREAD

**Issue by BotchedRPR** [bkerler/mtkclient#1117]
Hi bkerler!
Admiring your work. Helped me in a lot of situations.
This might be a dead-end though. I have a brand-new CMF Phone1 with a mt6878 chip.
Problem is, that i've bricked it. :trollface: 
Keeps trying to boot to a non-existent recovery. But that's beyond the point.
I tried to get mtkclient working, and I expected it not to work, which is exactly what it did, but I noticed that SLA is off. Maybe useful for unbricking?
Logs: https://pastebin.com/XXY5kJmh
I'm ready to help to bring support for this SoC. 
Thanks again

**Comment by bkerler** [comment]
You need a special da for this device. You can unbrick it using the official tools.

**Comment by BotchedRPR** [comment]
> You need a special da for this device. You can unbrick it using the official tools.

Yep. Found everything out later. Sorry to bother and thanks. Now to wait for official tools...

**Comment by 83747aman** [comment]
yes sir i am also facing that issue of disabling auth please find a new way for bootloader unlocking for newer chipset

**Comment by sm455** [comment]
@BotchedRPR a cmf 2 bricked.you have any way to fix
