### ISSUE TITLE
How to make it run on the Android Nethunter OS?

### ISSUE THREAD

**Issue by R1punk** [bkerler/mtkclient#1123]
![Screenshot_20240725-081202](https://github.com/user-attachments/assets/fa207806-aeb5-41ba-bf18-93153e5436d1)

**Comment by R1punk** [comment]
brom mode has been detected

![Screenshot_20240725-081845](https://github.com/user-attachments/assets/adfcf12a-1d3f-40d9-9dc5-e9d4a1d19db9)

**Comment by bkerler** [comment]
Android has no proper libusb stack I assume, so I don't think it will ever work. Also make sure to delete any .stage file before connection

**Comment by bkerler** [comment]
Closing, as double of #1113
