### ISSUE TITLE
Error in Installing OpenStack CLI 

### ISSUE THREAD

**Issue by Oyoh-Edmond** [bkerler/mtkclient#1124]
## Error

Building wheel for netifaces (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for netifaces (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'netifaces' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsofttools/
      [end of output]

### Solution

**What i did was quite simple** 

**Download and Install the Build Tools:**

- Go to the [Visual Studio Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) download page.

- Download the installer and run it.

### Select the Necessary Workloads:

- In the installer, select the "Desktop development with C++" workload.

- Ensure that the "MSVC v142 - VS 2019 C++ x64/x86 build tools" (or later) component is selected.

- You can also check "Windows 10 SDK" if it’s not already selected.

### Complete the Installation:

- Click on the "Install" button to begin the installation.

- Follow the prompts to complete the installation.

- Restart your computer if required.

### Here is the result below

![image](https://github.com/user-attachments/assets/8407beaa-5e26-48ff-b969-6e61de40c70b)

**Comment by bkerler** [comment]
Thanks, added it to the readme.
