### ISSUE TITLE
area not working using preloader

### ISSUE THREAD

**Issue by Herryarfiyan** [bkerler/mtkclient#1126]
![image](https://github.com/user-attachments/assets/116e3dd8-5438-46a6-b207-a94c0e488f0e)
![image](https://github.com/user-attachments/assets/3369d3cb-4e14-443a-b90a-fd750b17b597)

**Comment by ThunderStud613** [comment]
This doesn't help at all. What's the exact issue you're having with this?

**Comment by Herryarfiyan** [comment]
look and read the picture there is a difference there

**Comment by bkerler** [comment]
Fixed with issue [34f1341](https://github.com/bkerler/mtkclient/commit/34f1341da942aa98badcf849d866e92ae1c84e3a)
