### ISSUE TITLE
Mtkclient

### ISSUE THREAD

**Issue by Yuppo00** [bkerler/mtkclient#1129]
Everything's installed right I had a group of people help n go over the files to double check ect long story short mtk_gui.bat handshake failed device not found for samsung galaxy a14 5g us modle

**Comment by Yuppo00** [comment]
![20240727_210633](https://github.com/user-attachments/assets/5aa23c0d-ad3f-4acb-aaee-3964c87a1113)
I fought to get that Pic but operation failed in debugging log  mtkclient log screaming preloader lib 31m status handshake failed and mtk gui states no phone detected

**Comment by bkerler** [comment]
1. You need to have brom mode. 2. For Samsung you require a testpoint to go to brom mode. 3. You need a proper preloader with --preloader option ..... etc.
and 4. Use linux instead.
