### ISSUE TITLE
Unlock on HyperOS printing error

### ISSUE THREAD

**Issue by super-manis** [bkerler/mtkclient#1138]
I recently tried unlocking the bootloader of my xiaomi phone that has a mediatek processor. I ran the GUI and pressed unlock. Everything seemed to have worked fine. Even pressing unlock again gives me a message that the device is already unlocked (even after restart). However, fastboot doesn't work and it's still in locked state. Can somebody help me understand why this is happening? Note that my phone recently updated to HyperOS (if that matters). Any response appreciated.

**Comment by hujinqw** [comment]
Your phone has an issue with LK, and Xiaomi HyperOS cannot use this tool

**Comment by bkerler** [comment]
This is no issue, please ask in the discussions section.
