### ISSUE TITLE
da_handler bugs 8e46df6

### ISSUE THREAD

**Issue by whis222** [bkerler/mtkclient#1139]
command "python mtk.py ess args"  performs no use as well as get args type error
mtk_da_handler.py (8e46df6) 
in line 752 type error
in lin 486 and line ,which leads to not erase correctly
i found my phone boot normally after ess perform

**Comment by bkerler** [comment]
Thanks, fixed in commit [18784ac](https://github.com/bkerler/mtkclient/commit/18784ac75be0c157997a576f0ab6db0903cb26ab)
