### ISSUE TITLE
Preloader - [LIB]: Status: Handshake failed, retrying...

### ISSUE THREAD

**Issue by Tonklaistonton** [bkerler/mtkclient#1140]
how to fix this in windows 11  linux dont have this error   do you have any recommended drivers? If so, please tell me. Thank you for solving this problem.

**Comment by hujinqw** [comment]
Perhaps your phone has preloader auth

**Comment by bkerler** [comment]
If linux works and windows 11 doesn't it is most probably windows driver related.
