### ISSUE TITLE
Vivo X100/Dimensity 9300 fails handshake/doesn't boot into BROM mode

### ISSUE THREAD

**Issue by Nameless-Moonster** [bkerler/mtkclient#1144]
I have tried all volume and power button combination only to find that device allows preloader to be accessed  for few seconds , After that it disconnects .  
![Screenshot (4)](https://github.com/user-attachments/assets/febf6d7d-833d-4b2a-a66b-b15c776b9bf5)

**Comment by bkerler** [comment]
Most probably brom mode is patched. In order to be sure, try the linux version instead as windows is pretty unreliable.

**Comment by Nameless-Moonster** [comment]
Since Mtk client wasn't able recognize device I used android utility tool . It does give a successful connection but when I try to read info in brom mode this shows up .  How do I pass this da signature fail ?

![PXL_20240825_083923276](https://github.com/user-attachments/assets/f92b348c-e126-49af-9dab-851a472f0f4c)
