### ISSUE TITLE
USB Device Not Detected on MacOS M1 MBP

### ISSUE THREAD

**Issue by 4rianton** [bkerler/mtkclient#1158]
I believe I followed all the instructions but while trying to test using `sudo python mtk.py printgpt --debugmode`, the output is: 

```
Traceback (most recent call last):
  File "/Users/xxxx/Desktop/mtkclient/mtk.py", line 1000, in <module>
    mtk = Main(args).run(parser)
  File "/Users/xxxx/Desktop/mtkclient/mtkclient/Library/mtk_main.py", line 662, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "/Users/xxxx/Desktop/mtkclient/mtkclient/Library/DA/mtk_da_handler.py", line 87, in configure_da
    mtk.port.cdc.connected = mtk.port.cdc.connect()
  File "/Users/xxxx/Desktop/mtkclient/mtkclient/Library/Connection/usblib.py", line 299, in connect
    devices = usb.core.find(find_all=True, bDeviceClass=devclass, backend=self.backend)
  File "/Users/xxxx/Desktop/mtkclient/mtk_venv/lib/python3.9/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

The log.txt file is empty. 

While trying to run `sudo python mtk_gui.py`, the UI appears but never detects the device I am trying to attach (X04G)

**Comment by bkerler** [comment]
Sorry, but the problem is related to mac arm, which doesn't seem to provide proper libusbv1 functionality.

**Comment by rashidmp** [comment]
To fix the "No backend available" issue, please follow these steps:

1. Install `libusb` via Homebrew:

```bash
brew install libusb
```

2. Link the Homebrew lib path:

```bash
ln -s /opt/homebrew/lib ~/lib
```

These steps have been tested and worked on an M1 MacBook Air (2020).

**Comment by lkenner** [comment]
> To fix the "No backend available" issue, please follow these steps:
> 
> 1. Install `libusb` via Homebrew:
> 
> ```shell
> brew install libusb
> ```
> 
>  2. Link the Homebrew lib path:
> 
> ```shell
> ln -s /opt/homebrew/lib ~/lib
> ```
> 
> These steps have been tested and worked on an M1 MacBook Air (2020).

thanks, that helped!
