### ISSUE TITLE
Filename doesn't exists: boot.patched, aborting flash write

### ISSUE THREAD

**Issue by MelancholyDay** [bkerler/mtkclient#1163]
Hello, i have an issue trying to root realme 8i.
Got all files required i woud say, vbmeta was easy to find, boot.img was bit tricky i had to decrypt .ofm to .img 
Now when i tried to flash using 

python mtk.py w boot,vbmeta boot.patched,vbmeta.img.empty

Im getting this 
![image](https://github.com/user-attachments/assets/ea0a3fdd-b118-46b4-a5f6-2f07a32beb03)

This is how my MTK folder looks like 
![image](https://github.com/user-attachments/assets/4b806fa2-3c5f-4b3a-a85f-009fcb666925)

Phone is unlocked, did i miss anything or any idea wtd

I started from scratch, had to get all files mostly by googling since there was nothing for my version in guide i was folowing, did bricked my phone 2 times, it took me last whole week to get to this point, i feel im close to be done, but everytime theres something that makes me spend another day looking up info, trying to fix things.
This is first time asking for help, im mentally exhausted :( :D 

_Originally posted by @MelancholyDay in https://github.com/bkerler/mtkclient/issues/1088#issuecomment-2308507587_

**Comment by bkerler** [comment]
see readme. instead of writing empty vbmeta, try to set the right flag (2 or 3) using vbmeta option. Doesn't work for some vendors though and more patching might be needed.

**Comment by saru4406D** [comment]
@MelancholyDay Hey dude. were you successful in unlocking the bootloader and rooting the device ?

also can we connect. I need to ask so many things on this topic , as I am trying to root exact same device.

if okay just mail me at Sarveshwar.sharma321@gmail.com.
