### ISSUE TITLE
mt 6886 problem redmi note 13 pro plus

### ISSUE THREAD

**Issue by prexuutr** [bkerler/mtkclient#1171]
When I connect my Redmi Note 13 Pro Plus device to mtkclient in Brom mode, I encounter the problem in the photo. @bkerler 
![github](https://github.com/user-attachments/assets/f6ddbcae-4e2d-4b33-a102-26052f56ee8e)

**Comment by R0rt1z2** [comment]
I think the error is pretty clear. The device uses SLA and therefore mtkclient won't work.

**Comment by bkerler** [comment]
Well at least for the newer chipsets as they are patched against kamakiri2. Correct.
