### ISSUE TITLE
Preloader Handshake failure

### ISSUE THREAD

**Issue by notMyRealName12** [bkerler/mtkclient#1185]
I get a handshake failure error retrying twice and then device boots like normal
Pid 2000 mt8163 I updated it and I think brom was removed or disabled. 
Tried test point to no avail. 
I was able to root the device and flash the old preloader back thinking that would allow me to use mtkclient again but I didn't realize brom was gone. Now my device is stuck in fastboot loop. Not unlocked. 
Is there anyway to write to this device through another method?

**Comment by 19atlas** [comment]
i have mt8163 device too and i think i currupt preloader but i booted device fastboot via `python mtk.py plstage --preloader=preloader_tb8163.bin` and flashed preloader but still device can't boot itself.

**Comment by notMyRealName12** [comment]
> i have mt8163 device too and i think i currupt preloader but i booted device fastboot via `python mtk.py plstage --preloader=/path/to/preloader_tb8163.bin` and flashed preloader but still device can't boot itself.
> 
> also mtk_gui.py stucks `jumping to 0x2000` in brom mode

You have brom enabled ? 
I need a way to write to the device in preloader more without brom. I think mine has been disabled by efuse

**Comment by 19atlas** [comment]
> You have brom enabled ? 
yes When you remove and insert the battery it goes into brom mode. 

> I need a way to write to the device in preloader more without brom. I think mine has been disabled by efuse

what is your device?
my device is Hometech 8MZ

**Comment by notMyRealName12** [comment]
> > You have brom enabled ?
> > yes When you remove and insert the battery it goes into brom mode.
> 
> > I need a way to write to the device in preloader more without brom. I think mine has been disabled by efuse
> 
> what is your device? my device is Hometech 8MZ

Pixel coral 
Battery him removable but how does it go into brom from removal and replace? No button sequence? Just plug up and remove and insert? Do you think it'll work with brom disabled by efuse?
