### ISSUE TITLE
writing RPMB, UNLOCK RELOCK BOOTLOADER  issue

### ISSUE THREAD

**Issue by Herryarfiyan** [bkerler/mtkclient#1193]
please fix RPMB erase write problem

**Comment by samuel1003** [comment]
I see a commit about Unlock/relock Bootloader, seems fixed. No tested RPMB yet, but this issue long time ago without solution from Bkerler

**Comment by bkerler** [comment]
rpmb write and erase works fine for v5 (emmc + ufs) as long as the right rpmb key has been sent

**Comment by Herryarfiyan** [comment]
@bkerler vivo not work sir
only read ok

**Comment by Herryarfiyan** [comment]
if dax old version ok worked
