### ISSUE TITLE
MT6853 Fails, libusb?

### ISSUE THREAD

**Issue by mvaisakh** [bkerler/mtkclient#12]
I have a Redmi Note 9T (cannong) with mt6853 (Dimensity 800U), running Android 11 firmware.
My device is in bricked state, and I'm trying to bypass the SLA and DAA but it strangely fails with an error: 

`[Errno 32] Pipe error`

When I try to dumpbrom, the device, same error message shows up with kamakiri and amonet methods, but a different error pops up with hashimoto, more like a python script error:
```
File "./mtk.py", line 795, in <module>
   mtk = Main().run()
File "./mtk.py", line 229, in run
   plt.run_dump_brom(filename, self.args["--ptype"])
File "/opt/mtkclient/Library/pltools.py", line 171, in run_dump_brom
   if self.dump_brom(filename, "cqdma"):
File "/opt/mtkclient/Library/pltools.py", line 228, in dump_brom
   wf.write(self.hwcrypto.cqdma.mem_read(addr, 16, True))
File "/opt/mtkclient/Library/cqdma.py", line 104, in mem_read
   res = self.cqread32(addr, dwords)
File "/opt/mtkclient/Library/cqdma.py", line 71, in cqread32
   dst_addr = self.chipconfig.ap_dma_mem
AttributeError: 'cqdma' object has no attribute 'chipconfig'
```
I've also attached a log for the reset command.
[Log](https://drive.google.com/file/d/1uJyQ2Cmet-anApyfDvtD0d8NKBJOOy4E/view?usp=sharing)

I also face similar issues as mentioned here https://github.com/MTK-bypass/bypass_utility/issues/14

I've tried brute forcing, but even after hours of reconnection and disconnection, I can't seem to find the exact value for val1 and/or var_1.

PS: I have performed everything on LiveDVD ubuntu environment.

**Comment by mvaisakh** [comment]
Hi Bjoern,
So I tried with the latest changes, especially had an eye on this one ce8845673a753bfbfdfc11a9c12121dc92feab8c, but it doesn't seem to work here. I'm trying to run payload and dumpbrom, it still fails with `[Errno 32] Pipe error`

I booted the livedvd, upgraded all packages with `sudo apt-get update && sudo apt-get upgrade`, `git pull` all the latest changes from the repository and try again, everything was the same. Windows refuses to detect my device even with zadig.

Here's a log for the payload: https://katb.in/meow2141
If you need anything more from me, i.e., like testing, let me know, I can do that.

Also, my device is MT6853T (Dimensity 800U), which is basically an overclocked MT6853 (Dimensity 720).

Thanks!

**Comment by bkerler** [comment]
Hi,

the reason might be simple. The newer mt68xx chips are already patched against kamakiri and thus won't work.

**Comment by mvaisakh** [comment]
I'm guessing that too. Thanks!
