### ISSUE TITLE
MT6739 ERROR DA-CODE      : 0x999F0 

### ISSUE THREAD

**Issue by StelinFex** [bkerler/mtkclient#120]
Port - Device detected :)
Preloader -     CPU:                    MT6739/MT6731()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xb4
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x699
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb00
Preloader -     SW Ver:                 0x2
Preloader - ME_ID:                      09DA2F8B575108A8A1C3D49F6143330A
Preloader - SOC_ID:                     DB3F67997429C9F8DFF6778CEBE3485BFA87F3937F2BA4C5D148F5D48B52679D
PLTools - Loading payload from mt6739_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6739_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.1824.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         FJ25AB
DAXFlash - EMMC CID:        150100464a323541420229d590ffc269
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x80000
DAXFlash - EMMC USER Size:  0xe9000000
DAXFlash - DA-CODE      : 0x999F0
Traceback (most recent call last):
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtk", line 1709, in <module>
    mtk = Main(args).run()
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtk", line 662, in run
    if not mtk.daloader.upload_da(preloader=preloader):
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 141, in upload_da
    return self.da.upload_da()
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 1093, in upload_da
    if self.boot_to(at_address=0x68000000, da=daextdata):
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 341, in boot_to
    status = self.status()
  File "C:\Users\Chappie\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 211, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**Comment by etmatrix** [comment]
If you are running on windows try to delete MTK_AllInOne_DA_5.1824.bin so mtk should use the version 2024

**Comment by kashifbharwana** [comment]
Problem solved

**Comment by StelinFex** [comment]
> Driver issue

Thank you sir, I was busy in study. My model is Jazz Digit V2 new version.
Thank you for helping me!

**Comment by kashifbharwana** [comment]
Easy way sptool for jazz digit

**Comment by StelinFex** [comment]
> Easy way sptool for jazz digit

I want to unlock bootloader of this version. But I am facing error.

**Comment by kashifbharwana** [comment]
This mobile have kiaos so try to cm2

**Comment by StelinFex** [comment]
> This mobile have kiaos so try to cm2

Sir CM2 expensive, I want help in unlock bootloader using this tool.
I am very thankful for your time

**Comment by bkerler** [comment]
Can you please use commit 94953e8 and try --debugmode and send me the log ? Or best: use wireshark and sniff usb and send me pcap when using mtkclient

**Comment by bkerler** [comment]
No further details provided, closing this issue for now.
