### ISSUE TITLE
write rpmb error!

### ISSUE THREAD

**Issue by Gsmlvdeshui** [bkerler/mtkclient#121]
python mtk xflash rpmb w

Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

...........
Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      75730E580C6D8C39A659885228C4C8CC
Preloader - SOC_ID:                     BC8E2530290297FCA942DAEC7F904D725288A87CA2FEA92FEBFC66015497E037
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\joh\Desktop\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6853_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ16AFAMMDAR
DAXFlash - UFS CID:      ad014839485131364146414d4d444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ad014839485131364146414d4d444152
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ16AFAMMDAR
DAXFlash - UFS CID:      ad014839485131364146414d4d444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x969F0
DAXFlash - DA Extensions successfully added
Traceback (most recent call last):
  File "mtk", line 1720, in <module>
    mtk = Main(args).run()
  File "mtk", line 1119, in run
    mtk.daloader.write_rpmb(args.filename)
  File "C:\Users\joh\Desktop\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 185, in write_rpmb
    return self.xft.write_rpmb(filename)
  File "C:\Users\joh\Desktop\mtkclient-main\mtkclient-main\mtkclient\Library\xflash_ext.py", line 434, in write_rpmb
    if self.custom_rpmb_init():
  File "C:\Users\joh\Desktop\mtkclient-main\mtkclient-main\mtkclient\Library\xflash_ext.py", line 377, in custom_rpmb_init
    status = self.status()
  File "C:\Users\joh\Desktop\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 211, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**Comment by bkerler** [comment]
Closing this issue, as it will continue on issue #29
