### ISSUE TITLE
userdata partition dump!

### ISSUE THREAD

**Issue by thelamewizard** [bkerler/mtkclient#1217]
is it possible to dump the userdata partition without the file being the siize of the whole partition? if not, could i ust dump everything else, then dump the userdata using fastboot and add that to the folder and then use it to write the whole backup to the phone?

**Comment by ferouzkassim** [comment]
Am not so sure there's a command to dump anything in fastboot but u mean unwanted to dump the stock user data file not the whole used user data is it ?

**Comment by thelamewizard** [comment]
ah youre correct, for some reason i had it in my head that fastboot had that option. not qute the stock rom, but rather my own current userdata which is close to stock since i havent really done anything yet other than install some basic updates. my goad is to get a full dump that i can then flash onto the device using mtkclient, and then have the phone work straight away. ie ithout having to  boot into recovery and wipe the data firsm (which is what i have to do right now when i flash any rom usin mtkclient).

**Comment by thelamewizard** [comment]
also, i dont understand why, but i cant seem to flash any other rom other than my own dump or camellian_global_images_V14.0.5.0.TKSMIXM_13.0. i dont fully understand why. my main goal is to flash the indonesian rom onto the device, but it just doesnt work, when i fllash that, the phone will start not booting.

**Comment by thelamewizard** [comment]
basically, i want call recording to work natively, which i have managed i have on my samsung A10s by just flashing indonesian stock rom. and since its still a stock rom, it doesnt trigger any security issues with any other apps either like banking and stuff. i want to do the same with my redmi note 10 5g.

**Comment by ferouzkassim** [comment]
so first things frst u need bootloader unlokced abd then if your intention is to wipe userdata because of encryptionn that userdata will be flashed on but it will have to wipe in the event of unencrypting the userdata  so if you want thee moded features to wor yu would have to mode your own rom tweak build.prop unlock bootloader then flash it on via fastbooot its worht noting some samsungs featres are csc based were as most features indevices like xiaomi are super based though i dnt think this is till connected to this repo anymore but  take your shot

**Comment by thelamewizard** [comment]
i have bootloader unlocked. i dont really care about losing the userdata. it just seems to be creating issues when i flash other roms. but basically what i want is to get the indonesian version because i read that it has miui dialer which seems to have recording enabled. or another option would be to get the indonesian or indian version of the google phone app (this would be the best scenario for me) but i cant find it, and if i did, i wouldnt know how to get it onto the device. thats true though, it is no longer connected to this repo. as far as this repo goes... THANK YOU for a great piece of software. it has saved my phone.

**Comment by thelamewizard** [comment]
imma close this case now.
