### ISSUE TITLE
Dimensity 700 5G k6833  The preloader mode cannot be connected without Brom mode

### ISSUE THREAD

**Issue by xxroot** [bkerler/mtkclient#1221]
Port - Device detected :)
Preloader -     CPU:                    MT6833(Dimensity 700 5G k6833)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x73
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x989
Preloader - Target config:              0x7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      404EF52D351902429D74E9D4A87296F8
Preloader - SOC_ID:                     F1AA36A445B8CA83AE3B37D9AC779CDC88152A64D5D5C58275B84C3C5DF14BDF
DaHandler - Device is protected.
DaHandler - Device is in Preloader-Mode.
DAXFlash - Uploading xflash stage 1 from DA.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Uploading stage 2...
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - Boot to succeeded.
DAXFlash - Successfully uploaded stage 2
DAXFlash - DA SLA is enabled
No valid sla key found, trying dummy auth ....
DAXFlash
DAXFlash - [LIB]: [31mError on sending parameter: RSA pss op fail (0xc0020017)[0m
DAXFlash
DAXFlash - [LIB]: [31mCan't bypass DA SLA[0m
DAXFlash
DAXFlash - [LIB]: [31mError on boot to, addr: 0x68000000[0m
DAXFlash
DAXFlash - [LIB]: [33mDA Extensions failed to enable[0m
DAXFlash
DAXFlash - [LIB]: [31mError on reading data: Unsupported command (0xc0010003)[0m
DaHandler
DaHandler - [LIB]: [31mError getting the partition table.[0m
@bkerler

**Comment by bkerler** [comment]
For 6833 you need to use brom mode, preloader mode isn't supported as DA SLA is enabled obviously, sorry.

**Comment by raphael1233333** [comment]
@xxroot Could you please share the device model you used here?
