### ISSUE TITLE
Samsung tablet handshake problem

### ISSUE THREAD

**Issue by Brickedboot** [bkerler/mtkclient#1222]
ive had my tablet connect before but after restoring it from a softbrick i cant connect to mtkclient i get this every time

..........Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m
.......

**Comment by IsHacker003** [comment]
It's a common problem if you are using windows, I don't know how to fix it, but you should use linux to avoid these problems.
