### ISSUE TITLE
 MT6795x Meizu Mx5 failed

### ISSUE THREAD

**Issue by long36708** [bkerler/mtkclient#123]
Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

.....Port - Device detected :)
Preloader -     CPU:                    MT6795(Helio X10)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x110000
Preloader -     CQ_DMA addr:            0x10212c00
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x6795
Preloader - Target config:              0x7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      3686627E11E65909297234C8998BD96D
PLTools - Loading payload from mt6795_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\mys\Desktop\demo\mtkclient\payloads\mt6795_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DALegacy - Uploading da...
DALegacy - Uploading stage 1...
Preloader - Jumping to 0x110000
Preloader - Jumping to 0x110000: ok.
DALegacy - Got loader sync !
DALegacy - Reading nand info
DALegacy - Reading emmc info
DALegacy - DRAM config needed for : 15010042474e443352013c9d49fd8235
DALegacy - Reading nand info ...
DALegacy - Uploading stage 2...
usb_class - USBError(5, 'Input/Output Error')
DALegacy
DALegacy - [LIB]: [31mError on sending brom stage 1 : [0m
Main
Main - [LIB]: [31mError uploading da[0m

**Comment by bkerler** [comment]
Closing for now, as no further details were provided.
