### ISSUE TITLE
Attempting to follow instructions on Moto G Pure (XT2163DL) gets me nowhere

### ISSUE THREAD

**Issue by SerraraFluttershy** [bkerler/mtkclient#1234]
Tried following the instructions to set up MTKClient on both Windows and Linux (Linux via a VM) and in both cases MTKClient is unable to perform the handshake.
Tried resorting to this since Motorola refuses to unlock a Tracfone...yet the OEM Unlocking toggle in developer settings can be flipped on and stays on after rebooting.

I've looked around and the model of CPU in this phone _is_ supported by MTKClient.
Is there anything I can do?

**Comment by shomykohai** [comment]
> Tried following the instructions to set up MTKClient on both Windows and Linux (Linux via a VM) and in both cases MTKClient is unable to perform the handshake. Tried resorting to this since Motorola refuses to unlock a Tracfone...yet the OEM Unlocking toggle in developer settings can be flipped on and stays on after rebooting.
> 
> I've looked around and the model of CPU in this phone _is_ supported by MTKClient. Is there anything I can do?

Windows is the issue here, and using Linux under VM won't work if Windows USB filter isn't set up correctly.

The phone, as you said, has a supported CPU (Helio G25), and most likely BROM mode too.
I sugest booting linux from a USB drive and do what you need to do from there.
I suggest using manjaro for this, since you can download mtkclient with one command and set it up automatically (usb stuff too).

Also, I suggest looking at #1405, which has the same SoC but needed more patches for it to be actually unlocked

**Comment by SerraraFluttershy** [comment]
The issue is that I can't get the phone into BROM mode regardless of [what](https://xdaforums.com/t/tool-tool-all-in-one-drivers-unlock-twrp-factory-image-stock-recovery.3358711/) [software](https://xdaforums.com/t/dev-motorola-unbrick-tool.4491309/) I've used. This includes using [a custom fastboot](https://xdaforums.com/t/guide-how-to-reboot-to-edl-from-fastboot.3394292/) that was _intended_ to force EDL mode, which failed because this phone apparently doesn't support it.

My last hope is to see if booting the Live USB on bare metal changes anything, but I really doubt it at this point.

**Comment by shomykohai** [comment]
> The issue is that I can't get the phone into BROM mode regardless of [what](https://xdaforums.com/t/tool-tool-all-in-one-drivers-unlock-twrp-factory-image-stock-recovery.3358711/) [software](https://xdaforums.com/t/dev-motorola-unbrick-tool.4491309/) I've used. This includes using [a custom fastboot](https://xdaforums.com/t/guide-how-to-reboot-to-edl-from-fastboot.3394292/) that was _intended_ to force EDL mode, which failed because this phone apparently doesn't support it.
> 
> My last hope is to see if booting the Live USB on bare metal changes anything, but I really doubt it at this point.

Mmh, surely using qualcomm tools won't help, being it MTK.
There might be the chance Moto blocked BROM USBDL via an OTA update, and in that case you can only hope for preloader handshake and Carbonara.

If you're comfortable with it, you might try using the Testpoint to force BROM.
If not even then the USB enumerates, it means USBDL via BROM is indeed blocked.
