### ISSUE TITLE
MT6763解锁 BL 锁时,出现了以下报错

### ISSUE THREAD

**Issue by a5mimnc2** [bkerler/mtkclient#1238]
我的手机机型是  oppo a83 [ MT6763]  将电池拆下短接进入深刷模式后,尝试解锁 BL 出现以下报错
...........
Port - Device detected :)
Port - Device detected :)
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da1 ...
xflashext
xflashext - [LIB]: [33mError on patching da1 version check...[0m
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
usb_class - USBError(5, 'Input/Output Error')
DAXFlash
DAXFlash - [LIB]: [31mxread error: unpack requires a buffer of 12 bytes[0m
DAXFlash
DAXFlash - [LIB]: [31mError jumping to DA: -1[0m
None

**Comment by a5mimnc2** [comment]
> 我的手机机型是 oppo a83 将电池拆下短接进入深刷模式后,尝试解锁 BL 出现以下报错 ...........端口 - 检测到的设备:)端口 - 检测到的设备:)DAXFlash - 从 MTK_AllInOne_DA_5.2152.bin 上传 xflash 阶段 1xflashext - 正在修补 da1 ... xflashextxflashext - [LIB]：[修补 da1 版本检查时出现 33m错误...[0 分钟xflashext - 正在修补 da2 ...DAXFlash - 成功上传第 1 阶段，跳跃 ..usb_class - USBError（5， '输入/输出错误'） DAXFlashDAXFlash - [LIB]：[31mx读取错误：解压缩需要 12 字节 [0m] 的缓冲区 DAXFlashDAXFlash - [LIB]： [31m跳转到 DA 时出错： -1 [0m 没有

**Comment by bkerler** [comment]
you need to use a different da loader or use --stock as it cannot be patched.

**Comment by NasiGorengBurung** [comment]
> you need to use a different da loader or use --stock as it cannot be patched.

What's the different da loader? And what do you mean that it cannot be patched?
