### ISSUE TITLE
DRAM issue on MTK8163

### ISSUE THREAD

**Issue by jphilpot6** [bkerler/mtkclient#125]
Hello,

I have been trying to unlock my bootloader and keep getting error

 DALegacy - [LIB]: Preloader error: 3012 => S_DA_NAND_FLASH_NOT_FOUND

[log.txt](https://github.com/bkerler/mtkclient/files/7391308/log.txt
[preloader_hq8163_tb_a8_n.zip](https://github.com/bkerler/mtkclient/files/7391286/preloader_hq8163_tb_a8_n.zip)
[brom_8163.zip](https://github.com/bkerler/mtkclient/files/7410490/brom_8163.zip)
)

Jonathan

**Comment by mpalpha** [comment]
I have this issue too. Also do you have a patreon or donations setup?

**Comment by mpalpha** [comment]
possible additional reference: https://research.nccgroup.com/2020/10/15/theres-a-hole-in-your-soc-glitching-the-mediatek-bootrom/

**Comment by bkerler** [comment]
@mpalpha Sure, donation link is here on github :)
Can you try if the latest commit of today works ?

**Comment by mpalpha** [comment]
`Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m`

**Comment by xilohs** [comment]
Hello. Has this issue been resolved? Currently facing a similar challenge on my infinix phone. I have wasted a whole lot of time on it and it is no longer powering up. Anything i try to do end up at DALegacy - [LIB]: [31mPrwloader error: 3012 => S_DA_NAND_FLASH_NOT_FOUND
