### ISSUE TITLE
Write Userdata Min Size Not Work, if Size min 512 this Work

### ISSUE THREAD

**Issue by komenkHp** [bkerler/mtkclient#131]
userdata size : 133kb this failed
Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      944DCAEFCA604EC382241D891E8B21D6
Preloader - SOC_ID:                     87C8D9678C55A8EAB901DB229136DBA5CF7F7EDA6CB8803A8C61866743702607
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Client\payloads\mt6765_payload.bin
Port - Device detected :)
Main - HDevice isX protected
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage_DA 1 from MTK_AllInOne_DA.bin
DAXFlash - Successfully X_DA 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping Berhasil to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 150100445836384d
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         DX68MB
DAXFlash - EMMC CID:        150100445836384d42096bb7dc75871d
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x747c00000
DAXFlash - DA-CODE      : 0x666D0
DAXFlash - DA Extensions successfully added
Start Addr:20021248
Done |--------------------------------------------------| 0.0% Write (Sector 0x0 of 0x109) 0.00 MB/sDAXFlash
DAXFlash - [LIB]: ←[31munpack requires a buffer of 12 bytes←[0m
Failed to Write Data sector 20021248

H:\DATAX\MTKClien Anyaran\2\mtkclient-main>

userdata Size 512 This Done
Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      944DCAEFCA604EC382241D891E8B21D6
Preloader - SOC_ID:                     87C8D9678C55A8EAB901DB229136DBA5CF7F7EDA6CB8803A8C61866743702607
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Client\payloads\mt6765_payload.bin
Port - Device detected :)
Main - HDevice isX protected
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage_DA 1 from MTK_AllInOne_DA.bin
DAXFlash - Successfully X_DA 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping Berhasil to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 150100445836384d
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         DX68MB
DAXFlash - EMMC CID:        150100445836384d42096bb7dc75871d
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x747c00000
DAXFlash - DA-CODE      : 0x666D0
DAXFlash - DA Extensions successfully added
Start Addr:20021248
Progress: |██████████████████████████████████████████████████| 100.0% Write (Sector 0x400 of 0x400, ) 4.00 MB/s
Write Data sector 20021248

H:\DATAX\MTKClien Anyaran\2\mtkclient-main>

**Comment by bkerler** [comment]
Closing for now, as no further details were provided.
