### ISSUE TITLE
stylo 6 windows connection

### ISSUE THREAD

**Issue by Warlockguitarman** [bkerler/mtkclient#138]
I got it connected to do a full rl out read finally, but after the backup i tried to reconnect to run the python mtk e metadata,userdata,md_udc command and i tried and tried and after nearly 40 attempts it connected but failed, heres what happened.
..........Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0x5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Mtk - We're not in bootrom, trying to crash da...
PLTools - Crashing da...
Preloader
Preloader - [LIB]: ←[31mupload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)←[0m
Preloader
Preloader - [LIB]: ←[31mError on uploading da data←[0m
Preloader - Jumping to 0x0
usb_class - USBError(5, 'Input/Output Error')
Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

**Comment by Warlockguitarman** [comment]
I got it unlocked finally using windows 10, it was alot more difficult than the k51 but it worked

**Comment by etmatrix** [comment]
Could you explain how? May is useful also to somebody else.
On my device when I received DAA_SIG_VERIFY_FAILED I solve before with `mtk payload` and after I use the command

**Comment by Warlockguitarman** [comment]
Well I also used sp flash tool with this, I found while flashing the preloader only, which fails because it's protection isn't disabled at that point it helped the tool connect, i figured this out while having issues getting it to connect to chimera to do a backup, i always had difficulties and needed the bypass utility and sp flash tool to get the phones security disabled to connect,  but I got it connected on my first try and noticed I forget to hit enter in bypass utility to start the command when I connected it, I'm also not holding any buttons,  just plugging it in. I'm almost done writing a tutorial specifically for the stylo 6 with the files needed and the steps to do it in detail, I have a discord group called The Bootloader Locksmiths that I made as a spin off of the stylo 6 discord that I was removed from. Here's a link https://discord.gg/9AnNHzBtZv

**Comment by Warlockguitarman** [comment]
Here's my write up on xda with a step by step description on how to unlock the stylo 6 on windows with mtkclient 

https://forum.xda-developers.com/t/how-to-unlock-bootloader-and-root-the-lg-stylo-6-and-k51-k61-and-other-k-model-lg-devices.4364489/
