### ISSUE TITLE
The utility does not work on Windows 10 x32 (x86)

### ISSUE THREAD

**Issue by marat2509** [bkerler/mtkclient#14]
The utility does not work on this OS. The program swears on libusb1.0.dll. When I manually replaced the file with the file from LibUSB x32 for Windows The utility has stopped "seeing" COM-ports. Let's try to make the utility work on Windows 10 x32 (x86)

**Comment by bkerler** [comment]
That's an issue on pyusb, not in mtkclient. Right now only 64bit works, but according to pyusb issue, 32bit is being worked on.

**Comment by marat2509** [comment]
I managed to get the utilities working on Windows 10 x32
