### ISSUE TITLE
Edits to work in the mtk file (Honor 7A DUA-L22 MT6739).

### ISSUE THREAD

**Issue by TolstyLuty** [bkerler/mtkclient#143]
1) The command did not work: 
python mtk wo 0x10DFB000 0x2000 oeminfo_unlock_part.img
Edit on the photo:
https://4pda.to/forum/index.php?act=findpost&pid=110704986&anchor=Spoil-110704986-5
2) The command did not work: 
python mtk w preloader preloader.bin --parttype=boot1
Edit on the photo:
https://4pda.to/forum/index.php?act=findpost&pid=110732861&anchor=Spoil-110732861-1

**Comment by bkerler** [comment]
Thanks for pointing out the bugs. Fixed with commit a7038dc. Closing this now.
