### ISSUE TITLE
Need Update MT6781

### ISSUE THREAD

**Issue by ianchopel** [bkerler/mtkclient#148]
.....Port - Device detected :)
Preloader - CPU: MT6781(Helio A22)
Preloader - HW version: 0x0
Preloader - WDT: 0x10007000
Preloader - Uart: 0x11002000
Preloader - Brom payload addr: 0x100a00
Preloader - DA payload addr: 0x200000
Preloader - Var1: 0xa
Preloader - Disabling Watchdog...
Preloader - HW code: 0x1066
Preloader - Target config: 0xe5
Preloader - SBC enabled: True
Preloader - SLA enabled: False
Preloader - DAA enabled: True
Preloader - SWJTAG enabled: True
Preloader - EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT: False
Preloader - Root cert required: False
Preloader - Mem read auth: True
Preloader - Mem write auth: True
Preloader - Cmd 0xC8 blocked: True
Preloader - HW subcode: 0x8a00
Preloader - HW Ver: 0xca00
Preloader - SW Ver: 0x0
Preloader - ME_ID: 57E043F4DBC720A0045ACD8BC9185FBD
PLTools - Kamakiri / DA Run
PLTools - Loading payload from generic_preloader_dump_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri..
Kamakiri - Done sending payload...
usb_class - USBError(5, 'Input/Output Error')
PLTools - Error, payload answered instead:
PLTools
PLTools - [LIB]: ←[31mError on sending payload: C:\mtk\mtkclient\payloads\generic_preloader_dump_payload.bin←[0m

**Comment by bkerler** [comment]
Double of #141. Closing this issue, please continue at #141
