### ISSUE TITLE
Preloader - Jumping to 0x200000 error on mt8127 tablet

### ISSUE THREAD

**Issue by bim777bis** [bkerler/mtkclient#15]
I have an old  chinese tablet, noname, bricked.
Its practically analog of amazon fire: same processor, gps/bt/wifi chip, power control, same flash and ram size.... So Im trying to fix it using your script.
At first it didnt want to connect at all (timed out). After I uncommented these lines:
    # self.cdc.setLineCoding(19200)
    # self.cdc.setcontrollinestate(RTS=True,DTR=True)
    # self.cdc.setbreak()
in Library/Port.py it actually got connected. Now I have another problem:
...
-DALegacy - Uploading stage 1...
-Preloader - Jumping to 0x200000
-USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5

and i have no idea how to fix it.
Any suggestions?

Thanks.

p.s. Logs, regular and with debug mode on attached.
[log_timedout.txt](https://github.com/bkerler/mtkclient/files/6759320/log_timedout.txt)
[log1.txt](https://github.com/bkerler/mtkclient/files/6759321/log1.txt)
[log.txt](https://github.com/bkerler/mtkclient/files/6759327/log.txt)

**Comment by bkerler** [comment]
Most probably the offset is wrong. Can you let me know which exact chipset you've got ?

**Comment by bim777bis** [comment]
Update.
Looks like any command, except empty one, fails at this point.
What is wrong?

Thanks

**Comment by bim777bis** [comment]
Chipset? Hm...
Thats all chips on the board:
mt8127a (1605-DACAH)
SK hynix (H5TC4G63CFR)   - 2 of em
Samsung (KLM8G1WEPD-B031)
mt6323LGA
mt6727N
thats it.

**Comment by bkerler** [comment]
Actually what command did you run ? It should have taken 0x201000 from config, but not 0x200000 (this pretty much fails)

**Comment by bim777bis** [comment]
Just python3 mtk.py
Also tried python3 mtk.py plstage --preloader=path_to_preloader_from_amazon_fire7_ford.bin
then it shows 0x00201000
Fails still...
Also changed address in script itself, just to check it, fail.

**Comment by bim777bis** [comment]
update.
My mistake, missed space, not 000000, 0x200000
-----
Ok, looks like your scripts got all info from mtk_allinone_da right.
Found script that parse allinone, this is what i got from it on mt8127:

--- file_offset, size, load_addr
  da_part0: [0x14a954, 0x00270, 0x80010000]  # 0x14a954-0x14abc4
  da_part1: [0x14abc4, 0x11a28, 0x00200000]  # 0x14abc4-0x15c5ec
  da_part2: [0x15c5ec, 0x388c4, 0x80000000]  # 0x15c5ec-0x194eb0
  da_part3: [0x0, 0x00000, 0x00000000]  # 0x0-0x0

This is where 0x00200000 comes from!
So, ive tried 0x00200000 and 0x00201000 with same result. As i wrote
before any command sent afrer uploading da part 1 results in usb in/out error.
Maybe there should be some extra step/sequence for mt8127?
I understand your script works without problems for other procesors, so there should
be some explanation for this.

**Comment by bkerler** [comment]
Ok, so two assumptions for you:
1. The preloader for the fire7 ford won't work for other devices with similar chipset. You need the right preloader.
2. If the device is a amazon fire7, it means you need to stay in bootrom, as preloader won't work.

**Comment by bim777bis** [comment]
I guess theres only one option left,
short vdd,clk,cmd to get into boot rom.
Will try :-)

**Comment by bkerler** [comment]
yes, and from brom, commit 1e0340b4edd12228d93625cca9aa302cdb5a4720 should work fine and pretty fast :)

**Comment by bim777bis** [comment]
Worked!
Shorted pin 28 on flash (vcc) and got into brom.
So i guess issue is closed.
Thanks.
