### ISSUE TITLE
boot loop after flashing magisk patched kernel image

### ISSUE THREAD

**Issue by MCredbear** [bkerler/mtkclient#152]
My phone is vivo y81 with mt6765,Android 8. After flashing the boot.patched created by the magisk you offered, it got boot loop(also tried official magisk,got the same result).I don't know how to get any log

**Comment by lpxx50117** [comment]
VIVO have second verify that you can't modify any images,
(VIVO解了bl也没用，底层会校验文件是不是官方文件，不用想着解bl了）

**Comment by MCredbear** [comment]
> VIVO have second verify that you can't modify any images, (VIVO解了bl也没用，底层会校验文件是不是官方文件，不用想着解bl了）

所以说，只要没有内核源码就没有卵用是吗（），现在没内核源码应该没法移植类原生了吧（）

**Comment by lpxx50117** [comment]
> > VIVO have second verify that you can't modify any images, (VIVO解了bl也没用，底层会校验文件是不是官方文件，不用想着解bl了）
> 
> 所以说，只要没有内核源码就没有卵用是吗（），现在没内核源码应该没法移植类原生了吧（）

之前Y67倒是可以移植第三方？Y81是安卓8了校验机制又不一样了

**Comment by bkerler** [comment]
Please use discussions for that. Issues are for issues on mtkclient only. Closing now.
