### ISSUE TITLE
Add support for G96 (mt6781)

### ISSUE THREAD

**Issue by DrtSinX98** [bkerler/mtkclient#153]
I pulled the BROM dump from my device with Helio g96 (mt6781) plox add support for it

Brom dump - https://raw.githubusercontent.com/DrtSin-EXP/artworks-1/master/brom_1066.bin

**Comment by bkerler** [comment]
It has been added. However they seem to have added additional security. Can you try and report back with the latest commit ?

**Comment by bkerler** [comment]
Double of #141 , closing now.
