### ISSUE TITLE
dm-verify error

### ISSUE THREAD

**Issue by BoBppy** [bkerler/mtkclient#156]
device:MT6761 Android9
OS:Windows8.1
Environment:Python3.10

i just used this tool to unlock bootloader,

> Python mtk xflash seccfg unlock

after booting,
i got a "dm-verify error,device will boot in 5s" and orange state

Even if used

' python mtk xflash seccfg lock '

it still remained "dm-verify error"

**Comment by bkerler** [comment]
That's not a mtkclient issue. DM-Verify error will happen if the device is unlocked, you will need to replace vbmeta as stated in the readme. If you use oppo based devices, you're doomed as they add their crappy non-typical android stuff preventing regular unlock.

**Comment by BoBppy** [comment]
@bkerler but i have tried xflash seccfg lock

**Comment by bkerler** [comment]
After relocking, you also need to wipe userdata and metadata and md_udc  as stated. As said, no mtkclient issue.

**Comment by BoBppy** [comment]
after my test,i found it would be perfect when i relocked via livedvd(v2)(even if remained empty vbmeta),but failed on Windows(almostly latest commit).
And i skipped wiping data,both unlock and lock.
