### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by RecSpeed** [bkerler/mtkclient#157]
How to bypass and auto meta mode please ?

**Comment by MofadalAltyeb** [comment]
@RecSpeed 
Can you explain what you mean exactly by (auto meta mode)?

**Comment by RecSpeed** [comment]
> @RecSpeed Can you explain what you mean exactly by (auto meta mode)?

without maui meta , auto boot META MODE , 
example : phyton mtk payload meta - phyton mtk meta ..

**Comment by MofadalAltyeb** [comment]
you mean booting to meta mode to use Modem Meta Tool!, 
if your device can connect in preloader mode , 
or brom mode without SLA enabled , 
you don't need to use bypass payload for meta mode entering.
if SLA enabled, can you can bypass auth, then use UART settings in MMT and select the COM ,
i think if you used USB settings the tool will wait for usb device insering (hot-plug).

**Comment by RecSpeed** [comment]
> you mean booting to meta mode to use Modem Meta Tool!, if your device can connect in preloader mode , or brom mode without SLA enabled , you don't need to use bypass payload for meta mode entering. if SLA enabled, can you can bypass auth, then use UART settings in MMT and select the COM , i think if you used USB settings the tool will wait for usb device insering (hot-plug).


I want to enter "meta mode" without using any software

**Comment by MofadalAltyeb** [comment]
oh, ok hope boot mode entering/switch feature will be implanted soon @bkerler .

**Comment by RecSpeed** [comment]
mtk_daxflash.py     
    SET_RESET_KEY = 0x020004
        SET_HOST_INFO = 0x020005
        **SET_META_BOOT_MODE = 0x020006**   ?
        SET_EMMC_HWRESET_PIN = 0x020007
        SET_GENERATE_GPX = 0x020008

**Comment by bkerler** [comment]
What is meta mode needed for?

**Comment by RecSpeed** [comment]
> Meta mod ne için gereklidir?

I've been researching for "meta mode" commands and if I can get it to "meta mode" I'll go one step further. thanks @bkerler

**Comment by bkerler** [comment]
What do you mean by "one step further" ?

**Comment by RecSpeed** [comment]
> What do you mean by "one step further" ?

sorry I m speak bad english lan. I meant phobia and curiosity

**Comment by RecSpeed** [comment]
Is what I want possible?

**Comment by etmatrix** [comment]
I use [this](https://gist.github.com/plugnburn/b3b0bcfd926c48ec5373bea84ce59337) gist for enter in meta mode without windows tool.
It's a python script as mtkclient

**Comment by RecSpeed** [comment]
> 
file mtk-bootseq.py METAMETA
line 19, in <module>
    from serial import Serial
ModuleNotFoundError: No module named 'serial'

**Comment by etmatrix** [comment]
you should install the module pyserial

`pip install pyserial`

**Comment by RecSpeed** [comment]
> you should install the module pyserial
> 
> `pip install pyserial`

I m Already installed  bro

**Comment by etmatrix** [comment]
Which OS are you using?
In many linux distributions there are 2 versions of python 2.7 and 3.x, the script use python3 so the module pyserial must be installed in python3.
You should verify if use pip or pip3 or install the module with commands of your distributions.
There are many linux distrubutions is not easy write all informations.

**Comment by RecSpeed** [comment]
> Hangi işletim sistemini kullanıyorsunuz? Birçok linux dağıtımında python 2.7 ve 3.x'in 2 sürümü vardır, komut dosyası python3'ü kullanır, bu nedenle pyserial modülü python3'e kurulmalıdır. Pip veya pip3 kullanıp kullanmadığınızı doğrulamalı veya dağıtımlarınızın komutlarıyla modülü kurmalısınız. Birçok linux dağıtımı var, tüm bilgileri yazmak kolay değil.

python 3.9 WINDOWS 10 x64 Edu

**Comment by etmatrix** [comment]
I use linux but I tested for you on windows 10, I installed python 3.9.9 and after I installed pyserial the import of module serial works.
In directory scripts there are both pip.exe and pip3.exe.
Try to execute `pip list` you should see a similar output

```
Package    Version
---------- -------
pip        21.2.4
pyserial   3.5
setuptools 58.1.0
```
if pyserial is missing something is wrong in your installation

**Comment by RecSpeed** [comment]
thank you for test @etmatrix 

pip       21.3.1
pyserial    3.5
setuptools  49.2.1

me screen 
https://ibb.co/19rwXwd
https://ibb.co/CmPGtS6

**Comment by bkerler** [comment]
I will try to add meta mode soon.

**Comment by bkerler** [comment]
I've reversed meta mode .... and SET_META_BOOT_MODE  has nothing to do with meta commands like "FASTBOOT".

**Comment by bkerler** [comment]
meta mode stuff has been added in commit e6458de (both xflash meta boot mode and preloader meta cmd)

**Comment by bkerler** [comment]
metamode via payload has been added as well in 534c0d0

example : ./mtk payload --metamode FASTBOOT

**Comment by RecSpeed** [comment]
> metamode via payload has been added as well in [534c0d0](https://github.com/bkerler/mtkclient/commit/534c0d0a973b50cb73e7d3b435bdab8a221510ad)
> 
> example : ./mtk payload --metamode FASTBOOT

Thank you sir, I'm try "mtk payload --metamode METAMETA" or "FASTBOOT" but phone is shutdown or restart not entered meta mode 

> 
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x813
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      35C07F0386360A760ED880C5F473709F
Preloader - SOC_ID:                     C83C394229BF0C17EF5E6420954320DB60BF3630FF763290F5C8E1E69FB6AE8E
PLTools - Loading payload from mt6785_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\RecSpeedPC\Desktop\RRR\data\mtkclient\payloads\mt6785_payload.bin
Port - Device detected :)
META - Status: Waiting for PreLoader VCOM, please connect mobile
>

**Comment by RecSpeed** [comment]
@bkerler

**Comment by deyvs02** [comment]
> I'm tested Note 8 pro , Note 10s and Infinix x682 not entered meta mode. device is shutdown. Port - Device detected :) META - Status: Waiting for PreLoader VCOM, please connect mobile

I can put any device in meta-mode via the command line, I would like to know which commands are accepted by the meta modem. I've tried several AT commands but without success. You have reset commands, serial repair, etc. I give you the meta-mode send command

**Comment by EruElm356** [comment]
How would I find the code for Samsung enable USB debugging in META MTK TOOl vXXX
