### ISSUE TITLE
[MT6877]Device has is either already unlocked or algo is unknown. Aborting.

### ISSUE THREAD

**Issue by dstmath** [bkerler/mtkclient#159]
Port - Device detected :)
Preloader - 	CPU:			MT6877(Dimensity 900)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x959
Preloader - Target config:		0xe5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			1824AC6E2112B0FDB36F73E76EA51077
Preloader - SOC_ID:			B53705A5A026B620FB9E213B23E2941842C62D44CA501D7E082725D324F06B0E
PLTools - Loading payload from mt6877_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/toor/code/mtkclient/mtkclient/payloads/mt6877_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AFAMBDAR
DAXFlash - UFS CID:      ad014839485131354146414d42444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ad014839485131354146414d42444152
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AFAMBDAR
DAXFlash - UFS CID:      ad014839485131354146414d42444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x59620
DAXFlash - DA Extensions successfully added
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate
xflashext
xflashext - [LIB]: [Device has is either already unlocked or algo is unknown. Aborting.

**Comment by dstmath** [comment]
[preloader_oplus6877.zip](https://github.com/bkerler/mtkclient/files/7561713/preloader_oplus6877.zip)

**Comment by dstmath** [comment]
[seccfg.zip](https://github.com/bkerler/mtkclient/files/7561738/seccfg.zip)

**Comment by bkerler** [comment]
Seems to be a duplicate of #54

**Comment by dstmath** [comment]
Still `Device has is either already unlocked or algo is unknown. Aborting.` on MT6877.
@bkerler
