### ISSUE TITLE
[MT6582] Problem when rooting

### ISSUE THREAD

**Issue by joaopa00** [bkerler/mtkclient#160]
Hello. I have an old Archos 101b copper tablet (running android 4.4.2). I would like to root it. I try to use mtkclient.
But at the first step, I already have an error. Have a look at the console output.
Thanks  in advance for any help to fix my problem.

[log.txt](https://github.com/bkerler/mtkclient/files/7565072/log.txt)

**Comment by PizzaG** [comment]
Main - BOOTIMG

**Comment by bkerler** [comment]
As pizzag said, the partition is called BOOTIMG not boot.

**Comment by joaopa00** [comment]
And for the partition vbmeta?

**Comment by PizzaG** [comment]
> And for the partition vbmeta?

that's too old of a device to have vbmeta artition, there isn't one for your device.  No need to worry about it

**Comment by joaopa00** [comment]
Good to know

**Comment by RecSpeed** [comment]
your device sofware older android version

**Comment by bkerler** [comment]
Closing this now, no issue with mtkclient. Please use discussions for stuff relating android.
