### ISSUE TITLE
multiple commands without exiting flash mode

### ISSUE THREAD

**Issue by deyvs02** [bkerler/mtkclient#170]
there is the possibility of performing multiple commands without exiting flash mode 
example: 
mtk printgpt 
mtk e userdata 
Whenever I try to do it, I get the following result. the first command is carried out without errors but the second is not carried out and I get errors and then I get the message on windows that the usb is not recognized so I have to remove the cable and perform command by command

**Comment by bkerler** [comment]
Duplicate of #42
