### ISSUE TITLE
Write RPMB Failed

### ISSUE THREAD

**Issue by ianchopel** [bkerler/mtkclient#175]
..Port - Device detected :)
Preloader - CPU : MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader - WDT : 0x10007000
Preloader - Uart : 0x11002000
Preloader - Brom payload addr : 0x100a00
Preloader - DA payload addr : 0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code : 0x766
Preloader - Target config:              0xe5
Preloader - SBC enabled : True
Preloader - SLA enabled : False
Preloader - DAA enabled : True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      EE845F1E8A538E8B005F07A432E5FE59
Preloader - SOC_ID:                     C76D721DE47C3497623B04E8F52FEB9D39E44F15A79F5D24BCED6D4B5469D733
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Chopel Flasher\Documents\Project VB\WindowsApplication9\bin\x64\Release\Data\Port\payloads\mt6765_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 90014a6843396150
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         hC9aP3
DAXFlash - EMMC CID : 90014a6843396150330110011b6d3829
DAXFlash - EMMC Boot1 Size : 0x400000
DAXFlash - EMMC Boot2 Size : 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size : 0x1000000
DAXFlash - EMMC USER Size : 0xe8f800000
DAXFlash - DA-CODE      : 0x666D0
DAXFlash - DA Extensions successfully added
xflashext - Derived rpmb key:d3d76d12accb859fea41e9c510927449efc7d46d3efcc1f79a37e7b98040d061
Done |--------------------------------------------------| 0.0% RPMB written (Sector 0x0 of 0x10000) 0.00 MB/sxflashext
xflashext - [LIB]: ←[31mCouldn't write rpmb at sector 0.←[0m

**Comment by jamb84** [comment]
most likely related to the hmac issues that are still existing after rpmb init was repaired.

**Comment by bkerler** [comment]
Issue #29 already exists. Closing.
