### ISSUE TITLE
DM-Verity Question?

### ISSUE THREAD

**Issue by ra997mi** [bkerler/mtkclient#177]
Hello guys, thanks for this greet tool, I was able to unlock bootloader and root my phone  [Oppo Reno 5F](https://www.gsmarena.com/oppo_reno5_f-10763.php)

i have a simple question: 
how to get rid of this message on boot (when removing the root  and relocking the bootloader)
[dm-verity corruption](https://static.c.realme.com/IN/thread/1308318711483990016.jpg)

i did a full dump before rooting using:

`python mtk rl out`

im keep getting the dm-verity error even when locking bootloader + flashing all stock dump && wipe data
`python mtk da seccfg lock` && `python mtk wl out`

**Comment by bkerler** [comment]
No chance to get it removed, as long as secure boot is enabled. Oppo does that intentionally within LK.

**Comment by NCLnclNCL** [comment]
> Hello guys, thanks for this greet tool, I was able to unlock bootloader and root my phone [Oppo Reno 5F](https://www.gsmarena.com/oppo_reno5_f-10763.php)
> 
> i have a simple question: how to get rid of this message on boot (when removing the root and relocking the bootloader) [dm-verity corruption](https://static.c.realme.com/IN/thread/1308318711483990016.jpg)
> 
> i did a full dump before rooting using:
> 
> `python mtk rl out`
> 
> im keep getting the dm-verity error even when locking bootloader + flashing all stock dump && wipe data `python mtk da seccfg lock` && `python mtk wl out`

you know fix ?
