### ISSUE TITLE
Oppo based devices - Unlock bootloader not supported

### ISSUE THREAD

**Issue by ra997mi** [bkerler/mtkclient#179]
Unlock bootloader, rooting seems not be working anymore on new Oppo reno 5f A27 update
it was working well on old Version A25

When doing the unlock bootloader, rooting, I'm getting:

[the current image (boot/recovery) have been destroyed and cannot boot](https://img.gem-flash.com/images/51670737399160196818.png)

Note: when unlocking bootloader  only on A25 i was getting (this device is unlocked and cannot be trusted) when rebooting
but on A27 I'm not getting it, and in developer options i was able to enable/disable OEM unlock switch
(on A25 its disabled afer unlocking)

Any Idea?
Thanks

**Comment by ra997mi** [comment]
Not sure if this files are helpful but here:

Dump preloader: [preloader_oppo6779](https://www.mediafire.com/file/y4erz148a42jfez/preloader_oppo6779.bin/file)
Dump brom: [brom_MT6779_725](https://www.mediafire.com/file/409ihdh0u7wbvgk/brom_MT6779_725.bin/file)
Dump A27 Boot [boot.img](https://www.mediafire.com/file/ezn4jte6dj5ez63/boot.img/file)
Dump A27 vbmeta [vbmeta.img](https://www.mediafire.com/file/hcxyh6e27gwzdbe/vbmeta.img/file)

**Comment by MlgmXyysd** [comment]
![image](https://user-images.githubusercontent.com/17919858/144811944-4d48fe2f-b802-4c14-8c04-a9b4fe88e564.png)
Same here. @bkerler 
OPPO Reno 7 Pro PFDM00domestic_11_A.09_202111060645030
[dump_oplus6893_preloader_brom_seccfg.zip](https://github.com/bkerler/mtkclient/files/7659221/dump_oplus6893_preloader_brom_seccfg.zip)

**Comment by Nunovaz9117** [comment]
Any news about Oppo bootloaders ?

**Comment by Nunovaz9117** [comment]
Any news about Oppo bootloaders ?

**Comment by Peterlai123** [comment]
Any new way to root oppo phones?
