### ISSUE TITLE
Utility work on Windows 10 x32

### ISSUE THREAD

**Issue by marat2509** [bkerler/mtkclient#18]
I was able to get the utility running on a 32-bit PC. I did it by recompiling libusb engine.
I just replaced the file with my compiled one and it worked. It remains only to configure the autoselection of the desired libusb for the capacity of the system

The libraries themselves: 
[dll32.zip](https://github.com/bkerler/mtkclient/files/7006415/dll32.zip)

Proof of complete work (lancelot, MT6768):
[logs.txt](https://github.com/bkerler/mtkclient/files/7006439/logs.txt)

**Comment by bkerler** [comment]
Hi, yes, 32bit does work, but it might cause several issues as usbdk library doesn't offer full support for it. Please try commit d5923b1

**Comment by marat2509** [comment]
![Безымянный](https://user-images.githubusercontent.com/52219238/130313724-c8ebee8c-26a7-434a-bbf5-32d52f409170.png)

We can try:
`import platform
bit = platform.architecture()[0]
if bit=="64bit":
    self.backend = usb.backend.libusb1.get_backend(find_library=lambda x: "libusb-1.0.dll")
else:
    self.backend = usb.backend.libusb1.get_backend(find_library=lambda x: "libusb32-1.0.dll")`

**Comment by marat2509** [comment]
Please try commit https://github.com/bkerler/mtkclient/commit/91c93e1fb38c75f65d3baa490b3aec1a02d66a93 :)

Ok, i try

**Comment by bkerler** [comment]
So, does it work ?

**Comment by marat2509** [comment]
> So, does it work ?

Unfortunately, due to my health, I have no opportunity to try to check now.

**Comment by bkerler** [comment]
No worries, get well soon ;)

**Comment by marat2509** [comment]
Works! Thanks!
