### ISSUE TITLE
OPPO F5 youth F7 F9 - testpoint needed

### ISSUE THREAD

**Issue by chandarakk** [bkerler/mtkclient#182]
i try many F5 f7 f9 with mtk client alway 

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

..........Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m

Port - Hint:

but with testpoint all work well any other way without disembly the phone?

**Comment by bkerler** [comment]
Guess you will need to use a testpoint.

**Comment by chandarakk** [comment]
> Guess you will need to use a testpoint.

i know testpoint stantalone work with mtkclient but other tool work with meta factory reset stantalone no disembly so any new work with meta mod ?

**Comment by NeonzGamingYT** [comment]
yeah i got the same error like you on my oppo F5

**Comment by NeonzGamingYT** [comment]
do you know where is testpoint for oppo F5 cuz i can disassemble the phone

**Comment by bkerler** [comment]
No, sorry. Please search on the internet for a possible pinout.

**Comment by NeonzGamingYT** [comment]
> No, sorry. Please search on the internet for a possible pinout.

ok
