### ISSUE TITLE
Cant read boot or etc on biloba

### ISSUE THREAD

**Issue by marat2509** [bkerler/mtkclient#19]
Trying on Biloba (RN8 2021, MT6768):
Works: printgpt, payload
the rest doesn't work
[logs.log](https://github.com/bkerler/mtkclient/files/6998799/logs.log)
Video: https://ghostmirror.hitesh920.workers.dev/0://bandicam%202021-08-17%2012-35-07-712.mp4 (login and pass: ghostmirror)

Trying on Merlin (RN9, MT6768):
success!

[successmerlin_without_debug.txt](https://github.com/bkerler/mtkclient/files/6998831/successmerlin_without_debug.txt)

_Originally posted by @marat2509 in https://github.com/bkerler/mtkclient/issues/15#issuecomment-900150325_

**Comment by bkerler** [comment]
Hi, please try commit 3850c55

**Comment by bkerler** [comment]
Commit f0c6ad1 also got improvements.
