### ISSUE TITLE
Lephone V8 for mt6737m processor cannot use this tool

### ISSUE THREAD

**Issue by wangst2005** [bkerler/mtkclient#196]
Before Android 5.1, you can directly oemunlock, but later upgraded 6.0 and added verification, resulting in an error in entering oemunlock and an error in the boot prompt of the third-party img. It is difficult to do and cannot be degraded

The following is the CMD output

........Port - Device detected :)Preloader -     CPU:                    MT6737M()Preloader -     HW version:             0x0Preloader -     WDT:                    0x10212000Preloader -     Uart:                   0x11002000Preloader -     Brom payload addr:      0x100a00Preloader -     DA payload addr:        0x201000Preloader -     CQ_DMA addr:            0x10217c00Preloader -     Var1:                   0x28Preloader - Disabling Watchdog...Preloader - HW code:                    0x335Preloader - Target config:              0x1Preloader -     SBC enabled:            TruePreloader -     SLA enabled:            FalsePreloader -     DAA enabled:            FalsePreloader -     SWJTAG enabled:         FalsePreloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  FalsePreloader -     Root cert required:     FalsePreloader -     Mem read auth:          FalsePreloader -     Mem write auth:         FalsePreloader -     Cmd 0xC8 blocked:       FalsePreloader - Get Target infoPreloader 

>

**Comment by wangst2005** [comment]
![Uploading IMG_20211221_002257.jpg…]()

**Comment by wangst2005** [comment]
![IMG_20211221_002257](https://user-images.githubusercontent.com/96435884/146799540-f1f90094-db11-4586-abad-52b5a0fd3ec5.jpg)

**Comment by bkerler** [comment]
Sorry, but your device is currently unsupported for unlocking.
