### ISSUE TITLE
can not use on macos

### ISSUE THREAD

**Issue by bukaixyz** [bkerler/mtkclient#199]
<img width="576" alt="屏幕快照 2021-12-24 下午9 09 25" src="https://user-images.githubusercontent.com/85857425/147382320-f0f81e02-b4af-4d81-8ea6-f1d890631e64.png">

**Comment by keerttttt** [comment]
You can try to use kamakiri instead of the default kamakiri2. I made a patch to make kamakiri 1 default on Mac, but I think it's not live yet.

**Comment by keerttttt** [comment]
Should be fixed after the last commits :) Try again please.

**Comment by bkerler** [comment]
Closing this issue.
