### ISSUE TITLE
Can you manually modify the seccfg partition?

### ISSUE THREAD

**Issue by qianmo-xw** [bkerler/mtkclient#203]
For some cases, such as windows7, authorization bypass works well, but unlocking the bootloader is not so optimistic. I wonder if it is possible to add a separate command to the tool to implement changes to the seccfg partition using sp_flash read back, and then write back to the partition. BL unlock

**Comment by bkerler** [comment]
you can simply use read and write partition command for that.

**Comment by qianmo-xw** [comment]
> you can simply use read and write partition command for that.

Yes, but I don’t know that some Windows 7 computers will have various problems. I have tried several Internet cafes that are not compatible, so I think there is a separate command to modify the seccfg partition so that mtkcilent is not compatible. A good computer is only used for algorithm unlocking.

**Comment by qianmo-xw** [comment]
> you can simply use read and write partition command for that.

I mean, add a separate command line for mtkcilent to manually specify the readback of the seccfg file to achieve unlocking. is it possible?

**Comment by bkerler** [comment]
the unlocking is done by the phone itself. There is no internet needed for that. And no, you can't just do the unlocking by software.
If auth bypass works, unlocking will as well, if the device is supported.

**Comment by qianmo-xw** [comment]
> the unlocking is done by the phone itself. There is no internet needed for that. And no, you can't just do the unlocking by software. If auth bypass works, unlocking will as well, if the device is supported.

I find seccfg is about unlockbootloader partition，your mean  unlock by the phone itself，not read seccfg and direct fix this partition，then write seccfg to phone  the bootloader will be unlock？

**Comment by bkerler** [comment]
Right. Due to the hw crypto being used you can only patch seccfg using the device itself.

**Comment by qianmo-xw** [comment]
> Right. Due to the hw crypto being used you can only patch seccfg using the device itself.

Ok, thank you answer.Now I understand
