### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by SoeHtikeAung199** [bkerler/mtkclient#206]
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2

**Comment by SmallPP420** [comment]
i think u might have to downgrade to python 3.8

**Comment by keerttttt** [comment]
Or python 3.9 should be an option too..

**Comment by bkerler** [comment]
@SoeHtikeAung199 we need more details about your os, used python version, etc. Otherwise I will need to close this issue as it's not an issue of mtkclient itself but your setup.

**Comment by cples408** [comment]
Windows 8.1 x64  Python 3.10.1 
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)

**Comment by bkerler** [comment]
you can download and install the needed windows wheels either via pip or from here :
https://download.qt.io/official_releases/QtForPython/

**Comment by bkerler** [comment]
https://download.qt.io/official_releases/QtForPython/pyside6/shiboken6-6.2.2.1-6.2.2-cp36.cp37.cp38.cp39.cp310-none-win_amd64.whl
https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.2.2.1-6.2.2-cp36.cp37.cp38.cp39.cp310-none-win_amd64.whl

**Comment by cples408** [comment]
Python 3.10.1 and Pyside6 everything works

**Comment by bkerler** [comment]
Closing this now, as users have reported it to work as expected.
