### ISSUE TITLE
Can't Wire oppo_custom

### ISSUE THREAD

**Issue by trancullong** [bkerler/mtkclient#21]
DAXFlash - [LIB]: [31mError on sending parameter, status 0xc002000c.[0m
Wrote oppo_custom.bin to sector 412736 with sector count 2048.

**Comment by bkerler** [comment]
Just because you see the status 0xc002000c error, it doesn't mean it failed to write.

**Comment by trancullong** [comment]
> Chỉ vì bạn thấy trạng thái 0xc002000c lỗi, không có nghĩa là nó không ghi được.

Nvdata Nvaram oppo_custom Can Not Wire | Not completed

**Comment by bkerler** [comment]
please share a full debug log so we can see what might have failed.

**Comment by bkerler** [comment]
Error code c002000c means : Write not allowed

**Comment by trancullong** [comment]
> Error code c002000c means : Write not allowed

Yes, these are the partitions that are not allowed to write Sp Flash Tool also error when writing these partitions...but somehow Unlocktool or Hydra Tool write these partitions successfully.

**Comment by MofadalAltyeb** [comment]
> > Error code c002000c means : Write not allowed
> 
> Yes, these are the partitions that are not allowed to write Sp Flash Tool also error when writing these partitions...but somehow Unlocktool or Hydra Tool write these partitions successfully.

to be able to write oppo_custom, nvdata, opporeserve , etc.
you need bootloader to be unlocked, or verification disabled.
or need to use offical da which available only via hw/seller-vendor,
these tools you mentioned disable verification before write such partitions.

**Comment by awsaxf** [comment]
Switch to high-speed mode to solve this problem, or remove this verification!

**Comment by bkerler** [comment]
What do you mean by high-speed mode ? Most likely the gpt or pmt has flags which partitions may not be written.

**Comment by bkerler** [comment]
Please try latest commit 05833f1, should work now.
