### ISSUE TITLE
usb_class - [LIB]: Couldn't get device configuration.

### ISSUE THREAD

**Issue by bartlomiejduda** [bkerler/mtkclient#211]
Hi, after holding volume + and - buttons and connecting a USB cable I'm getting this error:
usb_class - [LIB]: ←[31mCouldn't get device configuration.←[0m

I'm using instructions from this guide https://forum.xda-developers.com/t/guide-unbrick-realme-8i-unbrick-free-without-auth-rmx3151.4370619/

And it happens very often on step 5:
"Now power off the phone and connect the phone while holding volume + and - (Don't leave the buttons until the bypass is done)"

But sometimes it kinda works (?), because I'm getting "Successfully sent payload" message, but after that Python is crashing - should this happen?

Do you know what is the real issue here and how to solve it?

**Comment by bartlomiejduda** [comment]
Ok, it seems that this issue completely dissapeared after I have installed proper USB drivers from the guide and then restarted the system on my computer AND restarted the phone.

After that steps for me were as below:
1. open "cmd.exe" from the "mtkclient-main" directory
2. Run command from the guide (python mtk ...)
3. Hold volume + and - buttons
4. While holding the buttons, connect phone with the USB cable.

You can close this issue, I think. Sorry for the trouble. :)

**Comment by bkerler** [comment]
Thanks for reporting :) Closing the issue now.
