### ISSUE TITLE
GUI Overflow error

### ISSUE THREAD

**Issue by Aztorius** [bkerler/mtkclient#214]
Hi ! Just a small bug with the GUI.

This is a GUI only issue and it does not prevent from using mtkclient.

```
/MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2436890624 exceeds limits of type  [signed] "i" (4bytes).
  self.guiprogress(pos)
OverflowError
Traceback (most recent call last):
  File "/MTK/mtkclient/mtk_gui", line 196, in updateProgress
    self.updateState()
  File "/MTK/mtkclient/mtk_gui", line 161, in updateState
    convert_size(self.Status["currentPartitionSizeDone"]) + " / " + \
  File "/MTK/mtkclient/mtkclient/gui/toolkit.py", line 93, in convert_size
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
```

**Comment by Col-Serra** [comment]
Same here CPU Hardware : MT6762V/WD windows
﻿File "C:\mtkclient\mtkclient\gui\toolkit.py", line 93, in convert_size
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
C:\mtkclient\mtkclient\Library\utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 3666345984 exceeds limits of type  [signed] "int" (4bytes).
  self.guiprogress(pos)
OverflowError
Traceback (most recent call last):
  File "C:\mtkclient\mtk_gui", line 196, in updateProgress
    self.updateState()
  File "C:\mtkclient\mtk_gui", line 161, in updateState
    convert_size(self.Status["currentPartitionSizeDone"]) + " / " + \
  File "C:\mtkclient\mtkclient\gui\toolkit.py", line 93, in convert_size
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
C:\mtkclient\mtkclient\Library\utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 3670736896 exceeds limits of type  [signed] "int" (4bytes).
  self.guiprogress(pos)
Traceback (most recent call last):
  File "C:\mtkclient\mtk_gui", line 196, in updateProgress
    self.updateState()
  File "C:\mtkclient\mtk_gui", line 161, in updateState
    convert_size(self.Status["currentPartitionSizeDone"]) + " / " + \
  File "C:\mtkclient\mtkclient\gui\toolkit.py", line 93, in convert_size
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
OverflowError
C:\mtkclient\mtkclient\Library\utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 3675062272 exceeds limits of type  [signed] "int" (4bytes).
  self.guiprogress(pos)
OverflowError
Traceback (most recent call last):
  File "C:\mtkclient\mtk_gui", line 196, in updateProgress
    self.updateState()
  File "C:\mtkclient\mtk_gui", line 161, in updateState
    convert_size(self.Status["currentPartitionSizeDone"]) + " / " + \
  File "C:\mtkclient\mtkclient\gui\toolkit.py", line 93, in convert_size
    i = int(math.floor(math.log(size_bytes, 1024)))
ValueError: math domain error
C:\mtkclient\mtkclient\Library\utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 3679453184 exceeds limits of type  [signed] "int" (4bytes).
  self.guiprogress(pos)
OverflowError
Traceback (most recent call last):
  File "C:\mtkclient\mtk_gui", line 196, in updateProgress
    self.updateState()

**Comment by bkerler** [comment]
Interesting, seems to be another windows issue. Just tested the linux gui without issues. Will have a closer look.

**Comment by bkerler** [comment]
Please try if commit b64801f81c6b8faed19eb0761138ddb19a535e06 solves your issue

**Comment by Aztorius** [comment]
It doesn't work. I'm running it on Linux.
When reading a big partition (several GB) this error shows up after some time (when the overflow occurs).
```
/MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2708471808 exceeds limits of type  [signed] "i" (4bytes).
  self.guiprogress(pos)
OverflowError
/MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2713714688 exceeds limits of type  [signed] "i" (4bytes).
  self.guiprogress(pos)
OverflowError
/MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2718957568 exceeds limits of type  [signed] "i" (4bytes).
  self.guiprogress(pos)
OverflowError
```
This is a capture of the dump (userdata is still dumping) :
![image](https://user-images.githubusercontent.com/6351814/148226272-3cb6198b-c097-4a1b-9bf8-574e27f0ea44.png)

**Comment by bkerler** [comment]
Yeah I think I found the reason why. Gonna fix it.

**Comment by Col-Serra** [comment]
> It doesn't work. I'm running it on Linux. When reading a big partition (several GB) this error shows up after some time (when the overflow occurs).
> 
> ```
> /MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2708471808 exceeds limits of type  [signed] "i" (4bytes).
>   self.guiprogress(pos)
> OverflowError
> /MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2713714688 exceeds limits of type  [signed] "i" (4bytes).
>   self.guiprogress(pos)
> OverflowError
> /MTK/mtkclient/mtkclient/Library/utils.py:113: RuntimeWarning: libshiboken: Overflow: Value 2718957568 exceeds limits of type  [signed] "i" (4bytes).
>   self.guiprogress(pos)
> OverflowError
> ```
> 
> This is a capture of the dump (userdata is still dumping) : ![image](https://user-images.githubusercontent.com/6351814/148226272-3cb6198b-c097-4a1b-9bf8-574e27f0ea44.png)

It still successfully dumps though instead of getting stuck like before

**Comment by bkerler** [comment]
I haven't updated the relevant parts, please wait

**Comment by Aztorius** [comment]
With the latest version it works very well !
Thank you.
