### ISSUE TITLE
support request for mt6762 chipset

### ISSUE THREAD

**Issue by ghost** [bkerler/mtkclient#222]
the tool runs fine without any errors but after booting the phone, there is no effect on the bootloader unlock status. I did some research and found out that my redmi 6a had a mt6762 chipset which isn't currently supported by mtkclient. i request you to add support for this chipset as soon as possible.
I have tried unlocking the bootloader using fastboot after that too.
![image](https://user-images.githubusercontent.com/74340401/149288868-87193182-cc60-43ad-83aa-e1f5930e0d09.png)

[https://en.wikichip.org/wiki/mediatek/helio/mt6762m](url)
[
![image](https://user-images.githubusercontent.com/74340401/149286292-ddaa204d-e331-4592-ba00-71bea333b485.png)
](url)

**Comment by lpxx50117** [comment]
Redmi 6/6A?These two phones using devinfo to control the bootloader unlock state,but mtkclient only support seccfg.So you should use another third-party modify mtkclient to unlock.

**Comment by Kody-K** [comment]
Yes, it's a Redmi 6A. What third party clients are you talking about ?
