### ISSUE TITLE
Need CMD Project update Also

### ISSUE THREAD

**Issue by samuel1003** [bkerler/mtkclient#227]
I tested mtk_gui and many improvements done like doing multiple operation without reconnect cable.
But i use your tool as complement for my app. I know many more doing so.

We need your mtk_gui improvements also for CMD, i tried python.exe mtk_gui payload but only able to send 1 command.
If you can add both using way would be amazing.

**Comment by nabicapar** [comment]
Yes, I have the same request.
There is also a request one after the other, we have to remove and plug the cable in every transaction.

**Comment by bkerler** [comment]
That issue seems to be windows and maybe driver related. Tested under Linux and not found any issue.

**Comment by schizoidcock** [comment]
> That issue seems to be windows and maybe driver related. Tested under Linux and not found any issue.

for the new gui it works fine without the need of reconnecting the device but when you try the cmd way you have to disconnect the device, run the new command that you want and then reconnect the device

**Comment by samuel1003** [comment]
> That issue seems to be windows and maybe driver related. Tested under Linux and not found any issue.

If driver related would no work either using your grafic tool. It seems you added some improvements, but we are unable to use this changes using the existing cmd tool.

**Comment by bkerler** [comment]
What device, mode (xflash or legacy) and os is affected ? I've tested cmd version under Linux, both legacy and xflash work fine for me.

**Comment by schizoidcock** [comment]
i mean the commands are not the issue, the issue is for example you read a partition and after the partition is read, you have to disconnect the device to do another operation for example erase a partition or unlock bootloader, when that doesnt happen with the gui interface, device just need to be plugged in and you can do any operation one after another

**Comment by bkerler** [comment]
mhmm sounds like the device does expect some kind of ack or data wasn't read fully. But I need to know if xflash or legacy is affected. On my devices (both legacy and xflash) I do not have any issue at all.

**Comment by schizoidcock** [comment]
all the commands are affected, if you as a said connect a device and read or erase or unlock bl at the end of the operation you need to disconnect the device and write the next command then reconnect it to be able to do the next operation.
