### ISSUE TITLE
Huawei MT6853:sending emi data error

### ISSUE THREAD

**Issue by lpxx50117** [bkerler/mtkclient#232]
Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      22BCD40D1440F18C601BE19576A8413E
Preloader - SOC_ID:                     AFBEA627354FFB5351F833AD545BF3FD56BC77747D7F255AB5FCE1A7958495F7
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: F:\phone\通用工具\mtkclient\mtkclient\payloads\mt6853_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x32
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM5V8001DM-B62
DAXFlash - UFS CID:      ce014b4d355638303031444d2d423632
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ce014b4d355638303031444d2d423632
DAXFlash - Sending emi data ...
DAXFlash
DAXFlash - [LIB]: [31mError on sending emi: unpack requires a buffer of 12 bytes[0m
DA_handler
DA_handler - [LIB]: [31mError uploading da[0m
Traceback (most recent call last):
  File "F:\phone\通用工具\mtkclient\mtk", line 695, in <module>
    mtk = Main(args).run()
  File "F:\phone\通用工具\mtkclient\mtkclient\Library\mtk_main.py", line 515, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "F:\phone\通用工具\mtkclient\mtkclient\Library\mtk_da_cmd.py", line 521, in handle_da_cmds
    data, guid_gpt = mtk.daloader.get_gpt()
AttributeError: 'NoneType' object has no attribute 'daloader'

Preloader::[preloader_k6853v1_64.zip](https://github.com/bkerler/mtkclient/files/7877021/preloader_k6853v1_64.zip)
@bkerler

**Comment by bkerler** [comment]
Will have a look

**Comment by grizlikoff** [comment]
Same issue on Xiaomi [(https://github.com/bkerler/mtkclient/issues/283#issue-1139707406`)]

**Comment by latvianjb** [comment]
oukitel wp17 (mt6585) stuck here...
DAXFlash - [LIB]: �[31mError on sending emi: unpack requires a buffer of 12 bytes
0037129426486 whatsapp
