### ISSUE TITLE
Redmi Note 11 Pro+/Xiaomi 11i Hypercharge is unable to be unlocked with mtkclient

### ISSUE THREAD

**Issue by duttajit50** [bkerler/mtkclient#233]
I have unlocked the bootloader of several Xiaomi based phones like Redmi note 10s, Poco F3 GT etc. Bootloader can be unlocked instantly using mtkclient. But, for Redmi note 11 pro/Xiaomi 11i, the tool shows success message. But the bootloader still in a locked state. It's the mtk d920 processor. Any valid solution??

**Comment by Rony-21** [comment]
Friend post here logs

**Comment by Zdxx21** [comment]
> Friend post here logs

Power off the phone before connecting. For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb. For preloader mode, don't press any hw button and connect usb. ..........Port - Device detected :) Preloader - CPU: MT6877(Dimensity 900) Preloader - HW version: 0x0 Preloader - WDT: 0x10007000 Preloader - Uart: 0x11002000 Preloader - Brom payload addr: 0x100a00 Preloader - DA payload addr: 0x201000 Preloader - CQ_DMA addr: 0x10212000 Preloader - Var1: 0xa Preloader - Disabling Watchdog... Preloader - HW code: 0x959 Preloader - Target config: 0xe5 Preloader - SBC enabled: True Preloader - SLA enabled: False Preloader - DAA enabled: True Preloader - SWJTAG enabled: True Preloader - EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT: False Preloader - Root cert required: False Preloader - Mem read auth: True Preloader - Mem write auth: True Preloader - Cmd 0xC8 blocked: True Preloader - Get Target info Preloader - BROM mode detected. Preloader - HW subcode: 0x8a00 Preloader - HW Ver: 0xca00 Preloader - SW Ver: 0x0 Preloader - ME_ID: 539FE5DAAD31E061F08BEF93F1D06F07 Preloader - SOC_ID: 19A4FA24AA8ABFDF15A56734D57221AE89C8972C0A967B4A6B01CBC1172D65F0 PLTools - Loading payload from mt6877_payload.bin, 0x264 bytes PLTools - Kamakiri / DA Run Kamakiri - Trying kamakiri2.. USB CORE ERROR [Errno 10060] Operation timed out Kamakiri - Done sending payload... PLTools - Error, payload answered instead:

**Comment by duttajit50** [comment]
![IMG_20220117_113903](https://user-images.githubusercontent.com/9468471/149940618-ec2bc124-bf35-4dfe-a7dc-4f824b58963d.jpg)
Here is what happened in BROM mode with my Xiaomi 11i Hypercharge device. It shows success but bootloader actually unable to unlock

**Comment by grizlikoff** [comment]
It is UnlockTool software. Mess forum
