### ISSUE TITLE
how about python mtk reboot fastboot/fastbootD ?

### ISSUE THREAD

**Issue by KFMDMSolutions** [bkerler/mtkclient#236]
would be great to have a option to boot in to fastboot and fastbootD with a command from brom mode.

**Comment by SpaceSaver** [comment]
That really depends on whether the mode that mtkclient takes advantage of supports rebooting to specific modes like fastboot does.

**Comment by benthetechguy** [comment]
You can get to fastboot with meta mode: `python mtk payload --metamode FASTBOOT`
