### ISSUE TITLE
Mtk 6877 not support

### ISSUE THREAD

**Issue by Zdxx21** [bkerler/mtkclient#237]
Power off the phone before connecting. For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb. For preloader mode, don't press any hw button and connect usb. ..........Port - Device detected :) Preloader - CPU: MT6877(Dimensity 900) Preloader - HW version: 0x0 Preloader - WDT: 0x10007000 Preloader - Uart: 0x11002000 Preloader - Brom payload addr: 0x100a00 Preloader - DA payload addr: 0x201000 Preloader - CQ_DMA addr: 0x10212000 Preloader - Var1: 0xa Preloader - Disabling Watchdog... Preloader - HW code: 0x959 Preloader - Target config: 0xe5 Preloader - SBC enabled: True Preloader - SLA enabled: False Preloader - DAA enabled: True Preloader - SWJTAG enabled: True Preloader - EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT: False Preloader - Root cert required: False Preloader - Mem read auth: True Preloader - Mem write auth: True Preloader - Cmd 0xC8 blocked: True Preloader - Get Target info Preloader - BROM mode detected. Preloader - HW subcode: 0x8a00 Preloader - HW Ver: 0xca00 Preloader - SW Ver: 0x0 Preloader - ME_ID: 539FE5DAAD31E061F08BEF93F1D06F07 Preloader - SOC_ID: 19A4FA24AA8ABFDF15A56734D57221AE89C8972C0A967B4A6B01CBC1172D65F0 PLTools - Loading payload from mt6877_payload.bin, 0x264 bytes PLTools - Kamakiri / DA Run Kamakiri - Trying kamakiri2.. USB CORE ERROR [Errno 10060] Operation timed out Kamakiri - Done sending payload... PLTools - Error, payload answered instead:

**Comment by Linssang** [comment]
did you solve this?
