### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by N4k4myr4** [bkerler/mtkclient#243]
### Discussed in https://github.com/bkerler/mtkclient/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **N4k4myr4** January 20, 2022</sup>
I accidentally plugged off phone while flashing preloader,I can't turn on my phone,I hold all three buttons for full 5 minutes and nothing happen. Any help? And I succesfully entered mtk again with good connection,what should I do now?

**Comment by Appleisbest** [comment]
did you make a backup of your phone before you tried flashing the preloader? If you did, you can restore your preloader with your backup.

**Comment by N4k4myr4** [comment]
Okay thanks everything is fine now <3
