### ISSUE TITLE
Speed USB

### ISSUE THREAD

**Issue by cples408** [bkerler/mtkclient#244]
Is it possible to increase the speed of downloading?
Now  mtkclient - 9 Mb/s    Flash Tool - 16 Mb/s   (windows 8.1 x64)

**Comment by bkerler** [comment]
We could increase the speed but that will also break compatibility with older mtk chipsets.

**Comment by cples408** [comment]
ok

**Comment by Khalylexe** [comment]
> We could increase the speed but that will also break compatibility with older mtk chipsets.

can you at least tell us how do we increase it

**Comment by Khalylexe** [comment]
> We could increase the speed but that will also break compatibility with older mtk chipsets.

can you at least tell us how do we increase it

**Comment by YaSSaX77** [comment]
import threading

class FlashReader:
    def __init__(self, mtk, xflash):
        self.mtk = mtk
        self.xflash = xflash

    def read_flash(self, start_addr, length, chunk_size=1024*1024):
        data = bytearray()
        threads = []
        for addr in range(start_addr, start_addr + length, chunk_size):
            thread = threading.Thread(target=self._read_chunk, args=(addr, chunk_size, data))
            threads.append(thread)
            thread.start()

        for thread in threads:
            thread.join()

        return data

    def _read_chunk(self, addr, chunk_size, data):
        chunk = self.xflash.read(addr, chunk_size)
        data.extend(chunk)

# Usage
mtk = ...  # Initialize MTK object
xflash = ...  # Initialize XFlash object
reader = FlashReader(mtk, xflash)
flash_data = reader.read_flash(0x0, 0x1000000)  # Read 16MB of flash
