### ISSUE TITLE
Please Update Payload for mt6877 [Dimensity 920]

### ISSUE THREAD

**Issue by ianchopel** [bkerler/mtkclient#246]
My Device
Vivo V23 5G [PD2167F]

log mtk payload
Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

......Port - Device detected :)
Preloader -     CPU:                    MT6877(Dimensity 900)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x959
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      66170C72265AFA7510F1356DEEC6FBEF
Preloader - SOC_ID:                     2C308013598E7674F573F91EA194D29821BADAACA34B6B118F6BD48F5650F15D
PLTools - Loading payload from mt6877_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
USB CORE ERROR
[Errno 10060] Operation timed out
Kamakiri - Done sending payload...
PLTools - Error, payload answered instead:

log in --debug mode
dumpbrom and dumpreloader
[logs.zip](https://github.com/bkerler/mtkclient/files/7921277/logs.zip)

preloader
[preloader_k6877v1_64.zip](https://github.com/bkerler/mtkclient/files/7921352/preloader_k6877v1_64.zip)

please check and fix it

**Comment by bkerler** [comment]
Not possible. It has been patched.
