### ISSUE TITLE
error reading hwcode + logs

### ISSUE THREAD

**Issue by ssbz** [bkerler/mtkclient#249]
[log.txt](https://github.com/bkerler/mtkclient/files/7929291/log.txt)
i have retrieved a couple files( boot and keys), but most of the time i get error reading hwcode or nand flash not found. Any ideas? Just checked, boot and preloader dumps are empty files.

**Comment by bkerler** [comment]
I'd guess bad usb cable or port.

**Comment by ssbz** [comment]
Actually it was a corrupted preloader file. Since that post I have
practiced extensively with your outstanding app and have recovered or
rooted half a dozen or so. It's been my experience that if you don't get
the preloader with the dumppreloader command you will spend a lot of
frustrating time finding the right one and most of the preloaders are like
coded enough to fool one with a partial execution then an error message.




⁰

**Comment by bkerler** [comment]
Thanks, good to know. I will also review the dumppreloader function for possible issues.

**Comment by ssbz** [comment]
I didn't mean your app was at fault. You have to find the correct vcom
drivers to apply in device manager, the wrong drivers result in a cache
error. I got the best results by using the dump preloader command first.
Your app has expanded my knowledge of personal computing systems, and
android operating system devices. Thank you.
