### ISSUE TITLE
boot_para partition

### ISSUE THREAD

**Issue by Raulsc9** [bkerler/mtkclient#252]
Hello friends, by mistake I flashed the wrong file in the "boot_para" partition and since then I can't power on the device at all. 

I have tried flashing all the partitions that the device has, but it still won't turn on.

It is a Xiaomi Redmi note 8 pro, and in its rom, there is no such partition.

In short; I get Mtkclient to recognise the device and I can flash the images, but there is no way to turn it on in normal mode or in download mode. 

Before this error, I managed to turn it on in fastboot mode, but when I rebooted, it stayed in hard brick again. 

Greetings!

**Comment by bkerler** [comment]
Try to find the firmware, if you are lucky, the boot_para just needs to be flashed again, if it's a device config partiiton, chances are low to unbrick your device.

**Comment by Raulsc9** [comment]
Thank you for your quick response. What happens is that the firmware of this device has no partition called "boot_para" and I can't find any information about it. I don't know if it's a translation problem...

And so far I'm still the same. The phone does absolutely nothing. I only manage to boot in "fastboot" mode, when I run this line:

python mtk plstage --preloader=preloader_begonia.bin

(If I'm not wrong, with that line I get the preloader to flash)

 When I boot into fastboot mode, I flash the whole rom from fastboot, but again, I can't get the phone to turn on at all. 

Translated with www.DeepL.com/Translator (free version)

**Comment by bkerler** [comment]
the boot para partition has boot parameters. try to ask someone with the same device to dump it, then reflash, hopefully will work.
