### ISSUE TITLE
Please Add feature to write preloader in MTK client tool 

### ISSUE THREAD

**Issue by nandbabai** [bkerler/mtkclient#253]
Hi Sir,
Please add a new feature to flash preloader from command line.

[preloader_k6877v1_64_NandPhone.zip](https://github.com/bkerler/mtkclient/files/7945954/preloader_k6877v1_64_NandPhone.zip)

**Comment by nandbabai** [comment]
@bkerler , Can you please update on this case.

**Comment by grizlikoff** [comment]
Can you support MT6877T ?

**Comment by nandbabai** [comment]
@bkerler , Hello sir, is there any progress on this case.

**Comment by bkerler** [comment]
Writing preloader is possible via mtk w preloader preloader.bin --parttype boot1

**Comment by bkerler** [comment]
And no, mt6877t won't be supported for now unless someone pushes a pr for it.
