### ISSUE TITLE
Preloader handshake fail

### ISSUE THREAD

**Issue by Sym8** [bkerler/mtkclient#254]
device nokia 5.1 plus (mtk6771) Android 10
Windows 10
 Preloader mode doesnt work and i get this error 

Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m
brom mode wroks but im unable to dump boot and vbmeta images.
 
I have looked and tried things mentioned in other threads like deleting mtk 5.1824 file
bypass tools etc and nothing has worked.

I can unlock and relock the bootloader but im not sure if it works since it says i should use it in preloader mode?

Preloader -     CPU:                    MT6771/MT8385/MT8183/MT8666(Helio P60/P70/G80)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x788
Preloader - Target config:              0xe1
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      03AA497758B7D8ABADF7C83D32A1B8DA
Preloader - SOC_ID:                     8B8A588C1E2D4CF48789EDF7A60689EFE53C7B82AB363669706E7871351C3C75
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6771_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Desktop\folder\mtkclient-main\mtkclient\payloads\mt6771_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: ←[33mDevice is in BROM mode. No preloader given, trying to dump preloader from ram.←[0m
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 150100474436424d
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         GD6BMB
DAXFlash - EMMC CID:        150100474436424d4201421f07f295d1
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x747c00000
DAXFlash - DA-CODE      : 0x888F0
DAXFlash - DA Extensions successfully added
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate
Progress: |██████████████████████████████████████████████████| 100.0% Write (Sector 0x1 of 0x1, ) 0.05 MB/s
DA_handler - Successfully wrote seccfg.

Is there any other way to dump boot and vbmeta img so i can root?

**Comment by bkerler** [comment]
Reading should work. What error do you get ?

**Comment by Sym8** [comment]
> Reading should work. What error do you get ?

Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m 
i get this error trying to connect to preloader mode
