### ISSUE TITLE
Please add a feature to skip "user" partition from dump full partition

### ISSUE THREAD

**Issue by nandbabai** [bkerler/mtkclient#255]
Hi sir,
I have MT6877 phone having internal storage 128 GB, when I full backed up using below command:

python mtk rl <Path/directory to save partition binaries> 

It dumped all partitions, where user partition was 110 GB which is very huge and useless.

I ran command "python mtk rf flash.bin" to create single flash file called flash.bin, it created 120 GB file which is nearly impossible to open on any tool.

So I request you if you could add a feature to skip any partition (like user,cache etc), new command can be like below

python mtk rf flash.bin --skippart=["user","cached"]

**Comment by rany2** [comment]
You already can.

Based on your example,

`python3 mtk rl --skip user,cached <Path/directory to save partition binaries>`

**Comment by nandbabai** [comment]
Thank you. its working , tested command>

python mtk rl --skip cache,userdata <Path/directory to save partition binaries>
