### ISSUE TITLE
Phone boots up when DA is crashed, Kamikari2 fails, MT6883Z/CZA (LG Velvet 5G G900TM)

### ISSUE THREAD

**Issue by PrizmJKR** [bkerler/mtkclient#256]
[console.txt](https://github.com/bkerler/mtkclient/files/7957511/console.txt)
[log.txt](https://github.com/bkerler/mtkclient/files/7957513/log.txt)

Using the premade LiveDVD.
Whenever I run a command, then connect the phone, the command starts executing but the phone boots up when MTKclient attempts to crash the DA. Then when I turn off the phone then reconnect it to MTKclient, it tries to load the payload using Kamikiri2 but it fails. Can you please take a look at this?

**Comment by samuel1003** [comment]
This device no enter brom mode, maybe over testpoint would work

**Comment by bkerler** [comment]
Yep. And there will be no support, as kamakiri won't work for these devices.

**Comment by PrizmJKR** [comment]
> Yep. And there will be no support, as kamakiri won't work for these devices.

Well turns out LG patched up the preloader in the Android 11 firmware for the Velvet. The phone still works perfectly fine with MTKclient by preserving the older Android 10 preloader when manually updating the phone to Android 11.
