### ISSUE TITLE
DAXFlash error

### ISSUE THREAD

**Issue by seadeor** [bkerler/mtkclient#259]
DAXFlash - [LIB]: ←[31mxread error: unpack requires a buffer of 12 bytes←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError jumping to DA: -1←[0m
Main
Main - [LIB]: ←[31mError uploading da←[0m

**Comment by bkerler** [comment]
Please provide a FULL log, otherwise we can't fix anything.
