### ISSUE TITLE
Not select Manual DA loader error

### ISSUE THREAD

**Issue by Junnsa** [bkerler/mtkclient#26]
DAconfig
DAconfig - [LIB]: ←[31mNo da config set up←[0m
DALegacy - Uploading da...
DALegacy
DALegacy - [LIB]: ←[31mNo valid da loader found... aborting.←[0m
Main
Main - [LIB]: ←[31mError uploading da←[0m

MTK_AllInOne_DA_5.1420.bin
MTK_AllInOne_DA_5.1824.bin
MTK_AllInOne_DA_5.2124.bin

All tested not working manual select.

**Comment by bkerler** [comment]
Hi, which cpu ? Can you share the full console log ?

**Comment by Junnsa** [comment]
Of course my friend.
[log.txt](https://github.com/bkerler/mtkclient/files/7031441/log.txt)

**Comment by bkerler** [comment]
Please try commit f0c6ad1

**Comment by bkerler** [comment]
Please try commit f0c6ad1

**Comment by Junnsa** [comment]
not working

**Comment by marat2509** [comment]
@bkerler

**Comment by bkerler** [comment]
Please try the latest commit
