### ISSUE TITLE
Fix for dm-verity error on Xiaomi devices

### ISSUE THREAD

**Issue by rany2** [bkerler/mtkclient#261]
Hi, I've managed to fix the dm-verity error on the Redmi Note 10 Pro 5G/Poco X3 GT by simply rebooting into the bootloader and running `fastboot oem cdms`.

After running this my device remains unlocked and the dm-verity error is gone. I don't have your expertise to figure out why that oem command fixes it but it might be helpful to solve this error for all devices.

**Comment by rany2** [comment]
Maybe also helps: 

```
$ diff <(xxd seccfg_good_unlock.bin) <(xxd seccfg_bad_unlock.bin) 
2,4c2,4
< 00000010: 0000 0000 0000 0000 4545 4545 62c0 1e2b  ........EEEEb..+
< 00000020: 3d29 0f8a 750d bc7c 1262 6a8e 183c ed6f  =)..u..|.bj..<.o
< 00000030: 0e1d 6c72 373f 534e e29f 5231 0000 0000  ..lr7?SN..R1....
---
> 00000010: 0100 0000 0000 0000 4545 4545 806c 6527  ........EEEE.le'
> 00000020: a2b1 b2c0 7992 f1e0 bec7 4908 1c42 9a5f  ....y.....I..B._
> 00000030: 0748 437a 765c 7a22 a5f7 81e6 0000 0000  .HCzv\z"........
```

**Comment by bkerler** [comment]
Hi, I will add this, thx !

**Comment by julianxhokaxhiu** [comment]
I'm having a Redmi 9 with this very same issue. Unfortunately the command `fastboot oem cdms` doesn't work ( says "error command not found" ), and using `python mtk da seccfg lock` doesn't work either ( the script does return a successful write, but the error message is still there on boot ).

Any idea what else can I try?

**Comment by xxroot** [comment]
fastboot flash vbmeta vbmeta_system vbmeta_vendor Remove checksum ing files

**Comment by google-mirror** [comment]
> I'm having a Redmi 9 (lancelot) with this very same issue. Unfortunately the command `fastboot oem cdms` doesn't work ( says "error command not found" ), and using `python mtk da seccfg lock` doesn't work either ( the script does return a successful write, but the error message is still there on boot ).
> 
> Any idea what else can I try?

https://zhuanlan.zhihu.com/p/538441745

**Comment by kendling** [comment]
Same issue in Realme X7 ProUltra.
Is it solve?

**Comment by msghost** [comment]
“fastboot oem cdms ”

It's good work for my redmi note 11t pro.

Thanks!

**Comment by dipenmagdani** [comment]
Yo! Bro thank you. It worked on my poco m4 pro 5g indian (evergo)

**Comment by rayene01** [comment]
it work for me in my redmi note 10s
thanks

**Comment by shidalao** [comment]
If `fastboot oem cdms` failed, then try `fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img`, and vbmeta.img should come from the original ROM.

Let me know if it works or not :)

**Comment by Lavish1707** [comment]
I'm my redmi 9 prime dm variety corroupted is showing and it's don't even fastboot or recovery it just loop there

**Comment by Xenon1357** [comment]
Just run ```fastboot oem cdms``` after this I got rid of the dm-variety message but my phone was still stuck in a bootloop so to fix it I used this command to get back the vbmeta.img file from the phone's stock from ```fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img```

**Comment by Marius-Sheppard** [comment]
fastboot flash vbmeta doesn't work: FAILED (remote: 'not allowed in locked state')

**Comment by DemetrioLima** [comment]
> funcionou para mim no meu redmi note 10s, obrigado

Estou com problemas no meu 10s também, como vc fez?, n sei como executar esse codigo kk.

Se alguém puder me ajudar, eu agradeço.

**Comment by gustavoozo** [comment]
tmb gostaria de saber n entendi nada do q os cara falou msm sabendo ingles sadokosadsa

**Comment by koyuyesil** [comment]
In the tools I used before, I didn't have to erase the data, but I had to erase it due to the vbmeta issue. Is there a way to fix it? Which codes need to be edited, or do I need to add custom codes to the device? What is the purpose of fastboot oem cdms?

**Comment by EuroFounder** [comment]
polla

**Comment by Miguelarias0413** [comment]
llevo mucho tiempo con un celular asi. Si porfavor alguien conoce una solucion la cual no sea estas de acá (Que no me sirvieron), le pido que me contacte

**Comment by armeya25** [comment]
fastboot oem cdms
also worked for me

**Comment by sainannuri** [comment]
> fastboot flash vbmeta doesn't work: FAILED (remote: 'not allowed in locked state') and fastboot oem cdms results in bootloop
Did your issue resolved?
I also facing the same issue could you help me?

**Comment by macekboris** [comment]
Any command for QualComm devices, this doesnt work 4 me, also AVB is tripped, cannot copy avb footer header on system verified partitions.

> fastboot flash vbmeta doesn't work: FAILED (remote: 'not allowed in locked state') and fastboot oem cdms results in bootloop

Unlock the bootloader to be able to flash ...
