### ISSUE TITLE
After Root Device stuck in Bootloop

### ISSUE THREAD

**Issue by ASIMKHAN222** [bkerler/mtkclient#264]
i tried to Root my Device with Mtkclient commands, i follow All Steps & type all commands correctly.
i patched boot.img file with latest magisk v24 canary.
when i run these commands"  python mtk w boot,vbmeta boot.patched,vbmeta.img.empty "
All Were fine
There is No Any Error...
But When i tried to Restart My Device its Stuck in bootloop

Device;
Vivo S1, Android 11 version.
chipset; MT6768

**Comment by bkerler** [comment]
Sorry, that's an android issue. Please write that issue at the magisk repo.

**Comment by NeonzGamingYT** [comment]
> i tried to Root my Device with Mtkclient commands, i follow All Steps & type all commands correctly. i patched boot.img file with latest magisk v24 canary. when i run these commands" python mtk w boot,vbmeta boot.patched,vbmeta.img.empty " All Were fine There is No Any Error... But When i tried to Restart My Device its Stuck in bootloop
> 
> Device; Vivo S1, Android 11 version. chipset; MT6768

Please dont use normal magisk it would not work on vivo
