### ISSUE TITLE
[mtk6765] Couldn't find CDC interface

### ISSUE THREAD

**Issue by FilipeSDonato** [bkerler/mtkclient#266]
I have a lg k51s, mtk6765v/wa.
I updated it for Android 11.
Now the MTKClient does not recognize it or Windows or Linux (Re LiveDVD).
The following error appears 5 times or more and the phone restarts:
Couldn't Find CDC Interface. Aborting.
Is it any MTKClient or Android problem?

**Comment by bkerler** [comment]
That's a MTKClient issue that will be fixed today.

**Comment by bkerler** [comment]
Issue is fixed with commit b30d65c
