### ISSUE TITLE
it can't work on my meizu mx6

### ISSUE THREAD

**Issue by Thepersimmon** [bkerler/mtkclient#268]
The program got stuck in the middle for a long time. 
could you please tell me how to unlock my meizu mx6?
here is the log

Port - Device detected :)
Preloader -     CPU:                    MT6797/MT6767(Helio X23/X25/X27)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212c00
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x279
Preloader - Target config:              0x7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca01
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      04B86E4F91500741280B52C207C2B854
PLTools - Loading payload from mt6797_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: D:\shuaji\mtkclient-gui\mtkclient-gui\mtkclient\mtkclient\payloads\mt6797_payload.b
in
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         BJNB4R
DAXFlash - EMMC CID:        150100424a4e42345207ccdd47958373
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x747c00000
DAXFlash - Reconnecting to preloader
DAXFlash - Connected to preloader
DAXFlash - DA-CODE      : 0x797B0
DAXFlash - DA Extensions successfully added
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init

**Comment by bkerler** [comment]
Most probably your device has a specific sej init. Can you upload the preloader ?

**Comment by Thepersimmon** [comment]
Do you mean this file? It is extracted from the latest ROM of meizu mx6. If not, please tell me and I will upload it again immediately. Thank you very much. 
[preloader.zip](https://github.com/bkerler/mtkclient/files/8029638/preloader.zip)

**Comment by Thepersimmon** [comment]
Will you consider supporting my device?

**Comment by momo54181** [comment]
I also encountered such a problem.

**Comment by momo54181** [comment]
I have already prepared TWRP Recovery.
https://github.com/momo54181/Action-TWRP-builder/releases/tag/7305913328

**Comment by momo54181** [comment]
Data
F2FS

**Comment by lmanukyan** [comment]
Any solution?

**Comment by momo54181** [comment]
> 有什么解决方案吗？

You can use the engineering LK to bypass the verification and boot an unauthenticated BOOT image even if the BL is not unlocked

**Comment by lmanukyan** [comment]
> You can use the engineering LK to bypass the verification and boot an unauthenticated BOOT image even if the BL is not unlocked

How do I do that? Are there any instructions?
