### ISSUE TITLE
(MT6765 - Vivo y81) After flash magisk not installed 

### ISSUE THREAD

**Issue by nusht** [bkerler/mtkclient#269]
Please help me,
Everything goes well and at the end the magisk manager is installed but the magisk system isn't 

After flash magisk not installed

MT6765 vivo y81

**Comment by bkerler** [comment]
Sorry, for magisk questions, go to magisk repo.

**Comment by muhammadrafiasyddiq** [comment]
pakai magisk patch for vivo
