### ISSUE TITLE
MediaTek Helio G25 (MT6762G) - Disable Verified Boot

### ISSUE THREAD

**Issue by 6a6f6a6f** [bkerler/mtkclient#273]
I was able to patch and rewrite `boot_a` and `boot_b` with the original `boot.img` from my partition (and also `vbmeta_a` and `vbmeta_b`). However, I still got the error on AVB.

There is a way to disable AVB with mtkclient?

**Comment by bkerler** [comment]
Sorry, no issue with mtkclient, but android / magisk.
