### ISSUE TITLE
error on DA send 

### ISSUE THREAD

**Issue by bukaixyz** [bkerler/mtkclient#274]
<img width="798" alt="屏幕快照 2022-02-12 下午7 19 33" src="https://user-images.githubusercontent.com/85857425/153709183-77902148-ae94-49de-aeb1-59e3a75e0934.png">

**Comment by bukaixyz** [comment]
I use redmi note 9

**Comment by bkerler** [comment]
That means the device has been patched and won't be supported with kamakiri2.
