### ISSUE TITLE
PySide6 is required also with CLI

### ISSUE THREAD

**Issue by etmatrix** [bkerler/mtkclient#277]
I always used this tool in cli mode and I'd like to continue to use in cli mode without gui and without install pyside6.
From commit 17e6abcba88acca2e9a0e6348224d0ac7b197619 this isn't more possible, because there is the import of PySide6.QtCore.
Is it possible to come back to previous behaviour?

**Comment by joaopa00** [comment]
What is the problem to install Pyside6?

**Comment by etmatrix** [comment]
@joaopa00 is very simple is useless library! 
why do i need to install a library that i don't need?
cli and gui must remain separate, this is the linux / unix philosophy

**Comment by bkerler** [comment]
you can use it without installing the pyside6 Library. you just need to uncomment the gui functions.

**Comment by etmatrix** [comment]
for me it was better before, when the gui was not there.There were so many features to add, because waste time with a useless gui, the cli was already perfect.

**Comment by bkerler** [comment]
That's sad. Doing those code changes are easy. But I guess it's easier to just moan about missing stuff than to ask nicely even though it has already been implemented. 😭

**Comment by patrick777777777** [comment]
I really find it bad whenever am reminded fake people like @**ghost"" exist
