### ISSUE TITLE
METAMODE

### ISSUE THREAD

**Issue by Herryarfiyan** [bkerler/mtkclient#280]
how to fix META MODE command
.../mtk payload --metamode FASTBOOT
.../mtk payload --metamode METAMETA  not work

Port - Device detected :)
Preloader - 	CPU:			MT6737M()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10212000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10217c00
Preloader - 	Var1:			0x28
Preloader - Disabling Watchdog...
Preloader - HW code:			0x335
Preloader - Target config:		0x5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			371015554A73502397B63F0C2F886FE5
PLTools - Loading payload from mt6737_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\TEAM EMMC ID\Documents\Visual Studio 2019\Project Mediatek New\DXApplication\DXApplication\bin\Debug\Python\Lib\1e7f37e_\_encoding\mtkclient\payloads\mt6737_payload.bin
Port - Device detected :)
META - Status: Waiting for PreLoader VCOM, please connect mobile

###################################################################################################

Port - Device detected :)
Preloader - 	CPU:			MT6765/MT8768t(Helio P35/G35)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0x25
Preloader - Disabling Watchdog...
Preloader - HW code:			0x766
Preloader - Target config:		0xe5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			1A58B76FBB8E3A3354AF54454D11D572
Preloader - SOC_ID:			7CE7D4FE6F46CB586E87D528ECDCB51637FE31B4E6212EF129B2DF9039FDE252
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\TEAM EMMC ID\Documents\Visual Studio 2019\Project Mediatek New\DXApplication\DXApplication\bin\Debug\Python\Lib\1e7f37e_\_encoding\mtkclient\payloads\mt6765_payload.bin
Port - Device detected :)
META - Status: Waiting for PreLoader VCOM, please connect mobile

**Comment by koyuyesil** [comment]
note9 brom sec. enabled how to enter meta mode ?
