### ISSUE TITLE
installing Error

### ISSUE THREAD

**Issue by ASIMKHAN222** [bkerler/mtkclient#281]
i face this error when installing python setup.py

**Reading_https://pypi.org/simple/PySide2/
No local packages or working download links found for PySide2
error: Could not find suitable distribution for _Requirement.parse('PySide2')**

Please Guide Me how can i fix it

i also get this error when upgrading pip version
**ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Khan\\AppData\\Local\\Temp\\pip-uninstall-434hpnem\\pip.exe'
Consider using the `--user` option or check the permissions.**

**Comment by grizlikoff** [comment]
What OS version? 32 or 64 bit?
1. Download and install last Python [https://www.python.org/downloads/](url)
2. Download and install last GithHub Desktop [https://desktop.github.com/](url)
3. Download and install last UsbDk [https://github.com/daynix/UsbDk/releases/](url)

**Comment by Herryarfiyan** [comment]
use phyton full and instal requirements.txt

done

**Comment by bkerler** [comment]
For Windows, if the python version is too new (like 3.10), sometimes pyside6 isn't supported. Then you either need to recompile the package yourself or you downgrade to python 3.9

**Comment by ASIMKHAN222** [comment]
> What OS version? 32 or 64 bit?
> 
> 1. Download and install last Python [https://www.python.org/downloads/](url)
> 2. Download and install last GithHub Desktop [https://desktop.github.com/](url)
> 3. Download and install last UsbDk [https://github.com/daynix/UsbDk/releases/](url)

My OS is 64bit

**Comment by ASIMKHAN222** [comment]
> For Windows, if the python version is too new (like 3.10), sometimes pyside6 isn't supported. Then you either need to recompile the package yourself or you downgrade to python 3.9

THANK YOU VERY MUCH!
Issue is resolved by installing Python 3.9.7 version
