### ISSUE TITLE
Unlocking bootloader on Oppo F7 

### ISSUE THREAD

**Issue by chaikovskiy99** [bkerler/mtkclient#282]
I am able to unlock the bootloader on oppo F7 using this tool, however, when I try to reboot to bootloader, I get "usb serial does not match" and "fastboot unlock verify failed" message and then it reboots to system. Is there any idea, why this is happening?

**Comment by lpxx50117** [comment]
OPPO's fastboot mode only support official unlock bootloader method,third-party unlock bootloader like mtkclient cannot enter fastboot mode.

**Comment by chaikovskiy99** [comment]
> OPPO's fastboot mode only support official unlock bootloader method,third-party unlock bootloader like mtkclient cannot enter fastboot mode.

That's strange, I mean the tool is able to lock or unlock the bootloader(maybe false flag), I do get bootloader unlocked status in developer options. And I am able to root my phone after unlocking with the tool, the only thing that I can't do is get to fastboot mode, which seems to be disabled by oppo. I just decompiled their in depth test app, I will be analysing it for any traces that can help with fastboot. There is no test app for my phone. So, I am relying on several close models.

**Comment by CNLM** [comment]
The bootloader is unlocked. On Oppo/realme devices, they use own deep-testing app (official bootloader unlock method) to authorize fastboot access. Without using it fastboot is disabled by default.
