### ISSUE TITLE
Xiaomi Redmi Note 11 Pro MTK can't boot after Unlock Bootloader

### ISSUE THREAD

**Issue by grizlikoff** [bkerler/mtkclient#283]
Phone boot only BootROM
Trying write Preloder - FAIL
`Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

Port - Device detected :)
Preloader -     CPU:                    MT6877(Dimensity 900)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x959
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      058D92AC859D863421FA0A86E76510BD
Preloader - SOC_ID:                     8E7614EF372A6B3EA1D57F4EE67FB46D696461529E9520252803A23C110D05C6
PLTools - Loading payload from mt6877_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\grizl\OneDrive\Documents\GitHub\mtkclient\mtkclient\payloads\mt6877_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AECMBDAR
DAXFlash - UFS CID:      ad014839485131354145434d42444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ad014839485131354145434d42444152
DAXFlash - No preloader given. Searching for preloader
DAXFlash - Sending emi data ...
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: DA exceed max num (0xc0070005)←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: DA exceed max num (0xc0070005)←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: DA exceed max num (0xc0070005)←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: DA exceed max num (0xc0070005)←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: DA exceed max num (0xc0070005)←[0m
DAXFlash`

**Comment by grizlikoff** [comment]
It is UsbDK driver fail.

**Comment by qianmo-xw** [comment]
> It is UsbDK driver fail. libusb-win32-devel-filter-1.2.6.0.exe working fine
> 
> Bat, after bootloader unlocking - it dtill locked (

How to solve still locked？
