### ISSUE TITLE
Live CD boot screen

### ISSUE THREAD

**Issue by finnroth09** [bkerler/mtkclient#285]
Booted into the live CD and got a distorted screen for a moment, followed by a black screen.
![IMG_20220217_223124](https://user-images.githubusercontent.com/98442142/154618469-b0785d90-488f-4d3d-9fc5-98bc5ee502a3.jpg)
![IMG_20220217_223215](https://user-images.githubusercontent.com/98442142/154618481-1a069197-b924-49f9-937b-f01a2c527ede.jpg)

**Comment by bkerler** [comment]
Hi, you need to use the grub boot screen to set a different video mode in the cmdline. Sorry I can't help you any further as this is device specific linux setup.
