### ISSUE TITLE
DA_handler - [LIB]: Unknown seccfg partition header. Aborting unlock

### ISSUE THREAD

**Issue by StevenKim523** [bkerler/mtkclient#286]
Hi! Bro. I got a copycat phone with chip mt6753. I tried to unlock it with mtk client under the Ubuntu 20.04. But I got this error:DA_handler - [LIB]: Unknown seccfg partition header. Aborting unlock.
Here are logs and preloader. Hope these be helpful. If anything else is needed, tell me and i will upload it as quickly as possible.
```
Port - Device detected :)
Preloader - 	CPU:			MT6753()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10212000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10217c00
Preloader - 	Var1:			0x28
Preloader - Disabling Watchdog...
Preloader - HW code:			0x337
Preloader - Target config:		0x1
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			847F5289E3A74EC2D2F6A8DD856AD5A3
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6753_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/steven/mtkclient/mtkclient/payloads/mt6753_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
Successfully extracted preloader for this device to: preloader_droi6753_35g_m0.bin
DALegacy - Uploading da...
DALegacy - Uploading legacy stage 1 from MTK_AllInOne_DA_5.2136.bin
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DALegacy - Got loader sync !
DALegacy - Reading nand info
DALegacy - Reading emmc info
DALegacy - Setting stage 2 config ...
DALegacy - DRAM config needed for : 514e011337394a338d041056f5e9a57f
DALegacy - Reading dram nand info ...
DALegacy - Sending dram info ...
DALegacy - M_EXT_RAM_RET : 0
DALegacy - M_EXT_RAM_TYPE : 0x2
DALegacy - M_EXT_RAM_CHIP_SELECT : 0x0
DALegacy - M_EXT_RAM_SIZE : 0xc0000000
DALegacy - Uploading stage 2...
DALegacy - Successfully uploaded stage 2
DALegacy - Connected to preloader
DALegacy - Reconnecting to preloader
DALegacy - Connected to preloader
DALegacy - m_int_sram_ret = 0x0
m_int_sram_size = 0x20000
m_ext_ram_ret = 0x0
m_ext_ram_type = 0x2
m_ext_ram_chip_select = 0x0
m_int_sram_ret = 0x0
m_ext_ram_size = 0xc0000000
randomid = 0x19838E4A2B5D468951A17C4112C6F882

m_emmc_ret = 0x0
m_emmc_boot1_size = 0x400000
m_emmc_boot2_size = 0x400000
m_emmc_rpmb_size = 0x400000
m_emmc_gp_size[0] = 0x0
m_emmc_gp_size[1] = 0x0
m_emmc_gp_size[2] = 0x0
m_emmc_gp_size[3] = 0x0
m_emmc_ua_size = 0x747c00000
m_emmc_cid = 334a393713014e517fa524f55610048d
m_emmc_fwver = 1000000000000000

Done |--------------------------------------------------| 0.0% Read (Sector 0x0 of 0x400) 0.00 MB/sDA_handler
DA_handler - [LIB]: Unknown seccfg partition header. Aborting unlock.
```

[preloader_droi6753_35g_m0.zip](https://github.com/bkerler/mtkclient/files/8094432/preloader_droi6753_35g_m0.zip)

**Comment by EmsTatay** [comment]
Hello!
THANKS for your great creation and hard work...
I am new to your application (begging for patience!)
After reading through the guides and cloning building the latest (today) ... I ended up with the exact same error.
MY target device is different ... (I actually have 2 of them... old = no problem to try things... flashing stock back...)

Device: ASUS ZC520TL X008D wtih stock ROM  (13.1 = Android 6, 14.14 = 7.0 or 15.14 = 8.1)
CHIP  MT6737M 
2GB - 16GB...

I am attaching the preloader (RENAMED - NOT ZIPPED)
[preloader_D281L.bin.not.zip](https://github.com/bkerler/mtkclient/files/8105339/preloader_D281L.bin.not.zip)

Please let me know if I can provide any other dump or device info...

Cheers!

**Comment by StevenKim523** [comment]
Somebody help us? Thanks a lot in advance!

**Comment by TheRealDarkn3ss** [comment]
Same right here! Any solution?

**Comment by kmeaw** [comment]
Could you dump your seccfg partition? If it is empty (md5=59071590099d21dd439896592338bf95) then there is no need to unlock.

**Comment by chris1892006** [comment]
> Could you dump your seccfg partition? If it is empty (md5=59071590099d21dd439896592338bf95) then there is no need to unlock.

How do I make a dump of my seccfg partition?  My device is AGPTek T06S with MT6753T.

Thanks

**Comment by StevenKim523** [comment]
> > Could you dump your seccfg partition? If it is empty (md5=59071590099d21dd439896592338bf95) then there is no need to unlock.
> 
> How do I make a dump of my seccfg partition? My device is AGPTek T06S with MT6753T.
> 
> Thanks

Maybe you can try this cmd: python mtk dumppreloader

**Comment by chris1892006** [comment]
It was bootloader unlocked I'm rooted now on mt6753t agptek t06s mp4 player but cannot get viper4android driver to install.  Advice?

**Comment by StevenKim523** [comment]
> It was bootloader unlocked I'm rooted now on mt6753t agptek t06s mp4 player but cannot get viper4android driver to install. Advice?

How did you unlock your device?

**Comment by chris1892006** [comment]
OEM unlocking in dev options may of did it and patched my firmware boot.IMG on magisk for root.

**Comment by StevenKim523** [comment]
> OEM unlocking in dev options may of did it and patched my firmware boot.IMG on magisk for root.

did mtk-client works?

**Comment by chris1892006** [comment]
Didn't need to because I think we found out with the developers for mtk telegram channel that all I did was oem unlocking idk if it did anything but it was allowed to be unlocked from the factory in fact we are thinking all mtk devices are factory unlocked according to the boot.img and source code.
