### ISSUE TITLE
See folder and file structures inside paritions ???

### ISSUE THREAD

**Issue by nabicapar** [bkerler/mtkclient#287]
With ( python mtk pringtp ) we can read all partitions without any problems.

My Question Is: Is it possible to read subsections of partitions?

example : Super > Default.prop

**Comment by zeugensativas** [comment]
Yes it is, you could use the Tool- Mobile Relevator from this hub.

https://github.com/bkerler/MR

**Comment by nabicapar** [comment]
well, but this allows us to examine the existing file in the local.
but i want to read inside the device

**Comment by zeugensativas** [comment]
oh yeah thats not possible yet, as far as i know

**Comment by bkerler** [comment]
Not possible if the files are encrypted, otherwise have a look at the new fuse functionality.
