### ISSUE TITLE
Mtk driver issue in Nokia 2.3

### ISSUE THREAD

**Issue by sachinachude** [bkerler/mtkclient#288]
I have to unlock bootloader of my Nokia 2.3 (1086) mt6761 through this method but no suitable driver found. Whenever I install driver it says The device cannot start. (Code 10) .FailReasonString --> The specified request is not a valid operation for the target device. I searched out everything on Google but no luck. I am using it on Android 11. I contacted to Nokia support but they said we can not provide driver as we don't support unlocking. You can use your phone to transfer file from phone to pc and vice versa through MTP and share internet connection through wifi hotspot or usb.

**Comment by rany2** [comment]
Have you tried on Linux? If you don't know how to use Linux try the Live CD

**Comment by sachinachude** [comment]
> Have you tried on Linux? If you don't know how to use Linux try the Live CD

No, I don't have Linux. Could OEM block the device from being detected.

**Comment by rany2** [comment]
@sachinachude Not sure but what you're describing sounds more like a Windows problem than an issue with your device. Try it on Linux to see if that fixes it.
