### ISSUE TITLE
Unable to write preloader (MT8167 / BROM mode)

### ISSUE THREAD

**Issue by YiB-PC** [bkerler/mtkclient#289]
Thank you very much for developing such a useful tool.

I have written a Preloader on a device with MT8167.
This is because it won't boot so I wanted to Unbrick it, since all the backups are there.

The result of `mtk gettargetconfig` is as follows.
```
........Port - Device detected :)
Preloader -     CPU:                    MT8167/MT8516/MT8362()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11005000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212c00
Preloader -     Var1:                   0xcc
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x8167
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb00
Preloader -     SW Ver:                 0x1
Preloader - ME_ID:                      31A00196F191B25A01730313AC9548DA
Preloader - SOC_ID:                     0000000000000000000000000000000000000000000000000000000000000000
Main - Getting target info...
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
```

In the past, I wrote pgpt because I remembered that it was broken because I wrote an image with the wrong Scatter file, but since it did not start, I wrote Preloader again.
Then the boot screen came out.

Later, Preloader was found to write to EMMC_BOOT1 according to the Scatter file, so Preloader was given the `--parttype boot1` option, and pgpt and others were baked with the `--parttype user` option.
```shell
python3 mtk wo 0x0 0x80000 ../TAB-A03-BR3/br3image/preloader_a04br3.bin --parttype boot1
```

Then it would not start and even the charging screen would not appear.
It is always running in BROM mode.

The files in the Preloader are correct, and I have been able to burn them using SP Flashtool in the past.
Currently, unless I specify the Preloader with the `--preloader` option, I get this error and cannot burn.

I think it may have something to do with the fact that the mtk printgpt command stops with the following error.
![image](https://user-images.githubusercontent.com/67213134/155240173-f98c6038-b2d6-40cf-80cd-0800401979da.png)

No matter how many times I re-write the Preloader, the situation is the same.

I apologize if this is my fault and the problem is not related to mtkclient.
I would appreciate a reply.
(I'm not very good at English, so I use deepl to translate. I'm sorry if this is hard to read.)

**Comment by bkerler** [comment]
You can't just write the preloader ... it has to have a emmc_boot or ufs_boot header. Also the preloader dumped using dumppreloader function is taken from ram and might be broken, unless you were reading preloader initially directly from flash. If you are lucky your device has a preloader partition in user which should be able to be shortened and then flashed to parttype=boot1.

**Comment by YiB-PC** [comment]
Thank you for your reply.
The preloader file is extracted from the update zip file. Is it still not possible to just burn the image?
Since I have another working machine, do I need to run `dumppreloader` from it and dump the preloader?
