### ISSUE TITLE
Write RPMB fails

### ISSUE THREAD

**Issue by komenkHp** [bkerler/mtkclient#29]
How to write RPMB..?

**Comment by KeuntaeShin** [comment]
Today, i added statements for calling  it you want, but i'm not sure it will work or not:

/git/mtkclient/mtk


                elif subcmd == "rpmb":
                    rpmb_subcmd = args.rpmb_subcmd
                    if rpmb_subcmd is None:
                        print('Available xflash rpmb cmds are: [r w]')
                    '''
                        Keuntae Shin: add rpmb_subcmd for writing
                    '''
                    if rpmb_subcmd == "r":
                        mtk.daloader.read_rpmb(args.filename)                        
+                  elif rpmb_subcmd == "w":
+                      mtk.daloader.write_rpmb(args.filename)


Also, i added several statements to respond unexpected exception of original code, that is raised by return code from devices. I'm afraid that it would depend on target devices, so i omit it.


And the command i used:
python3 mtk xflash rpmb w --filename /git/mtkclient/rpmb_image

**Comment by bkerler** [comment]
The current payload has a small bug, support should be added on the next release

**Comment by jamb84** [comment]
i really don't want to be one of those "weneta" people, but i am curious if you have an idea of when the payload fix might be released? will it allow us to clean the rpmb?

**Comment by jamb84** [comment]
is there any indication of what the bug is? i've done everything i know to reverse the payloads myself and i'm struggling.

**Comment by bkerler** [comment]
Yes. It's the way how some devices create the rpmb key. I will soon have a closer look

**Comment by bkerler** [comment]
Write RPMB was added, but there is a bug in Init RPMB right now.

**Comment by bkerler** [comment]
Keeping this issue alive ... work is in progress.
