### ISSUE TITLE
Not work on MT8590

### ISSUE THREAD

**Issue by azwhikaru** [bkerler/mtkclient#295]
Sorry, I can't provide any logs: **because the program doesn't output anything**

I tried many commands, but they didn't work. When my device entered the preloader port, it would prompt "handshake failed". Then my device started normally and the program stopped working.

For spflashtool, my device works normally, but on bypass and mtkclient, it doesn't work at all

I try to attach my preloader. May it help us solve the problem?
Maybe it's related to my device using MBR partition instead of GPT?
[preloader_bbdmp2_linux.zip](https://github.com/bkerler/mtkclient/files/8143577/preloader_bbdmp2_linux.zip)

**Comment by StevenKim523** [comment]
Maybe you should try Brom mode

**Comment by azwhikaru** [comment]
> 

How do I enter Brom mode?

I've tried several possible key combinations, but none of them seem to have a significant effect.

Alternatively, can I enter Brom mode in PreLoader mode?
