### ISSUE TITLE
USB IO error in "Sending dram info"

### ISSUE THREAD

**Issue by azwhikaru** [bkerler/mtkclient#296]
**All console logs**

`python mtk da seccfg unlock --preloader=preloader_bbdmp2_linux.bin`

Port - Device detected :)
Preloader -     CPU:                    MT8590/MT7683/MT8521/MT7623()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x8590
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb01
Preloader -     SW Ver:                 0x102
Preloader - ME_ID:                      19361288812E4593176B4D86496CA979
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt8590_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\payloads\mt8590_payload.bin
Port - Device detected :)
DALegacy - Uploading legacy da...
DALegacy - Uploading legacy stage 1 from MTK_AllInOne_DA.bin
legacyext
legacyext - [LIB]: Legacy address check not patched.
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DALegacy - Got loader sync !
DALegacy - Reading nand info
DALegacy - Reading emmc info
DALegacy - Setting stage 2 config ...
DALegacy - DRAM config needed for : 150100415750443352008faef4f3a3ff
DALegacy - Reading dram nand info ...
DALegacy - Sending dram info ...
**usb_class - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtk", line 698, in <module>
    mtk = Main(args).run()
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_main.py", line 518, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_da_cmd.py", line 112, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 202, in upload_da
    return self.da.upload_da()
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1067, in upload_da
    if self.upload():
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1039, in upload
    self.set_stage2_config(self.config.hwcode)
  File "C:\Users\Teio\Downloads\Compressed\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 918, in set_stage2_config
    checksum = unpack(">H", self.usbread(2))[0]  # 0x440C
struct.error: unpack requires a buffer of 2 bytes**

**Comment by honjiidar** [comment]
You closed it. How did you get it fixed? Experiencing the same issue.

**Comment by lelenext** [comment]
same issue, how to solve it?
