### ISSUE TITLE
Direct File System Explorer from Preloader and Brom Mode

### ISSUE THREAD

**Issue by nabicapar** [bkerler/mtkclient#299]
Direct File System Explorer from Preloader and Brom Mode
Expamle : https://www.youtube.com/watch?v=qQPJnfNfGYk

**Comment by bkerler** [comment]
Yes, it's a nice feature. However I agreed to the scene not to add it as it might be closed by the vendors soon.

**Comment by balveerjat7** [comment]
This will help to recover data.
