### ISSUE TITLE
mtk.py payload cannot recognize BOOTROM!

### ISSUE THREAD

**Issue by awsaxf** [bkerler/mtkclient#3]
It is scanning preloader VCOM, but it cannot recognize BOOTROM!

**Comment by bkerler** [comment]
Please provide a log and more details.

**Comment by awsaxf** [comment]
![MTK](https://user-images.githubusercontent.com/44595743/127967024-baaa5c7f-ddda-490b-b059-fdf774570b93.png)

Thanks! It has been solved, Zadig has not been set up, but has encountered a new problem. After executing the mtk.py payload, the SP Flash tool cannot recognize the port because the driver is like this!

**Comment by bkerler** [comment]
If you want to use SP Flash Tool, the only solution is to use Linux right now (you can use the live dvd for that as well). The filter driver doesn't work.

**Comment by awsaxf** [comment]
Currently, SP Flash Tool cannot be used under windows, right?Looking forward to the solution of the Great God!

**Comment by bkerler** [comment]
One dirty solution for windows might be : run payload command, then don't disconnect the mobile, replace the driver with the stock one using zadig and then start sp flash tool with uart option.

**Comment by awsaxf** [comment]
Thanks! I try it!

**Comment by bkerler** [comment]
Windows works fine now using usbdk. No need to replace the original mtk driver with commit e2ac0a0. sp flash tool should work fine now.

**Comment by bkerler** [comment]
Just install regular MTK Port driver and then install the usbdk driver as stated in the readme.

**Comment by awsaxf** [comment]
Thank you, I have solved the mobile phone problem that has troubled me for a long time. Will the new chip support be updated in the future?

**Comment by bkerler** [comment]
Sure, if we are getting devices or bootroms of newer device
