### ISSUE TITLE
Stuck in BROM mode

### ISSUE THREAD

**Issue by CyberPhy** [bkerler/mtkclient#302]
I have a slight problem with mine, I was trying to flash twerp with mtkclient_gui but I accidently clicked delete preloader, and now my phone only boots into brom mode.

I did do a full backup before doing anything and I have tried restoring the backup with mtkclient but I keep getting emi timeout, the only way I can get it to write the backup is with --preloader=preloader.bin, but even after it write the backup back to the phone it still boots to brom.

I did get it to boot up but only with the command python mtk plstage --preloader=preloader.bin and if I turn the phone off it will just go back to brom mode.

I can get logs if you need them 
the phone has MT6761

**Comment by samuel1003** [comment]
python mtk w --preloader=preloader.bin

Try this, good luck

**Comment by CyberPhy** [comment]
that did not work, I had to add --preloader=preloader.bin to even get it to flash
but it did that something after flashing

**Comment by CyberPhy** [comment]
After installing security update, it's no longer stuck in BROM mode
