### ISSUE TITLE
Live image not available due too many downloads

### ISSUE THREAD

**Issue by sebastianha** [bkerler/mtkclient#308]
Hi,

I just tried to download the live image and I cannot download it because too many users have been downloading it in the past.

Could someone please mirror it somewhere to circumvent this limitation by google drive?

Regards, Sebastian

**Comment by sebastianha** [comment]
I just had luck and could download it, but it really would make sense to host it somewhere else.

**Comment by bkerler** [comment]
Sure, I will upload it somewhere else.

**Comment by bkerler** [comment]
Solved with commit 541985b
