### ISSUE TITLE
Unable to connect device - Error on DA sync - CPU: MT6592

### ISSUE THREAD

**Issue by AharonGon** [bkerler/mtkclient#314]
Hi Guys, I recently tried connecting a device with a MT6592 SoC and i got this error on DA sync: (THE EROOR LOG)
Thanks in advance for any help 🙂

Preloader -     CPU:                    MT6592()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x111000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x6592
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      7FFFAE5E06E91135AEFB9E9EE92857F0
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6592_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\user\mtkclient\mtkclient\payloads\mt6592_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: ←[33mDevice is in BROM mode. No preloader given, trying to dump preloader from ram.←[0m
DALegacy - Uploading legacy da...
DALegacy - Uploading legacy stage 1 from MTK_AllInOne_DA_5.1824.bin
legacyext
legacyext - [LIB]: ←[33mLegacy address check not patched.←[0m
Preloader - Jumping to 0x110000
Preloader - Jumping to 0x110000: ok.
DALegacy
DALegacy - [LIB]: ←[31mError on DA sync←[0m

**Comment by Mordechay0000** [comment]
I encountered this too, did you find a solution?
(I heard that in miracle box it works)

**Comment by Abyxkojwniko** [comment]
I meet the same problem too,use many tools,but i still can't solve it
