### ISSUE TITLE
Must manually hide all but one Loader file for LG Stylo 6 (LM-Q730..)

### ISSUE THREAD

**Issue by OneOfMany07** [bkerler/mtkclient#319]
From https://forum.xda-developers.com/t/how-to-unlock-bootloader-and-root-the-lg-stylo-6-and-k51-k61-and-other-k-model-lg-devices.4364489/

"***For the Stylo 6 to connect you must remove some of the loaders from the mtkclient-main\mtkclient\Loader file leaving MTK_AllInOne_DA_5.2136.bin as the only loader needed."

I assume this means the selection mechanism is broken, or the newer version can't work?  I haven't tried this myself, but wanted to be sure it was known in case you could fix it.

**Comment by bkerler** [comment]
That means that the older loaders can cause connection issues.
