### ISSUE TITLE
Use BROM mode to power the device off?

### ISSUE THREAD

**Issue by mastercodeon314** [bkerler/mtkclient#325]
Is there any way to send a command via mtkclient while the device is in brom mode to make it power off? A feature like this would be highly useful for situations where the device is bootlooping and mtkclient cant connect since the device needs to be powered off first.

**Comment by bukaixyz** [comment]
mtk reset

**Comment by mastercodeon314** [comment]
> mtk reset

Does this make the process shutdown and completely power off, or does it restart the device, similar to asb reboot?
