### ISSUE TITLE
How to use this cmd

### ISSUE THREAD

**Issue by SoeHtikeAung199** [bkerler/mtkclient#33]
cmd == "seccfg":
            with open("seccfg.bin", "wb") as wf:
                seccfg_ver = 4
                seccfg_size = 0x3C
                lock_state = 3
                """
                LKS_DEFAULT = 0x01
                LKS_MP_DEFAULT = 0x02
                LKS_UNLOCK = 0x03
                LKS_LOCK = 0x04
                LKS_VERIFIED = 0x05
                LKS_CUSTOM = 0x06
                """
                critical_lock_state = 1
                """
                LKCS_UNLOCK = 0x01
                LKCS_LOCK = 0x02
                """
                sboot_runtime = 0
                """
                SBOOT_RUNTIME_OFF = 0
                SBOOT_RUNTIME_ON  = 1
                """
                seccfg_data = pack("<IIIIIII", 0x4D4D4D4D, seccfg_ver, seccfg_size, lock_state,
                                   critical_lock_state, sboot_runtime, 0x45454545)
                dec_hash = hashlib.sha256(seccfg_data).digest()
                enc_hash = st2.keys(data=dec_hash, mode="sej_aes_encrypt")
                data = seccfg_data + enc_hash
                data += b"\x00" * (0x200 - len(data))
                wf.write(data)
            print("Successfully wrote seccfg.")
    st2.close()

    st2.close()

if __name__ == "__main__":
    main()

**Comment by marat2509** [comment]
Wait official release

**Comment by SoeHtikeAung199** [comment]
> release

You have any solution sent me😍

**Comment by SoeHtikeAung199** [comment]
> Wait for the official release.

Ok thank sir

**Comment by ligteltelecom** [comment]
C:\mtkclient-main>py stage2 seccfg
Capstone library is missing (optional).
Keystone library is missing (optional).
sej - HACC init
sej - HACC run
sej - HACC terminate
Traceback (most recent call last):
  File "C:\mtkclient-main\stage2", line 616, in <module>
    main()
  File "C:\mtkclient-main\stage2", line 606, in main
    data = seccfg_data + enc_hash
TypeError: can't concat str to bytes

C:\mtkclient-main>

**Comment by marat2509** [comment]
Wait, there will be an update soon, which will involve the new payload

**Comment by marat2509** [comment]
Try again with commit https://github.com/bkerler/mtkclient/commit/65c6ff01b747381cb537a008bb9e91122ff2bdb8

**Comment by ligteltelecom** [comment]
C:\mtk>py mtk stage
Capstone library is missing (optional).
Keystone library is missing (optional).

Preloader - Status: Waiting for PreLoader VCOM, please connect mobile
Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - ME_ID:                      B4FD7FAA01E367EAF68C1B76393EF17D
Preloader - SOC_ID:                     08F3DD3663A645FDD0FDEDF058241653134C146F32C21D89993F57619BF27C96
Main - Uploading stage 1
PLTools - Loading payload from C:\mtk\mtkclient\payloads\generic_stage1_payload.bin, 0x3ec bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\mtk\mtkclient\payloads\generic_stage1_payload.bin
Main - Successfully uploaded stage 1, sending stage 2
Main - Done sending stage2, size 0x4000.
Main - Done jumping stage2 at 00201000
Main - Successfully loaded stage2

C:\mtk>py stage2 seccfg
Capstone library is missing (optional).
Keystone library is missing (optional).
Traceback (most recent call last):
  File "C:\mtk\stage2", line 637, in <module>
    main()
  File "C:\mtk\stage2", line 627, in main
    data = seccfg_data + enc_hash
TypeError: can't concat list to bytes

C:\mtk>

**Comment by awsaxf** [comment]
I also found that in win7 (Python3.8.7 version), the stage2 command seems to be invalid!

C:\mtkclient-main>python stage2 seccfg
Traceback (most recent call last):
  File "stage2", line 19, in <module>
    class Stage2(metaclass=LogBase):
  File "stage2", line 354, in Stage2
    def keys(self, data=b"", otp=None, mode="dxcc") -> tuple[list or bytes or None,str]:
TypeError: 'type' object is not subscriptable

**Comment by bkerler** [comment]
Closing this issue for now, as it will be added as a feature soon.
