### ISSUE TITLE
Is there any hope of Dimensity 9000 being supported?

### ISSUE THREAD

**Issue by feixieer** [bkerler/mtkclient#332]
122 / 5,000
translation result
Recently MediaTek released their latest 5G chips Dimensity 9000 and 8100, but Mtk client cannot run successfully on this SOC.
The method of Mtk client has been fixed on Dimensity 920, will there be new solutions in the future?

**Comment by bkerler** [comment]
Unless we haven't got another bootrom bug : Most probably no.
