### ISSUE TITLE
Read device info

### ISSUE THREAD

**Issue by xinextialmatrix** [bkerler/mtkclient#338]
Is there a way to read device info like 
android version 
ram size
device name or model?

**Comment by kenkit** [comment]
yes, but first we will need an ext4/ext3  added onto mtkclient for this to work.

**Comment by kenkit** [comment]
That opens a whole new can of worms though, nowadays there is something called super image container, modern devices use this instead of system.

**Comment by Alephgsm** [comment]
hi , this operation need to mount ext4 partition and read file from partition,
i have c++\qt src if you want i can send you to adding on mtkclient
@bkerler

**Comment by bkerler** [comment]
Yes, sounds interesting.

**Comment by Alephgsm** [comment]
@bkerler you can send me message on telegram for src? t.me/GsmCoder
