### ISSUE TITLE
Can it unlock bootloader on MT6873?

### ISSUE THREAD

**Issue by ColorlessCat** [bkerler/mtkclient#340]
I mean,If the "fastboot flashing unlock" command doesn't work on my smartphone,Does this tool works?

**Comment by bukaixyz** [comment]
can

**Comment by ColorlessCat** [comment]
> can

型号是Oppo A92s，官方说修过漏洞了，真的可以吗

**Comment by ColorlessCat** [comment]
> can

闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。

**Comment by bukaixyz** [comment]
> > can
> 
> 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。

你才是呢 神精病 去宛平南路600号去，不要在github上发疯！

**Comment by bukaixyz** [comment]
> > can
> 
> 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。



> > can
> 
> 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。

恶心不拉的，可恶的要死

**Comment by bukaixyz** [comment]
> > can
> 
> 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。

脑子进水了，给大脑刷机修复一下，找上帝的售后去维修一下啊！自己解锁不了就在这发泄骂人

**Comment by bukaixyz** [comment]
> > can
> 
> 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。

DAMN IT

**Comment by ColorlessCat** [comment]
> > > can
> > 
> > 
> > 闭嘴吧，你就是个脑瘫玩意，老子日死你的妈。
> 
> 你才是呢 神精病 去宛平南路600号去，不要在github上发疯！

你母亲都下葬了还在这叫？知道你是精神病院跑出来的，出门小心点明天老子就给你抓进去
