### ISSUE TITLE
"mtk w recovery recovery.img" not working

### ISSUE THREAD

**Issue by JackuXL** [bkerler/mtkclient#347]
First, I executed `python3 mtk w recovery recovery.img` and it was successful. (recovery.img 16.3MB)
But after restarting, I executed `adb reboot recovery` but entered the official recovery.
I tried to execute `python3 mtk r recovery a.img` immediately after flashing the recovery.img, and the a.img obtained is the same size as the recovery of the original system.
`python3 mtk w recovery recovery.img` doesn't seem to be working?

----

首先，我执行`python3 mtk w recovery recovery.img`并成功。（recovery.img 16.3MB）
但是重启之后我执行`adb reboot recovery`却进入了官方的recovery。
我试着在刷入recovery.img之后立即执行了`python3 mtk r recovery a.img`，得到的a.img与原系统的recovery大小相同。
`python3 mtk w recovery recovery.img` 似乎并没有正常工作？

**Comment by JackuXL** [comment]
MT8167

**Comment by bukaixyz** [comment]
用按钮进rec，不要重启后再进

**Comment by JackuXL** [comment]
> 用按钮进rec，不要重启后再进

但是这个设备比较特殊没办法用按钮进rec

**Comment by bukaixyz** [comment]
> > 用按钮进rec，不要重启后再进
> 
> 但是这个设备比较特殊没办法用按钮进rec

啊这

**Comment by bukaixyz** [comment]
用fastboot刷rec,再用fastboot reboot recovery试一下

**Comment by kenkit** [comment]
immediately after flash, hold vol+ and power button wait for phone to start, after it starts release power button only.
When you restart your phone normally it overwrites with stock recovery.
