### ISSUE TITLE
redime 9c trying to flash Custom ROM

### ISSUE THREAD

**Issue by alaenvargut** [bkerler/mtkclient#356]
hey there!! I'm trying to use the tool with a Xiaomi Redmi 9C but it shows:

> Port - Device detected :)
> 
> Preloader - 	CPU:			MT6765/MT8768t(Helio P35/G35)
> Preloader - 	HW version:		0x0
> Preloader - 	WDT:			0x10007000
> Preloader - 	Uart:			0x11002000
> Preloader - 	Brom payload addr:	0x100a00
> Preloader - 	DA payload addr:	0x201000
> Preloader - 	CQ_DMA addr:		0x10212000
> Preloader - 	Var1:			0x25
> Preloader - Disabling Watchdog...
> Preloader - HW code:			0x766
> Preloader - Target config:		0xe7
> Preloader - 	SBC enabled:		True
> Preloader - 	SLA enabled:		True
> Preloader - 	DAA enabled:		True
> Preloader - 	SWJTAG enabled:		True
> Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
> Preloader - 	Root cert required:	False
> Preloader - 	Mem read auth:		True
> Preloader - 	Mem write auth:		True
> Preloader - 	Cmd 0xC8 blocked:	True
> Preloader - Get Target info
> Preloader - BROM mode detected.
> Preloader - 	HW subcode:		0x8a00
> Preloader - 	HW Ver:			0xca00
> Preloader - 	SW Ver:			0x0
> Preloader - ME_ID:			5AF36B06ADFCE3E072922319AABCAA38
> Preloader - SOC_ID:			3065E7F8477CBC5AD13926BC34E199DBEE98EB3E820D394C2DAD621BF10EE11B
> PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
> PLTools - Kamakiri / DA Run
> Kamakiri - Trying kamakiri..
> Kamakiri - Done sending payload...
> PLTools - Successfully sent payload: /Users/alaenvargut/mtkclient/mtkclient/payloads/mt6765_payload.bin
> Port - Device detected :)
> DA_handler - Device is protected.
> DA_handler - Device is in BROM mode. Trying to dump preloader.
> DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
> xflashext - Patching da2 ...
> DAXFlash - Successfully uploaded stage 1, jumping ..
> Preloader - Jumping to 0x200000
> Preloader - Jumping to 0x200000: ok.
> DAXFlash
> DAXFlash - [LIB]: xread error: local variable 'timeout' referenced before assignment
> DAXFlash
> DAXFlash - [LIB]: Error jumping to DA: -1

And idea of what should i do?

here is the preloader don't know if it is needed for something

[preloader_k65v1_64_bsp.bin.zip](https://github.com/bkerler/mtkclient/files/8597860/preloader_k65v1_64_bsp.bin.zip)

**Comment by KevinEduardo** [comment]
Try different cable
