### ISSUE TITLE
realmex7max Handshake failed

### ISSUE THREAD

**Issue by 1423947322** [bkerler/mtkclient#359]
......Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
Preloader
Preloader - [LIB]: [31mStatus: Handshake failed, retrying...[0m
DA_handler - Please disconnect, start mtkclient and reconnect.

Tried many times or showed a handshake failure driver is installed

**Comment by awsaxf** [comment]
Yes, this is the case with me too!

**Comment by patrick777777777** [comment]
Am using v1.6.0 but same issue
