### ISSUE TITLE
New Fixes Many Features Not Working

### ISSUE THREAD

**Issue by trancullong** [bkerler/mtkclient#36]
![Capture](https://user-images.githubusercontent.com/88564446/131597030-3425a350-052f-4b02-927d-7f8d073e00dd.PNG)
mtk payload or mtk e frp Not Working

**Comment by awsaxf** [comment]
Yes, my payload cannot work either!

**Comment by bkerler** [comment]
Please send console logs so I can see why it fails

**Comment by trancullong** [comment]
> Vui lòng gửi nhật ký bảng điều khiển để tôi có thể biết lý do tại sao nó không thành công

[mtk e frp.txt](https://github.com/bkerler/mtkclient/files/7088755/mtk.e.frp.txt)
[mtk payload.txt](https://github.com/bkerler/mtkclient/files/7088756/mtk.payload.txt)

**Comment by bkerler** [comment]
Thanks ;) The issues should now be sorted.

**Comment by trancullong** [comment]
> Thanks ;) The issues should now be sorted.

DAXFlash - EMMC CID:        90014a68423861503e034388ad8127ff
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x1000000
DAXFlash - EMMC USER Size:  0x747c00000
DAXFlash - DA-CODE      : 0x666D0
Formatted sector 455744 with sector count 2048.

Thanks Done

**Comment by marat2509** [comment]
@bkerler Close issue!
