### ISSUE TITLE
Unable to write/erase RMPB

### ISSUE THREAD

**Issue by shankarEE** [bkerler/mtkclient#360]
i have samsung a12 sm120f mtk g35 device . i tried to write/erase its rmpb but it return with error - unable to write rmpb at sector 0. and while eraseing give u/p -
![Screenshot from 2022-05-02 14-27-32](https://user-images.githubusercontent.com/104766886/166226552-d77ad425-df4e-47b7-900e-d192d97a1d5d.png)
NULL
i can read RMPB but cant write it . for information the device is kg locked state

**Comment by samuel1003** [comment]
This a bug, hope be fixed soom. Same problem for MTK Client CMD.

**Comment by bkerler** [comment]
That's no bug. The rpmb key is derived from trustzone and that would be a bigger task to reverse engineer. Samsung has additional security that would break as well.

**Comment by shankarEE** [comment]
> That's no bug. The rpmb key is derived from trustzone and that would be a bigger task to reverse engineer. Samsung has additional security that would break as well.

but there is tool available for windows called "unlock tool" (of-course premium) which can write rmpb img https://unlocktool.net/

**Comment by brokeruly** [comment]
> 

its based on chimera method.
