### ISSUE TITLE
Facing some error after BL unlock

### ISSUE THREAD

**Issue by ASIMKHAN222** [bkerler/mtkclient#364]
Using Vivo S1, chipset MT6768 Helio P65..

I unlock bootloader by MTK client, with Gui interface.. 
After unlock my userdata was not wiped
Do i need to wipe data before or after unlocking bootloader? 
Because i am facing error in magisk Root and volume button...

**Comment by google-mirror** [comment]
No

**Comment by xloem** [comment]
just to be more positive after weird "no", I'm new to mtkclient but it looks like bootloader unlocking does not wipe user data. to wipe user data some other command after this is needed.

**Comment by bkerler** [comment]
For unlocking, please don't post issues over here, this is meant for mtkclient only, not for magisk issues.
