### ISSUE TITLE
Oneplus Nord 2 (DN2103)

### ISSUE THREAD

**Issue by high3eam** [bkerler/mtkclient#366]
Trying mtkclient to detect my phone (OP Nord 2 DN2103) by holding down all hw buttons on powered off device, then plugging in USB port to my machine (Windows 11: UsbDK and MTK Serial drivers installed), but mtkclient doesn't recognize my device.

Made a screenshot with the relevant info:

![image](https://user-images.githubusercontent.com/15855905/167460249-25706d98-b32d-483e-98ae-73397069f2ee.png)

Any idea on what I am missing for successful connection? Thanks!

**Comment by theman12344321** [comment]
if you find a fix let me know i too be stuck at this point

**Comment by guaro94** [comment]
Me too

**Comment by guaro94** [comment]
I tried to update driver to usb serial driver like xda tutorial say but nothing, seems it cant recognize it anyway. How to solve now?
