### ISSUE TITLE
python mtk stage error

### ISSUE THREAD

**Issue by trancullong** [bkerler/mtkclient#37]
python mtk stage

Preloader - Waiting PreLoader VCOM
............
............
Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - ME_ID:                      4FD38FC3D325E9352E9387CF1050E00C
Preloader - SOC_ID:                     94FD535E13F3BDA8F51960A06671C0863DF00DD61777B264E4511893086980FF
Main - Uploading stage 1
PLTools - Loading payload from C:\Dongle\PayLoads\MtkClientDebug\ref\mtkclient\payloads\generic_stage1_payload.bin, 0x3ec bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Dongle\PayLoads\MtkClientDebug\ref\mtkclient\payloads\generic_stage1_payload.bin
Main - Successfully uploaded stage 1, sending stage 2
Main - Done sending stage2, size 0x4000.
Main - Done jumping stage2 at 00201000
Traceback (most recent call last):
  File "C:\Dongle\PayLoads\MtkClientDebug\ref\mtk", line 1524, in <module>
    mtk = Main(args).run()
  File "C:\Dongle\PayLoads\MtkClientDebug\ref\mtk", line 578, in run
    ack = unpack(">I", mtk.port.read(4))[0]
AttributeError: 'Port' object has no attribute 'read'

**Comment by marat2509** [comment]
Please re-run with --debugmode option

**Comment by bkerler** [comment]
Not needed. Will be fixed in a few min

**Comment by bkerler** [comment]
fixed with commit 53f873a32579b21edb49f1d5768be06c019d08ef

**Comment by trancullong** [comment]
> fixed with commit [53f873a](https://github.com/bkerler/mtkclient/commit/53f873a32579b21edb49f1d5768be06c019d08ef)




python mtk stage
python stage2 rpmb
.Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - ME_ID:                      4FD38FC3D325E9352E9387CF1050E00C
Preloader - SOC_ID:                     94FD535E13F3BDA8F51960A06671C0863DF00DD61777B264E4511893086980FF
Main - Uploading stage 1
PLTools - Loading payload from C:\Dongle\PayLoads\MtkClientDebug\ref\mtkclient\payloads\generic_stage1_payload.bin, 0x3ec bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Dongle\PayLoads\MtkClientDebug\ref\mtkclient\payloads\generic_stage1_payload.bin
Main - Successfully uploaded stage 1, sending stage 2
Main - Done sending stage2, size 0x4000.
Main - Done jumping stage2 at 00201000
Main - Successfully loaded stage2
Stage2 - Reading rpmb...
Progress: |██------------------------------------------------| 3.3% Complete, Sector:0x421500

Done - thanks you so much
