### ISSUE TITLE
Unknown seccfg partition header

### ISSUE THREAD

**Issue by CancroPlus** [bkerler/mtkclient#371]
Hello, I have a Mblu 5S (MT6753) and I tried to unlock Bootloader for it, but it failed, just like below
![屏幕截图 2022-05-13 130517](https://user-images.githubusercontent.com/70503811/168214878-39a7d78b-99a7-468d-9143-b792636f2ad5.jpg)
![屏幕截图 2022-05-13 130531](https://user-images.githubusercontent.com/70503811/168214895-2c144db0-b415-4f2c-bc15-e127b566d48a.jpg)
Could you please help me？

**Comment by bukaixyz** [comment]
Please post a full console log. A screenshot doesn't help.
