### ISSUE TITLE
blu g1 pro 

### ISSUE THREAD

**Issue by dtingley11** [bkerler/mtkclient#374]
Tried using this on the g91 pro:

I get this error

**upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)*
[log.txt](https://github.com/bkerler/mtkclient/files/8694108/log.txt)
[hwparam.json.zip](https://github.com/bkerler/mtkclient/files/8694114/hwparam.json.zip)
*

**Comment by Appleisbest** [comment]
[bootrom_813.bin.zip](https://github.com/bkerler/mtkclient/files/8694118/bootrom_813.bin.zip)
I did dump the bottom, so I also attached it here. Hope that is useful.

**Comment by bkerler** [comment]
Please post the console log so I can see what the error might be caused by.
