### ISSUE TITLE
--serialport

### ISSUE THREAD

**Issue by oakieville** [bkerler/mtkclient#377]
Im confused on the exact useage of --serialport command in afew ways, first the format of the command --serialport COM1 or --serialport 1 or --serialport=COM1 etc...
Also is usbdk still needed, if --serialport is not given does it auto find serialport or would it then use usbdk. With latest version im haing an isdue detecting the device

**Comment by bkerler** [comment]
Serialport isn't yet supported, it just has been prepared so far.

**Comment by oakieville** [comment]
Oh ok i see awesome ty
