### ISSUE TITLE
Console multiple commands

### ISSUE THREAD

**Issue by breakersvd** [bkerler/mtkclient#379]
Hi,

I know this question has been asked many times but the since you made `mtk_gui` script to perform several commands on same connetion then `mtk` script can did that, Please can edit that or help to do that ?

It is very important

Thanks in advance

@bkerler

**Comment by samuel1003** [comment]
It have been asked many times, but it seems @bkerler no interested. Same happening with Write RPMB. Long time issue, but no solved yet. Maybe he focus in others things.

**Comment by breakersvd** [comment]
> It have been asked many times, but it seems @bkerler no interested. Same happening with Write RPMB. Long time issue, but no solved yet. Maybe he focus in others things.

Strange, despite the script have `reinit` function to support that, it seems it miss something

**Comment by bkerler** [comment]
The reinit works fine. If it doesn't work, it could be that the .state file cannot be written for some unknown reason. I haven't tried on Windows however, but on Linux it works fine for both xflash and legacy on sending multiple commands (like mtk r gpt gpt.bin two times after another)

**Comment by samuel1003** [comment]
> The reinit works fine. If it doesn't work, it could be that the .state file cannot be written for some unknown reason. I haven't tried on Windows however, but on Linux it works fine for both xflash and legacy on sending multiple commands (like mtk r gpt gpt.bin two times after another)

It works disconnecting phone on each command. Many request about this. Hope you can take some time to fix this problem bro.

**Comment by breakersvd** [comment]
> The reinit works fine. If it doesn't work, it could be that the .state file cannot be written for some unknown reason. I haven't tried on Windows however, but on Linux it works fine for both xflash and legacy on sending multiple commands (like mtk r gpt gpt.bin two times after another)

On Windows, the `.state` file is written fine but the problem happened on `reinit` daloader exactly in `status()` function on SENDCTRL device command.

I fixed that by making interactive shell in the mtk script itself, this will save connection session for the device and allow do multi commands in same session, But it will be great if you fix this issue completely.

**Comment by bkerler** [comment]
There is no status() function in the reinit of daloader. Can you be more precise ? There are many Control commands

**Comment by bkerler** [comment]
If you are having this issue under Windows, it's very much likely you're having a driver issue because on leaving the connection, the port should normally be left open.

**Comment by breakersvd** [comment]
> If you are having this issue under Windows, it's very much likely you're having a driver issue because on leaving the connection, the port should normally be left open.

All drivers listed in the solution are installed correctly, I will do the test and upload to you the exact error results

**Comment by bkerler** [comment]
With drivers I mean you need to ensure that after using mtkclient, in the device manager the port doesn't have a question mark, otherwise you may need to reinstall the driver first before reusing the mtkclient again. That's a common issue with usbdk which likely won't be fixed by the usbdk author.

**Comment by samuel1003** [comment]
> With drivers I mean you need to ensure that after using mtkclient, in the device manager the port doesn't have a question mark, otherwise you may need to reinstall the driver first before reusing the mtkclient again. That's a common issue with usbdk which likely won't be fixed by the usbdk author.

This error only occure in console mode, that is why i am sure can be fixed same like you doing in GUI.
i just tested your final release but still need to disconnect device for each command i wish to send.
I could send you teamviewer if you willing to check.

**Comment by bkerler** [comment]
> 

Yes teamviewer would be good with pycharm preinstalled. Contact me via telegram.

**Comment by bkerler** [comment]
> > There is no status() function in the reinit of daloader. Can you be more precise ? There are many Control commands
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ValueError: underlying buffer has been detached
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ValueError: underlying buffer has been detached
> Traceback (most recent call last):
>   File "mtk", line 1709, in <module>
>   File "mtk", line 632, in run
>   File "mtkclient\Library\mtk_daloader.py", line 61, in reinit
>   File "mtkclient\Library\mtk_daxflash.py", line 994, in reinit
>   File "mtkclient\Library\mtk_daxflash.py", line 482, in get_ram_info
>   File "mtkclient\Library\mtk_daxflash.py", line 260, in send_devctrl
>   File "mtkclient\Library\mtk_daxflash.py", line 211, in status
> struct.error: unpack requires a buffer of 12 bytes
> ```
> 
> @bkerler this is the error results.

Thanks that will help to track the issue

**Comment by bkerler** [comment]
Implemented with [537c8c7](https://github.com/bkerler/mtkclient/commit/537c8c76bccfc5fe7615ecf578081257e45b2591)
