### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by rebainoor** [bkerler/mtkclient#38]
C:\Users\Administrateur\Desktop\mtkclient--1.42>python mtk printgpt --preloader=preloader_oppo6765.bin

Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

...........

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

...........

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

...........

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

...........

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

..Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - ME_ID:                      0E7222F1FE852E5909CD57027BFB3120
Preloader - SOC_ID:                     1C79ADE6F3FCFB84A4A6C82BA846E379AD40CD11830AE83C7E9E97680AE52B6E
PLTools - Loading payload from C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\payloads\mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\payloads\mt6765_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 13014e47314a3953
Traceback (most recent call last):
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtk", line 1569, in <module>
    mtk = Main(args).run()
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtk", line 673, in run
    if not mtk.daloader.upload_da(preloader=preloader):
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\Library\mtk_daloader.py", line 87, in upload_da
    return self.da.upload_da()
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\Library\mtk_daxflash.py", line 991, in upload_da
    if not self.send_emi(self.daconfig.emi):
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\Library\mtk_daxflash.py", line 304, in send_emi
    return self.send_param([emi])
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\Library\mtk_daxflash.py", line 259, in send_param
    status = self.status()
  File "C:\Users\Administrateur\Desktop\mtkclient--1.42\mtkclient\Library\mtk_daxflash.py", line 227, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**DEBUG_LOG**
[log.zip](https://github.com/bkerler/mtkclient/files/7091648/log.zip)
![brom](https://user-images.githubusercontent.com/30597366/131693632-6c86f496-d6de-48d4-b218-8e7cbc467956.jpg)

**Comment by bkerler** [comment]
Please try the latest commit.

**Comment by bkerler** [comment]
Closing as this is same as issue #32
