### ISSUE TITLE
Configuring of Stage 2 in DA_Legacy is broken.

### ISSUE THREAD

**Issue by Boggart** [bkerler/mtkclient#381]
Configuring the [second stage](https://github.com/bkerler/mtkclient/blob/998fed5f90c5cfc2ce4b04657f12a2f952841a8c/mtkclient/Library/mtk_dalegacy.py#L1038) fails with a NoneType error because [da](https://github.com/bkerler/mtkclient/blob/bb165a0b49d90e795960d5cc52e071a80b4588de/mtkclient/config/mtk_config.py#L51) in mtk_config.py is never changed from it's default of None, but the [bmtsettings](https://github.com/bkerler/mtkclient/blob/bb165a0b49d90e795960d5cc52e071a80b4588de/mtkclient/config/mtk_config.py#L187) function attempts to access it's daconfig variable resulting in an exception.
Issues that are related:
#270, #301, #328

**Comment by xxroot** [comment]
Yes, now all my Xiaomi phones are disconnected
It always stops here
`Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.


Port - Device detected :)

`

**Comment by xxroot** [comment]
How to fix this problem?

**Comment by bkerler** [comment]
Yes, I'm aware of this problem, not sure yet what is causing it. The reason is that the phone doesn't respond to the bmt settings. I think the 5.2152 driver might cause this.

**Comment by bkerler** [comment]
@Boggart Please provide a full log so I can see what causes your issue.

**Comment by Boggart** [comment]
Unfortunately the laptop I was using this on cratered and I haven't had time to dig through the linux partition using my desktop. I'll update this issue when I can, sorry.
