### ISSUE TITLE
After Xiaomi unlocks the bootloader Show the dm - verity  

### ISSUE THREAD

**Issue by xxroot** [bkerler/mtkclient#383]
After Xiaomi unlocks the bootloader Show the dm - verity  
chimera and unlockTools is unlocked, it is not displayed. Can repair it?

**Comment by google-mirror** [comment]
Clear dm-verity status via ``fastboot oem cdms``

**Comment by xxroot** [comment]
> Clear dm-verity status via `fastboot oem cdms`

`fastboot oem cdms
FAILED (remote: 'unknown command')
fastboot: error: Command failed`

**Comment by bkerler** [comment]
Sorry, I don't support unlocking issues.
