### ISSUE TITLE
MT6771 error

### ISSUE THREAD

**Issue by adityathapa** [bkerler/mtkclient#396]
I have a Vivo V11i (Mt6771). The MTK client gets stuck at 

![image](https://user-images.githubusercontent.com/74758072/173221039-0841d6d8-4902-441e-8788-dd128295f917.png)

What could be the issue?

Currently running Windows 10, all drivers are installed.

**Comment by bkerler** [comment]
Please retry using --preloader option and preloader from the firmware

**Comment by adityathapa** [comment]
I used this command:
`python mtk printgpt --preloader vivov11i_preloader.bin`

And once again got an error. This is the output:
![image](https://user-images.githubusercontent.com/74758072/173623426-188a99b8-ba04-46fb-a563-c5a224c04224.png)
