### ISSUE TITLE
Error on sending parameter: Read parttbl failed 

### ISSUE THREAD

**Issue by samuel1003** [bkerler/mtkclient#399]
Some idea how to fix this Issue?

Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      151F022C61F82E6B2340038B9E93F5E9
Preloader - SOC_ID:                     5D7E1B05F504736C2FD422D1303455350DDF2A73BF5EB5F706A21F5833E18F91
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\samuel\Desktop\mtkclient-main_3\mtkclient-main\mtkclient\payloads\mt6853_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x34
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM5P8001DM-B42
DAXFlash - UFS CID:      ce014b4d355038303031444d2d423432
DAXFlash - UFS LU0 Size: 0xee5800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ce014b4d355038303031444d2d423432
DAXFlash - Sending emi data ...
DAXFlash - DRAM setup passed.
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x34
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM5P8001DM-B42
DAXFlash - UFS CID:      ce014b4d355038303031444d2d423432
DAXFlash - UFS LU0 Size: 0xee5800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - HW-CODE         : 0x996
DAXFlash - HWSUB-CODE      : 0x8A00
DAXFlash - HW-VERSION      : 0xCA00
DAXFlash - SW-VERSION      : 0x0
DAXFlash - CHIP-EVOLUTION  : 0x1
DAXFlash - DA-VERSION      : 1.0
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - DA Extensions successfully added
DA_handler - Writing offset 0x53b0000 with length 0x80000
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: Read parttbl failed (0xc0040007)←[0m
Failed to write partition.img to offset 0x53b0000 with length 0x80000.

**Comment by mtklover** [comment]
@bkerler  this is what i mean

**Comment by bkerler** [comment]
No idea, but it seems like you need to write a partition table to the first sectors first

**Comment by oakieville** [comment]
I get this error also i can read the same offset i tried writing gpt first still same
