### ISSUE TITLE
Writing to the boot file will randomly stop at 15%-90% and cannot be written completely.  The phone doesn't work anymore 

### ISSUE THREAD

**Issue by xxroot** [bkerler/mtkclient#403]
.....Port - Device detected :)
Preloader -     CPU:                    MT6755/MT6750/M/T/S(Helio P10/P15/P18)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212c00
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x326
Preloader - Target config:              0x5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb00
Preloader -     SW Ver:                 0x1
Preloader - ME_ID:                      6937B29C48D8849ADAC6309CE058A4B0
Port - Device detected :)
Successfully extracted preloader for this device to: preloader_mtk6750_nice_al10.bin
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - DRAM setup passed.
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         HAG4a2
DAXFlash - EMMC CID:        90014a484147346132d41e73dc7824dd
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x400000
DAXFlash - EMMC USER Size:  0x3ab400000
DAXFlash - HW-CODE         : 0x6750
DAXFlash - HWSUB-CODE      : 0x8A00
DAXFlash - HW-VERSION      : 0xCB00
DAXFlash - SW-VERSION      : 0x1
DAXFlash - CHIP-EVOLUTION  : 0x0
DAXFlash - DA-VERSION      : 1.0
DAXFlash - Reconnecting to preloader
DAXFlash - Connected to preloader
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - DA Extensions successfully added
Progress: |████████------------------------------------------| 15.0% Write (Sector 0x1000 of 0x6AFF, 01s left) 7.07 MB/s
DAXFlash
DAXFlash - [LIB]: [31munpack requires a buffer of 12 bytes[0m

**Comment by xxroot** [comment]
Tried all USB ports, all the same results

**Comment by kenkit** [comment]
which phone ?
you are welcome to use my tool to write custom partitions.
Just open qtapp choose flash custom partition, write boot and choose file.
If phone needs auth use mct bypass or similar.
Inbox for free support or join our discord 
[Neon support](https://discord.gg/VMzpQUS)

**Comment by xxroot** [comment]
> 

huswei nice-al10
