### ISSUE TITLE
bootloader unlocked and safe mode for "illegal unlock"

### ISSUE THREAD

**Issue by DoctorSubtilis** [bkerler/mtkclient#405]
I want to unlock the bootloader of my mtk device (Moto e6 plus), using your live-dvd v.4.  
I didn't manage to use it as usb-live (and this is a first problem: it is possible to have a usb-live bootable?), so I'm trying to use it in virtualbox (I managed to install it in virtualbox).  

Before proceeding, a question: can I unlock the bootloader and install supersu instead of magisk (I don't want wipe all my data)?

If the answer is yes, how should I go ahead? Virtualbox recognizes the phone, but mtkclient doesn't, even after rebooting with both vol key pressed.

**Comment by DoctorSubtilis** [comment]
I burnt a dvd, but nothing to do: the live-dvd doesn't recognize the newtwork, and neither the device, even trying in several ways.

**Comment by bkerler** [comment]
What hardware / device do you use ?

**Comment by DoctorSubtilis** [comment]
> What hardware / device do you use ?

At least two different PC (with DVD RW, and 8 gb of ram, wired connection), and a Motorola e6 plus.

**Comment by DoctorSubtilis** [comment]
This time I the network is recognized. But the smartphone not. What steps I should follow, and what program?

**Comment by bkerler** [comment]
Make sure the rules match your device, and also that the device is booting into brom mode

**Comment by DoctorSubtilis** [comment]
Hello, today I managed (not in virtualbox but in a desktop linux system) to unlock the bootloader of my moto e6 plus. But I had to re-lock because the phone restarted in "safe mode" due to a "illegal unlock".
Therfore let me re-ask: can I unlock the bootloader and install **supersu** instead of magisk? And how?

**Comment by DoctorSubtilis** [comment]
I solved with the command: `python mtk **w** boot,vbmeta boot.img,vbmeta.img`

But how can root my phone?

**Comment by DoctorSubtilis** [comment]
I open now a new thread, because I solved somehow the problem of safe mode (even I had to reinstall all my accounts and apps).
