### ISSUE TITLE
Add ability to boot an image without flashing it (like fastboot boot boot.img)

### ISSUE THREAD

**Issue by benthetechguy** [bkerler/mtkclient#408]
It would be very helpful if mtkclient had the ability to load and boot an image instead of the current method of flashing it to the boot partition then rebooting. fastboot can do this with `fastboot boot boot.img` as an example.

**Comment by bkerler** [comment]
That would require that at least preloader and lk are patched and depending on the device, this is not trivial as one would need to patch away all efuse checks to disable secure boot. Or alternatively loading a mini-lk .. but still no trivial task either.

**Comment by bkerler** [comment]
from RAM means you need to init dram first and setup the rest like tz and atf as well.
