### ISSUE TITLE
stage2 error sej_aes_decrypt and sej_aes_encrypt are both False

### ISSUE THREAD

**Issue by 330wang** [bkerler/mtkclient#41]
stage2 Line:389 Line:395  all are False

if mode == "sej_aes_decrypt":
dec_data = self.hwcrypto.aes_hwcrypt(mode="cbc", data=data, btype="sej", encrypt=**False**)
keyinfo+="\n"
keyinfo+="Data: " + hexlify(dec_data).decode('utf-8')
keyinfo+="\n"
return dec_data, keyinfo
elif mode == "sej_aes_encrypt":
enc_data = self.hwcrypto.aes_hwcrypt(mode="cbc", data=data, btype="sej", encrypt=**False**)
keyinfo+="\n"
keyinfo+="Data: " + hexlify(enc_data).decode('utf-8')
keyinfo+="\n"
return enc_data, keyinfo

**Comment by bkerler** [comment]
Sorry I don't understand what you mean with that issue ....

**Comment by 330wang** [comment]
the mode sej_aes_decrypt -> encrypt=False

**Comment by 330wang** [comment]
the new code is right!!
