### ISSUE TITLE
Android 12 ( Realme UI 3.0) / ( Color OS version - V12 )  Support request

### ISSUE THREAD

**Issue by RaghuVarma331** [bkerler/mtkclient#410]
Hi ,

Recently i procured Realme Narzo 50 ( 5G ) running on Android 12 ( Realme UI 3.0) / ( Color OS version - V12 ) out of the box.

Well , for this device we don't have official unlock yet. So i just tried using your MTK client to unlock my device bootloader. everything went fine during unlocking process. I even get dm Verity error while booting up my phone but unfortunately bootloader is still locked. 

i checked the bootloader unlock status in developer options and from fastbootd as well but it didn't unlocked my phone.

I attached the output for bootloader unlock command execution and preloader from factory stock rom.

[preloader_k6833v1_64.bin](https://github.com/bkerler/mtkclient/files/9029081/preloader_k6833v1_64.zip)

[unlock_output-log.txt](https://github.com/bkerler/mtkclient/files/9029076/log.txt)

Please have a look & add the support in your valuable free time.

Thank you!

**Comment by RaghuVarma331** [comment]
Hi ,

I am attaching the dumps from my phone ( preloader , lk , seccfg-locked & seccfg-unlocked ).

Moreover i attached the output for bootloader unlock command execution as well.

Can you please help me at the earliest?

[preloader_k6833v1_64.bin](https://github.com/bkerler/mtkclient/files/9092024/preloader_k6833v1_64.zip)
[seccfg-unlocked.bin](https://github.com/bkerler/mtkclient/files/9092022/seccfg-unlocked.zip)
[seccfg-locked.bin](https://github.com/bkerler/mtkclient/files/9092023/seccfg-locked.zip)
[lk.img](https://github.com/bkerler/mtkclient/files/9092058/lk.zip)
[[unlock_output-log.txt](https://github.com/bkerler/mtkclient/files/9092025/log.txt)

Thank you!

**Comment by rama982** [comment]
Hello, sorry if out of topic but i also have realme narzo 50 5g and get dm corruption, how to revert back to stock?

**Comment by RaghuVarma331** [comment]
Hi [bkerler](https://github.com/bkerler)

Almost 7 months completed but still Realme didn't even bother about New models which are newly launched after March 2022. Now the mediatek models has no proper way to unlock bootloader via deeptest apk to submit application either.

Now we all have very less hopes towards official way to unlock through deeptest apk. but the only way for us is all about your mtkclient so please spare sometime and show some path for Realme mediatek community on latest security scrap by them.

Thank you for your hardwork.

**Comment by tr1ten** [comment]
@RaghuVarma331 Were you able root your device? i have realme 7 RMX2151 but this method doesn't work :(
