### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by benthetechguy** [bkerler/mtkclient#413]
Your current versioning scheme goes like this:
1.4
1.41
...
1.5
1.51
...
1.9

The problem is 1.52 is considered the newest version by any automated version comparison, for example in a package manager.
The solution is to use [semantic versioning](https://semver.org) in the future. That would make your versions look like this:
1.4.0 (or just 1.4)
1.4.1
...
1.5.0 (or just 1.5)
1.5.1
...
1.9.0 (or just 1.9)

Using the semantic versioning scheme, the automated version comparison would correctly see 1.9(.0) as the newest version.

**Comment by bkerler** [comment]
There is no 1.9 version. It was just prepared for release. But thanks for the hint.
