### ISSUE TITLE
Support mt6895

### ISSUE THREAD

**Issue by ghost** [bkerler/mtkclient#429]
Good evening. 🌙
Is it planned to support the mtkclient on the mt6895 platform?

**Comment by imyashaswee** [comment]
Hi,
Any plans to add support for MT6895?

**Comment by bkerler** [comment]
Sorry, but third party tools are currently not supported. mt68xxT support research will be done, but won't be published.

**Comment by imyashaswee** [comment]
> Sorry, but third party tools are currently not supported. mt68xxT support research will be done, but won't be published.

@bkerler thanks for the reply. So if I follow the installation guide mentioned by you then MT6895 is supported or yet support is to be added? 

Processor - MediaTek Dimensity 8100
Device - OnePlus 10R/ Ace

**Comment by bkerler** [comment]
If you are able to dump the brom, then yes, support for this device will be added.

**Comment by imyashaswee** [comment]
@bkerler Olay. Thanks. Appreciate the response.

**Comment by railjty** [comment]
> If you are able to dump the brom, then yes, support for this device will be added.

So how can we export the brom?

**Comment by Evengard** [comment]
The preloader is not the same as the brom, right?
Is there a possibility to dump it from a running system? If yes, which partition it is? Or which offset?

**Comment by Atassen21** [comment]
> Sorry, but third party tools are currently not supported. mt68xxT support research will be done, but won't be published.

sir my device redmi k50i with mt 6895 is bricked...i really need this tool to suuport this chip ..plz do something😥😥
