### ISSUE TITLE
moto e6 plus root failed

### ISSUE THREAD

**Issue by DoctorSubtilis** [bkerler/mtkclient#437]
Yesterday I went near to the root, following the steps in your webpage, except for the reset after unlocking the device: I didn't reset, because I was afraid to get a "safe mode" device (as previously was happened: the first thing I tried was to unlock the Moto e6 plus, successfully but uselessly, unlocked the device goes in safe mode).   
As a result I got a device any way unusable:  
 * if unlocked: starting in safe mode for illegal unlock,
 * if (re-)locked: with an infinite loop at boot, claiming for a non-corresponding image (for a signature problem, it seems to remember)

Now (after flashing the original boot.img) I have again a normal smartphone, but I want to root it.

What should I do? Was the lack of reset after unlocking the problem, or maybe I had to downgrade the firmware?

**Comment by mslhii** [comment]
For some reason mtkclient doesn't play nice with Moto boot loaders due to how they do things but you can try this: https://forum.xda-developers.com/t/guide-how-to-unlock-bootloader-in-the-moto-e6-plus-install-twrp-with-windows-and-linux.4204519/

**Comment by DoctorSubtilis** [comment]
Thank you. Uhm.. It seems quite complicated: do you think that it without risk?
