### ISSUE TITLE
Cannot read ROM with MT6592

### ISSUE THREAD

**Issue by Martilb** [bkerler/mtkclient#441]
Impossible to do something else that extracting preloader.
Here is the log file and preloader extracted.
For info, SP Flash Tool get stuck also..
[ErrorLog.txt](https://github.com/bkerler/mtkclient/files/9199169/ErrorLog.txt)
[preloader_sf6592_wet_l.zip](https://github.com/bkerler/mtkclient/files/9199177/preloader_sf6592_wet_l.zip)
Any help to understand what is missing ?
Thanks

**Comment by Martilb** [comment]
ErrorLog with Debug option
[ErrorLogDebug.txt](https://github.com/bkerler/mtkclient/files/9199271/ErrorLogDebug.txt)
.

**Comment by Martilb** [comment]
Log.txt file
[log.txt](https://github.com/bkerler/mtkclient/files/9199363/log.txt)
.

**Comment by R0rt1z2** [comment]
Try with [this commit](https://github.com/bkerler/mtkclient/pull/436/commits).

**Comment by Martilb** [comment]
Hi. Thanks for your help but program get stuck a little bit forward in the code. See log file attached
[log.txt](https://github.com/bkerler/mtkclient/files/9222650/log.txt)
.

**Comment by R0rt1z2** [comment]
Can you try with this [DA](https://github.com/bkerler/mtkclient/files/9226583/MTK_AllInOne_DA.zip)?

**Comment by Martilb** [comment]
How to force mtk to use it ? Whatever I do it allways load MTK_AllInOne_DA_5.1824.bin ? (If I change the name, it take the new name).

**Comment by Martilb** [comment]
It seems by deleting MTK_AllInOne_DA_5.1824.bin and taking the one you sent me and changing the name, program run a bit longer but get out with an error. See log attached
[log.txt](https://github.com/bkerler/mtkclient/files/9228271/log.txt)
.

**Comment by Martilb** [comment]
For your info this last DA file is not recognized by SP Flash Tool.

**Comment by Martilb** [comment]
DeviceClass - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "C:\Users\marcl\Downloads\mtkclient-main\mtk", line 814, in <module>
    mtk = Main(args).run(parser)
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_main.py", line 615, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_da_cmd.py", line 112, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 209, in upload_da
    return self.da.upload_da()
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1102, in upload_da
    if self.upload():
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1073, in upload
    if self.set_stage2_config(self.config.hwcode):
  File "C:\Users\marcl\Downloads\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 943, in set_stage2_config
    checksum = unpack(">H", self.usbread(2))[0]  # 0x440C
struct.error: unpack requires a buffer of 2 bytes

**Comment by Martilb** [comment]
[ErrorLogDebug.txt](https://github.com/bkerler/mtkclient/files/9228456/ErrorLogDebug.txt)

**Comment by Martilb** [comment]
I tried with older version 1420, and another error. But in stage 2
[log.txt](https://github.com/bkerler/mtkclient/files/9228505/log.txt)
.

**Comment by Martilb** [comment]
Hi, 
I found the problem. It is due to the specifiv hardawre of the tablet. You have to disconnect the battery when you plug the USB cable and reconnect the battery when DA is loaded (1/10 sec to do it !).

**Comment by Martilb** [comment]
And DA has to be from a version of SP Flash Tool < V5.1548 (MTK_AllInOne_DA.bin from 2015/11/29 or older).
