### ISSUE TITLE
Timing out waiting for Stage 2 to Execute

### ISSUE THREAD

**Issue by bbetter173** [bkerler/mtkclient#448]
Device: [Opel Touch Flip](https://www.opelmobile.com.au/our-products/touch-flip/)
[log.txt](https://github.com/bkerler/mtkclient/files/9265253/log.txt)

On a sidenote, I haven't been able to figure out how to get this device to enter BROM mode yet either if anyone has suggestions. Lots of hardware keys, but I've tried the common ones:

Vol Up + Power On (Boots to Recovery)
Vol Down + Power On (Seems to stay in Preload mode until volume released)
Vol Up + Vol Down (Boots to recovery sometimes, might be missing the down key when it does)

It does have some hardware similarities with the Sunbeam F1: CPU and the external appearance look very familiar.

**Comment by bkerler** [comment]
If it hangs in stage 2 it is very likely your device isn't in brom but preloader mode and has daa enabled, even though it might be displayed as False/disabled, or your dram setup in the preloader doesn't match your device (i.e. delete the mtkclient/loader/preloader directory).
