### ISSUE TITLE
can't start GUI

### ISSUE THREAD

**Issue by AshiVered** [bkerler/mtkclient#450]
![image](https://user-images.githubusercontent.com/76535872/183305136-8bfc1e52-0595-4271-b260-f4072743c00c.png)
CLI working.
windows 11 home
thanks!

**Comment by skemp117** [comment]
Same problem windows 10

**Comment by skemp117** [comment]
What worked for me was copying the platforms in pyside anaconda3\Lib\site-packages\PySide6\plugins\platforms to anaconda3\Library\plugins\platforms

**Comment by bkerler** [comment]
Closing this now as it's not mtkclient but os related.
