### ISSUE TITLE
Source code for payloads

### ISSUE THREAD

**Issue by benthetechguy** [bkerler/mtkclient#452]
Even though the payloads are only a few bytes and run on the phone's CPU instead of that of the computer running mtkclient, many distributions like Debian require source code for all binaries to be available if a piece of software is to be considered free.
If these payloads are hand-written, which could be likely given their size and number, could you provide any kind of source code used to generate the payloads at all?

**Comment by bkerler** [comment]
I refer to the license of the code. The payloads are planned to be released but not right now.
