### ISSUE TITLE
 ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Theo1996** [bkerler/mtkclient#454]
I installed it without issues
 then I run  "python mtk_gui" and I get this

Traceback (most recent call last):
  File "mtk_gui", line 13, in <module>
    from PySide6.QtCore import Qt, QVariantAnimation, Signal, QObject, QSize, QTranslator, QLocale, QLibraryInfo, \
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.

**Comment by bkerler** [comment]
Please make sure you install the requirements first (pyside6 and qt5)

**Comment by Theo1996** [comment]
I did install the requirements though. Maybe I need to reinstall python and everything else?
