### ISSUE TITLE
bootloader not unlocked

### ISSUE THREAD

**Issue by LolekLiam** [bkerler/mtkclient#457]
at boot screen it says Orange state Your device has been unlocked and can’t be trusted…Your device will boot in 5 seconds.
but when i try fastboot flashing unlock or any other fastboot unlock cmd it fails. also adb shell getprop sys.oem_unlock_allowed returns with 0. How to fix this? also i have android 7.0 and my device is meizu m3 max.

**Comment by ruudvtony** [comment]
if u have unlock ur devices with mtk client or default fastboot unlock command, u will get 0 since it's already unlocked, it's different when u havent unlocked, u will get 1xxx result or chances to unlock

**Comment by LolekLiam** [comment]
yes but why does it fail at fastboot unlock? the phone has no oem unlock option at developer options and the phone wasn't even meant to be unlocked. it was supposed to be locked by the manufacturer or smthing like that. also smthing not relevant to this...when i format data and flash forceencrypt disabler, my device doesn't boot and just hangs at the boot animation. However if i flash back stock recovery and install update.zip, it says "decryption failed the password you entered is correct but unfortunately your data is corrupt" or smthing like that. How to fix this?

**Comment by ruudvtony** [comment]
try to erase ur data partition, thats because u havent use "python mtk e userdata, metadata, md_udc" command??? when u lock or unlock bootloader, data partition always erased.

**Comment by LolekLiam** [comment]
ok idk how i was just tinkering with it and i think i got it working for now...
