### ISSUE TITLE
M7322 is not a phone.

### ISSUE THREAD

**Issue by Ph0rk0z** [bkerler/mtkclient#470]
It is a smart tv. There is no volume key method to enter the brom. USB console works and you can go into bootloader. Can it be supported? There are mediatek references all over the OS. Supposedly fastboot oem unlock works but there has been no way to dump the roms.

**Comment by XRedCubeX** [comment]
Try to crash the preloader (if is shown) to get to BootROM

**Comment by riegaz** [comment]
@Ph0rk0z did you manage to crash the bootloader and dump the images?

**Comment by dslim666** [comment]
I'm interested too.  I have realme tv sled 55. It is also on the m7322 platform(mt6886).  The bootloader is unlocked, but I can't do anything.  I had Android 11, I found factory firmware with Android 9 (there is adb root, but it is cut down).  I would like to dump boot.img and patch it in magisk
