### ISSUE TITLE
Error on sending brom stage 2 

### ISSUE THREAD

**Issue by FireFlyin44** [bkerler/mtkclient#481]
Getting this error on every option other than dumping sram and preloader
..........
Port - Device detected :)
Preloader - 	CPU:			MT6580()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11005000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x1020ac00
Preloader - 	Var1:			0xac
Preloader - Disabling Watchdog...
Preloader - HW code:			0x6580
Preloader - Target config:		0x0
Preloader - 	SBC enabled:		False
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			06C97183752F0CAF027AFB60BF9C755D
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6580_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/alamdar/anaconda3/lib/python3.9/site-packages/mtkclient-1.5.9-py3.9.egg/mtkclient/payloads/mt6580_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
DALegacy - Uploading legacy da...
DALegacy - Uploading legacy stage 1 from MTK_AllInOne_DA_5.2152.bin
legacyext - Legacy DA2 is patched.
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DALegacy - Got loader sync !
DALegacy - Reading nand info
DALegacy - Reading emmc info
DALegacy - ACK: 04029c
DALegacy - Setting stage 2 config ...
DALegacy - Uploading stage 2...
DALegacy
DALegacy - [LIB]: Error on sending brom stage 2 : 41

**Comment by bkerler** [comment]
That means that you need to specify a valid preloader using --preloader option, as the automatically detected one might be bad.

**Comment by bkerler** [comment]
That means that you need to specify a valid preloader using --preloader option, as the automatically detected one might be bad.

**Comment by FireFlyin44** [comment]
ok what are the instruction to specify a preloader I have it from stock rom how should send it. Phone is mtk 6572 with possible corrupted preloader give 4048 or 4038 dram error and mtkclient gives error on preloader needed for dram config I want to dump data partition and system partition find which rom version I have on it
