### ISSUE TITLE
Érvénytelen partíciós tábla

### ISSUE THREAD

**Issue by baracsipeti** [bkerler/mtkclient#484]
### Discussed in https://github.com/bkerler/mtkclient/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **bkerler** September 19, 2021</sup>
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.</div>

**Comment by bkerler** [comment]
Sorry, this is no issue.
