### ISSUE TITLE
Érvénytelen partició

### ISSUE THREAD

**Issue by baracsipeti** [bkerler/mtkclient#485]
Sziasztok!
Szeretnék egy kis segítséget kérni! Hosszadalmas lenne leírnom, ezért inkább mellékelem a képet.
Erre valami megoldás, esetleg? A segítséget előre is Köszönöm!!!!!!

![Mi-Bypass Screentshot(2022 09 22 12 39 33)](https://user-images.githubusercontent.com/39876566/191727261-cb5b8a66-807c-47d0-8949-f27ca22f8e32.png)

**Comment by zalnaRs** [comment]
Kell egy gpt particios táblat flash-elni.

**Comment by bkerler** [comment]
Sorry no support for other tools or language other than english.
