### ISSUE TITLE
How do I use python3 mtk script

### ISSUE THREAD

**Issue by JeanDeaux615** [bkerler/mtkclient#492]
Would the proper context be
python3 mtk script test.sh

**Comment by oakieville** [comment]
the script isnt an sh its just a list of commands he also gave an example 
https://github.com/bkerler/mtkclient/blob/main/run.example

**Comment by JeanDeaux615** [comment]
But is it saved as a regular .txt?

**Comment by JeanDeaux615** [comment]
Thanks

**Comment by oakieville** [comment]
Save as whatever you want

**Comment by oakieville** [comment]
If name it something.txt then python mtk script something.txt  if name it bob then python mtk script bob

**Comment by JeanDeaux615** [comment]
Thanks.. I really was hoping I could use an sh script but.....ole well..
