### ISSUE TITLE
GPT Partition table

### ISSUE THREAD

**Issue by jhay06** [bkerler/mtkclient#500]
Hi , is mtk client supports this feature ? edit the partition table example i want to resize  or change the offset and then when i do that gpt.bin updates also .  

or if there's none would like to ask to add this features, there are phone with same partition table but different definition of sizes . 

example my phone redmi note 8 pro has 128GB  and i flashed the wrong gpt.bin because when i search through google the only dump rom file for redmi note 8 pro available for now is for 64GB , but per observation partitions of both phone has the same table list , but they are different only in terms of sizes , example the userdata other has 56.4GB , the other has 110GB , resizing the 56.4GB to 110GB will help 128GB pro user to restore their own gpt partition table using other gpt.bin with the same partition tables

**Comment by oakieville** [comment]
couldnt you just read gpt edit it write it back

**Comment by jhay06** [comment]
> couldnt you just read gpt edit it write it back

no , there are some cases actually this is the problem before i created this thread ( luckily i managed to obtain gpt.bin from other user)  ,  i messed up the first partition of my phone , 0x0 0x8000  this is where GPT.bin lives .   
so mtkclient cannot read the partition of the phone because of the missing GPT table definition from the 0x0 address ,  

so at first i to google if there's available dump rom files for my phone ,   Yes there is but not for the phone specs that i have , Redmi note 8 pro 128GB (my phone)  but the available on the google was for 64GB only , i flashed its GPT.bin  

then i saw that it was for 64GB phone 

, can i edit it ?  -> this is the big question that i'm sufferring that time because there's no easy way to do that , and i don't know how to do it , i'm looking for a tools that can do this stuff edit the partitions of the GPT.bin , but there's none . So that time i have a wrong GPT.bin installed on my phone .    that's why i open this issue to request to have this features so if there's another mtk phone that messed with 0x0 address and downloaded wrong GPT.bin they can edit it easily using this tool .

hope you understand thanks

**Comment by Manggohype** [comment]
> > couldnt you just read gpt edit it write it back
> 
> no , there are some cases actually this is the problem before i created this thread ( luckily i managed to obtain gpt.bin from other user) , i messed up the first partition of my phone , 0x0 0x8000 this is where GPT.bin lives . so mtkclient cannot read the partition of the phone because of the missing GPT table definition from the 0x0 address ,
> 
> so at first i look to google if there's available dump rom files for my phone , Yes there is but not for the phone specs that i have , Redmi note 8 pro 128GB (my phone) but the available on the google was for 64GB only , i flashed its GPT.bin
> 
> then i saw that it was for 64GB phone
> 
> , can i edit it ? -> this is the big question that i'm sufferring that time because there's no easy way to do that , and i don't know how to do it , i'm looking for a tools that can do this stuff edit the partitions of the GPT.bin , but there's none . So that time i have a wrong GPT.bin installed on my phone . that's why i open this issue to request to have this features so if there's another mtk phone that messed with 0x0 address and downloaded wrong GPT.bin they can edit it easily using this tool .
> 
> hope you understand thanks

how did you manage to flash gpt.bin? via  w offset and lentgh gpt.bin?

**Comment by Mark-Joy** [comment]
@jhay06 
I also trashed [my gpt](https://forum.xda-developers.com/t/help-recovering-data-on-a-broken-fstab-redmi-note-8-pro.4611163/) Could you please upload your gpt.bin here?
