### ISSUE TITLE
usb_class - USBError(5, 'Input/Output Error') >>> struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by TMDevel89** [bkerler/mtkclient#501]
Can you help me with this error?

![ERR unpack requires a buffer of 2 bytes](https://user-images.githubusercontent.com/39184377/193684975-4ecb0a39-49fb-4815-8ea5-4ccd5cd687f7.JPG)

**Comment by diamant3** [comment]
maybe just a connection issue. Install necessary [requirements](https://github.com/bkerler/mtkclient#windows) or change your usb cable.

**Comment by xinextialmatrix** [comment]
i fix this by changing a proper data cable usb
