### ISSUE TITLE
DAA_SIG_VERIFY_FAILED (0x7024)

### ISSUE THREAD

**Issue by Aditya-Jagwani** [bkerler/mtkclient#503]
Hello. Please help me out. It used to work before ota update...

DeviceClass - [LIB]:   CONFIGURATION 1: 500 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x43 (67 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x3 USB CDC ACM for preloader
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0xfa (500 mA)
    INTERFACE 0: CDC Communication =========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x2 CDC Communication
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :    0x1
     iInterface         :    0x5 CDC ACM Comm Interface
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :   0x10
    INTERFACE 1: CDC Data ==================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0xa CDC Data
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x4 CDC ACM Data Interface
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
DeviceClass
DeviceClass - [LIB]: Detaching kernel driver
DeviceClass
DeviceClass - [LIB]:   CONFIGURATION 1: 500 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x43 (67 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x3 USB CDC ACM for preloader
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0xfa (500 mA)
    INTERFACE 0: CDC Communication =========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x2 CDC Communication
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :    0x1
     iInterface         :    0x5 CDC ACM Comm Interface
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :   0x10
    INTERFACE 1: CDC Data ==================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0xa CDC Data
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x4 CDC ACM Data Interface
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
Port - Device detected :)
DeviceClass
DeviceClass - [LIB]: TX:fd
DeviceClass
DeviceClass - [LIB]: echo:0x1
DeviceClass
DeviceClass - [LIB]: RX:fd
DeviceClass
DeviceClass - [LIB]: rdword:0x4
DeviceClass
DeviceClass - [LIB]: RX:09590000
Preloader - 	CPU:			MT6877(Dimensity 900)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
DeviceClass
DeviceClass - [LIB]: TX:d4
DeviceClass
DeviceClass - [LIB]: echo:0x1
DeviceClass
DeviceClass - [LIB]: RX:d4
DeviceClass
DeviceClass - [LIB]: TX:10007000
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:10007000
DeviceClass
DeviceClass - [LIB]: TX:00000001
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:00000001
DeviceClass
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:0000
DeviceClass
DeviceClass - [LIB]: TX:22000064
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:22000064
DeviceClass
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:0000
Preloader - HW code:			0x959
DeviceClass
DeviceClass - [LIB]: TX:d8
DeviceClass
DeviceClass - [LIB]: echo:0x1
DeviceClass
DeviceClass - [LIB]: RX:d8
DeviceClass
DeviceClass - [LIB]: rbyte:0x6
DeviceClass
DeviceClass - [LIB]: RX:000000050000
Preloader - Target config:		0x5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
DeviceClass
DeviceClass - [LIB]: TX:fe
DeviceClass
DeviceClass - [LIB]: get_blver:0x1
DeviceClass
DeviceClass - [LIB]: RX:03
DeviceClass
DeviceClass - [LIB]: TX:ff
DeviceClass
DeviceClass - [LIB]: get_bromver:0x1
DeviceClass
DeviceClass - [LIB]: RX:ff
DeviceClass
DeviceClass - [LIB]: TX:fc
DeviceClass
DeviceClass - [LIB]: mtk_cmd:0x1
DeviceClass
DeviceClass - [LIB]: RX:fc
DeviceClass
DeviceClass - [LIB]: mtk_cmd:0x8
DeviceClass
DeviceClass - [LIB]: RX:8a00ca0000000000
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
DeviceClass
DeviceClass - [LIB]: TX:fe
DeviceClass
DeviceClass - [LIB]: get_meid:0x1
DeviceClass
DeviceClass - [LIB]: RX:03
Mtk - We're not in bootrom, trying to crash da...
PLTools - Crashing da...
DeviceClass
DeviceClass - [LIB]: TX:d7
DeviceClass
DeviceClass - [LIB]: echo:0x1
DeviceClass
DeviceClass - [LIB]: RX:d7
DeviceClass
DeviceClass - [LIB]: TX:00000000
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:00000000
DeviceClass
DeviceClass - [LIB]: TX:00000118
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:00000118
DeviceClass
DeviceClass - [LIB]: TX:00000000
DeviceClass
DeviceClass - [LIB]: echo:0x4
DeviceClass
DeviceClass - [LIB]: RX:00000000
DeviceClass
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:0000
DeviceClass
DeviceClass - [LIB]: TX:00019fe510ff2fe10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: TX:00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: TX:00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: TX:00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: TX:000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:faa0
DeviceClass
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:7024
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
Preloader - Jumping to 0x0
DeviceClass
DeviceClass - [LIB]: TX:d5

[mtk client log.txt](https://github.com/bkerler/mtkclient/files/9724708/mtk.client.log.txt)

**Comment by bkerler** [comment]
Double of issue #830
