### ISSUE TITLE
Is MT6833P (Dimensity 810) Supported?

### ISSUE THREAD

**Issue by raymond-1227** [bkerler/mtkclient#506]
I couldn't use MTKClient on the chipset I mentioned above.

When I use MTKClient on macOS, it constantly shows `Preloader - Status: Handshake failed, retrying...` and soon resumes into looking for devices after too many failed attempts.
When I use MTKClient on Windows, it stops responding (like the BROM/Payload mode thing just hangs there and do nothing for about a minute or so), and my phone always start 5 seconds after cable was plugged in even when volume buttons are held down still.

I tried a different device with MT6853T (Dimensity 800U) chipset, which MTKClient did its job for the command executed when device was detected.

So now I wonder is this chipset even supported or perhaps its BROM has been patched already?

**Comment by bkerler** [comment]
It should be supported normally, and it should work fine under Linux.
