### ISSUE TITLE
Do I need a scatter file to restore a hard brick?

### ISSUE THREAD

**Issue by rsbotting123** [bkerler/mtkclient#509]
I plan on playing around with my device and am worried that it will get hard bricked and/or partitions messed up.

I read online you need this scatter file to restore what memory addresses things should go? Do I need it in this case? If I back up the entire flash and restore when I hard brick, will I be okay?

**Comment by bkerler** [comment]
If you don't erase the flash and/ or the gpt table, you are safe. So yes, if you restore the entire flash, you should be fine, just make sure not to mess around with the gpt.
