### ISSUE TITLE
Seccfg option freezes (MT6737M)

### ISSUE THREAD

**Issue by XRedCubeX** [bkerler/mtkclient#51]
Hi, as you can read from the title, when I try to modify seccfg with stage2, it freezes without giving any output and the only way to unfreeze is to stop python or unplug the device, I have tried with both Windows 11 and Arch Linux.
I attach the terminal output, even with the debug option:

`python stage2 seccfg unlock
sej - HACC init`

`python stage2 seccfg unlock --debugmode
usage: stage2 [-h]
              {rpmb,preloader,boot2,memread,memwrite,reboot,seccfg,keys} ...
stage2: error: unrecognized arguments: --debugmode`

**Comment by marat2509** [comment]
Try `python stage2 unlock`

**Comment by XRedCubeX** [comment]
> 
> 
> Try `python stage2 seccfg unlock`

I did exactly this command

**Comment by SoeHtikeAung199** [comment]
> > Try `python stage2 seccfg unlock`
> 
> I did exactly this command

Not work and not out put data stop terminal

**Comment by XRedCubeX** [comment]
> 
> 
> > > Try `python stage2 seccfg unlock`
> > 
> > 
> > I did exactly this command
> 
> Not work and not out put data stop terminal

?

**Comment by SoeHtikeAung199** [comment]
please bug error fix sir

**Comment by XRedCubeX** [comment]
> 
> 
> please bug error fix sir

i can't, im not a developer

**Comment by kashifbharwana** [comment]
try
python stage2 seccfg --sw unlock

**Comment by kashifbharwana** [comment]
and after try 
python mtk w seccfg seccfg.bin

**Comment by SoeHtikeAung199** [comment]
> and after try
> python mtk w seccfg seccfg.bin

Ok Thank You

**Comment by XRedCubeX** [comment]
> 
> 
> try
> python stage2 seccfg --sw unlock

I tried to flash seccfg from recovery (flash from mtkclient I don't know why but it gives me problems) and the variable has not changed

**Comment by kashifbharwana** [comment]
wait next update

**Comment by bkerler** [comment]
Next update should solve most issues with unlocking, hopefully.

**Comment by XRedCubeX** [comment]
> Next update should solve most issues with unlocking, hopefully.

Ok good luck with the development, can't wait to try the feature.  
A little tip: in the readme, add how to correctly execute the command and the difference between hw and sw. 
Good luck!

**Comment by XRedCubeX** [comment]
Mh... I think it is a problem that xflash does not work on legacy DA, I don't think it is possible to unlock
