### ISSUE TITLE
Hard bricked

### ISSUE THREAD

**Issue by duckytutorials** [bkerler/mtkclient#510]
my phone hardbricked i unpluged phone while in brom in

sending emi data

Port - Device detected :)
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      D3A4D9C2D8C4F3E6F18FB1F2CDACE08D
Preloader - SOC_ID:                     65907E53F21C517D669468DF4B3FA0816A1207AA1B9109F0B680FD4342361B07
Port - Device detected :)
Successfully extracted preloader for this device to: preloader_k62v1_64_bsp.bin
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da1 ...
xflashext
xflashext - [LIB]: ←[33mError on patching da1 version check...←[0m
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 4501004441343033
DAXFlash - Sending emi data ...

**Comment by King12689** [comment]
that happens to me moments ago(hardbricked, cannot boot my phone or vibrate) but i manage to fix it by flashing stock rom

**Comment by duckytutorials** [comment]
> that happens to me moments ago(hardbricked, cannot boot my phone or vibrate) but i manage to fix it by flashing stock rom

ahhhh i dont have boot loader unlock

**Comment by King12689** [comment]
why!?? and did you already fix  your phone??

**Comment by bkerler** [comment]
You can't hardbrick the device using mtkclient, except you erase data.
Just remove the battery (with no usb cable connected) and it should work fine again.
