### ISSUE TITLE
Possible to load a patched stock preloader?

### ISSUE THREAD

**Issue by dylangerdaly** [bkerler/mtkclient#512]
I'd like to byte patch preloader to not check the authenticity of lk, but I'm not sure if mtkclient allows the ability to load a patched preloader as a stage2.

Is this possible?

**Comment by halal-beef** [comment]
Try using the argument --preloader=pathtopreloader

**Comment by bkerler** [comment]
Exactly. Just use your patched or own preloader using --preloader option. For DA (stage2), use the --loader option instead.

**Comment by FireFlyin44** [comment]
> 
hey can you provide a example as to how provide a preloader myself I don't understant the code how to specify preloaders address currently phone has an invalid preloader and I want to back up data from it. Its a mtk6572 with 4/512 config
everytime I connect it says preloader needed for dram config and is unable to dump.
