### ISSUE TITLE
Please add support for Dimensity 900 MT6877

### ISSUE THREAD

**Issue by RusevPutin** [bkerler/mtkclient#517]
I would like to see support for MT6877 added. If you need any help please tell, I will help and give you the required information and files.

**Comment by bkerler** [comment]
MT6877 is already added.

**Comment by bkerler** [comment]
If you have a T-Variant, its bootrom has been patched and thus kamakiri won't work anymore.

**Comment by RusevPutin** [comment]
> MT6877 is already added.

Thanks developer, appreciate your hardwork 👍

**Comment by NasiGorengBurung** [comment]
> If you have a T-Variant, its bootrom has been patched and thus kamakiri won't work anymore.

But hey, wondering for the one without letter T
