### ISSUE TITLE
Bootloader unlocked successfully, but still can not flash image using fastboot

### ISSUE THREAD

**Issue by hkhere** [bkerler/mtkclient#519]
The cpu is acutually `Dimensity 810 MT6833P`(Redmi Note 11 5G). But is was identified as `Demensity 700` in the log. Don't know if it makes a difference.
After unlocking the bootloader, on booting it says
> dm-verity corruption. You device is corrupt. 
> It can't be trusted and may not work properly. Press power button to continue. 
> Or, device will power off in 5s

I have tried to use fastboot to flash patched boot image into `boot_a` partition, but fastboot said `not allowed in locked state`. 
Although by using `mtkclient` I can successfuly flash the patched boot image into `boot_a` and `vbmeta.img.empty` into `vbmeta_a` partition, on booting it showed the error `The system has been destroyed`. 

Below is the log of command `python mtk da seccfg unlock`.
> ........Port - Device detected :)
> Preloader -     CPU:                    MT6833(Dimensity 700 5G k6833)
> Preloader -     HW version:             0x0
> Preloader -     WDT:                    0x10007000
> Preloader -     Uart:                   0x11002000
> Preloader -     Brom payload addr:      0x100a00
> Preloader -     DA payload addr:        0x201000
> Preloader -     CQ_DMA addr:            0x10212000
> Preloader -     Var1:                   0x73
> Preloader - Disabling Watchdog...
> Preloader - HW code:                    0x989
> Preloader - Target config:              0xe7
> Preloader -     SBC enabled:            True
> Preloader -     SLA enabled:            True
> Preloader -     DAA enabled:            True
> Preloader -     SWJTAG enabled:         True
> Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
> Preloader -     Root cert required:     False
> Preloader -     Mem read auth:          True
> Preloader -     Mem write auth:         True
> Preloader -     Cmd 0xC8 blocked:       True
> Preloader - Get Target info
> Preloader - BROM mode detected.
> Preloader -     HW subcode:             0x8a00
> Preloader -     HW Ver:                 0xca00
> Preloader -     SW Ver:                 0x0
> Preloader - ME_ID:                      C51C31EE612C78232DD311137588DF34
> Preloader - SOC_ID:                     D8570F4752313F93D5B1775792D8CFC00B1A0AF08D7E857EFFE6500C59866660
> PLTools - Loading payload from mt6833_payload.bin, 0x264 bytes
> PLTools - Kamakiri / DA Run
> Kamakiri - Trying kamakiri2..
> Kamakiri - Done sending payload...
> PLTools - Successfully sent payload: D:\github\mtkclient\mtkclient\payloads\mt6833_payload.bin
> Port - Device detected :)
> DA_handler - Device is protected.
> DA_handler - Device is in BROM mode. Trying to dump preloader.
> DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
> xflashext - Patching da1 ...
> Mtk - Patched "Patched loader msg" in preloader
> xflashext
> xflashext - [LIB]: Error on patching da1 version check...
> Mtk - Patched "Patched loader msg" in preloader
> Mtk - Patched "get_vfy_policy" in preloader
> xflashext - Patching da2 ...
> DAXFlash - Successfully uploaded stage 1, jumping ..
> Preloader - Jumping to 0x200000
> Preloader - Jumping to 0x200000: ok.
> DAXFlash - Successfully received DA sync
> DAXFlash - UFS FWVer:    0x0
> DAXFlash - UFS Blocksize:0x1000
> DAXFlash - UFS ID:       H9HQ21AFAMADAR
> DAXFlash - UFS CID:      ad014839485132314146414d41444152
> DAXFlash - UFS LU0 Size: 0x3b96000000
> DAXFlash - UFS LU1 Size: 0x400000
> DAXFlash - UFS LU2 Size: 0x400000
> DAXFlash - DRAM config needed for : ad014839485132314146414d41444152
> DAXFlash - Sending emi data ...
> DAXFlash - DRAM setup passed.
> DAXFlash - Sending emi data succeeded.
> DAXFlash - Uploading stage 2...
> DAXFlash - Upload data was accepted. Jumping to stage 2...
> DAXFlash - Successfully uploaded stage 2
> DAXFlash - UFS FWVer:    0x0
> DAXFlash - UFS Blocksize:0x1000
> DAXFlash - UFS ID:       H9HQ21AFAMADAR
> DAXFlash - UFS CID:      ad014839485132314146414d41444152
> DAXFlash - UFS LU0 Size: 0x3b96000000
> DAXFlash - UFS LU1 Size: 0x400000
> DAXFlash - UFS LU2 Size: 0x400000
> DAXFlash - HW-CODE         : 0x989
> DAXFlash - HWSUB-CODE      : 0x8A00
> DAXFlash - HW-VERSION      : 0xCA00
> DAXFlash - SW-VERSION      : 0x0
> DAXFlash - CHIP-EVOLUTION  : 0x1
> DAXFlash - DA-VERSION      : 1.0
> DAXFlash - Upload data was accepted. Jumping to stage 2...
> DAXFlash - DA Extensions successfully added
> sej - HACC init
> sej - HACC run
> sej - HACC terminate
> sej - HACC init
> sej - HACC run
> sej - HACC terminate
> sej - HACC init
> sej - HACC run
> sej - HACC terminate
> Progress: |██████████████████████████████████████████████████| 100.0% Write (Sector 0x1 of 0x1, ) 0.04 MB/s
> DA_handler - Successfully wrote seccfg.

the device's partition(not all partitions, some large partitions are not listed):

> boot_a
> boot_b
> boot_para
> countrycode
> cust
> dpm_a
> dpm_b
> dtbo_a
> dtbo_b
> efuse
> expdb
> ffu
> flashinfo
> frp
> gsort
> gz_a
> gz_b
> lk_a
> lk_b
> logo_a
> logo_b
> mcupm_a
> mcupm_b
> md1img_a
> md1img_b
> metadata
> misc
> nvcfg
> nvdata
> nvram
> otp
> para
> persist
> pi_img_a
> pi_img_b
> proinfo
> protect1
> protect2
> rescue
> scp_a
> scp_b
> sec1
> seccfg
> spmfw_a
> spmfw_b
> sspm_a
> sspm_b
> super
> tee_a
> tee_b
> userdata
> vbmeta_a
> vbmeta_b
> vbmeta_system_a
> vbmeta_system_b
> vbmeta_vendor_a
> vbmeta_vendor_b
> vendor_boot_a
> vendor_boot_b

**Comment by bkerler** [comment]
This might be due to the way the device is being unlocked. Especially Oppo / Realme / Vivo have some additional checks, preventing unlocking.
