### ISSUE TITLE
Script does not process properly the directories with spaces while we use the commands to read/write (r/w)

### ISSUE THREAD

**Issue by starlyn1232** [bkerler/mtkclient#525]
For example, the script has these lines:

r boot "C:\Users\Starlyn1232\MTK Improve\boot.img"

This throw this:

mtk: error: unrecognized arguments

I have made some quick temporal solutions at "mtk_main.py" (I know nearer nothing about Python, so it's not a "clean" solution), now we could use the word "super" while processing the script which read/write partitions, for example: 

super r boot "C:\Users\Starlyn1232\MTK Improve\boot.img"

These have been the changes at the "script" arg lines: 

if cmd == "script":
            if not os.path.exists(self.args.script):
                self.error("Couldn't find script: "+self.args.script)
                self.close()
                return
            commands=open(self.args.script,"r").read().splitlines()
            # DA / FLash commands start here
            try:
                preloader = self.args.preloader
            except:
                preloader = None
            da_handler = DA_handler(mtk, loglevel)
            mtk = da_handler.configure_da(mtk, preloader)
            if mtk is not None:
                for rcmd in commands:
                    #Check "super" command for read/write partitions
                    #to paths with space, Starlyn, let's do it                
                    if rcmd[0:rcmd.index(' ')] == 'super':
                        #Remove "super" arg
                        rcmd = rcmd[rcmd.index(' ')+1:]
                        #Create dummy data
                        self.args = parser.parse_args(['r', 'frp', 'C:\\frp.bin'])  
                        #Manual properties setup
                        #
                        #CMD
                        self.args.cmd = rcmd[0:rcmd.index(' ')]
                        rcmd = rcmd[rcmd.index(' ')+1:]
                        #Partition
                        self.args.partitionname = rcmd[0:rcmd.index(' ')]
                        #FileName Wrap
                        rcmd = rcmd[rcmd.index(' ')+1:].replace('\"','')
                        self.args.filename = rcmd
                    #Else, we'll use the "standard" parse
                    else:
                        self.args = parser.parse_args(rcmd.split(" "))
                    #Handle command
                    ArgHandler(self.args, config)
                    cmd = self.args.cmd
                    da_handler.handle_da_cmds(mtk, cmd, self.args)
                    sys.stdout.flush()
                    sys.stderr.flush()
            else:
                self.close()

**Comment by bkerler** [comment]
Actually this error shouldn't happen with proper quotation under Windows. I will have a look.

**Comment by Manggohype** [comment]
> Actually this error shouldn't happen with proper quotation under Windows. I will have a look.

is it posstible after sending payload command i can use again to read partitions without disconnecting 
it does not happen on your older version but in new one DA handler kept saying reconnect again

**Comment by Manggohype** [comment]
> Actually this error shouldn't happen with proper quotation under Windows. I will have a look.

Please Fix this sir
