### ISSUE TITLE
writing the seccfg to the K61

### ISSUE THREAD

**Issue by Warlockguitarman** [bkerler/mtkclient#53]
I used chimera to unlock the bootloader on my k61 but I backed up the seccfg.bin before I did it, I successfully relocked the bootloader by flashing the stock one back to it, but when i tried to flash the one from it when it was unlocked it would not flash successfully.

PS C:\Users\jones\Downloads\mtkclient-main\mtkclient-main> python mtk w seccfg seccfg.bin

Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.

.......Port - Device detected :)
Preloader -     CPU:                    MT6765(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - ME_ID:                      0E2BA12FFA7E848DE6D3275850FAC4A5
Preloader - SOC_ID:                     0D32C53FC55CE1CC7973A954A700F7C9D39691BEF06CF7BD11C1CBA395E20525
PLTools - Loading payload from C:\Users\jones\Downloads\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\jones\Downloads\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6765_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 150100445636444d
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC CID:        150100445636444d4203f12e6879478f
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x1000000
DAXFlash - EMMC USER Size:  0x1d1ec00000
DAXFlash - DA-CODE      : 0x666D0
DAXFlash
DAXFlash - [LIB]: ←[31mError on sending parameter: Write data not allowed (0xc002000c)←[0m
Failed to write seccfg.bin to sector 557056 with sector count 16384.
PS C:\Users\jones\Downloads\mtkclient-main\mtkclient-main>

**Comment by Warlockguitarman** [comment]
when i use chimera to flash the seccfg from the unlocked back up to the phone after i lock it back i get the bootloader to unlock again, so if this can be repaired we will have the bootloader unlock done.

**Comment by Warlockguitarman** [comment]
K61 locked
4D 4D 4D 4D 04 00 00 00 3C 00 00 00 01 00 00 00 
00 00 00 00 00 00 00 00 45 45 45 45 53 75 32 6A 
63 6A 5B FE 02 A5 E7 18 2C A4 9B F1 25 D3 91 07 
B2 41 7B 6E 07 04 35 5B 9C 06 67 41 00 00 00 00

unlocked
4D 4D 4D 4D 04 00 00 00 3C 00 00 00 03 00 00 00 
00 00 00 00 00 00 00 00 45 45 45 45 8E BC B9 FF 
21 82 FA 02 06 DC 35 36 0F 9C 53 38 3D 24 C4 49 
BE C5 89 49 A8 D9 D4 DD 12 16 51 91 00 00 00 00




Stylo 6 locked
4D 4D 4D 4D 04 00 00 00 3C 00 00 00 01 00 00 00 
00 00 00 00 00 00 00 00 45 45 45 45 42 67 E5 6D 
97 62 1D B2 7D A7 EF AE 08 D8 24 6E 18 A1 46 E1 
79 B8 5F CE 1A 97 B1 50 C7 46 C4 7C 00 00 00 00

unlocked
4D 4D 4D 4D 04 00 00 00 3C 00 00 00 03 00 00 00 
00 00 00 00 00 00 00 00 45 45 45 45 3E 23 5F DF 
48 80 0A 20 0C 3D F4 46 E0 AE 75 5C 44 76 7B 4F 
CC 2D 49 B6 69 BB 91 0A 8A 6E 84 E6 00 00 00 00

**Comment by Warlockguitarman** [comment]
I have learned the correct way to go about this is the memwrite command with the correct start of the seccfg partition,  I attempted it on a k51 without success,  I'm gonna take the k61 back to stock later and try it again with the correct commands,  and still can't connect the stylo 6 without using the chimera tool for its payloads to put it in the right state first then unplugging it and closing chimera and plugging it back in with your tool waiting for a connection

**Comment by TheNextGamer21** [comment]
Hi
