### ISSUE TITLE
Moto C Plus xt1723 not unlocking

### ISSUE THREAD

**Issue by MarkPCExpertYT** [bkerler/mtkclient#531]
I have this Moto C Plus (it was my old phone) and i've been trying to unlock it. So i tried to do it and it said:
 `DA_handler - [LIB]: Unknown seccfg partition header. Aborting unlock.`
I don't know what to do now since i'm a beginner.

I've seen other issues like this so i'll include the seccfg partition (the preloader partition is not there for some reason)
[seccfg](https://mega.nz/file/B9gjhQAb#Ft6Iq9NgixmGy_CPkmsf4GsAam4_KOvvPVj-zEC8d-M)

Also i don't understand the difference between writing partitions and a full flash.

**Comment by ilovevkapi** [comment]
the developer never answers issues about unlock (

**Comment by StevenKim523** [comment]
@ilovevkapi Do you know why?

**Comment by MarkPCExpertYT** [comment]
This project really just got revived, 1.5 years later.
Anyways, I'll try it with the new version and see if it works.

**Comment by bkerler** [comment]
Very unlikely as it would require custom vendor adaptions :) And I concentrate more on other things as unlocking as quite a lot people only copy my code and sell it expensively.
