### ISSUE TITLE
Multiple script command ?

### ISSUE THREAD

**Issue by RecSpeed** [bkerler/mtkclient#534]
example txt file

w preloader "C:\Users\RecSpeedPC\Desktop\mmm\images\preloader_merlin.bin"
w recovery "C:\Users\RecSpeedPC\Desktop\mmm\images\recovery.img"
w vbmeta "C:\Users\RecSpeedPC\Desktop\mmm\images\vbmeta.img"
w vbmeta_system "C:\Users\RecSpeedPC\Desktop\mmm\images\vbmeta_system.img"
w vbmeta_vendor "C:\Users\RecSpeedPC\Desktop\mmm\images\vbmeta_vendor.img"
w logo "C:\Users\RecSpeedPC\Desktop\mmm\images\logo.bin"
w md1img "C:\Users\RecSpeedPC\Desktop\mmm\images\md1img.img"
w spmfw "C:\Users\RecSpeedPC\Desktop\mmm\images\spmfw.img"
w scp1 "C:\Users\RecSpeedPC\Desktop\mmm\images\scp.img"
w scp2 "C:\Users\RecSpeedPC\Desktop\mmm\images\scp.img"
w sspm_1 "C:\Users\RecSpeedPC\Desktop\mmm\images\sspm.img"
w sspm_2 "C:\Users\RecSpeedPC\Desktop\mmm\images\sspm.img"
w lk "C:\Users\RecSpeedPC\Desktop\mmm\images\lk.img"
w lk2 "C:\Users\RecSpeedPC\Desktop\mmm\images\lk.img"
w boot "C:\Users\RecSpeedPC\Desktop\mmm\images\boot.img"
w dtbo "C:\Users\RecSpeedPC\Desktop\mmm\images\dtbo.img"
w tee1 "C:\Users\RecSpeedPC\Desktop\mmm\images\tee.img"
w tee2 "C:\Users\RecSpeedPC\Desktop\mmm\images\tee.img"
w exaid "C:\Users\RecSpeedPC\Desktop\mmm\images\exaid.img"
w cust "C:\Users\RecSpeedPC\Desktop\mmm\images\cust.img"
w super "C:\Users\RecSpeedPC\Desktop\mmm\images\super.img"
w cache "C:\Users\RecSpeedPC\Desktop\mmm\images\cache.img"
w userdata "C:\Users\RecSpeedPC\Desktop\mmm\images\userdata.img"

![mtkfiledoesnt](https://user-images.githubusercontent.com/94472598/200611489-3abce40d-37b1-4285-b973-f04121f4a928.png)

**Comment by bkerler** [comment]
obviously if a file is missing, this won't work

**Comment by RecSpeed** [comment]
Thanks, I'm delete ""  and worked.

**Comment by xinextialmatrix** [comment]
The downside of using script command you cant flash or read with directory that has spaces it can't accept chr(34) characters so the path with the "" is invalid

**Comment by Manggohype** [comment]
> obviously if a file is missing, this won't work

its not missing ,it just can accept this ""
