### ISSUE TITLE
Can't unlock bootloader on MTK6833

### ISSUE THREAD

**Issue by ilovevkapi** [bkerler/mtkclient#535]
Device: Xiaomi Poco M4 Pro 5G
MTK: 6833 Dimensity 700 5g k6833

I've tried to unlock with `mtk da seccfg unlock`.
MTKClient said unlock succeed (`successfully wrote seccfg`). But when my device boots, it remains in locked state. In fastboot I can't flash anything because of lock, and device doesn't boot custom firmware.

I've tried to erase metadata,userdata,md_udc. And redo unlock, but still locked.

I've tried `fastboot oem unlock` and  `fastboot flashing unlock` commands but they don't work.

Pls help

**Comment by bkerler** [comment]
Sorry, but support for xiaomi 5g isn't available and currently not planned.
