### ISSUE TITLE
how to install mtkclient on fedora?

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [bkerler/mtkclient#545]
hi, i'm using fedora kinux and can anyone help me on how to install this client for fedora? thanks

**Comment by nba123-985** [comment]
pip3 install -r requirements.txt ─╯
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: wheel>=0.37.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: pyusb>=1.2.1 in /usr/local/lib/python3.10/dist-packages/pyusb-1.2.1-py3.10.egg (from -r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: pycryptodome>=3.15.0 in /usr/local/lib/python3.10/dist-packages/pycryptodome-3.16.0-py3.10-linux-aarch64.egg (from -r requirements.txt (line 3)) (3.16.0)
Collecting pycryptodomex
Downloading pycryptodomex-3.16.0-cp35-abi3-manylinux2014_aarch64.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.4 MB/s eta 0:00:00
Requirement already satisfied: colorama>=0.4.4 in /usr/local/lib/python3.10/dist-packages/colorama-0.4.6-py3.10.egg (from -r requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: usb>=0.0.83.dev0 in /usr/local/lib/python3.10/dist-packages/usb-0.0.83.dev0-py3.10.egg (from -r requirements.txt (line 6)) (0.0.83.dev0)
ERROR: Could not find a version that satisfies the requirement shiboken6>=6.4.0.1 (from versions: none)
ERROR: No matching distribution found for shiboken6>=6.4.0.1

**Comment by nba123-985** [comment]
How to solve the problem of installing mtkclient

**Comment by nba123-985** [comment]
> Just download the script and install the requirements using "pip install -r requirements.txt" as stated in the readme.md



> Just download the script and install the requirements using "pip install -r requirements.txt" as stated in the readme.md

How to solve the problem of installing mtkclient

**Comment by nba123-985** [comment]
> Just download the script and install the requirements using "pip install -r requirements.txt" as stated in the readme.md

pip3 install -r requirements.txt ─╯
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: wheel>=0.37.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: pyusb>=1.2.1 in /usr/local/lib/python3.10/dist-packages/pyusb-1.2.1-py3.10.egg (from -r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: pycryptodome>=3.15.0 in /usr/local/lib/python3.10/dist-packages/pycryptodome-3.16.0-py3.10-linux-aarch64.egg (from -r requirements.txt (line 3)) (3.16.0)
Collecting pycryptodomex
Downloading pycryptodomex-3.16.0-cp35-abi3-manylinux2014_aarch64.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.4 MB/s eta 0:00:00
Requirement already satisfied: colorama>=0.4.4 in /usr/local/lib/python3.10/dist-packages/colorama-0.4.6-py3.10.egg (from -r requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: usb>=0.0.83.dev0 in /usr/local/lib/python3.10/dist-packages/usb-0.0.83.dev0-py3.10.egg (from -r requirements.txt (line 6)) (0.0.83.dev0)
ERROR: Could not find a version that satisfies the requirement shiboken6>=6.4.0.1 (from versions: none)
ERROR: No matching distribution found for shiboken6>=6.4.0.1

**Comment by bkerler** [comment]
shoud be fixed by now.
