### ISSUE TITLE
Error on sending parameter : Read parttbl failed (0xc0040007)

### ISSUE THREAD

**Issue by fayharinn** [bkerler/mtkclient#55]
On MT6853 Redmi note 9T after all the partitions were deleted, I tried to flash my backup with :
`./mtk wf flash.bin --preloader_cannong.bin`

It throws this error `DAXFlash - [LIB]: Error on sending parameter : Read parttbl failed (0xc0040007)`
I think DAXFlash tries to read the gpt partition but can't find it right ? 
Do you think my phone is dead forever ?

**Comment by bkerler** [comment]
Use preloader with --preloader=preloader.bin. write flash normally shouldn't read the gpt, will have a look if it does.

**Comment by fayharinn** [comment]
Yes I did it (with the last commit)
``./mtk wf "/media/fayhe/My Passport/flash.bin" --preloader=preloader_cannong.bin``

Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      ...
Preloader - SOC_ID:                     ...
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/fayhe/Bureau/mtkclient/mtkclient/payloads/mt6853_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2124.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x32
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM5C7001DM-B62
DAXFlash - UFS CID:      ce014b4d354337303031444d2d423632
DAXFlash - UFS LU0 Size: 0xee5800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ce014b4d354337303031444d2d423632
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x32
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM5C7001DM-B62
DAXFlash - UFS CID:      ce014b4d354337303031444d2d423632
DAXFlash - UFS LU0 Size: 0xee5800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x969F0
DAXFlash - DA Extensions successfully added
DAXFlash
DAXFlash - [LIB]: Error on sending parameter: Read parttbl failed (0xc0040007)
Failed to write /media/fayhe/My Passport/flash.bin to sector 0 with sector count 124960768.

**Comment by Mr4ucker** [comment]
Sow how did you solve the error?

**Comment by kenkit** [comment]
writting preloader alone may not be enough, tbh that phone is as good as bricked.
You have to figure out how to write pgpt, if you can get this done, the device should work.
Some firmware come with pgpt in flashtool but some remain dead since even flashtool refuses to write this devices.
I think we should have a feature to write UA partition without availability of pgpt.
