### ISSUE TITLE
MT6765 Nokia G10 TA-1334 cant unlock bootloader 

### ISSUE THREAD

**Issue by ghost** [bkerler/mtkclient#554]
i tried to to unlock bootloader and after running first command i just got error i tried every version of mtkclient and none of them worked is unlocking bootloader of this phone even possible????? 

Port - Device detected :)
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      B0D441CAABCC7F6A221DC55CC3BB2C8F
Preloader - SOC_ID:                     67BB3F225D061FD06C1A9EE033FBB948E289F8AA14B1CBF874ED4F94B7E92D6A
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\DATA-REDACTED\Downloads\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6765_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da1 ...
Mtk - Patched "Patched loader msg" in preloader
xflashext
xflashext - [LIB]: ←[33mError on patching da1 version check...←[0m
Mtk - Patched "Patched loader msg" in preloader
Mtk - Patched "get_vfy_policy" in preloader
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash
DAXFlash - [LIB]: ←[31mxread error: unpack requires a buffer of 12 bytes←[0m
DAXFlash
DAXFlash - [LIB]: ←[31mError jumping to DA: -1←[0m

**Comment by chiron853** [comment]
@bkerler

**Comment by bkerler** [comment]
you need to dump the preloader first and use with --preloader option.

**Comment by chiron853** [comment]
> you need to dump the preloader first and use with --preloader option.


i did that but still same issue

**Comment by chiron853** [comment]
this issue also happens in all other tools too and idk why

**Comment by chiron853** [comment]
> you need to dump the preloader first and use with --preloader option.

so how to fix this thing every program has the same issue and cant sync da

**Comment by weskerty** [comment]
same error
