### ISSUE TITLE
root oppo a93 mt6779v

### ISSUE THREAD

**Issue by mrking89** [bkerler/mtkclient#561]
Hi, I rooted my phone but it won't boot

![images](https://user-images.githubusercontent.com/78631247/206570889-b5f6e123-8319-40ba-ad71-07c1d5e706f1.jpeg)

Note that I have an unlocked bootloader

**Comment by muhammadrafiasyddiq** [comment]
> Hi, I rooted my phone but it won't boot
> 
> ![images](https://user-images.githubusercontent.com/78631247/206570889-b5f6e123-8319-40ba-ad71-07c1d5e706f1.jpeg)
> 
> Note that I have an unlocked bootloader

no support oppo new version patch try downgrade to unlock if not you device no booted
