### ISSUE TITLE
BROM mode without volume buttons

### ISSUE THREAD

**Issue by riegaz** [bkerler/mtkclient#571]
I do have a development board not having a volume button. It only has a power button. It uses the MT6890. Could you tell me how to enter BROM mode? I would like to dump the partitions and reflash them.

I found that a certain pin forces the MT6890 into USB download mode. I was wondering if this is the way how to set the BROM mode and use the MTK Client?

Does anyone know?

**Comment by bkerler** [comment]
Yes. using KCOL0 or if you short the emmc clk or dat0 pin to ground
