### ISSUE TITLE
add support for dimencity 8100 [mt 6895]

### ISSUE THREAD

**Issue by Atassen21** [bkerler/mtkclient#576]
my device redmi k50i has bricked for flashing an unofficial TWRP over wrong kernel...
now my phone is stuck on bootloop on twrp logo....
i think the kernel is corrupted .....i cant use sp flash tool bcz of SLA error ...
plz give me any solution 😥😥

is there any way to flash the boot img only ?

**Comment by Atassen21** [comment]
Please reply😢

**Comment by muhammadrafiasyddiq** [comment]
write boot.img python mtk w boot boot.img
