### ISSUE TITLE
Support for flash boot img for mt 6895 (dimencity 8100)

### ISSUE THREAD

**Issue by Atassen21** [bkerler/mtkclient#577]
Sir, 
My device is redmi k50i ...
I've flashed twrp over wrong kernel which doesn't support the twrp...& Now my device is in boot loop on twrp logo , no fastboot no nothing

Now i need to flash the boot img to get my device working...
If i cant bypass it now for mtk high security issues...atleast can u plz add support for this please😢

0x1172: chipconfig(
    var1=0xA,
    watchdog=0x1c007000,
    uart=0x11001000,
    brom_payload_addr=0x100A00,
    da_payload_addr=0x201000,
    pl_payload_addr=0x40200000,
    gcpu_base=0x10050000,
    dxcc_base=0x10210000,
    sej_base=0x1000a000,
    cqdma_base=0x10212000,
    ap_dma_mem=0x11300800 + 0x1a0,
    #blacklist=[(0x102848, 0x0), (0x00106B60, 0x0)],
    #blacklist_count=0x0000000A,
    #send_ptr=(0x102888, 0xE79C),
    #ctrl_buffer=0x00102A9C,
    #cmd_handler=0x0000F569,
    #brom_register_access=(0xeba4, 0xec5c),
    #meid_addr=0x102B98,
    #socid_addr=0x102BA8,
    #prov_addr=0x1066C0,
    damode=damodes.XFLASH,
    dacode=0x6895,
    name="MT6895",
    description="Dimensity 8100"

**Comment by Atassen21** [comment]
> Sir, My device is redmi k50i ... I've flashed twrp over wrong kernel which doesn't support the twrp...& Now my device is in boot loop on twrp logo , no fastboot no nothing
> 
> Now ineed to flash the boot img to get my device unbrick... If it cant bypass it now for mtk high security issues...atleast can u plz add support for this please😢
> 
> 0x1172: chipconfig( var1=0xA, watchdog=0x1c007000, uart=0x11001000, brom_payload_addr=0x100A00, da_payload_addr=0x201000, pl_payload_addr=0x40200000, gcpu_base=0x10050000, dxcc_base=0x10210000, sej_base=0x1000a000, cqdma_base=0x10212000, ap_dma_mem=0x11300800 + 0x1a0, #blacklist=[(0x102848, 0x0), (0x00106B60, 0x0)], #blacklist_count=0x0000000A, #send_ptr=(0x102888, 0xE79C), #ctrl_buffer=0x00102A9C, #cmd_handler=0x0000F569, #brom_register_access=(0xeba4, 0xec5c), #meid_addr=0x102B98, #socid_addr=0x102BA8, #prov_addr=0x1066C0, damode=damodes.XFLASH, dacode=0x6895, name="MT6895", description="Dimensity 8100"

**Comment by Atassen21** [comment]
@bkerler sir plz atleast give me some hope?😢

**Comment by bkerler** [comment]
Sorry, but there are no plans for support. Mediatek has locked it down completely.

**Comment by Evengard** [comment]
Is it possible to execute operations via mtkclient with an auth file?
