### ISSUE TITLE
Why am I getting this error? It gets stuck at "Trying Kamakiri 2"

### ISSUE THREAD

**Issue by ARandomComputerNerd** [bkerler/mtkclient#578]
I'm on Ubuntu 22.04 LTS, and when I try to bypass auth (Device - Realme 8 5G RMX3241 Indian, Dimensity 700 aka MT6833) this error shows up. Image (screenshot of the error): [https://imgur.com/a/uNxs3BT]

**Comment by ARandomComputerNerd** [comment]
It is basically stuck at "Trying kamakiri 2" for too long, and then I removed the USB and got this error.

**Comment by ARandomComputerNerd** [comment]
I tried leaving it for a while, and it still showed the same error after a while. Then tried the Re LiveDVD provided in the page and still got the exact same results. Please look into it, I'm desperate to fix my phone!

**Comment by CitrusSin** [comment]
I have met the same situation, and I am curious about it too.
