### ISSUE TITLE
New update coming soon? 

### ISSUE THREAD

**Issue by Warlockguitarman** [bkerler/mtkclient#58]
Sorry,  no new issues,  just checking everyday for that next big update,  waiting with great anticipation, hoping things are going good and hoping that it will be compatible with these LG's. I've got many people that I've taught how to use this tool so they can unlock their bootloaders once it is finally compatible with their stylo 6 or K model phones.

**Comment by bkerler** [comment]
It's almost done. Unlocking will be safe and very easy with the next release. Please keep issues just for issues. I will add "discussions" for these types of questions very soon.
