### ISSUE TITLE
win10 stuck in 'waiting for preloader vcom'

### ISSUE THREAD

**Issue by mamaoi** [bkerler/mtkclient#580]
HI, in windows 10 when I do connect my device to mtkclient, it get connected but halfway, stuck in 'waiting for preloader vcom' .
In Linux it connect without problems, but its a mess every time to switch from one system to another 

Any help for solving this issue ?

thanks anyway

**Comment by muhammadrafiasyddiq** [comment]
same i get stuck and freeze not running after device detect

**Comment by mamaoi** [comment]
By the way, it works only via command line, no GUI, under windows 10

**Comment by muhammadrafiasyddiq** [comment]
> By the way, it works only via command line, no GUI, under windows 10

but i am use windows 8.1
