### ISSUE TITLE
Need clarification for stage2 keys command

### ISSUE THREAD

**Issue by viraniac** [bkerler/mtkclient#581]
Hi,

Could you please clarify what the `stage2 keys` command does? The description says "write memory", which is not really helpful. Which one of the following is correct description of the functionality?

- generates new keys and store them in hwparam file
- fetches existing keys and store them in hwparam file

**Comment by bkerler** [comment]
generates key parameters (not keys) to be used for example as rpmb key (depending on implementation of the vendor) or to decrypt seccfg.
