### ISSUE TITLE
receive dvb-s signals by mt6762 helio p22 reverse engineering on Samsung Galaxy A10s 

### ISSUE THREAD

**Issue by bracop8** [bkerler/mtkclient#582]
As I came across to project named cyrozap/mediatek-lte-baseband-re in the GITHUB website, In order to receive dvb-s channels by lte chipset on my smartphone (Samsung Galaxy A10s) is required lte baseband reverse engineering.
I think that we require a dvb-s driver for mt6762 helio p22 and an app for watching dvb-s channels.

Would you please let me know how we can implement this work on my phone.
Please guide me at this regards.
Thank you very much.

**Comment by bkerler** [comment]
Sorry, but this is a software for dumping rom, not a linux kernel support group.
