### ISSUE TITLE
Failing handshake

### ISSUE THREAD

**Issue by patrick777777777** [bkerler/mtkclient#586]
Am successful on other phones but on one particular phone (tecno pop 5 pro bd4h) which I really need to flash am getting this same error no matter what command i put. 
.....Preloader
Preloader - [LIB]: ←[31mStatus: Handshake failed, retrying...←[0m
[mtk client output.txt](https://github.com/bkerler/mtkclient/files/10328820/mtk.client.output.txt)

The log is in the attached file in the link above

**Comment by kyeboard** [comment]
Try running `python mtk payload` then the command that you are trying to run
