### ISSUE TITLE
Unlock Bootloader support on Xiaomi D810 (MT6833)

### ISSUE THREAD

**Issue by Sushrut1101** [bkerler/mtkclient#588]
Hey @bkerler , can you please add the bootloader unlock support for the following devices:
- Redmi Note 11T 5G (evergo)
- POCO M4 Pro 5G (evergreen)
- Redmi Note 11S 5G (opal)

Thanks in advance!

**Comment by bukaixyz** [comment]
Your CPU is too new, the vulnerability is fixed.

**Comment by Sushrut1101** [comment]
> Your CPU is too new, the vulnerability is fixed.

That's Sad :( (or maybe not?)
