### ISSUE TITLE
MT6580 Failed to Unlock

### ISSUE THREAD

**Issue by Destroy-God** [bkerler/mtkclient#591]
Preloader -     CPU:                    MT6580()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11005000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x1020ac00
Preloader -     Var1:                   0xac
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x6580
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      2F58CC6F20AA0270953A1EC2739BBD00
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6580_payload.bin, 0x258 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Administrator\Downloads\Compressed\mtkclient-main\mtkclient-main\mtkclient\payloads\mt6580_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
DALegacy - Uploading legacy da...
DALegacy - Uploading legacy stage 1 from MTK_AllInOne_DA_5.2136.bin
legacyext - Legacy DA2 is patched.
legacyext
legacyext - [LIB]: Legacy DA2 CMD F0 not patched.
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DALegacy - Got loader sync !
DALegacy - Reading nand info
DALegacy - Reading emmc info
DALegacy - ACK: 04029c
DALegacy - Setting stage 2 config ...
DALegacy - DRAM config needed for : 15010034465445345201f2ebfe34461f
DALegacy - Reading dram nand info ...
DALegacy - Sending dram info ...
DALegacy - RAM-Length: 0xbc
DALegacy - Checksum: 11DB
DALegacy - M_EXT_RAM_RET : 0
DALegacy - M_EXT_RAM_TYPE : 0x2
DALegacy - M_EXT_RAM_CHIP_SELECT : 0x0
DALegacy - M_EXT_RAM_SIZE : 0x20000000
DALegacy - Uploading stage 2...
DALegacy - Successfully uploaded stage 2
DALegacy - Connected to preloader
DALegacy - Reconnecting to preloader
DALegacy - Connected to preloader
DALegacy - m_int_sram_ret = 0x0
m_int_sram_size = 0x20000
m_ext_ram_ret = 0x0
m_ext_ram_type = 0x2
m_ext_ram_chip_select = 0x0
m_int_sram_ret = 0x0
m_ext_ram_size = 0x20000000
randomid = 0x3984E79BA0FAF8E022AC2AE44E4E7C83

m_emmc_ret = 0x0
m_emmc_boot1_size = 0x400000
m_emmc_boot2_size = 0x400000
m_emmc_rpmb_size = 0x80000
m_emmc_gp_size[0] = 0x0
m_emmc_gp_size[1] = 0x0
m_emmc_gp_size[2] = 0x0
m_emmc_gp_size[3] = 0x0
m_emmc_ua_size = 0xe9000000
m_emmc_cid = 4654453415010034fe34461f5201f2eb
m_emmc_fwver = 0100000000000000

Done |--------------------------------------------------| 0.0% Read (Sector 0x0 of 0x200) 0.00 MB/sDA_handler
DA_handler - [LIB]: Unknown seccfg partition header. Aborting unlock.

my seccfg file:
[seccfg.zip](https://github.com/bkerler/mtkclient/files/10367874/seccfg.zip)

**Comment by R0rt1z2** [comment]
Pretty sure MT6580 uses GCPU, which IIRC isn't implemented yet in mtkclient.
