### ISSUE TITLE
Mtk Client Was Freeze After Device detected

### ISSUE THREAD

**Issue by muhammadrafiasyddiq** [bkerler/mtkclient#592]
my 
![IMG-20230104-WA0047](https://user-images.githubusercontent.com/66067362/211197065-2d7a4877-1507-47f7-9475-cbfae4a7ed16.jpg)
cmd I get a freeze when the device is detected and does not move stuck is there a problem? on windows 8.1???

**Comment by sallecta** [comment]
According to your log, device is not detected in your OS and there is no freeze. Message "Port - Hint..." comes where MTKClient  lists USB devices (connected to your PC and detected by OS, not by MTKClient) , and tries to filter from it the device with know Vendor ID, Product ID, etc. 
The MTKClient will repeat device search operation until device is found (forever if not found). No freeze, just infinity loop. 
Try to follow the displayed hint message.
