### ISSUE TITLE
Very Slow read flash speed

### ISSUE THREAD

**Issue by deyvs02** [bkerler/mtkclient#599]
I manage to modify the code to increase the writing speed to 19mbps

but I can't find a way to increase the reading speed so I always have a low speed of 4mpbs

@bkerler 
Can you tell me which parameter to change?

**Comment by bkerler** [comment]
Speed is device and os dependent. Only async read would ensure highest speed, but pyusb hasn't implemented it currently

**Comment by deyvs02** [comment]
> Speed is device and os dependent. Only async read would ensure highest speed, but pyusb hasn't implemented it currently

OK thanks
