### ISSUE TITLE
Error while unlocking bootloader - somebody help

### ISSUE THREAD

**Issue by TeamAnonymous6733** [bkerler/mtkclient#600]
device > Vivo y17 {1902}

 
...Port - Device detected :)
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0x5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
PLTools - Crashing da...
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
Preloader
Preloader - [LIB]: Error on DA_Send cmd
Preloader - Status: Waiting for PreLoader VCOM, please connect mobile

Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.
If it is already connected and on, hold power for 10 seconds to reset.

**Comment by ColtB45** [comment]
I am getting the exact same issue with a Samsung A03s from TracFone.

**Comment by TeamAnonymous6733** [comment]
> I am getting the exact same issue with a Samsung A03s from TracFone.

did u find a way to fix it?

**Comment by Umeaboy** [comment]
Did you follow the instructions at the bottom of your output exactly when you're supposed to?
Just asking, no offence meant.
Sometimes it's easy to miss steps.

**Comment by TeamAnonymous6733** [comment]
> Did you follow the instructions at the bottom of your output exactly when you're supposed to? Just asking, no offence meant. Sometimes it's easy to miss steps.

yes i did .. and i heared about new vivo security patch prevents flashing .. i think thats the issue
