### ISSUE TITLE
Status: Handshake failed, retrying...

### ISSUE THREAD

**Issue by zeng-github01** [bkerler/mtkclient#602]
Model: RMX2121 From Realme

and how to get log?

**Comment by kyeboard** [comment]
I had the same error, and I ran `python mtk payload` to fix that.
If the command still doesnt work, Disconnect the battery and `python mtk payload`, it should work.

**Comment by muhammadrafiasyddiq** [comment]
> I had the same error, and I ran `python mtk payload` to fix that. If the command still doesnt work, Disconnect the battery and `python mtk payload`, it should work.

if vivo brom blocked can?
