### ISSUE TITLE
Hardware failed device disconnects when doing a dump of userdata partition - Help for restart the dump of the missing part

### ISSUE THREAD

**Issue by gartstell** [bkerler/mtkclient#603]
I really don't think it's a bug, but when I'm doing a dump of the 5GB userdata of a cell phone that stopped working several years ago, the computer disconnects at various moments (at 30 49, 55%) and you have to start again, but it doesn't finish. 

This command is explained in the documentation:

`python mtk ro 0x128000 0x200000 flash.bin.
`

With the information of the GPT table and the data of the last sector that it read, I believe that the download could be resumed from where it was left and thus achieve 100% (and then I just unite the files). But I have no experience and I don't know if this is the right approach:

According to the GPT table, the userdata partition has the following values:

```
Offset 0x00000000000084000000
Length 0x000000014cf80000
```

The error of the last dump indicates the following:  

`58.2% Read (Sector 0x60E000 of 0xA67C00, 24m:51s left) 1.28 MB/sDeviceClass - USBError(19, 'No such device (it may have been disconnected)')`

So what values in the `mtk ro` command should I use to continue the download? Or is there a way to prevent it from disconnecting randomly?

Thank you very much. 

Pd. I have been using your EDL tool to rescue an LG phone and just noticed by chance your mtkclient project. I installed it and tried it on that cel. of my wife's that suddenly failed and got stuck with several of our daughter's early photos. I didn't want to throw it away because I thought I would have to do something sometime to get them back, and now thanks to you I'm about to :)

**Comment by bkerler** [comment]
Sounds like broken hardware. you can use the ro command with length offset (file size), which should be 0x60E000*0x200 (sectorsize) = 0xC1C00000 as offset in your case.
