### ISSUE TITLE
Win Defender находит в клиенте MTK «Trojan:Script/Wacatac.H!ml»

### ISSUE THREAD

**Issue by DrowASD** [bkerler/mtkclient#611]
Win Defender находит в клиенте MTK «Trojan:Script/Wacatac.H!ml»

_Originally posted by @DrowASD in https://github.com/bkerler/mtkclient/issues/609#issuecomment-1407918942_

**Comment by bkerler** [comment]
It's a python script and open source. No idea what win defender is claiming.
