### ISSUE TITLE
redmi note 10s not detected

### ISSUE THREAD

**Issue by sss123next** [bkerler/mtkclient#624]
using `Live DVD V4` redmit note 10s not detected at all

![shitphone2023-02-10_07-49](https://user-images.githubusercontent.com/202772/218003493-143cd295-9fda-4614-8795-e4cd918e5ae0.png)

fastboot commands are working, phone is in bootloader mode.

![FC_00876](https://user-images.githubusercontent.com/202772/218006387-af21bf72-f2b6-49e2-9967-96a2b93dde91.jpg)

**Comment by sss123next** [comment]
same problem on m$ os

**Comment by R0rt1z2** [comment]
... you're supposed to plug in the phone in bootrom mode and not in fastboot mode.

**Comment by sss123next** [comment]
it is bootloader mode.
but problem cause by my misunderstanding of whole concept.
as i figured out by trial and error, phone expose com port interface during turning on process for few seconds i guess, so it was impossible to do procedure on qemu/kvm with manual usb passthrough.
i have completed procedure on m$ os on real hardware, sorry to trouble, but i guess docs need to be more specific about device modes.
