### ISSUE TITLE
Question about secure boot bypass

### ISSUE THREAD

**Issue by max-r-b** [bkerler/mtkclient#626]
Hey,

Thank you for that impressive work.
I am playing with a Samsung A326B (MT6853). When I use mtkclient, the attack kamakiri2 is used (and the tool tells me that it works). What isn't clear to me however is if SBC is disabled or not. After running the `payload` command and rebooting, I can still see `SBC enabled:		True`.
Should I consider that the _kamakiri2_ attack can disable the secure boot? Is there any documentation/explanation about this attack/vulnerability?

Thanks

**Comment by bkerler** [comment]
Haha ... you should have contacted me directly. Sorry, I rarely read issues because they get flooded very often. Kamakiri2 is only temporary but yes, on some devices you can change the seccfg bits (critical unlock) and disable secure boot this way.
