### ISSUE TITLE
pass custom preloader to mtk_gui

### ISSUE THREAD

**Issue by kenkit** [bkerler/mtkclient#628]
Hi, How do we  pass preloader file to mtk_gui ?

**Comment by justaCasualCoder** [comment]
Same here...

**Comment by bkerler** [comment]
via --preloader option

**Comment by justaCasualCoder** [comment]
Hmm... Just tried using `--preloader`... It doesn't seem to work.. Using it with `mtk` works fine, but running `python3 mtk_gui --preloader=my_preloader` is not any different then running `mtk_gui`
