### ISSUE TITLE
Error on sending parameter: DA version Anti-Rollback error (0xc0020053)

### ISSUE THREAD

**Issue by AptGetGnome** [bkerler/mtkclient#640]
I have an issue when trying to get the device to connect, this is using the RE LiveDVD

Port - Device detected :)
Preloader - 	CPU:			MT6779(Helio P90 k79v1)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x725
Preloader - Target config:		0xe5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca01
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			D80F63F328C333D48BF280ED0ABF38A4
Preloader - SOC_ID:			768EE57120BA05762AF1231129A111B2B4A53888C0C1A6BB63BFCCF5BAB2514D
PLTools - Loading payload from mt6779_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /opt/mtkclient/mtkclient/payloads/mt6779_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash
DAXFlash - [LIB]: Error on sending parameter: DA version Anti-Rollback error (0xc0020053)

**Comment by AptGetGnome** [comment]
[log.txt](https://github.com/bkerler/mtkclient/files/10890794/log.txt)

**Comment by ardrag0n** [comment]
How did you fix?
