### ISSUE TITLE
I got everything installed but cannot recognize device on USB

### ISSUE THREAD

**Issue by bendow99** [bkerler/mtkclient#642]
Port - Hint:

Power off the phone before connecting.
For brom mode, press and hold vol up, vol dwn, or all hw buttons and connect usb.
For preloader mode, don't press any hw button and connect usb.
If it is already connected and on, hold power for 10 seconds to reset.

.........C:\WINDOWS\system32\mtkclient\mtk_gui:557: DeprecationWarning: Enum value 'Qt::ApplicationAttribute.AA_EnableHighDpiScaling' is marked as deprecated, please check the documentation for more information.
  QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
C:\WINDOWS\system32\mtkclient\mtk_gui:118: DeprecationWarning: Function: 'QLibraryInfo.location(QLibraryInfo.LibraryPath location)' is marked as deprecated, please check the documentation for more information.
  translations_path = QLibraryInfo.location(QLibraryInfo.TranslationsPath)

**Comment by bkerler** [comment]
I strongly recommend to use linux instead. Windows has a lot of issues and with each Win11 update, more usb issues appear.
