### ISSUE TITLE
Hash computation failed.

### ISSUE THREAD

**Issue by bphd** [bkerler/mtkclient#643]
https://github.com/bkerler/mtkclient/commit/9880651559d6d10cbfe98c7df9385274411cd9aa#diff-a09f685b6a4a5d351f9119b898cbe6fd3cd1348ec8c246c38455edff965bbe58R328

I'm the first one to get that error, that's a celebration!

Idk what to share, considering that debug mode shares a lot of personal informations (even the info one, but here it's literally everywhere). But `mtkclient` do this exchange just before the error

```
DeviceClass - [LIB]: rword:0x2
DeviceClass
DeviceClass - [LIB]: RX:0000
DeviceClass - USBError(5, 'Input/Output Error')
DA_handler
DA_handler - [LIB]: unpack requires a buffer of 65536 bytes
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAloader
DAloader - [LIB]: Hash computation failed.
```

Operating system: Linux
Manufacturer: Oppo
Model: CPH2273
Download agent loader: MTK_AllInOne_DA_5.2136.bin
Hardware code: 0x766

**Comment by bkerler** [comment]
Not sure what you mean with "personal" informations. But for a bug report, there is no need to run in debug mode. But at least the os, device model / manufacturer, used da loader and hwcode is needed to do anything useful

**Comment by bphd** [comment]
> Not sure what you mean with "personal" informations. [...] and hwcode

> In the context of MediaTek Android devices, "HW code" refers to the hardware code or identification number that is associated with a specific device. The HW code is a unique identifier that is used to differentiate one device from another.

The HW code is typically a combination of letters and numbers, and it is often printed on the back of the device or can be found in the device's settings. It is used by manufacturers, developers, and users to identify a specific device and ensure that the correct firmware or software is being installed or applied.

**Comment by bphd** [comment]
Updated

**Comment by bkerler** [comment]
This error looks like you need to use a usb hub in between. Some usb xci don't work with mtkclient. Furthermore, oppo devices often need a testpoint and a custom da to work.
