### ISSUE TITLE
Fatal error when running git clone.

### ISSUE THREAD

**Issue by ihavenull** [bkerler/mtkclient#645]
When running git clone https://github.com/bkerler/mtkclient/ , `fatal: unable to access 'https://github.com/bkerler/mtkclient/': error setting certificate verify locations:  CAfile: C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt CApath: none` shows.
Windows 10 x86-64, professional, 19045.2728.

**Comment by bkerler** [comment]
No idea, ask on reddit.
