### ISSUE TITLE
Meta mode?

### ISSUE THREAD

**Issue by biden2020prez** [bkerler/mtkclient#646]
Hi @bkerler does your tool have the ability to communicate with an MTK device in meta mode? I don't have too much undersanding of meta mode, but it looks like your tool might have 'mtk meta' commands?

Specifically, I am interested in dumping and flashing partitions, but would also be interested in other documentation of meta mode. 

I am very impressed by this tool by the way, it is by far my favorite MTK tool, with so much packed into one tool

**Comment by bkerler** [comment]
Yes, it support the meta mode, but only the reboot stuff so far.
