### ISSUE TITLE
Pyinstaller spec will work for 'mtk' without GUI?

### ISSUE THREAD

**Issue by SZRabinowitz** [bkerler/mtkclient#647]
Hi @bkerler . Thanks for the PyInstaller spec. If I edit 'mtk_gui' and change it to 'mtk' in the spec file, will it work to make a standalone mtk? thanks!

**Comment by bkerler** [comment]
yes, that should normally be sufficient, but I'd remove from requirements.txt the shiboken6 and pyside6 packages, as otherwise it would be unneccessary big

**Comment by biden2020prez** [comment]
should I close this?

**Comment by tungtata** [comment]
Hi after build using command pyinstaller mtk_standalone.spec then my execute got some problem

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
```

```
Traceback (most recent call last):
  File "mtk", line 812, in <module>
NameError: name 'exit' is not defined
[28748] Failed to execute script 'mtk' due to unhandled exception!
```

**Comment by tungtata** [comment]
Hi, @biden2020prez can you please share your execution of mtk tool? thank you

**Comment by biden2020prez** [comment]
hi @tungtata. I have not yet built MTK with PyInstaller, but I will be happy to try. Did you build the MTK Command line or the GUI? I think @bkerler made a new spec for non-gui.

**Comment by tungtata** [comment]
> hi @tungtata. I have not yet built MTK with PyInstaller, but I will be happy to try. Did you build the MTK Command line or the GUI? I think @bkerler made a new spec for non-gui.

I tried build the commandline version but not works

**Comment by bkerler** [comment]
Should be fixed by now.
