### ISSUE TITLE
Is this code from mtkclient

### ISSUE THREAD

**Issue by biden2020prez** [bkerler/mtkclient#648]
HI, @bkerler.  Here is a gist for booting to Fastboot, Metamode, etc. https://gist.github.com/plugnburn/b3b0bcfd926c48ec5373bea84ce59337

It looks like it was taken right out of MtkClient without recognition. Not sure whether or not I am supposed to post that here

**Comment by SenseiHugeD** [comment]
> HI, @bkerler. Here is a gist for booting to Fastboot, Metamode, etc. https://gist.github.com/plugnburn/b3b0bcfd926c48ec5373bea84ce59337
> 
> It looks like it was taken right out of MtkClient without recognition. Not sure whether or not I am supposed to post that here

"without recognition" my foot.

**Comment by biden2020prez** [comment]
> 
> "without recognition" my foot.

I would love for you to explain yourself. I don't see credits there. That's all.
