### ISSUE TITLE
Unable to resolve

### ISSUE THREAD

**Issue by littlebone1** [bkerler/mtkclient#655]
When I tried this step of "python setup.py install" in the MTK tutorial, the program told me that pyside2 could not be parsed, what should I do
Searching for PySide2
Reading https://pypi.org/simple/PySide2/
No local packages or working download links found for PySide2
error: Could not find suitable distribution for Requirement.parse('PySide2')

**Comment by bkerler** [comment]
Means you need to compile it yourself or find a wheel for your python version.
