### ISSUE TITLE
[MT6762G] Phone detected incorrectly, then it loads endlessly

### ISSUE THREAD

**Issue by anon1892** [bkerler/mtkclient#661]
Hello, thanks for your works.

I want to unlock my Redmi 9A (MT6762G, Helio G25), and use MTK Client 2.0 beta from live USB.
I start the phone, MTKclient start loading and write : "Phone detected : MT6765/MT8768t (Helio P35/G35) Jumping to 0x200000: ok"
But after that, the loading animation never stops. And the phone no longer responds, I have to wait the battery to run down (few days), charge it again and after it works.

There are the logs
```
Loading payload from MT6765_payload.bin, 0x264 bytes
Kamakiri / DA Run
Trying kamakiri2..
Donc sending payload...
Successfully sent payload: /opt/mtkclient/payloads/mt6765_payload.bin
Device is protected
Device is in BROM mode. Trying to dump preloader.
```

Am I doing something wrong ? Is it normal that the phone is detected wrongly ?
Thanks

**Comment by bkerler** [comment]
Did you try to use the latest version ? Also did you try using the console and are you in brom, not preloader mode ?

**Comment by anon1892** [comment]
Yes, I was using the latest version.
If I recall correctly, was the same problem in the console too.
Logs said "Device is in BROM mode", but cannot be certain.
I gave up and unlocked bootloader with official Xiaomi tool (for readers : you have to create a Xiaomi account located in the USA, even if you're not from there, then connect it to the phone, wait a week, it works like that)
