### ISSUE TITLE
Is Nokia C2 2nd Edition not supported?

### ISSUE THREAD

**Issue by Umeaboy** [bkerler/mtkclient#662]
I have compiled and installed mtkclient using the instructions in the README.md.
As I run python mtk_gui and booting the phone to bootloader I can't get mtk_gui to detect the device and I'm using the cable that came with the box.
I'm using Mageia 8 and it's a fresh installation so no odd tinkering has been done.

**Comment by MageiaLinuxOnSiliconDevices** [comment]
Ping?
