### ISSUE TITLE
[Attempt] Installing `mtkclient` on a rooted Android 11 device with Termux having issues with PySide6 not installing

### ISSUE THREAD

**Issue by VenomousSteam81** [bkerler/mtkclient#667]
PySide6 will not install because the PySide6 distribution. Everything else seems to install fine, except for PySide6. Any help would be appreciated, thanks!

**Comment by kzwkt** [comment]
if you don't need gui you can remove pyside from requirements.txt

**Comment by oddsito** [comment]
Is it possible to run mtkclient without root?

**Comment by bkerler** [comment]
@oddsito yes
pyside is only needed for gui.

**Comment by VenomousSteam81** [comment]
Huh. Completely forgot about this issue. Thanks for the response!
