### ISSUE TITLE
[BootROM dump] Nokia 3.1 (TA-1063) BROM dumped successfully

### ISSUE THREAD

**Issue by Tryzen-0** [bkerler/mtkclient#669]
**I have managed to successfully dump my Nokia 3.1's BROM by bruteforcing with kamakiri**
- I would like to request the adding of full support for this phone.
  Here's the file uploaded to my own personal backups folder:
  https://mega.nz/file/26JzGJAC#Q9FubJ5rfEo8umaKyt3bJ0yrVrWbQcj2fkff0TOEzv4

- If you would like me to upload somewhere else please tell me. Thx in advance!

**Comment by panukooo** [comment]
hi dude i hope you can help me
i want to know what dump does and if i use this command, it modify anything from the phone? which command should i use and if something goes wrong how can i restore the dumped files?
greetigs

**Comment by bkerler** [comment]
0x326 is already supported.
