### ISSUE TITLE
Problem with preloader

### ISSUE THREAD

**Issue by Josh830-lab** [bkerler/mtkclient#673]
"Preloader - [LIB]: Status: Handshake failed, retrying..."
Using a TCL A509DL Alcatel phone

**Comment by SenseiHugeD** [comment]
> "Preloader - [LIB]: Status: Handshake failed, retrying..." Using a TCL A509DL Alcatel phone

This is normal good sir! You just need to unplug, and plug your device back in and it should work fine. Of course do this holding the button combo

**Comment by bkerler** [comment]
Exactly. Or testpoint needed or different usb hub might help.
