### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by BDTG** [bkerler/mtkclient#680]
Hey I try to install mtkclient in my pc completely success but when I try a command python mtk_gui the cmd show me this.
Traceback (most recent call last):
  File "C:\Users\tranv\mtkclient\mtk_gui", line 13, in <module>
    from PySide6.QtCore import Qt, QVariantAnimation, Signal, QObject, QSize, QTranslator, QLocale, QLibraryInfo, \
ValueError: source code string cannot contain null bytes

**Comment by bkerler** [comment]
this seems to be an issue with how you checked out your git code (unix style).
