### ISSUE TITLE
The ISO was not ready to go

### ISSUE THREAD

**Issue by VenomousSteam81** [bkerler/mtkclient#681]
**THIS ISN'T AN ERROR!!**

The ISO was not ready to go, because it doesn't have all the scripts for mtkclient itself (when I tried it at least). Did the download not get finished?

**Comment by bkerler** [comment]
It's recommended to first run git pull on the /opt/mtkclient folder and run pip install -r requirements.txt to get the latest version.

**Comment by BeWhoYouWannaBe** [comment]
When I do this (git pull) I get the following message: error: Your local changes to the following files would be overwritten bij merge: requirements.txt 
Please commit your changes or stash them before you merge.

then I needed to give the following command: git stash

and: pip install requirements.txt

After that I still got a error message when running ./mtk_gui and I still need to run the following command:
sudo apt install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

After this I can run the command ./mtk_gui

What is wrong or what am I not doing right? I am using the latest ISO version but after an restart I need to follow all these steps to work with the latest drivers...
