### ISSUE TITLE
Successful frp bypass SM-A146W U2

### ISSUE THREAD

**Issue by xdastuff** [bkerler/mtkclient#685]
No issue. Went to hell and back.
What i found worked beest was using another app to first disable authorization, then fire up the gui.

So, with phone off and disabler started, hold all three buttons and plug in until it starts to affect phone. Once complete, don't stop disabler and double click gui bat file. 
I also noticed in Windows, without gui, the command is ./ntk e frp for example. No python in command.

Anyway, the gui will sometimes fail but nostly not by this method.

From there i did all kinds of crazy stuff. Wiped it to nothing and back.

Then, i decided to wipe several partitions but cannot recall exactly. Userdata, metadata, persist, persistent, sec_config, vbmeta, frp and maybe more but that's close.

After reboot, i was forced to flash and the sm-a146w, on April patch, binary 2.... done. Didn't see that one on youtube.

I may have named some partitions wrong and missed on or two. Just do this if you're locked and experiment. That may be all it was. Thanks. Works great.

**Comment by bkerler** [comment]
Closing this now as it is no issue.
