### ISSUE TITLE
How to use SN Writer with mtk client

### ISSUE THREAD

**Issue by R-3MY** [bkerler/mtkclient#686]
Hi,

This is the first issue i open on github. So sorry if i do some mistakes :/

My device is an Oppo Reno 6 : CPH2251 with MT6877 MTK Chip.

I cannot use SN Writer, i read i just need to connect the powered off phone but without success...

I tried to check the already in meta mode option then use mtk payload --metamode METAMETA but without success too...

If someone can help me to restore my IMEI or use SN Writer it can be nice.

If someone can send the log of "normal" command output it can be nice too :)

**Comment by Khalylexe** [comment]
let me know if you find anything

**Comment by PRD-Pandat** [comment]
You can try other solutions, such as Sp's flash tools that record the IMEI (in this method, you need to back up the IMEI first).
https://www.hovatek.com/forum/thread-23412.html

You can also use Modem Meta or Maiu Meta to record the IMEI:
https://www.hovatek.com/forum/thread-31577.html
https://www.hovatek.com/forum/thread-12328.html

I had a similar problem,I ended up selecting format all + download in sp flash tools and used Maiu meta solved the problem.

I never had an oppo,more heard that advanced users always have headache with the brand.

**Comment by R-3MY** [comment]
i tried both modem and maui meta but without success, i successfully booted in meta mode (i have META MODE) written in the bottom left of the screen but cannot reach the end of the process, i'm locked to the Connect to MD step

**Comment by nibirrayy** [comment]
I am have same issue just that I am stuck at connecting to  the ap step. It would be nice if we could simple write IEMI using Mtk client. Not to change IEMI but just to recover our own IEMI

**Comment by R-3MY** [comment]
Yep same, it seem it's impossible to enter meta mode with mtkclient, i used another tool to enter meta mode but without success with mauimeta, impossible to complete all steps

**Comment by kzwkt** [comment]
my realme can reboot to meta mode by : adb reboot meta 
you sould select already in meta mode in sn writer tool and select usb port 
goto config and select apdb and mddb
i get nvram and maui db inconsistent error and cant write with tee support 
try it if it works for you and share results

**Comment by Pimp70434** [comment]
How can I use mtk to force brom to come on ?

**Comment by bkerler** [comment]
"mtk payload", then you can use the mtk tools.
