### ISSUE TITLE
Auth bypass not working properly 

### ISSUE THREAD

**Issue by git9t2** [bkerler/mtkclient#687]
After auth bypass using mtkclient by payload option, I unable to flash using spflash toll even after made connection mode uart. One more thing after  after auth bypass, mtkclient also give message reconnect the device to do any process like read write partition. Please enhance the issue.

**Comment by bkerler** [comment]
I assume that you aren't using the bypass on a supported device. On supported devices, it just works fine.
You need to provide more logs, device name and model, chipset to provide any help.
