### ISSUE TITLE
DeviceClass - [LIB]: Couldn't get device configuration.

### ISSUE THREAD

**Issue by laerte1000** [bkerler/mtkclient#694]
Hi, i'm trying to unlock the bootloader of my vivo y33s, but when i power it off, and press volume up and down at the same time, it just says: 
`DeviceClass - [LIB]: Couldn't get device configuration.`

Does anybody know how to fix this?

**Comment by goodair220917** [comment]
This happens to me everytime as how you said, just to unplug the phone and plug it in again.
(The model of my phone is MT6762G (MT6765)

**Comment by HaoTian22** [comment]
It happens on my MT6761 device too, even though I tried different computer and OS(tried Archlinux, Windows 10,Windows 11)

**Comment by Morax-Lizho** [comment]
我的MT6833上也发生了此类问题

**Comment by rodren-lion** [comment]
<img width="1746" height="1634" alt="Image" src="https://github.com/user-attachments/assets/f698587b-389b-4983-af2a-5ba21796aa4f" />  me too...
