### ISSUE TITLE
src directory of payloads missing

### ISSUE THREAD

**Issue by etmatrix** [bkerler/mtkclient#70]
In README I read this
```
Compile payloads (optional)
Install gcc armeabi compiler

sudo apt-get install gcc-arm-none-eabi

Compile

See src/readme.build for detailed instructions.

cd src
make
```
but directory is missing, so source code of payloads are missing?

**Comment by bkerler** [comment]
README has been adapted. As currently no real co-development happens on this github-repo, there is no plan to release the source code as for now.

**Comment by etmatrix** [comment]
It's ok, I'm studying the tool, so I wanted to see all code, I will decompile the payload for understand better.

**Comment by bkerler** [comment]
Basically it's just doing the same as preloader. If you want to understand how it works, better reverse preloader images.
