### ISSUE TITLE
Not show button.

### ISSUE THREAD

**Issue by seci20** [bkerler/mtkclient#701]
Hi master. Whats problem not show tab and button ? 

![Ekran Alıntısı](https://github.com/bkerler/mtkclient/assets/13988176/c032cf1b-36f4-4cc3-9b70-38d09ed65f6a)

**Comment by jwab-email** [comment]
me too \\:
on Debian 11

**Comment by bamsdjawir** [comment]
me to on windows 11

**Comment by bkerler** [comment]
that's most probably sla related, use a different da loader using --loader :)
