### ISSUE TITLE
Cannot boot without mtk plstage ...

### ISSUE THREAD

**Issue by WoozyDev** [bkerler/mtkclient#702]
I've hard bricked my phone and i tried unbricking it, now when trying to boot, i cannot, but, If i use `python mtk plstage --preloader [my preloader_camellia.bin]` it works, and it boots (finished the miui setup), but i can't do this all the time (maybe i wont have my pc with me to do the command)
Please help me!

If preloader needed, don't hesitate to ask me to upload,
or anything needed.

**Comment by fpeta** [comment]
Good morning,
Have you tried to erase preloader and reflash it with MTKClient and/or MediaTek SP Flash Tool ? 
Best regards
François

**Comment by WoozyDev** [comment]
yeah well, too late, I already sent it to repair.

**Comment by WoozyDev** [comment]
To be honest, i checked before sending it to repair if the system existed, but it doesn't, so they said it right

**Comment by WoozyDev** [comment]
or the preloader_camellia.bin

**Comment by WoozyDev** [comment]
I can't boot now, not to system, not even to bootloader.

**Comment by WoozyDev** [comment]
i can't flash to system partition because it seems like it doesn't exist anymore.

**Comment by WoozyDev** [comment]
```
Main - [LIB]: ←[31mError: Couldn't detect partition: system_a
Available partitions:←[0m
Main - misc
Main - para
Main - countrycode
Main - expdb
Main - frp
Main - nvcfg
Main - nvdata
Main - vbmeta_a
Main - vbmeta_system_a
Main - vbmeta_vendor_a
Main - vbmeta_b
Main - vbmeta_system_b
Main - vbmeta_vendor_b
Main - metadata
Main - persist
Main - persistbak
Main - protect1
Main - protect2
Main - seccfg
Main - otp
Main - md1img_a
Main - spmfw_a
Main - pi_img_a
Main - dpm_a
Main - scp_a
Main - sspm_a
Main - mcupm_a
Main - gz_a
Main - lk_a
Main - boot_a
Main - vendor_boot_a
Main - dtbo_a
Main - tee_a
Main - sec1
Main - proinfo
Main - efuse
Main - nvram
Main - boot_para
Main - logo
Main - md1img_b
Main - spmfw_b
Main - pi_img_b
Main - dpm_b
Main - scp_b
Main - sspm_b
Main - mcupm_b
Main - gz_b
Main - lk_b
Main - boot_b
Main - vendor_boot_b
Main - dtbo_b
Main - tee_b
Main - devinfo
Main - gsort
Main - ffu
Main - rescue
Main - cust
Main - super
Main - userdata
Main - flashinfo
```

**Comment by WoozyDev** [comment]
I just flashed pixel experience boot.img and now im in recovery mode, from here how can i fix all this?

**Comment by WoozyDev** [comment]
```
C:\Users\woozy\Documents\mtkclient-1.52>fastboot erase preloader
erasing 'preloader'...
FAILED (remote: Partition doesn't exist)
finished. total time: 0.012s

C:\Users\woozy\Documents\mtkclient-1.52>fastboot erase system
erasing 'system'...
FAILED (remote: Partition doesn't exist)
finished. total time: 0.012s
```

**Comment by WoozyDev** [comment]
actually, erasing system_a worked, but not preloader_a
