### ISSUE TITLE
Rooting results in "The current image (boot/recovery) have been destroyed and can not boot."

### ISSUE THREAD

**Issue by ljez** [bkerler/mtkclient#715]
I tried to root a Realme 7 RMX2155 phone with MediaTek Helio G95 MT6785 processor.  I followed the instructions for unlocking the bootloader and then rooting the phone.  Everything seemed to work, except once I was done the phone, trying to start the phone results in an error: "The current image (boot/recovery) have been destroyed and can not boot."  I would appreciate help with this.  Thank you.

**Comment by bkerler** [comment]
That is because Realme/Oppo/Vivo deactivate any unlocking in their smartphones. You might try to patch the lk, if it's possible. No mtkclient issue.
