### ISSUE TITLE
MT6589 - MT8125 too old for mtkclient?

### ISSUE THREAD

**Issue by AstroManta** [bkerler/mtkclient#716]
Am getting handshake failed on an old Asus tablet with this SoC. Is there support for this chipset in mtkclient, anybody? Thanks.

**Comment by bkerler** [comment]
If you can dump the brom for this device, I can try to add support

**Comment by ErfanMG2020** [comment]
> If you can dump the brom for this device, I can try to add support

How I can dump brom on MT6589 device?
I'm a beginner so I extra advices.
I have Huawei G610-U20

**Comment by AstroManta** [comment]
Your BROM should be in any official Huawei ROM you can download for your device.

**Comment by ErfanMG2020** [comment]
> Your BROM should be in any official Huawei ROM you can download for your device.

I have its official firmware, how can I get its BROM from it?
Can I get it from firmware files or only dump from device itself?

**Comment by ErfanMG2020** [comment]
> If you can dump the brom for this device, I can try to add support

I have found a BootROM for an MT6589 device, check if you can add support for MT6589
[MT6589 BootROM](https://github.com/arzam16/SoC-BootROMs/tree/main/mediatek/MT6589WTK%201325-ATAH%20DTNGT126)

**Comment by cristianc** [comment]
> > If you can dump the brom for this device, I can try to add support
> 
> I have found a BootROM for an MT6589 device, check if you can add support for MT6589 [MT6589 BootROM](https://github.com/arzam16/SoC-BootROMs/tree/main/mediatek/MT6589WTK%201325-ATAH%20DTNGT126)

By clicking your url, 'File not found' page appears. Where did you put your BROM?
