### ISSUE TITLE
Please add .img as extension

### ISSUE THREAD

**Issue by Ko-Hi-Dev** [bkerler/mtkclient#718]
I'm much aware of the tool but there's one *tiny feature* or let's say regular partition extensions to be added to the flash files option.

Currently only .bin is supported (which might be there for a reason?*)

But if you would want to flash a stock device partition you would need to rename it. (Not real issue) but as just renaming it will do fix the problem.

However if you are messing around way too much it might cause annoyance.

(I myself have Been wondering why only .bin extension is supported)

If possible could you add it ?

P.S I have had a drink or too so hope you understand this 🙏 

Thanks for taking your time 🙏

* I know this might be intentional if so please do reply that you won't fix, I'm sure a private build can be fixed for personal usage :)

**Comment by bkerler** [comment]
actually to what are you referring to ? You can name the files as you wish, it just has been chosen for wl/rl commands to have unique filenames.

**Comment by Ko-Hi-Dev** [comment]
> actually to what are you referring to ? You can name the files as you wish, it just has been chosen for wl/rl commands to have unique filenames.

What I'm trying to say that it should be possible to just select .img when flashing. Rather than just being needed to rename any file that you want to flash. Just a suggestion

**Comment by bkerler** [comment]
Not sure I understand. Are you referring to the gui ?

**Comment by Ko-Hi-Dev** [comment]
> Not sure I understand. Are you referring to the gui ?

Ah yes my bad that I didn't mention 🙏

**Comment by bkerler** [comment]
I will have a look if that can be changed in the gui, sure :)
