### ISSUE TITLE
MT6877(Dimensity 900) GUI client stuck?

### ISSUE THREAD

**Issue by MDo94** [bkerler/mtkclient#721]
Device gets detected but the client GUI just get stuck in [ Patched "get_vfy_policy" in preloader ]...

Port - Device detected :)
Preloader -     CPU:                    MT6877(Dimensity 900)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x959
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      B499429261CA25698792DD016AE56B18
Preloader - SOC_ID:                     6D964C96AAF76733812BA2C0E45C6DB2436F6FB3002BE9CF660B93422724500A
Port - Device detected :)
Successfully extracted preloader for this device to: preloader_pissarro.bin
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
xflashext - Patching da1 ...
xflashext
xflashext - [LIB]: [33mError on patching da1 version check...[0m
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       MT128GAXAU2U22
DAXFlash - UFS MID:      0x2c
DAXFlash - UFS CID:      2c014d54313238474158415532553232
DAXFlash - UFS FWVer:    30313031
DAXFlash - UFS Serial:   6c203c200000000000000000
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : 2c014d54313238474158415532553232
DAXFlash - Sending emi data ...
DAXFlash - DRAM setup passed.
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       MT128GAXAU2U22
DAXFlash - UFS MID:      0x2c
DAXFlash - UFS CID:      2c014d54313238474158415532553232
DAXFlash - UFS FWVer:    30313031
DAXFlash - UFS Serial:   6c203c200000000000000000
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - HW-CODE         : 0x959
DAXFlash - HWSUB-CODE      : 0x8A00
DAXFlash - HW-VERSION      : 0xCA00
DAXFlash - SW-VERSION      : 0x0
DAXFlash - CHIP-EVOLUTION  : 0x2
DAXFlash - DA-VERSION      : 1.0
DAXFlash - Extensions were accepted. Jumping to extensions...
DAXFlash - DA Extensions successfully added

![Screenshot 2023-07-09 171535](https://github.com/bkerler/mtkclient/assets/37194235/c61c55d8-ff23-4875-a851-33ac9712edea)

**Comment by bkerler** [comment]
Not sure why this happens (gui was developed by keert). Might have a look.
