### ISSUE TITLE
Device has is either already unlocked or algo is unknown. Aborting.

### ISSUE THREAD

**Issue by deep959** [bkerler/mtkclient#730]
Im trying to unlock realme X7 max but I'm always getting this 
Previously I unlocked it with deeptest app and relocked again
But now deeptest app server are closed so trying with this method but I'm getting 
Device has is either already unlocked or algo is unknown. Aborting.

I used mtk xflash secgf unlock something code 

Please give me a solution

**Comment by ElectroBoy404NotFound** [comment]
I think the device is not supported
