### ISSUE TITLE
python3 mtk_gui fails to load the gui due to problem loading the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by sailinggalaxians** [bkerler/mtkclient#731]
[kristoffer@localhost mtkclient (main)]$ python3 mtk_gui
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, offscreen, minimal, vkkhrdisplay, wayland, wayland-egl, minimalegl, vnc, linuxfb, eglfs.

Aborted (SIGABRT) (memory dump created)

I did use the pip install command to install all dependencies from requirements.txt before building as the README instructs and then building mtkclient using python3 bdist_wheel so what am I missing?

The python3 setup.py build command is no longer used so python3 bdist_wheel should be added to the README.

**Comment by sailinggalaxians** [comment]
I'm using Mageia 9 as my dist which uses rpm and urpmi to install packages.

**Comment by kzwkt** [comment]
its due to pure wayland, either install xwayland or qt5-wayland or just  use xorg   and set env variable, havent used Mageia ever

**Comment by bkerler** [comment]
most probably due to mix of qt5 libraries or interfering install of pyqt5 vs. pyside6. Make sure to use venv and don't install via pip in global
