### ISSUE TITLE
Error "unpack requires a buffer of 12 bytes" on Redmi 9a, both Windows and LiveUSB

### ISSUE THREAD

**Issue by nar001** [bkerler/mtkclient#736]
So I've got a Redmi 9a that I'm trying to unlock. I tried mtkclient both on Windows, and the provided LiveUSB. Both end with the same error. I tried deleting the "MTK_AllInOne_DA_5.1824.bin" file but it changed nothing, the error still happens, and nothing happens when I for example try to unlock the bootloader, so I can't continue and couldn't find any actual way of getting past this, even in older threads. Thanks for any help you could provide!

**Comment by Jairah7** [comment]
i solve this problem by trying other preloader for redmi 9a

**Comment by nar001** [comment]
How? I'm not sure how to do this.

**Comment by coloredmarble** [comment]
https://github.com/coloredmarble/redmi_9a_mtkclient/tree/main
