### ISSUE TITLE
Redmi 10A Sport (dandelionC3L2IN) bootloader unlock instructions do not work

### ISSUE THREAD

**Issue by eternalfrustation** [bkerler/mtkclient#738]
Upon following the instructions for unlocking the bootloader for Redmi 10A Sport (dandelionC3L2IN) (MT6762) running the current MIUI (miui_DANDELIONC3L2INGlobal_V12.5.13.0.RCZINXM_273b44438c_11.0),
The bootloader stays locked with only a dm-verity error on every boot.

There was no preloader partition accessible, I have attached the flashinfo and seccfg partition before da unlock, after da unlock and after first boot.
Please let me know if anything else is needed
[flashinfo_seccfg.zip](https://github.com/bkerler/mtkclient/files/12191387/flashinfo_seccfg.zip)

**Comment by Mavigsm** [comment]
Put the device in fastboot mode. execute the command "fastboot oem cdms"
