### ISSUE TITLE
mtk_gui crashes

### ISSUE THREAD

**Issue by 1amir0reza** [bkerler/mtkclient#741]
My phone bricked many years ago and I had forgotten about it until recently. I am now trying to unbrick my phone, but there is no output on the screen and no LEDs light up. However, when I connect the phone to my PC, a new device shows up called 'Preloader MediaTek 6580'.

I have tried multiple tools to fix the issue, but none of them have worked correctly. When I try to connect my phone to MTK GUI, it goes well until the stage 2. After that, the last log message is 'reconnecting to stage 2 with higher speed', and then the tool freezes and crashes.

**Comment by halal-beef** [comment]
same exact issue with me, mt6737, xperia L1 but when i am on linux it works fine so might be a usbdk issue or something

**Comment by ElectroBoy404NotFound** [comment]
What about mtk cli? does that work?

**Comment by halal-beef** [comment]
nope, crashes

**Comment by ElectroBoy404NotFound** [comment]
What happens when you mean "crash"

**Comment by ElectroBoy404NotFound** [comment]
I meant, by 'crash', what do you mean?

**Comment by bkerler** [comment]
Just use --noreconnect option and it should work. Most probably caused by a bad usb hub / setup.
