### ISSUE TITLE
Any plans to support for Dimensity 9000 (MT6983) ?

### ISSUE THREAD

**Issue by inferno0230** [bkerler/mtkclient#744]
I know its not currently not supported and mediatek have locked down 8000 series too,

Logs which i took (Used LiveCD)

* [python mtk printgpt --debugmode](https://katb.in/tiduzamoxur)

* [python mtk brute --debugmode](https://katb.in/zerogalamid)

**Comment by bkerler** [comment]
not supported for now. Support is being worked on. Refer to #758
