### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by Billybangleballs** [bkerler/mtkclient#749]
How do I compile mtkclient on my pi?

Raspberry Pi
Raspbian GNU/Linux 11
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
ERROR: Could not find a version that satisfies the requirement shiboken6>=6.4.0.1
ERROR: No matching distribution found for shiboken6>=6.4.0.1

**Comment by bkerler** [comment]
shiboken6 is only needed for the gui. If you want to use the gui on the pi, you will need to compile shiboken6 yourself.
