### ISSUE TITLE
[Feature Request] Split image into smaller ones while dumping big partition such as "userdata"

### ISSUE THREAD

**Issue by Mark-Joy** [bkerler/mtkclient#754]
Hello,
First, I want to thank you for the wonderful tool that give me a chance to restore my data after hard-bricked.
After reading 128GB userdata partition from Phone to D:\userdata.bin, I check if the file is OK by copying it to other partition such as G:\userdata.bin. I got `ReadFile(Data error (cyclic redundancy check).23)`  indicates that my drive has some failed sector.

So, by splitting the image into smaller ones while dumping, it may reduce the chance of this error happening.
Even if it happens, we can just re-read the offset where the error occurs using `python mtk ro 0xError_Address 0xSplit_Size`, rather than re-read the whole image 128GB, which takes a lot of time.
Option likes `/SplitSize` would work. Example: to split userdata.img to userdata_partXX, each 4GB in size while dumping:
`python mtk r userdata /SplitSize 0x100000000`
or
`python mtk ro 0xUserData_Address /SplitSize 0x100000000`

Thank you!

**Comment by bkerler** [comment]
I will have a look if it can be added.
