### ISSUE TITLE
[mt6765] TCL A3 Preloader Disconnect

### ISSUE THREAD

**Issue by ghost** [bkerler/mtkclient#756]
I am having this error on my mt6765 (technically mt6762) device the TCL A3. MTKClient is able to successfully connect to one of my TCL A3s, but is not able to connect to the second one. I assume this is a preloader patch in the second device, but I wanted to send an issue in just in-case.

The log from the erroring device is log.txt and the log from the working device is unlocked A3.txt

[unlocked A3.txt](https://github.com/bkerler/mtkclient/files/12328450/unlocked.A3.txt)
[log.txt](https://github.com/bkerler/mtkclient/files/12328448/log.txt)

**Comment by mslhii** [comment]
Use this to unlock the A3: https://xdaforums.com/t/alcatel-tcl-a502dl-a501dl-root-custom-recovery-custom-roms.4249853/post-88195915
