### ISSUE TITLE
my phone is just dead {PLEASE HELP}

### ISSUE THREAD

**Issue by iPurya** [bkerler/mtkclient#757]
hi there 
my phone is Redmi 9C
i did all steps and now my phone is off and wont on.
and when i connect usb its not recognized.
i cant do anything at all.
logs folder is emty
so can anybody help me please ?

**Comment by iPurya** [comment]
this is the output and after that phone is dead:


Port - Device detected :)
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      D36AA291053EFE96349545889ECB62C5
Preloader - SOC_ID:                     14B85C7C993EBAC50058E172774AEF6112D4D6716EE0E124CE0DBAC4259F40BE
PLTools - Loading payload from mt6765_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\MediatekBootloaderUnlock\mtkclient\mtkclient\payloads\mt6765_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
Successfully extracted preloader for this device to: preloader_k65v1_64_bsp.bin
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2228.bin
xflashext - Patching da1 ...
Mtk - Patched "Patched loader msg" in preloader
Mtk - Patched "hash_check" in preloader
xflashext
xflashext - [LIB]: Error on patching da1 version check...
Mtk - Patched "Patched loader msg" in preloader
Mtk - Patched "get_vfy_policy" in preloader
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - DRAM setup failed: unpack requires a buffer of 12 bytes

**Comment by ardx812** [comment]
same thing lol it's just not turning on also the same error

**Comment by bkerler** [comment]
1. No idea what you did (obviously you killed the preloader
2. use mtk with --preloader and preloader from firmware
3. repair the stuff you did

**Comment by Spiderfffun** [comment]
mine did this too but it isnt detected at all, almost as if its a broken thing, all i did was `mtk rl out` but i think i may have entered preloader instead of brom by accident
