### ISSUE TITLE
Xiaomi Redmi 6 bootrom dump

### ISSUE THREAD

**Issue by duanin2** [bkerler/mtkclient#763]
I have managed to succesfully dump the bootrom of my Xiaomi redmi 6 using mtk brute and would like to request full support.
[The dump.](https://drive.google.com/file/d/1vhMTCV2WsZSg4Gmp28nflDCN6cW6hmON/view?usp=sharing)

**Comment by bkerler** [comment]
MT6765 is already supported.

**Comment by duanin2** [comment]
Xiaomi Redmi 6 has an MT6762 SoC, not MT6765.

**Comment by jerinphilip** [comment]
I have a Redmi-6 I'm currently trying to develop PostmarketOS on. 

https://en.wikichip.org/w/index.php?title=mediatek/helio/mt6765 redirects to 6762.
Also https://github.com/xiaomi-mt6765/android_device_xiaomi_cereus is under 6765.

**Comment by duanin2** [comment]
It redirects to Helio A22, but Xiaomi Redmi 6 uses Helio P22.

**Comment by duanin2** [comment]
Well, I'm sorry, you are right. [postmarketOS wiki MT6765](https://wiki.postmarketos.org/wiki/MediaTek_MT6765)
