### ISSUE TITLE
[mt6833 Dimensity 700] Redmi 10 5G unlock bootloader problem

### ISSUE THREAD

**Issue by JuananInt** [bkerler/mtkclient#764]
The command "python mtk da seccfg unlock" works and the log shows that it has been unlocked successfully, but when I start the device it does not show the xiaomi padlock indicating that the bootloader is unlocked, also from fastboot I run the command "fastboot getvar unlocked" it shows that the bootloader it is not unlocked, just like the "mi unlock" page of miui advanced configuration settings:

Port - Device detected :)
Preloader - 	CPU:			MT6833(Dimensity 700 5G k6833)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0x73
Preloader - Disabling Watchdog...
Preloader - HW code:			0x989
Preloader - Target config:		0xe7
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		True
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			D72042A668BB39A226B5C8E159986A3A
Preloader - SOC_ID:			478655AFA79849C3E9945C5DE44815A46B0B0E24F3F64EF6C1CBB8505CE22E15
PLTools - Loading payload from mt6833_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Juanan\Downloads\MediatekBootloaderUnlock\file\mtkclient\payloads\mt6833_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x2020
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       SDINDDK4-128G 
DAXFlash - UFS CID:      45015344494e44444b342d3132384720
DAXFlash - UFS LU0 Size: 0x1dcd800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : 45015344494e44444b342d3132384720
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x2020
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       SDINDDK4-128G 
DAXFlash - UFS CID:      45015344494e44444b342d3132384720
DAXFlash - UFS LU0 Size: 0x1dcd800000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x89920
DAXFlash - DA Extensions successfully added
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate

Done |--------------------------------------------------| 0.0% Write (Sector 0x0 of 0x1) 0.00 MB/s
Progress: |ÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûêÔûê| 100.0% Write (Sector 0x1 of 0x1, ) 0.02 MB/s
xflashext - Successfully wrote seccfg.
Bootloader unlocked. Please disconnect the cable and press and hold the power button until the logo appears. 
.

**Comment by tacssuki** [comment]
is this already solved?
