### ISSUE TITLE
getting errors after it working "perfectly"

### ISSUE THREAD

**Issue by scopiwolf** [bkerler/mtkclient#776]
So I'm trying to dump the preloader, which worked, then went to dump the boot, which did not work so i tried the preloader again and well it didnt work, i keep getting this
```
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
```

on mt6735m, could anyone help? switching cables and ports didnt work. and im on linux

**Comment by bkerler** [comment]
try a different usb port or remove and reinsert battery :) Or force restart of phone with vol up + power and then try again.
