### ISSUE TITLE
any plans on adding Mediatek MT8781 Helio G99 (6nm)?

### ISSUE THREAD

**Issue by jesushrek** [bkerler/mtkclient#777]
i don't think this is added but if it is please tell me i am new to these things and i recently bricked my phone when trying to install twrp

**Comment by jefferson018200306** [comment]
to dump unknown bootroms, use brute option :

`python mtk brute`

If it's successful, please edit this issue containing the dump files

**Comment by jesushrek** [comment]
> to dump unknown bootroms, use brute option :
> 
> `python mtk brute`
> 
> If it's successful, please edit this issue containing the dump files and your phone model

so yea i tried doing it but no luck i press both buttons then connect it gets detected but after some seconds the phone boots and disconnects from pc and mtk client doesn't even do anything even if it is detected and the device i am working with is realme 10 4g rmx3630

**Comment by jefferson018200306** [comment]
Did you release the buttons after it is detected? Pressing it too long will only reboot the system

**Comment by jesushrek** [comment]
it isn't fully dead it is a constant loop turning on then turning off after 5 secs i can't access the recovery mode or fastboot mode 
i am thinking of just crushing this phone lol

**Comment by bkerler** [comment]
Refer to issue https://github.com/bkerler/mtkclient/issues/758 for progress updates
