### ISSUE TITLE
MTK_GUI is empty

### ISSUE THREAD

**Issue by WSHBRT** [bkerler/mtkclient#779]
So i tried to Unbrick my phone using this tool, but the tool return this code for me and the gui is empty. Any advice is welcome, thank you. 

![2](https://github.com/bkerler/mtkclient/assets/145015373/684e3eff-95cc-4e2a-863e-d8b2eaa333a2)
![1](https://github.com/bkerler/mtkclient/assets/145015373/dafc08ee-6ef2-493a-b757-a1bc68d55937)

**Comment by ap996688** [comment]
I am also facing this issue. Anyone can please help.
