### ISSUE TITLE
Fastboot stuck. Is there a way to use mtkclient to get out of w stuck fastboot on a mtk 8161 android 8.1 device?

### ISSUE THREAD

**Issue by mlolly** [bkerler/mtkclient#780]
I have several android 8.1 custom ROMS and a few of them are stuck in fastboot mode. Since it is custom ROM there are no options to select with in fastboot or recovery mode using volume keys. When I connect to these tablets I use fastboot reboot and the tablet reboots but goes right back into fastboot. I tried fastboot reboot-bootloader and it states success on my end and the tablet goes blank for a few seconds and then goes right back into fastboot.

My question is now that I have mtkclient working and it reads and writes image (bin) files to these android 8.1 custom mt8161 chipset...Is there any way to fix my fastboot issue with a few of these tablets using the mtkclient to flash the bootload or somehow get the fastboot back to normal mode? 

Is there a python script I can use to force it out of fastboot? 

Apparently there are a few programs on the market that will get a stuck fastboot out of that mode but those are windows based. i need something that is either android player to player base or linux based which i can use in the Ubuntu change root environment I work out of on my Android 8.1.

Thanks for any help
Mike

**Comment by jefferson018200306** [comment]
i think `fastboot` is a part of android `bootloader`. It is named `lk.img` or `lk.bin` inside the stock rom folder. i think reflashing it will fix your fastboot into normal again...

**Comment by mlolly** [comment]
Thank you. I will try it and see if it works.
Mike

**Comment by bkerler** [comment]
Closing as it's no mtkclient issue
