### ISSUE TITLE
GUI Tools Broken on LiveDVD - Missing Deps

### ISSUE THREAD

**Issue by wowitsjack** [bkerler/mtkclient#781]
The GUI tools in the LiveDVD distro don't work.

Many python deps are missing, and the shortcuts, and applications themselves do not launch.

**Comment by wowitsjack** [comment]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, minimalegl, offscreen, vkkhrdisplay, wayland, xcb, vnc, linuxfb, minimal, eglfs.

Aborted (core dumped)

**Comment by wowitsjack** [comment]
Fix:

`sudo apt install libxcb-cursor0 libxcb1 libxcb-render0 libxcb-shape0 libxcb-xfixes0`

**Comment by realflash** [comment]
Please could the README be updated with this information? I followed the README but the GUI didn't work until I added these packages.
