### ISSUE TITLE
request support MT6789 (helio G99) 

### ISSUE THREAD

**Issue by jammesop007** [bkerler/mtkclient#786]
Please update tool so it can bypass auth mt6789 helio g99

**Comment by Shakib-BD** [comment]
Poco M5? I also want. I use custom rom on Redmi 11 Prime, Poco M5 and Redmi 11 Prime is unified. But it's scary thing to use custom rom if device brick mistakenly.

**Comment by Shakib-BD** [comment]
@bkerler said, it's not supported for now. Support is being worked on. Refer to #758

**Comment by davidlip123** [comment]
it mt6789 supported now? @bkerler

**Comment by drsn00ker** [comment]
I'll add my name to the list here. Got a Headwolf FPAD5 (mt6789 helioG99) cheapo 8" tablet that I bricked. No luck getting it back working, let alone rooting. Still reading here in the discussion and issues threads. But I'm a complete N00B at rooting so a lot of the comments are over my head.

**Comment by Shakib-BD** [comment]
> I'll add my name to the list here. Got a Headwolf FPAD5 (mt6789 helioG99) cheapo 8" tablet that I bricked. No luck getting it back working, let alone rooting. Still reading here in the discussion and issues threads. But I'm a complete N00B at rooting so a lot of the comments are over my head.

the solution is paid flash. i can help, if you need then you can inbox me at my telegram (https://t.me/Shakib_BD)

**Comment by drsn00ker** [comment]
@Shakib-BD Thanks for that. Thankfully I managed to reflash the original boot_a (kept a backup) and that restored the tablet. I'm now reading on how to figure out what the right --loader file needs to be for my particular tablet.

**Comment by iwansal64** [comment]
How did you do that?? Was your tablet doesn't have remote auth or secure boot activated?

**Comment by drsn00ker** [comment]
I just used: 
python mtk.py w boot_a,boot_b org_boot_a.bin,org_boot_b.bin
I couldn't get it back using the gui, but it worked from the command line.

**Comment by iwansal64** [comment]
> I just used: 
> python mtk.py w boot_a,boot_b org_boot_a.bin,org_boot_b.bin
> I couldn't get it back using the gui, but it worked from the command line.

Ahh I see.. Where did you get all of the required files tho? Can you send the download link or can you store the files you use to google drive and send the link here please?

**Comment by drsn00ker** [comment]
I copied all partitions first before I started to mess with the boot files (as a precaution) but I'm glad I did. Unless you also got a Headwolf Fpad5 I doubt they'll be of use to you, but I'll find a place to upload boot_a and boot_b tomorrow.

**Comment by iwansal64** [comment]
I see.... Alrightt, I'll try to use mtkclient to flash the files that you'll give me to my phone and hope that it'll work... Though I don't really think it'll work perfectly without any further steps, knowing that my phone has SBC and SDA enabled :( ... Anyway, Thanks for your help man... I appreciate it :D

**Comment by Shakib-BD** [comment]
I can help if it's xiaomi device and soc mt6789

**Comment by iwansal64** [comment]
> Yeah if it's already bricked, doesn't hurt to try. Again here are boot_a and boot_b for the headwolf fpad5, use on different hardware at your own risk
> 
> https://limewire.com/d/f6f2d58f-a786-4482-84a3-618d09f95e8a#H2csEkNcseWSJVV71EScISrxupzjszhHuANHEk5xMvM

Thanks mann... I'll try it straight to my phone... There's nothing to lose anyway so.. yeah :)

**Comment by iwansal64** [comment]
> I can help if it's xiaomi device and soc mt6789

Sureee I will consider it... But for now I want to try to fix it on my own.. I want to explore about this first and if I'm stuck I'll comeback to you 😅

**Comment by Biraru** [comment]
Pm at [@BiraruX](https://t.me/BiraruX) on telegram, I can flash if bricked

**Comment by coppaxamsukk** [comment]
Dev.....Do please
