### ISSUE TITLE
[Request] Support For MT6789 [ POCO M5 ]

### ISSUE THREAD

**Issue by hopez13** [bkerler/mtkclient#789]
SOC: MT6789 ( Helio G99 )
Device: Poco M5 ( Rock )
****
### Attachments 
- [✓]     auth_sv5.auth
- [✓]     DA_BR.bin
- [✓]     MT6789_Android_scatter.txt
- [✓]     MT6789_Android_scatter.xml
- [✓]     PGPT_UFS
- [✓]    preloader_rock.bin

[**rock.zip**](https://github.com/bkerler/mtkclient/files/12725882/rock.zip)

**Comment by hahacandy** [comment]
@hopez13 
You use the same cell phone as me,
My phone is broken too.

**Comment by Shakib-BD** [comment]
all file for what? for flash poco m5 / mt6789 g99? work bro? really?

**Comment by thedark-ind** [comment]
Is it working now?

**Comment by ansoriroma** [comment]
> SOC: MT6789 ( Helio G99 ) Device: Poco M5 ( Rock )
> 
> ### Attachments
> * [✓]     auth_sv5.auth
> * [✓]     DA_BR.bin
> * [✓]     MT6789_Android_scatter.txt
> * [✓]     MT6789_Android_scatter.xml
> * [✓]     PGPT_UFS
> * [✓]    preloader_rock.bin
> 
> [**rock.zip**](https://github.com/bkerler/mtkclient/files/12725882/rock.zip)

hello, please give me step to copy paste this file also unbrick

**Comment by xMLSx** [comment]
any news ??
