### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by Warlockguitarman** [bkerler/mtkclient#79]
Unlock bootloader
Erase metadata and userdata (and md_udt if existing):
python mtk e metadata, userdata
Unlock bootloader:
python mtk xflash seccfg unlock

Remove the space after the,  behind Metadata, and for LG devices it's md_udc not udt but it worked,  it unlocked the bootloader on the k51! Awesome job

**Comment by Warlockguitarman** [comment]
## Usage may need to plug in and unplug and plug right back in all while holding volume down and google assist.

### Root the phone (Tested with android 9 - 12)

1. Dump boot and vbmeta and recovery/boot_b for TWRP
```
python mtk r boot_a,boot_b(or recovery),vbmeta_a boot_a.img,recovery.img,vbmeta_a.img
```
2. Reboot the phone
```
python mtk reset or unplug and hold power and volume down untill reboots
```

3. Download patched magisk for mtk:
Download (here)[https://raw.githubusercontent.com/vvb2060/magisk_files/44ca9ed38c29e22fa276698f6c03bc1168df2c10/app-release.apk]

4. Install on target phone
- you need to enable usb-debugging via Settings/About phone/Version, Tap 7x on build number
- Go to Settings/Additional settings/Developer options, enable "OEM unlock" and "USB Debugging"
- Install magisk apk by command or copy and paste
```
adb install app-release.apk
```
- accept auth rsa request on mobile screen of course to allow adb connection

5. Upload boot to /sdcard/Download by command or copy paste
```
adb push boot.img /sdcard/Download
```

6. Start magisk, tap on Install, select boot.img from /sdcard/Download, then:
```
adb pull /sdcard/Download/[displayed magisk patched boot filename here]
mv [displayed magisk patched boot filename here] boot.patched or copy and paste
rename to bootpatched.img
```

7. Do the steps needed in section "Unlock bootloader below" and "Build your own TWRP"

8. Flash magisk-patched boot and empty vbmeta
```
python mtk w boot_a,vbmeta_a bootpatched.img,vbmeta.img.empty
```

9. Reboot the phone
```
python mtk reset
```

10. Disconnect usb cable and enjoy your rooted phone :)

### Build your own TWRP for android 10 and under "still under development"

1. Go to (https://forum.hovatek.com/thread-21839.html) to download V1.8a for android 9 and 10 only
```
Follow instructions on the page to build your own twrp recovery from your boot_b.img

### Unlock bootloader

1. Erase metadata and userdata (and md_udt or md_udc if existing)
```
python mtk e metadata,userdata,md_udc
```

2. Unlock bootloader:
```
python mtk xflash seccfg unlock
```
for relocking use:
```
python mtk xflash seccfg lock
```

3. Reboot the phone:
```
python mtk reset or unplugging and holding power and volume down
```

**Comment by IdanBanani** [comment]
MT6781(Helio G96): **Successfully unlocked bootloader** with this method.
But **rooting process** (overwrite boot_a,vbmeta_a) with patched images using official Magisk.apj , then trying adb shell -> su root **had not effect** (data written, device boots, but magisk doesn't pop a message request for an update).

Note that I also have **vendor_boot_a.img** and  **vendor_system_a.img** which are not in a recognized format for magisk
I've also tried using the at the beginning to  use the --loader and --preloader flags (not-documented enough) with files from matching stock B/rom  but didn't manage to work it out, so eventually I didn't use the flags
 
example:
--preloader=preloader_fleur.bin --loader=DA_BR.bin
The preloader wasn't recognized by the script for some reason.

```
DAconfig - Using custom loader: DA_BR.bin

DAconfig
DAconfig - [LIB]: No da_loader config set up
DAXFlash
DAXFlash - [LIB]: No valid da loader found... aborting
```

**Comment by IdanBanani** [comment]
How does one should use the flags for the problematic cpu series models?
like this?
--preloader=preloader_fleur.bin --loader=DA_BR.bin

The preloader wasn't recognized by the script for some reason.

```
DAconfig - Using custom loader: DA_BR.bin

DAconfig
DAconfig - [LIB]: No da_loader config set up
DAXFlash
DAXFlash - [LIB]: No valid da loader found... aborting
```

I could only use the tool without the flags, otherwise- got this error.
By the way, for devices with boot_a.img boot_b.img etc., This tool was helpful just for BL unlock, not for rooting . for some reason patching boot_a.img and vbmeta wasn't enough. But I did find another way to make use of magisk to root.

**Comment by vaccarieli** [comment]
when Unlocking Bootloader could I just simply do `mtk xflash seccfg unlock` and skip the `mtk e metadata,userdata,md_udc' to avoid losing my data' or is that really necessary for rooting ?
