### ISSUE TITLE
OPPO A55, Dimensity 700 (MT6833), unlock reports success but the BL remains locked

### ISSUE THREAD

**Issue by MinGW32-2006** [bkerler/mtkclient#793]
I use mtkclient to unlock my OPPO A55. Everything is fine until I reboot to the OS. The "OEM Unlock" option in developer mode is not gray as expected. And I still can't enter fastboot. So what's wrong with the tool? How can I solve the problem?
Phone: OPPO A55 5G (PEMM20)
SoC: Dimensity 700 (MT6833)
ROM: ColorOS 11.1 (Android 11)

**Comment by bkerler** [comment]
Oppo uses signed rsa tokens. So no support for any oppo devices.

**Comment by MinGW32-2006** [comment]
> Oppo uses signed rsa tokens. So no support for any oppo devices.

I fixed this issue by modifying the lk and lk2 partition. Now magisk and lsposed run fine on my device.

**Comment by 58773622** [comment]
> > Oppo使用签名的rsa令牌。所以不支持任何oppo设备。
> 
> 我通过修改 lk 和 lk2 分区解决了这个问题。现在，magisk 和 lspose 在我的设备上运行良好。
Hello, could you please let me know how to fix it?

**Comment by shidalao** [comment]
> > Oppo uses signed rsa tokens. So no support for any oppo devices.
> 
> I fixed this issue by modifying the lk and lk2 partition. Now magisk and lsposed run fine on my device.

Yes, for MT6833 device, such as redmi note 11 5G(evergo), it can be unlocked by flashing lk_a and lk_b partition after mtkclient tell you "already unlocked".
