### ISSUE TITLE
Question about GPT

### ISSUE THREAD

**Issue by rsbotting123** [bkerler/mtkclient#795]
Hello,

Thank you for this tool, I had a question about the boot process which I can't seem to wrap my head around.

The official firmware file for my mtk device has a single pgpt bin that is flashed to the gpt partition. The question I have is how does a single pgpt know whether my device is 128gb internal storage or 64gb internal storage. The reason I ask is because I'm trying to back up everything before I start tinkering.

**Comment by bkerler** [comment]
it doesn't. gpt needs to be adapted of course :D
