### ISSUE TITLE
One question about Handshake failed, retrying

### ISSUE THREAD

**Issue by 12123ads** [bkerler/mtkclient#799]
I was in the process of trying to link the computer with a long press on the power button and volume up and down buttons in the off state when the programme on the computer prompted this. I then tried to force a reboot of the device by long pressing the power button and the reboot would not happen. I would like to know how to exit this state now.
![图片](https://github.com/bkerler/mtkclient/assets/69107029/b28c21b3-e66b-4173-acdb-529d13562562)

**Comment by bkerler** [comment]
Just keep pressing vol up and power until the device reboots or remove and reinsert the battery.
