### ISSUE TITLE
Runtime dependencies vs pep517 dependencies

### ISSUE THREAD

**Issue by SomeoneSerge** [bkerler/mtkclient#803]
The `build-system.requires` attribute of `pyproject.toml` is for [build-time dependencies](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#configuring-setuptools-using-pyproject-toml-files). Since you're using setuptools, you can list the runtime dependencies in `project.dependencies`.

Thus this list:
https://github.com/bkerler/mtkclient/blob/34135a74f4706d732941bb9a8cf5fa50fa1c48a7/pyproject.toml#L2-L12

...should only include `setuptools` and `wheel`. Everything else should go below `[project]` in `dependencies = [ ... ]` 

This would simplify consumption of the package for some users/in certain environments. Thanks.

P.S. I see your `requires` lists something called `usb` (in contrast to `pyusb`), which isn't in your `requirements.txt`. I presume it's not needed and can/should be removed?

**Comment by bkerler** [comment]
Thanks for pointing that out, fixed by now. Can you please check if commit [b206d11](https://github.com/bkerler/mtkclient/commit/b206d1157c28c86a2b62e3e5c777a1a610764b07) is ok by now ?

**Comment by SomeoneSerge** [comment]
Yes thank you!
