### ISSUE TITLE
question on the backup

### ISSUE THREAD

**Issue by zeeboi9** [bkerler/mtkclient#806]
so i ran this command on got a flash.bin

python3 mtk rf flash.bin

but I was wondering does this flash.bin contain all the files in my phone like apks downloaded files photos

**Comment by zeeboi9** [comment]
add if it doesn't then how to do a full back up

**Comment by bkerler** [comment]
it will contain the user partitions only (including the userdata). For a full backup you'd need to save boot1, boot2 (with boottype option) and rpmb as well (mtk da rpmb r)
