### ISSUE TITLE
HELP! It DOESN'T work with Redmi A2/A2+/Poco C51!

### ISSUE THREAD

**Issue by ValentyneMu** [bkerler/mtkclient#807]
MT6765/8768t (Helio P35/G35). OEM unlocking toogle enabled and USB debugging of course, I tried even with another programs. Still NO success and I never see the white open padlock at the top. The worse is that I CAN'T enter my MI account because it has Android 13 GO and no MIUI (which makes the process quite easy even if it requires 7 days of waiting). I'm so sad, this phone is very pretty but I can't use it without being rooted and for that I need yes or yes to unlock BL. I'll be forced to sell it if there's no solution ;(

**Comment by Radbert22** [comment]
i got same too

**Comment by RG-98** [comment]
> MT6765/8768t (Helio P35/G35). OEM unlocking toogle enabled and USB debugging of course, I tried even with another programs. Still NO success and I never see the white open padlock at the top. The worse is that I CAN'T enter my MI account because it has Android 13 GO and no MIUI (which makes the process quite easy even if it requires 7 days of waiting). I'm so sad, this phone is very pretty but I can't use it without being rooted and for that I need yes or yes to unlock BL. I'll be forced to sell it if there's no solution ;(

I unlocked bootloader on this device
