### ISSUE TITLE
Can't Install livedvd 4

### ISSUE THREAD

**Issue by KillerDogeEmpire** [bkerler/mtkclient#823]
I am not a very technical person, so I wanted to just install the thing that had everything already, so I made a live usb using the iso, however it doesn't show in the boot menu. Am I installing it wrong? It said based off Ubuntu so I made the usb like usual.

**Comment by KillerDogeEmpire** [comment]
@bkerler please help

**Comment by bkerler** [comment]
Disable secure boot, otherwise it won't work. Also, LiveDVD 5 will appear soon.
