### ISSUE TITLE
New seccfg method?

### ISSUE THREAD

**Issue by phhusson** [bkerler/mtkclient#829]
Hello,

My device (TCL Nxtpaper 11 won't unlock with `mtk da seccfg unlock`. After spending some time decompiling the preloader, my understanding is:

1. sej_sec_cfg_hw_V3 is still applied on the signature to decrypt the signature stored on the device
2. The hash is no longer sha256, but instead it's made of calls to SBROM(? Or SaSi? I don't really know). I see clear calls to SaSi_SB_AddDescSequence and SB_HalWaitDescCompletion, but the descriptors look largely different than those in da_x.

I've attached my current state of decompilation in ghidra. I called the interesting entry point load_seccfg, we can see the call to sej_aes_crypt on the checksum field read from disk, but then we see a call to seccfg_follow_up to compute the hash, and it is more convoluted. I had a hard time tracking everything, but it looks like it initializes something with  sbrom_aes_cmac_and_something, then the hashes are computed (through indirect function calls) with sbrom_something and then  sbrom_something2 which add Sasi_SB descriptors that doesn't look like what's in da_x.

I'm starting to get lost here, so I'm happy to take any recommendation.

[preloader_eternals_11.bin.zip](https://github.com/bkerler/mtkclient/files/13289961/preloader_eternals_11.bin.zip)

**Comment by sarunelis** [comment]
your file isnt zip or ghidra project

**Comment by phhusson** [comment]
Right I had to rename preloader_eternals_11.bin.ghz to preloader_eternals_11.bin.zip to make github happy. Rename it back to preloader_eternals_11.bin.ghz

**Comment by sarunelis** [comment]
Oki, I see. I bit corrected it:  
https://drive.google.com/file/d/1QUN-a2qN0-eDEqHuMXNYL7C6u2pxBFgH/view?usp=drive_link

**Comment by Shakib-BD** [comment]
Wew. Phh sur 🥹

**Comment by bkerler** [comment]
@phhusson Sasi (dxcc) is only used for decryption of the data. However on newer devices, it's decrypted by the modem normally. I can have a look at the preloader. If you can give me your seccfg, I can have a look at it.

**Comment by GreenIOur** [comment]
Maybe some help to get the boot process of newer devices :
https://mediatek.gitlab.io/aiot/doc/aiot-dev-guide/master/sw/yocto/secure-boot.html#secure-boot-bl1-to-bl2

**Comment by VesperiaArt** [comment]
Hello, I currently have an open issue for the same device (TCL NXTPaper 11) at #1345 . Altough mine was purchased recently, so maybe the cpu changed... @phhusson did you manage to unlock the bootloader of your device ? Else, was there a solution for this issue, since it has been closed ?

**Comment by phhusson** [comment]
No, I didn't manage to unlock that device

**Comment by VesperiaArt** [comment]
> No, I didn't manage to unlock that device

No worry, thank you for confirming.

@bkerler I have the same device, and have an open issue (#1345 ) regarding unlocking the bootloader.  You can find in my issue the preloader and seccfg that you requested here.

I can also do other commands and try pending fixes if needed. My device has been factory-reset, so I don't mind testing and having to reset it.

**Comment by bkerler** [comment]
Adding support should be easy, but I need a working device for that (TCL NXTPaper 11)
