### ISSUE TITLE
ISO and git pull command problems

### ISSUE THREAD

**Issue by BeWhoYouWannaBe** [bkerler/mtkclient#833]
Hi,
When using the iso for the first time and give in the git pull command I get the following message: error: Your local changes to the following files would be overwritten bij merge: requirements.txt
Please commit your changes or stash them before you merge.

then I needed to give the following command: git stash

and: pip install requirements.txt

After that I still got a error message when running ./mtk_gui and I still need to run the following command:
sudo apt install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

After this I can run the command ./mtk_gui

What is wrong or what am I not doing right? I am using the latest ISO version but after an restart I need to follow all these steps to work with the latest drivers...

**Comment by bkerler** [comment]
just use "git reset --hard" and then "git puil" on latest v5 of the iso.

**Comment by TheClogger666** [comment]
> just use "git reset --hard" and then "git puil" on latest v5 of the iso.

I'm glad I seen this I've been trying to get it going myself

**Comment by BeWhoYouWannaBe** [comment]
> just use "git reset --hard" and then "git puil" on latest v5 of the iso.

Thank you that was the solution I needed. git reset -- hard and git pull
