### ISSUE TITLE
MT6735 not supported

### ISSUE THREAD

**Issue by diepthaiphu** [bkerler/mtkclient#835]
DA_handler
DA_handler - [LIB]: ←[33mDevice is in BROM mode. No preloader given, trying to dump preloader from ram.←[0m
DALegacy - Uploading legacy da...
Traceback (most recent call last):

AttributeError: 'DALegacy' object has no attribute 'upload'

**Comment by bkerler** [comment]
Thanks, will be fixed in the next release
