### ISSUE TITLE
Does anyone have this problem?

### ISSUE THREAD

**Issue by ZakitheBig** [bkerler/mtkclient#838]
Well, I simply can't flash the system partition, I looked and saw that it doesn't appear in the firmware listing, but on my other device it appears normally

**Comment by SpaceSaver** [comment]
Do you see a `super` partition?

**Comment by ZakitheBig** [comment]
> Do you see a partition?`super`

yes I see, but I just want to modify the system, in my case I saw that my super has the vendor,product,odm and the system.

**Comment by SpaceSaver** [comment]
> > Do you see a partition?`super`
> 
> yes I see, but I just want to modify the system, in my case I saw that my super has the vendor,product,odm and the system.

Yep, that's the catch with this method of modifying the phone, you will have to repack the super partition with the modifications to system.  It's a process but it can be done.  Here's a tutorial on modifying the super partition: https://xdaforums.com/t/editing-system-img-inside-super-img-and-flashing-our-modifications.4196625/

**Comment by SpaceSaver** [comment]
> but on my other device it appears normally
It's dependent on the model and the device manufacturer.  Some opt for the classic separate system, vendor, product, and odm.  Whereas some opt for the easier to update super partition.  The super partition gives the manufacturer the freedom to resize these virtual partition in an OTA update.
