### ISSUE TITLE
Magisk Link Missing?

### ISSUE THREAD

**Issue by yeldarb1983** [bkerler/mtkclient#842]
Hey, trying to follow your instructions for using mtk, and it mentions a specific fork of magisk, but it's missing from the readme, and the link in the readme.md from my git clone appears to be broken as well.

**Comment by deedeedev** [comment]
I'm looking for this patched magisk too...

**Comment by bkerler** [comment]
Please use the official magisk, it's working now.

**Comment by yeldarb1983** [comment]
ah, okay. Thank you. Sorry for wasting your time.
