### ISSUE TITLE
WRITE

### ISSUE THREAD

**Issue by Herryarfiyan** [bkerler/mtkclient#845]
after I sent gpt and preloder devices it wouldn't turn on again

fix isue on c# methot  working
usb write(Encoding.utf8.getstring("sgpt"))
usb write(Bitcoverter.getbyte(gpt.lenght))
usb write(Encoding.utf8.getstring("preloder"))
usb write(Bitcoverter.getbyte(preloader.lenght))

**Comment by bkerler** [comment]
No idea what you are referring to. mtkclient is written in python and it doesn't support sgpt atm.
