### ISSUE TITLE
Found a fix for Redmi 9A issue

### ISSUE THREAD

**Issue by EAZYBLACK** [bkerler/mtkclient#846]
Sharing this for other users that have issues, my redmi 9a was stuck in sending emi data then unpack requires 12 buffer thing, and i was using master. i had to remove and reinsert battery for phone to get out of brom, well i found a preloader and that fixed and allowed me to pass sending emi data and mtkclient works fine now, here is the preloader
https://www.mediafire.com/file/487rnlfqhps52ly/preloader_dandelion--246.bin/file
i used it with --preloader

**Comment by stitpragya22** [comment]
thank you for sharing, I also installed the preloader boot.img but my problem is that my phone display is not showing anything even not the fastboot logo. BUt that mtkclient install of boot.img is successful.

**Comment by Sushrut1101** [comment]
Tysm!

**Comment by Ujjwalss** [comment]
How to use --preloader ?. Please help I want to unlock the bootloader of my phone.

**Comment by Ujjwalss** [comment]
> Sharing this for other users that have issues, my redmi 9a was stuck in sending emi data then unpack requires 12 buffer thing, and i was using master. i had to remove and reinsert battery for phone to get out of brom, well i found a preloader and that fixed and allowed me to pass sending emi data and mtkclient works fine now, here is the preloader https://www.mediafire.com/file/487rnlfqhps52ly/preloader_dandelion--246.bin/file i used it with --preloader

How to use --preloader ?. Please help I want to unlock the bootloader of my phone.

**Comment by JuaIMS** [comment]
Man... Funny thing is that even though my device is a cattail. This preloader binary worked. THANK YOU SOO MUCH MAN.
I have spent months on this.
