### ISSUE TITLE
Support for mt8781v (helio g99 [tablet])

### ISSUE THREAD

**Issue by Arpit-Shubham** [bkerler/mtkclient#853]
Does it have support for mt8781v? specifically for device Redmu Pad(yunluo).
I am getting error. As soon as I connect the device, the cmd promt quits and I have to restart the process.

**Comment by Shakib-BD** [comment]
Same as MT6789, No solution for now. Go to Xiaomi Customer care if you still has warranty. Or you've to flash mi authorization, you can pm me for that. [Paid]
