### ISSUE TITLE
Enable Modification of Specific LIDs in NVRAM using MTKClient in Meta Mode

### ISSUE THREAD

**Issue by MrJako2001** [bkerler/mtkclient#855]
Hello, sir. First of all, thank you very much for this fantastic tool.

Is it possible to use MTKClient to pass SLA in meta mode? I want to edit the nvram, but there are certain LIDs that I cannot modify.
![image](https://github.com/bkerler/mtkclient/assets/90351109/f690c9be-4b3a-471b-9a15-c0401ded0521)

**Comment by bkerler** [comment]
This is out of scope of the mtkclient and no mtkclient issue. Use discussions instead.
