### ISSUE TITLE
[Stylo 6] DAA_SIG_VERIFY_FAILED

### ISSUE THREAD

**Issue by ParzivalWolfram** [bkerler/mtkclient#856]
Attempting to connect to an LG Stylo 6. https://github.com/MTK-bypass/bypass_utility does not see device at all, even with kamakiri capable kernel.

[log.txt](https://github.com/bkerler/mtkclient/files/13717440/log.txt)

**Comment by TheClogger666** [comment]
> Attempting to connect to an LG Stylo 6. https://github.com/MTK-bypass/bypass_utility does not see device at all, even with kamakiri capable kernel.
> 
> [log.txt](https://github.com/bkerler/mtkclient/files/13717440/log.txt)

Correct me if I'm wrong here, but if you get a DAA_FAIL error that means your device is patched to this vulnerability

**Comment by tadekdudek** [comment]
Same problem, LG K62+ (almost same as K62, just has more storage and ram)

**Comment by bkerler** [comment]
Double of issue #830
