### ISSUE TITLE
(MT6895) DAA_Security_Error (0x7017)

### ISSUE THREAD

**Issue by catcatcatcatcatcatcatcatcatcatmeow** [bkerler/mtkclient#866]
PC : WIndows 11 Pro 10.0.22621.2861
Phone: Xiaomi 12T MIUI 14.0.7 Android 14

connected phone using mtkgui.bat

```
error output:
...Preloader -  CPU:                    MT6895(Dimensity 8100)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x1c007000
Preloader -     Uart:                   0x11001000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x1172
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      9B3A249BEE1C39D73A7C5C7CC4340021
Preloader - SOC_ID:                     A3279BCBDD750F0EEB8AF7B3AA1E1E6764DA9E84EB5C266D1DD94233F7EA1BE7
Preloader
Preloader - [LIB]: Send auth error:DAA_Security_Error (0x7017)
```

**Comment by gunawan092w** [comment]
i have a same phone. but i'm having the same problem as u too
![image](https://github.com/bkerler/mtkclient/assets/86261006/b0f9e792-b657-4e35-854b-09be8df77ba4)

**Comment by bkerler** [comment]
As stated in the readme (I'm sure you both read readme.md), MT6895 is NOT supported if DAA / SLA / SBC is enabled.

**Comment by gunawan092w** [comment]
possible to disable them?

**Comment by catcatcatcatcatcatcatcatcatcatmeow** [comment]
how do you disable it?

**Comment by catcatcatcatcatcatcatcatcatcatmeow** [comment]
i just found this tutorial on how to disable them:

https://www.getdroidtips.com/disable-bypass-daa-sla-authentication-oppo/

good luck

**Comment by gunawan092w** [comment]
don't mark it as complete bruh. if SP_Flash_Tool V6 have a UART Connection setting thing, this would be possible. but with V5, it's not compatible with MT6895

**Comment by catcatcatcatcatcatcatcatcatcatmeow** [comment]
eh

**Comment by gunawan092w** [comment]
._.

**Comment by cloudguy9** [comment]
> > PC : WIndows 11 Pro 10.0.22621.2861 Phone: Xiaomi 12T MIUI 14.0.7 Android 14
> > connected phone using mtkgui.bat
> > ```
> > error output:
> > ...Preloader -  CPU:                    MT6895(Dimensity 8100)
> > Preloader -     HW version:             0x0
> > Preloader -     WDT:                    0x1c007000
> > Preloader -     Uart:                   0x11001000
> > Preloader -     Brom payload addr:      0x100a00
> > Preloader -     DA payload addr:        0x201000
> > Preloader -     CQ_DMA addr:            0x10212000
> > Preloader -     Var1:                   0xa
> > Preloader - Disabling Watchdog...
> > Preloader - HW code:                    0x1172
> > Preloader - Target config:              0xe7
> > Preloader -     SBC enabled:            True
> > Preloader -     SLA enabled:            True
> > Preloader -     DAA enabled:            True
> > Preloader -     SWJTAG enabled:         True
> > Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
> > Preloader -     Root cert required:     False
> > Preloader -     Mem read auth:          True
> > Preloader -     Mem write auth:         True
> > Preloader -     Cmd 0xC8 blocked:       True
> > Preloader - Get Target info
> > Preloader - BROM mode detected.
> > Preloader -     HW subcode:             0x8a00
> > Preloader -     HW Ver:                 0xca00
> > Preloader -     SW Ver:                 0x0
> > Preloader - ME_ID:                      9B3A249BEE1C39D73A7C5C7CC4340021
> > Preloader - SOC_ID:                     A3279BCBDD750F0EEB8AF7B3AA1E1E6764DA9E84EB5C266D1DD94233F7EA1BE7
> > Preloader
> > Preloader - [LIB]: Send auth error:DAA_Security_Error (0x7017)
> > ```
> 
> Hello, I have a Redmi K50 Rubens phone with an MT6895 processor. No matter what I did, I couldn't disable DLA and SLA. How did you manage to do this?

you simply can't. As stated by the original author [bkerler], "MT6895 is NOT supported if DAA / SLA / SBC is enabled."
