### ISSUE TITLE
Problem with the patching

### ISSUE THREAD

**Issue by kayshinonome** [bkerler/mtkclient#87]
I unlocked the bootloader successfully and followed the intructions to write the image

My phone (u304aa) just goes in a bootloop after the Orange error screen
[file-used.zip](https://github.com/bkerler/mtkclient/files/7270789/file-used.zip)

**Comment by kayshinonome** [comment]
Ah, realized my mistake, blank vbmeta is not a empty file

**Comment by kayshinonome** [comment]
It works, but instructions how to make a blank image would be helpful ^^

**Comment by AStar-cai** [comment]
Hi, I meet the same problem. could you tell me how do you make a blank image?

**Comment by kayshinonome** [comment]
As said in https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)

You need to do 

```
avbtool make_vbmeta_image --flags 2 --padding_size 4096 --output vbmeta_disabled.img 
```

**Comment by AStar-cai** [comment]
> As said in https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)
> 
> You need to do
> 
> ```
> avbtool make_vbmeta_image --flags 2 --padding_size 4096 --output vbmeta_disabled.img 
> ```

Thank you, I will try it.
