### ISSUE TITLE
No module named 'mock'

### ISSUE THREAD

**Issue by vpolinov** [bkerler/mtkclient#879]
root@MINT:/home/me/mtkclient# python mtk_gui
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
root@MINT:/home/me/mtkclient# python3 mtk_gui
Traceback (most recent call last):
  File "/home/me/mtkclient/mtk_gui", line 6, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'

**Comment by vpolinov** [comment]
> Have you done this? https://github.com/bkerler/mtkclient?tab=readme-ov-file#install

Yes, I've done this.

I've done even more and solved this bug after some googling.  It means, the author of this code did not pay much attention to his/her install instructions.

Missing mock is not the only bug in the instruction.  People with fresh install of Linux Mint will have a LOT of funny time having to cope with more bugs before they could launch this piece of software.

**Comment by vpolinov** [comment]
very shallow and off-hand install instruction by the author

**Comment by smileyraver** [comment]
so can someone actaully provide the sollution? as I am getting the mock error? this doesnt help anyone if no one posts the solution
