### ISSUE TITLE
It doesn't recognize my device

### ISSUE THREAD

**Issue by Mr-Frey** [bkerler/mtkclient#885]
I'm trying to extract a boot from my Moto G5S for a test, but I can't use the tool, I looked at the description and the video of a guy from India but when I get to the part of recognizing my device it doesn't go any further than that, android enters the bootloader screen and the tool doesn't identify that there is a device connected to the computer. What am I doing wrong? Can you help me, if possible?

**Comment by bkerler** [comment]
Most probably your vendor has disabled bootrom via ota. sorry.
