### ISSUE TITLE
[mtk6595] Preloader needed due to dram config

### ISSUE THREAD

**Issue by qglzhglbz** [bkerler/mtkclient#888]
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode
Preloader - 	CPU:			MT6595()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x111000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x6595
Preloader - Target config:		0x7
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		True
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xcb00
Preloader - 	SW Ver:			0x1
Preloader - ME_ID:			*************************************
Preloader - Jumping to 0x110000
Preloader - Jumping to 0x110000: ok.
DeviceClass - [Errno 19] No such device (it may have been disconnected)
None

**Comment by qglzhglbz** [comment]
Erasing all partitions and then writing dump preloader_device.bin to preloader. This is an incorrect operation.

**Comment by bkerler** [comment]
if you erase all partitions, use the backup of preloader using --preloader option.
