### ISSUE TITLE
Error on uploading da data

### ISSUE THREAD

**Issue by levone1** [bkerler/mtkclient#891]
Any help with this...  Thanks

`...........

......Preloader -       CPU:                    MT6739/MT6731/MT8765()
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xb4
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x699
Preloader - Target config:              0x7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb00
Preloader -     SW Ver:                 0x2
Preloader - ME_ID:                      9383F38A601D5F6233D0F8EEDAACD716
Preloader - SOC_ID:                     8B6F7D4211A1C2DA11C8B66639887CBAF31ED17698699CEF95211A69D8396E2F
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a108, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a0e0, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
None
`

**Comment by bkerler** [comment]
I will soon look into this issue.
