### ISSUE TITLE
GUI closes after Preloader - Jumping to 0x200000: ok. , doesn't reach stage 2 (Nokia 5.1)

### ISSUE THREAD

**Issue by AmonDjoza** [bkerler/mtkclient#894]
.....Preloader -        CPU:                    MT6755/MT6750/M/T/S(Helio P10/P15/P18)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212c00
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x326
Preloader - Target config:              0x1
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xcb00
Preloader -     SW Ver:                 0x1
Preloader - ME_ID:                      4E92BC1BEB1A26F744D01F9A73E46B3F
Successfully extracted preloader for this device to: preloader_co2.bin
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.

C:\mtkclient-main>

**Watching this guide https://youtu.be/qcz54ujWFQI?si=m1oSLIasc3eeytGa&t=266 pause at the timestamp, you can see I am missing:**

Port - Device detected :)
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_S_5.2152.bin
xflashext - patching da1 ...
xflashext - [LIB]: Error on patching da1 version check...
xflashext - Patching da2 ...
DAXFlash - Successfully received DA sync
DAXFlash - Uploading stage 2
...

**When I look in the mtk_gui window I see "reconnecting to stage 2 with high speed connection" just before it closes**
Drivers are correctly installed.
![image4](https://github.com/bkerler/mtkclient/assets/31658532/1b181f2b-3791-4853-9f34-1ebe02b91fe0)

**Here is the link to the extracted preloader file https://www.mediafire.com/file/nd2m5t783st8btp/preloader_co2.bin/file**

All I want is to back up the current ROM, but I can't get to that point.

**Comment by bkerler** [comment]
that's a problem with the usbdk driver. try to use --reconnect or reinstall the driver when the question mark appears after reconnecting
