### ISSUE TITLE
Not booting in recovery, fastboot

### ISSUE THREAD

**Issue by GirishKumarSharma** [bkerler/mtkclient#896]
Device: Realme c3 RMX2027

1.Unlocked bootloader (1.python mtk e metadata,userdata,md_udc 2. python mtk da seccfg unlock)
(I did nothing in between unlocking bootloader and root) i.e. your next command should be of writing boot.patched
2.Root (python mtk w boot,vbmeta boot.patched,vbmeta.img.empty)
3.python mtk reset (You Done! No issue, no bootloop, nothing else!)

But now, I am not able to go in neither stock recovery, nor in fastboot. 
When I tries to boot from Magisk app, it displays dm-verify corruption and 4 line message.
If I tries to boot into fastboot by adb, It is waiting at Orange State. I want to flash TWRP.

What should I do?

**Comment by Manamama** [comment]
Press Power to boot to System. 
Or hold Volume Down and reboot a couple of times (4) with pressing Power each time, to boot to (forced) Recovery.

**Comment by Manamama** [comment]
Press Power to boot to System. 
Or hold Volume Down and reboot a couple of times (4) with pressing Power each time, to boot to (forced) Recovery.

**Comment by Manamama** [comment]
Press Power to boot to System. 
Or hold Volume Down and reboot a couple of times (4) with pressing Power each time, to boot to (forced) Recovery.

**Comment by Manamama** [comment]
Press Power to boot to System. 
Or hold Volume Down and reboot a couple of times (4) with pressing Power each time, to boot to (forced) Recovery.
