### ISSUE TITLE
No valid da loader found... （MT6895）

### ISSUE THREAD

**Issue by ClayCoffee** [bkerler/mtkclient#902]
.....Port - Device detected :)
Preloader - 	CPU:			MT6895(Dimensity 8100)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x1c007000
Preloader - 	Uart:			0x11001000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x1172
Preloader - Target config:		0x5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Preloader - Get Target info
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			-
Preloader - SOC_ID:			-
DA_handler - Device is unprotected.
DA_handler - Device is in Preloader-Mode.
DAconfig
DAconfig - [LIB]: No da_loader config set up
DAXML
DAXML - [LIB]: No valid da loader found... aborting.

**Comment by ClayCoffee** [comment]
OPPO K10 5G

**Comment by ClayCoffee** [comment]
@bkerler

**Comment by bkerler** [comment]
Fused mt689x and newer chipsets aren't supported.

**Comment by Ko-Hi-Dev** [comment]
> Fused mt689x and newer chipsets aren't supported.

This is the same with MT6983 

I'm unsure if kamikiri is working on the chip but I think you're having more knowledge on this then me.

Although is seccfg the only partition that is modified for unlock?
