### ISSUE TITLE
List of Unsupported Device or with V6 protocol[MT6877]

### ISSUE THREAD

**Issue by bijanbina** [bkerler/mtkclient#903]
Hi
Is there any list of devices that are using V6 protocol?

I think my device mt6877 is one of those chips but I don't know how I can confirm that

**Comment by bkerler** [comment]
mt6833/mt6877 supports both protocols v5 and v6. both protocols are supported.
it's just that the T-variants and higher do have patches against kamakiri.

**Comment by bijanbina** [comment]
@bkerler Thanks for the fast reply sir 
1. By V6 protocol do you mean the unofficial [SP flash tools V6](https://spflashtools.com/windows/sp-flash-tool-v6-2216)?
2. How do you know what protocol each chip supports is there any public way to find out?
3. That's great news that this chip supports V5. I used mtclient to connect to the device I can read all the partitions but I got the following errors when I try to write back anything.
```
DAXFlash - [LIB]: ←[31mError on sending parameter: Read parttbl failed (0xc0040007)←[0m
Failed to write cam_vpu1.img to sector 161920 with sector count 3840.
```
I'm willing to spend any amount of time debugging this and happy to help

----------------
- My Device: Samsung A34 5G SM-A346E
- Here also attached mtkclient[log.txt](https://github.com/bkerler/mtkclient/files/14051183/log.txt)

**Comment by bijanbina** [comment]
I test my phone with SP flash tool V5, it also shows the same error 
```
STATUS_PARTITION_NOT_FOUND (0xc0040007)
```
Is there any way to bypass this. I can read the Jupiter partition fine with mtkclient, the device is not bricked and I can boot successfully if want to

**Comment by SayuZX** [comment]
> mt6833/mt6877 supports both protocols v5 and v6. both protocols are supported. it's just that the T-variants and higher do have patches against kamakiri.

For realme 11 pro+ 5G with MT6877 or Dimensity 7050 chipset, you can't use MTKClient, is this really supported?

**Comment by SayuZX** [comment]
> mt6833/mt6877 supports both protocols v5 and v6. both protocols are supported. it's just that the T-variants and higher do have patches against kamakiri.

[16:48:45]: [Errno 10060] Operation timed out
[16:48:47]: [Errno 10060] Operation timed out
[16:48:49]: [Errno 5] Input/Output Error
[16:48:51]: Hint:

**Comment by bijanbina** [comment]
Successfully downgraded my device with SP Flash tool and backup using mtkclient
For anyone curious how to create the scatter file I wrote it down in my blog: [https://bijan.binaee.com/2024/01/flash-samsung-galaxy-a34-sp-flash-tool/)](https://bijan.binaee.com/2024/01/flash-samsung-galaxy-a34-sp-flash-tool/)

**Comment by gxosty** [comment]
> Successfully downgraded my device with SP Flash tool and backup using mtkclient For anyone curious how to create the scatter file I wrote it down in my blog: https://bijan.binaee.com/2024/01/flash-samsung-galaxy-a34-sp-flash-tool/

Hello @bijanbina . I also have Samsung Galaxy A34 5G (SM-A346E) device. Reading your last comment, I assume you have made the scatter file for this device. If it is so, could you please share it here (or anywhere else we can contact)? I am struggling with flashing my device without it.

**Comment by max8330** [comment]
I have Realme 11 Pro+ 5G
I tried this tool but it could not pass the handshaking 
do you have any solutions?

**Comment by bkerler** [comment]
Any V6 (mt689x/mt6877/mt6833t/mt69xx/mt60xx etc.) work as long as SBC, DAA and SLA are disabled (unfused). Otherwise vendor implementations like SLA might prevent any support in mtkclient.

**Comment by jaafar-c** [comment]
> Any V6 (mt689x/mt6877/mt6833t/mt69xx/mt60xx etc.) work as long as SBC, DAA and SLA are disabled (unfused). Otherwise vendor implementations like SLA might prevent any support in mtkclient.

Please tell me how to complete that my device is hard bricked and i want to install boot.img or preloader.img just to get to fastboot 
I tried to connect and this is the log 

[06:21:37]: Device detected :)
[06:21:37]: Auth file is required. Use --auth option.
[06:21:57]: [Errno 5] Input/Output Error
[06:21:59]: Device detected :)
[06:21:59]: Auth file is required. Use --auth option.
[06:21:59]: Device is protected.
[06:21:59]: Device is in BROM-Mode. Bypassing security.
[06:21:59]: Loading payload from mt6877_payload.bin, 0x264 bytes
[06:21:59]: Kamakiri Run
[06:22:06]: Error on sending payload.
[06:22:06]: Error on sending payload: C:\Users\agaaf\Desktop\mtkclient-main\mtkclient\payloads\mt6877_payload.bin
