### ISSUE TITLE
How to unpack the backup partition files named xx.bin which is using command option 'dump' or 'w' even the MTK gui client? 

### ISSUE THREAD

**Issue by icemmw** [bkerler/mtkclient#906]
Hi, To be honestly I'm a newbie about root or flash, so the bad news is that my [PDA] got bricked now. If you are an expert in this area, just look my questions below and Please help me, Thx a lot sincerely!

Here are some key information. 

SoC: MT6765
(maybe)preloader code: full_k65v1_64_bsp
OS: Android 9
Can not usb debugger or trigger the developer option.
BTW, It's a un-famous vendor so the compatible twrp-recovery I didn't found, even the stock rom.

Here are some steps I‘ve done before when I follow the tutorial.
#S1
python3 mtk r boot,vbmeta boot.img,vbmeta.img

#S2
python3 mtk reset

#S3
do some patched work with customized app - Magisk

#S4
python3 mtk w boot,vbmeta boot.patched,vbmeta.img.empty

#S5
python3 mtk e metadata,userdata

#S6
python3 mtk da seccfg unlock

After doing this, I restart my PDA and I found that it said unlocked and the system root succeed. Thx a lot again!
#S7
🔪Then I delete just one folder which is inside of path: /system/priv_app/XXFolder/XX.apk

Reboot to the recovery mode, I want to flash 3rd recovery like TWRP or CWM.
BTW, I never into the fastboot mode succeed no matter how I press the Physical buttons, I tried much much time, it‘s always failed.
So I type the command

#S8
python3 mtk payload --metamode FASTBOOT
I see the fastboot in the screen bottom left side, and I continue type

#S9
fastboot flash recovery --disable-verity --disable-verification twrp-3.2.1-0-geminipda.img 
fastboot boot twrpxxx

After that, I never into the system succeed as usual.

I didn't know the reason then I start to learn Sth. about that, so now I backup the entire partition using MTKClient2.0-beta-gui. I don't flash the 3rd rom actually, I just want to root the PDA from the very beginning. 
So I hope some one can help me solve this urgent problem, Thx a lot!!!

**#Q1**: How to use that backuped partition files like unpacking, repacking or Sth. else? The answer is very important to me. Pls.

**#Q2**: With Q1, If I unpack the system.img file and restore the XXFolder/XX.apk, repack and flash it, can everything restore as usual? 

**#Q3**: I can't into the recovery mode now, so anyone can give me a common&light recovery?

#Q4: Step-By-Step above, I missed the recovery and metadata partition backup, is that necessary?

#Q5: I want to know if I did S7 wrong lead to that bricked or Sth. else?

#Q6: Why I could't into the twrp and owm even any other 3rd recovery. Didn't I have any chance for that?

I tried by best as I can for my need, like XDA forums searching, MTK flash tools, MTK recovery tools, ext-typed img-unpack/repack tools, but still not work for my own. So I really really hope any one can help me, or just give me some advice.

Thx for your precious time.

**Comment by icemmw** [comment]
[Uploading dumped_imgs.zip…]()

**Comment by icemmw** [comment]
[dumped_imgs.zip](https://github.com/bkerler/mtkclient/files/14071099/dumped_imgs.zip)

**Comment by bkerler** [comment]
Long story short : Read-Only partitions that are signed (VBMeta) cannot be changed, otherwise the system is bricked and needs to be reflashed completely.
