### ISSUE TITLE
I get this error message when running the command on the MTKclient-main cmd screen.

### ISSUE THREAD

**Issue by franco121787** [bkerler/mtkclient#907]
I'm trying to unlock the bootloader on a Nokia G10 and when I tried to install the MTKclient-main cmd black screen to run the command python setup.py install and when I hit enter, I get the error message. (please see image)
! [image] 
image] (https://github.com/bkerler/mtkclient/assets/157842259/7fb91977-d4f9-4584-b32a-cd79a728c92e)

So, 1 on the screen shot shows that I have copied the address into the cmd screen, I have previously installed python and have installed all the necessary drivers.
2 on the image shows the result of the command python setup.py install that I'm wanting to run. I have checked out all the other websites and video and they just simply show them putting in that command and it goes through, what am I doing wrong here??? Please someone help me!!!!!

I do have python installed already and I even changed the path to it as well on the edit the environmental variables as well.

**Comment by shahabvbnet** [comment]
You need to reinstall python and click Add python to path checkbox

**Comment by franco121787** [comment]
Ok I did all of that already, but now I'm stuck at the part where my Nokia X10 wont boot up to Brom Mode and i have tried all combination that exist but i just cant boot into Brom Mode. How can i do that directly with the MTKclient cmd command, if there is any at all? What I'm trying to do exactly is to unlock the bootloader to be able to flash the device. Another issue that I'm presenting is that fact that my device manager is not recognizing my phone connected to my pc via usb cable. I can boot up into fastboot but that does nothing to help me to unlock the bootloader. I would greatly appreciate your help with these issues, and thank you for the last response. I was mistaken the Nokia that i have is the Nokia X100 or Nokia X10 but i thought it was the Nokia G10, and its not. I hope the MTKclient tool can still help me out?? I'll be on the lookout for your response soon.

**Comment by shahabvbnet** [comment]
I think your device is broken. You should write a scatter ROM and you should use the mtk bypass project available on Github before flashing.

**Comment by shahabvbnet** [comment]
۱

**Comment by franco121787** [comment]
Well my device is not broken for sure, it has the latest android 11 security patch and that causes the phone to be locked and not show even the recovery mode, nor the download mode, the only thing i can boot up to is fastboot mode and when i run the MTKclient tool it still ask's me to put my phone into brom mode since the preloader is not being detected either. What can i do to boot into brom mode on my Nokia X10 please?? If i could get a step-by-step instruction that would be greatly appreciated.
