### ISSUE TITLE
wiko t3

### ISSUE THREAD

**Issue by at0mix1961** [bkerler/mtkclient#912]
smartphone WIKO T3 running on MT6765 R35b processor android 11.
mtk_gui displays an error
Preloader -     CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0x1
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      556A304AC7BF9E797F33FC93C0636B29
Preloader - SOC_ID:                     C91992A87DF3B54ECD99507D183CB1C51273DB5F6234A741CF32F8DBE0BA3E2E
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a108, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: Error on da_write32, addr 0x1001a0e0, CRYPTO_DEINIT_FAIL (0x1001)
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data

there are 2 DA loaders
https://4pda.to/forum/dl/post/29050804/DA_SWSEC_2128_W-V770-V01.46-11.0-GBL.zip
https://4pda.to/forum/dl/post/29050493/WIKO_T3_DA.7z

can I use them with the program? where should they be placed?

debug.log:
[20:49:55]: Device detected :)
[20:49:55]: Device is unprotected.
[20:49:55]: Device is in Preloader-Mode.
[20:49:55]: Uploading xflash stage 1 from MTK_DA_V5.bin
[20:49:56]: Error on sending DA.

my email at0mix@bk.ru

**Comment by bkerler** [comment]
you can use the --loader option for that

**Comment by at0mix1961** [comment]
I'm using mtk_gui
response without pressing the volume buttons

.Preloader -         CPU:                    MT6765/MT8768t(Helio P35/G35)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0x1
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      556A304AC7BF9E797F33FC93C0636B29
Preloader - SOC_ID:                     C91992A87DF3B54ECD99507D183CB1C51273DB5F6234A741CF32F8DBE0BA3E2E
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
Preloader - Jumping to 0x0
Preloader - Status: Waiting for PreLoader VCOM, please reconnect mobile to brom mode
...........
..........Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...

answer with the volume buttons pressed:
..........Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...

**Comment by at0mix1961** [comment]
after that, the smartphone died completely - it did not respond even to lsusb
No reaction to the buttons
after the power reset came to life.

**Comment by at0mix1961** [comment]
is the --loader [DA file] option working
can I include DA in the TIKKA T3 list? or make it possible to use this option in mtk_gui
https://4pda.to/forum/dl/post/29050493/WIKO_T3_DA.7z

**Comment by bkerler** [comment]
@at0mix1961 The link isn't working without 4pda.to account. please attach the loader here.
