### ISSUE TITLE
Solution to unlock redmi 9a

### ISSUE THREAD

**Issue by RubensJr21** [bkerler/mtkclient#913]
Eu peguei um arquivo DA de uma ROM que baixei e mudei a pasta Loader.

Pasta Loader:
![explorer_ejKhLjUzdF](https://github.com/bkerler/mtkclient/assets/50061129/4f0152fb-9f22-43f5-abb8-19c012f5e29e)

Resultado:
![WindowsTerminal_HEudEKVTuO](https://github.com/bkerler/mtkclient/assets/50061129/0c914af5-8361-41b8-9d1f-f73fa4d2816e)

Solução para qualquer telefone:
Baixe sua ROM no [https://xiaomifirmwareupdater.com/](https://xiaomifirmwareupdater.com/) e extraia o arquivo DA da pasta raiz (depois de extrair o arquivo da ROM ou você pode extrair apenas o arquivo DA)

Para quem tem Redmi 9a: [MTK_AllInOne_DA.zip](https://github.com/bkerler/mtkclient/files/14125230/MTK_AllInOne_DA.zip)

**ENGLISH**

I did get a DA file from ROM and change in Loader folder.

Loader folder:
![explorer_ejKhLjUzdF](https://github.com/bkerler/mtkclient/assets/50061129/4f0152fb-9f22-43f5-abb8-19c012f5e29e)

Result:
![WindowsTerminal_HEudEKVTuO](https://github.com/bkerler/mtkclient/assets/50061129/0c914af5-8361-41b8-9d1f-f73fa4d2816e)

Soluction for any phone:
Download your ROM in site [https://xiaomifirmwareupdater.com/](https://xiaomifirmwareupdater.com/) and extract DA file from root folder (after extract de file or you can extract only DA file)

For who have Redmi 9a: [MTK_AllInOne_DA.zip](https://github.com/bkerler/mtkclient/files/14125230/MTK_AllInOne_DA.zip)

**Comment by RubensJr21** [comment]
Depois de ter concluído o processo o telefone ainda consta como bloqueado.

**ENGLISH**

After the process is complete, the smartphone appears as lock.

**Comment by mslhii** [comment]
You might need to patch lk or some other partition, I know Huawei does this and now all the Chinese phone companies are trending this way

**Comment by RubensJr21** [comment]
How I do this?
