### ISSUE TITLE
Sm-T220 Disable Auth is not only not working, but the A7 lite is bricked... (Idea's?)

### ISSUE THREAD

**Issue by kinto117** [bkerler/mtkclient#914]
So I began an FRP bypass for a friend, and it was proving itself to be rather difficult. I googled for 2 weeks before I decided to be daring and try the TP1 to nand or whatever it is, and it didn't do the trick. The device still booted and everything and then before ya know it... A promising and rather introspective approach using AUP, (android utility program), and after I crashed the preloader to brom it was never going to start again. I feel lucky when I get it to show me that my computer can still detect the device. I've tried 4 laptops, bypass-master files, I've tried the methods to get SPFT to work, many different error codes and found that the the DA (downloading agent) is incorrect, or maybe samsung patched the method. Now my device (my friend doesn't care for it anymore seeing as it's broken in his eyes) is but a device that CAN be repaired. Hoping to hear something back from you guys. First post ever, I've viewed many if not all of the post dealing with androids and Github. :) here is the message anyways. 

Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x766
Preloader - Target config:              0x5
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      9C3DA2EDFD45CEACC156D0EE8512606A
Preloader - SOC_ID:                     893806F1DD93CF2BF312D05215F2B0F4373C165882802C74E05DAE2C3E3F6B51
Preloader
Preloader - [LIB]: ←[31mError on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)←[0m
Preloader
Preloader - [LIB]: ←[31mError on da_write32, addr 0x1001a108, CRYPTO_DEINIT_FAIL (0x1001)←[0m
Preloader
Preloader - [LIB]: ←[31mError on da_write32, addr 0x1001a100, CRYPTO_DEINIT_FAIL (0x1001)←[0m
Preloader
Preloader - [LIB]: ←[31mError on da_write32, addr 0x1001a0e0, CRYPTO_DEINIT_FAIL (0x1001)←[0m
Preloader
Preloader - [LIB]: ←[31mupload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)←[0m
Preloader
Preloader - [LIB]: ←[31mError on uploading da data←[0m
None

Any idea's?

**Comment by bkerler** [comment]
Double of issue #830
