### ISSUE TITLE
Why does the mtk wo command need a length provided?

### ISSUE THREAD

**Issue by halal-beef** [bkerler/mtkclient#916]
Shouldnt it be able to work with just the filename and offset or no?

**Comment by halal-beef** [comment]
also it seems i found a bug, i was trying to write 9 bytes with of FF to lk using the wo command, in doing so dumping lk shows that some of the partition seems to accidentally get corrupted

Stock LK:

![image](https://github.com/bkerler/mtkclient/assets/78730004/bb009dfb-8d2a-417f-9bf9-22c4938aafc7)

FF written:

![image](https://github.com/bkerler/mtkclient/assets/78730004/c97fca26-5da0-43f4-9125-a09b32c71b39)

**Comment by halal-beef** [comment]
[lk_a.patched.zip](https://github.com/bkerler/mtkclient/files/14172856/lk_a.patched.zip)

thats the "patch" i did

./mtk wo 0x1AF00000 0x8 'lk_a.patched.bin'  

was the command ran

**Comment by bkerler** [comment]
the size needs to be page-aligned. you cannot flash smaller areas without data loss

**Comment by halal-beef** [comment]
Ah, okay that makes sense, thank you
