### ISSUE TITLE
Hardbricked Redmi 9a

### ISSUE THREAD

**Issue by anonymoususer787** [bkerler/mtkclient#919]
I hardbricked my Xiaomi Redmi 9a after accidentally closing the program before it finished. I can't access fastboot or recovery mode and my phone gets recognized as an unknown usb device. Is there anything I can do to save my phone?

**Comment by EAZYBLACK** [comment]
reconnect battery its not bricked

**Comment by anonymoususer787** [comment]
Holy cow. Thank you so much!
