### ISSUE TITLE
[SOLVED] Syntax error  File "mtk", line 30

### ISSUE THREAD

**Issue by hadtosignup** [bkerler/mtkclient#92]
Hi!
First of all, thanks for the tremendous work, it's much appreciated.
I literally had to sign up to reach you. :)

Now on topic.
I'm trying to unlock bootloader on Alcatel Idol 5 (MT6753).
All was fine until I executed `python mtk e metadata,userdata,md_udc`
which returned this error: 
`File "mtk", line 30
    class ArgHandler(metaclass=LogBase):
                              ^
SyntaxError: invalid syntax`

Not sure if it's related to Python version or something else.
Here's the output of all installed Python packages (I didn't mess with it, all here by default)
Slackware 15 (rc1) - x86_64
Kernel: 5.14.9
`The list below shows all packages with name matching "python".

[ installed ] - dbus-python-1.2.18-x86_64-1
[ installed ] - kdev-python-5.6.2-x86_64-3
[ installed ] - python-appdirs-1.4.4-x86_64-4
[ installed ] - python-certifi-2021.5.30-x86_64-1
[ installed ] - python-chardet-4.0.0-x86_64-3
[ installed ] - python-charset-normalizer-2.0.6-x86_64-1
[ installed ] - python-distro-1.5.0-x86_64-4
[ installed ] - python-dnspython-2.1.0-x86_64-1
[ installed ] - python-docutils-0.17.1-x86_64-1
[ installed ] - python-future-0.18.2-x86_64-5
[ installed ] - python-idna-3.2-x86_64-1
[ installed ] - python-markdown-3.3.4-x86_64-1
[ installed ] - python-notify2-0.3.1-x86_64-8
[ installed ] - python-packaging-21.0-x86_64-1
[ installed ] - python-pillow-8.3.2-x86_64-1
[ installed ] - python-pip-21.2.4-x86_64-1
[ installed ] - python-ply-3.11-x86_64-6
[ installed ] - python-pygments-2.10.0-x86_64-1
[ installed ] - python-pysol_cards-0.10.2-x86_64-1
[ installed ] - python-random2-1.0.1-x86_64-3
[ installed ] - python-requests-2.26.0-x86_64-1
[ installed ] - python-sane-2.9.1-x86_64-3
[ installed ] - python-setuptools-58.1.0-x86_64-1
[ installed ] - python-six-1.16.0-x86_64-1
[ installed ] - python-urllib3-1.26.7-x86_64-1
[ installed ] - python2-2.7.18-x86_64-4
[ installed ] - python2-module-collection-2.7.18-x86_64-6
[ installed ] - python3-3.9.7-x86_64-1`

Please advise.
Thanks!

EDIT Oct 4 2021: Same happens on Slackware 14.2 x86_64 with multilib.

**Comment by bkerler** [comment]
Hi, did you make sure you use a python >= 3.7 ? It looks like you might need to call python3 instead of python if you mix python 2 and 3 on your system.
