### ISSUE TITLE
DA_handler - [LIB]: Unknown lockstate or no lockstate (MT8163)

### ISSUE THREAD

**Issue by ivanao92** [bkerler/mtkclient#921]
Running the command: `python mtk da seccfg unlock`

-On Windows 10 the process crashes (Last message is: "DALegacy - Reconnecting to stage2 with higher speed")
[WINDOWS_BROM_LOG.txt](https://github.com/bkerler/mtkclient/files/14214844/WINDOWS_BROM_LOG.txt)

-On Linux Debian 11 it shows "DeviceClass - [Errno 2] Entity not found" right where it crashed on Windows (then it keeps on running)
[LINUX_BROM_LOG.txt](https://github.com/bkerler/mtkclient/files/14214843/LINUX_BROM_LOG.txt)

What's causing this and what can I do to fix it?

I also attached "seccfg" and preloader file
[seccfg_preloader.zip](https://github.com/bkerler/mtkclient/files/14214895/seccfg_preloader.zip)

**Comment by bkerler** [comment]
try to use --noreconnect option
