### ISSUE TITLE
Error in the python mtk w boot,vbmeta boot.img,vbmeta.img

### ISSUE THREAD

**Issue by VEX-glicth** [bkerler/mtkclient#924]
I tried Flash by MTK Client and only this error appears, by SP Flash Tools also only give error :

.........Port - Device detected :)
Preloader -     CPU:                    MT6761/MT6762/MT3369/MT8766B(Helio A20/P22/A22/A25/G25)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x717
Preloader - Target config:              0xe1
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca01
Preloader -     SW Ver:                 0x200
Preloader - ME_ID:                      20E1E3325EE0BED16AD08846E91C5948
Preloader - SOC_ID:                     5D3ADE3287B05453B7983F11E76CCC7716D519A087CAB72D8FBAF5A7F21C797D
DA_handler - Device is unprotected.
DA_handler - Device is in BROM-Mode. Bypassing security.
PLTools - Loading payload from mt6761_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\User\Downloads\MTKClient_GUI_2.0\mtkclient\mtkclient\payloads\mt6761_payload.bin
Port - Device detected :)
DA_handler
DA_handler - [LIB]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
DA_handler
DA_handler - [LIB]: Failed to dump preloader from ram.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2152.bin
xflashext - Patching da1 ...
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : f40122426977696e
DAXFlash - No preloader given. Searching for preloader
DAXFlash - Sending emi data ...
usb_class - USBError(5, 'Input/Output Error')
DAXFlash
DAXFlash - [LIB]: Error on sending emi: unpack requires a buffer of 12 bytes
DAXFlash
DAXFlash - [LIB]: No preloader given. Operation may fail due to missing dram setup.
DAXFlash - Uploading stage 2...
DAXFlash
DAXFlash - [LIB]: Error on booting to da (xflash)

**Comment by bkerler** [comment]
seems you need to use a preloader via --preloader as it cannot be dumped from ram.
