### ISSUE TITLE
Tecno POVA 2 unlock Bootloader and relock BL without data loss

### ISSUE THREAD

**Issue by Pises98** [bkerler/mtkclient#929]
I have unlock bootloader thus can't update the system. 
I plan to lock bootloader back without loss data.
Shoul I use tools to backup
- **userdata.img**
- **super.img**  and lock bootloader back.
Next step, should I flash **.img** file to get **all user data** back?
Which img file or method should be use to backup before relock BL?

Thanks for your reply !

**Comment by PC-Doctor666** [comment]
This isn't XDA dude...
