### ISSUE TITLE
Can't run plstage

### ISSUE THREAD

**Issue by AToska21** [bkerler/mtkclient#935]
Hey!
When I'm trying to run `python mtk plstage --preloader preloader_a12.bin --payload mtkclient/paylods/mt6765_payload.bin`, it exits and says "TypeError: Preloader.setreg_disablewatchdogtimer() missing 1 required positional argument: 'hwver'". Am I doing something wrong or is this a bug?

**Comment by helix-osdev** [comment]
> Hey! When I'm trying to run `python mtk plstage --preloader preloader_a12.bin --payload mtkclient/paylods/mt6765_payload.bin`, it exits and says "TypeError: Preloader.setreg_disablewatchdogtimer() missing 1 required positional argument: 'hwver'". Am I doing something wrong or is this a bug?

Sounds like a bug in the tool itself

**Comment by KowalskiStan** [comment]
I am getting the same thing @bkerler

**Comment by bkerler** [comment]
Let me check

**Comment by Binozo** [comment]
Confirmed this problem, getting this too on master branch
