### ISSUE TITLE
rf flash.bin 100.0% but display "Failed to dump"

### ISSUE THREAD

**Issue by mouzei** [bkerler/mtkclient#941]
Progress: |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚 枅鈻堚枅鈻堚枅鈻堚枅| 100.0% Read (Sector 0xE90000 of 0xE90000, ) 0.32 MB/s
Failed to dump sector 0 with flash size 0x1d2000000 as flash.bin.

I calculated the output file size and it is correct. 
By the way, in previous version, the same error occurred when reading back partitions.

**Comment by bkerler** [comment]
yeah, will have a look. reading flash should be fine, it's just the wrong result message.

**Comment by bkerler** [comment]
fixed with commit [eb6755e](https://github.com/bkerler/mtkclient/commit/eb6755e43eda3779ab3c1531c3e6ff0697703429)
