### ISSUE TITLE
Android 13 boot.img partition not found

### ISSUE THREAD

**Issue by slayerkaido** [bkerler/mtkclient#944]
I'm going to assume the mtkclient is just not there yet in terms of extracting the boot.img or init_boot.img, as my research has pointed out, from android 13 since it is not in ramdisk but I thought I'd open an issue just in case. Is it possible to extract the boot.img from android 13 using the mtkclient? I keep getting "partition boot not found" same thing for vbmeta but I'm not to concerrned about it.

**Comment by sem1c0lon** [comment]
If your device is an A/B device, you have to specify boot_a or boot_b

**Comment by Jerry12798** [comment]
> If your device is an A/B device, you have to specify boot_a or boot_b

I believe it should fallback to reading a if it's a a/b device. I just had this issue and assumed it was an error. I got my boot_a via GUI and was trying to flash without success. I was trying to flash in GUI but it wouldn't show my patched boot-patched.img
