### ISSUE TITLE
fire tv 4k

### ISSUE THREAD

**Issue by snam11** [bkerler/mtkclient#955]
hi everybody
long story short: i have a fire tv stick 4k in bootloop, on latest firwmare (i guess) with patched bootloader due to firmware ota update.
i've been able to flash a patched bootloader via ft232h, hoping that would be enough to use kamakiri script to install a twrp recovery (and flash a new image from there).
but the stick after the rpmb donwgrade gives me an anti rollback error at boot:
[boot.txt](https://github.com/bkerler/mtkclient/files/14756147/boot.txt)
and now it won't boot anymore (not that changes anything, but at least before the downgrade i had a bootloop with logo ;) )

using the MTKClient live iso was a smooth experience because i was able to connect the stick, rip all the partitions with few clicks, but it hangs when i try to read the rpmb.
i've tried several times but seems impossible to rip it from the device.
i dunno how to roll back to original rpmb and i'm too chicken to try to erase it, what would happens if i try to erase it?
also i was wondering if is possible to downgrade rpmb (zero out) with MTKClient

EDIT. i've attached also a log with the downgrade process just in case..
[putty.txt](https://github.com/bkerler/mtkclient/files/14763488/putty.txt)

@bkerler sorry to bother you with this issue, do you think is fixable?

**Comment by snam11** [comment]
i've attached the log of what happens if i try to read the device rpmb
[rpmb error.txt](https://github.com/bkerler/mtkclient/files/14788681/rpmb.error.txt)

if i try to extract the rpmb key it works fine (i guess)
`DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - DA Extensions successfully added
xflashext - MEID        : 37d6d9b4a061447dc3bdc20a12082bd9
xflashext - HWCODE      : 0x8695
xflashext - CID         : 4501004447343030380132a2481787a9
xflashext - Generating sej rpmbkey...
sej - HACC init
sej - HACC run
sej - HACC terminate
xflashext - RPMB        : XXXXXXXXX (dunno if i can show the value)
xflashext - Generating sej mtee...
sej - HACC init
sej - HACC run
sej - HACC terminate
xflashext - MTEE        : XXXXXXXXX (dunno if i can show the value)`

**Comment by bkerler** [comment]
it's fixable, but you need to have the original dump and then do a chipoff of the emmc flash, repair the data and resolder the emmc flash .. or use isp instead.

**Comment by snam11** [comment]
well, since is an used device (i bought it used as non working since it was in a bootloop)i don't have any original dump...
i have dumped all the partition after flashing the patched bl.
and i've used the ft232h because soldering 3 wires is way much easier than having the emcc desoldered/resoldered.

>  or use isp instead.
sorry, what do you mean?
