### ISSUE TITLE
Custom DA does not work ("No da_loader config set up", "No valid da loader found... aborting.")

### ISSUE THREAD

**Issue by SergioPrinci** [bkerler/mtkclient#965]
Hi, 
I'm trying to repair a dead device (still shows up as a device on the PC).
I asked for some help to the brand, and they sent me softwares and images to try to recover it.
The software they sent me won't work, so I tried to step in by using mtkclient.

They sent me too a download agent, and I'd like to use that one, but if I try to load it up, I get a "No da_loader config set up", with a subsequent "No valid da loader found... aborting." error.

I want to try using it because with every DA I used, I get a DA Hash Mismatch error.
Could be totally unrelated, but I'm trying all the solutions that come to mind.

I'll send the DA here and if requested, I can send some Wireshark captures of USB traffic with standard DAs.

Thanks in advance.
[MTK_AllInOne_DA_CUSTOMCHUWI.zip](https://github.com/bkerler/mtkclient/files/14894493/MTK_AllInOne_DA_CUSTOMCHUWI.zip)

**Comment by Mavigsm** [comment]
What is the brand and model of the device?

**Comment by SergioPrinci** [comment]
It is a Chuwi HiPad X (MT8788, 4GB 128GB), asking the manufacturer with the serial number they gave me the (supposed) original image and as for the DA, it was with the SP Flash Tool they gave me.Thanks in advance!On 7 Apr 2024 15:05, B-ilhan ***@***.***> wrote:
What is the brand and model of the device?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

On 7 Apr 2024 15:05, B-ilhan ***@***.***> wrote:
What is the brand and model of the device?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

On 7 Apr 2024 15:05, B-ilhan ***@***.***> wrote:
What is the brand and model of the device?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

On 7 Apr 2024 15:05, B-ilhan ***@***.***> wrote:
What is the brand and model of the device?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

On 7 Apr 2024 15:05, B-ilhan ***@***.***> wrote:
What is the brand and model of the device?

**Comment by SergioPrinci** [comment]
Good day everyone, I want to update this issue by asking for MT8788 support.
If I can be of any help, by dumping things from the device (which is, sadly, still bricked) I would be glad to help!

Thanks!

**Comment by SergioPrinci** [comment]
Little update:

I'm re-testing everything with the Xubuntu live distro, but nothing changed.
Anyway, I'm sending some Wireshark captures in the two situations:
1. custom DA, doesn't even try
2. MTK_AllInOne_5.1824, DA Hash Mismatch (the attached log refers to this case, which has been the biggest problem)

Thanks in advance, if you need anything else, such as info or dumps, just ask!
[Mt6771.zip](https://github.com/bkerler/mtkclient/files/15135762/Mt6771.zip)

**Comment by SergioPrinci** [comment]
Big update:

I don't know how and neither why, but this time it somehow passed the point where it always gave me Hash Mismatch.
I luckily had it in debugmode, so I will send the log here.

The binary data sent is different when examined... I hope that this clarifies some things!
[OROCOLATO.txt](https://github.com/bkerler/mtkclient/files/15142969/OROCOLATO.txt)
