### ISSUE TITLE
Please support for Dimensty 7200 Ultra

### ISSUE THREAD

**Issue by s2dness** [bkerler/mtkclient#983]
Please bring mtkclient support.

**Comment by macekboris** [comment]
I allready sent the loaders and da files to owner and that's for MTK 6886, Redmi Note 13 Pro + 5G [zircon].

@bkerler will do it, need a time for that. We're hoping he/team will.
Thx again.

**Comment by macekboris** [comment]
https://github.com/bkerler/mtkclient/issues/968

**Comment by bkerler** [comment]
Basic support has been added. Closing as it's double issue of #968
