### ISSUE TITLE
Stuck after "Upload data was accepted. Jumping to stage 2"

### ISSUE THREAD

**Issue by SergioPrinci** [bkerler/mtkclient#987]
Good day,
I'm trying to restore a bricked Chuwi HiPad X (MT6771 or MT8788, 4GB, 128GB) through mtkclient.
However, when I use it (in the logs I used `mtk printgpt --preloader path_to_preloader/preloader --loader /path_to_da/MTK_DA_V5.bin`), I always get stuck after "Upload data was accepted. Jumping to stage 2...", with a loop of the "Timed out" dialog.

I'm sending a PCAP made with Wireshark and a debug log.

Thanks in advance!
[log.zip](https://github.com/bkerler/mtkclient/files/15143665/log.zip)

**Comment by bkerler** [comment]
Hi, you need to use a valid da loader for your device or connect in brom mode instead of preloader.

**Comment by SergioPrinci** [comment]
Hi, thanks for answering.
What do you mean by "DA Loader"? Where can I find it?

**Comment by bkerler** [comment]
If you connect in brom mode, it should work. For preloader you need a da loader which is only available if provided by the vendor / firmware package.
