### ISSUE TITLE
Error during da seccfg unlock: "Status error: Wrong magic" and unpacking buffer error

### ISSUE THREAD

**Issue by ItTonySuperMan** [bkerler/mtkclient#997]
### **Environment:**

- Operating System: Windows 10
- Python Version: Python 3.10.11
- mtkclient Version: Public V2.0.0 Beta

### **Issue Description:**
While attempting to unlock the security configuration (seccfg) on a MediaTek device using the mtkclient tool, the process fails with a "Status error: Wrong magic" followed by an "unpack requires a buffer of 12 bytes" error.

### **Command Executed:**
```
python mtk da seccfg unlock --noreconnect --preloader=D:\preloader_mz6799_6m_v2_n.bin
```

### **Expected Behavior:**
The seccfg unlock command should successfully unlock the device's security configuration without errors.

### **Actual Behavior:**
The command execution halts with the following errors:
- Initially, a "Status error: Wrong magic" error occurs.
- Subsequently, the process fails with an "unpack requires a buffer of 12 bytes" error, indicating an issue with handling the device response.

### **Error Log:**
```
DAXFlash - Extensions were accepted. Jumping to extensions...
DAXFlash - DA Extensions successfully added
DAXFlash
DAXFlash - [LIB]: [31mStatus error: Wrong magic[0m
DeviceClass - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "C:\Users\Administrator\mtkclient\mtk", line 943, in <module>
    mtk = Main(args).run(parser)
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\mtk_main.py", line 655, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 813, in handle_da_cmds
    v = mtk.daloader.seccfg(args.flag)
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\mtk_daloader.py", line 390, in seccfg
    return self.xft.seccfg(lockflag)
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\xflash\extension\xflash.py", line 539, in seccfg
    seccfg_data = self.xflash.readflash(
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 795, in readflash
    self.get_packet_length()
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 711, in get_packet_length
    resp = self.send_devctrl(self.Cmd.GET_PACKET_LENGTH)
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 179, in send_devctrl
    status[0] = self.status()
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 130, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes
```

### **Steps to Reproduce:**
1. Connect the MediaTek device in BROM mode.
2. Execute the da seccfg unlock command with the specified preloader.
3. Observe the error output.

### **Additional Context:**

- The device is a MediaTek MT6799 (Helio X30/X35) based device.
- The issue occurs during the seccfg unlock procedure, specifically after successfully adding DA extensions and attempting to read or modify the security configuration.

### Possible Related Issues:

- Error handling and response parsing during DA extension operations might be failing.
- The "Status error: Wrong magic" error suggests an unexpected response from the device, potentially indicating a protocol mismatch or an issue with the DA extension's compatibility with the device's firmware version.

Would appreciate any guidance on resolving these errors or any workarounds that might be available.

**Comment by NasiGorengBurung** [comment]
Will MT6877 that cause 12 bytes error accept MT6877 preloader and solve problem?

**Comment by NasiGorengBurung** [comment]
Then. BROM work by vol then plug usb at Android 11. But at 13, it need to be test-point then face that issue. I thought boot ROM is immutable
